### ISSUE TITLE
Only run one recipe

### ISSUE THREAD

**Issue by eahrold** [lindegroup/autopkgr#107]
it the app table view, there should be a column with a button to run an update for the selected recipe

**Comment by homebysix** [comment]
![one-recipe-only](https://cloud.githubusercontent.com/assets/7801391/7615929/aaecefde-f955-11e4-999c-0f47e0bd5f5e.png)

Could we do something like this relatively easily? It would just trigger `autopkg run [recipe]`, and show the recipe progress indicator during the run.
