### ISSUE TITLE
Mac beeps when "Install AutoPkg" button is clicked

### ISSUE THREAD

**Issue by homebysix** [lindegroup/autopkgr#151]
The "Install Git" button doesn't produce a beep, but the "Install AutoPkg" button does. I don't think it's necessary.

**Comment by homebysix** [comment]
@eahrold Any chance we could knock this out for 1.2?

**Comment by eahrold** [comment]
I actually can't figure out why this is happening and can't reproduce. The buttons settings look identical in the XIB and it's not coded to beep/not beep.

**Comment by homebysix** [comment]
OK. I'll let it go.
