### ISSUE TITLE
Enhance: Customize how the email notifier notifies

### ISSUE THREAD

**Issue by WardsParadox** [lindegroup/autopkgr#184]
Not by any means necessary or urgent but, it would be nice if there was an ability to change how the Email Notifier works. An ability to add a notification Method to only notify if MakeCatalog's imports. I realize that Munki integration is not the point of Autopkgr but it would be great. 
Also add a notification center widget or notification (I guess back to the issue #79 ).

**Comment by charliwest** [comment]
Another tweak to this could be emails when there is an update for JSSImporter, AutoPkg or AutoPkgr?

**Comment by everetteallen** [comment]
Per 341 it would be great to see customization of the content of the email notification i.e. change the title, different text and variables in email body but, additionally would be good to have an email processor for either Autopkgr or maybe autopkg that can be part of a recipe allowing notification of different email addresses.  This allows for particular groups to be notified of say flash or java changes where they may not be interested in other changes.

**Comment by homebysix** [comment]
@everetteallen Per-recipe email settings are an interesting idea, but seems like the complexity/benefit ratio is a little too high to me. You can set up email filters, as I've done, to forward email notifications to certain people if the message contains certain software titles.

I do still like @WardsParadox's original idea: The ability to determine which actions are included in an email notification, and which are not. Spitballing:
![screen shot 2015-07-15 at 7 47 46 am](https://cloud.githubusercontent.com/assets/7801391/8701306/d9a2c8fc-2ac5-11e5-88b4-6d65c20fc9f9.png)

**Comment by futureimperfect** [comment]
I think instead of having additional checkboxes to enable/disable certain notifications it would be better to allow the user to customize the email template entirely. For example, we could present a text view with a default format and allow you to swap out text/variables/etc.

For example:

--------------------------------------
New software available

{{ new_downloads }}
...
--------------------------------------

**Comment by homebysix** [comment]
@futureimperfect I was thinking additional checkboxes would be a stepping stone towards full customization. But if you'd rather skip right to full customization, that sounds even better.

**Comment by everetteallen** [comment]
I second skipping to complete customization.  I especially want to be able to customize the subject text as well as the body

**Comment by everetteallen** [comment]
@homebysix so I do really agree that  it is more of a autopkg processor for the per recipe email customization.  I have been looking to see if anyone has done one or a "generic notify" processor but so far nothing.  Will suggest on autopkg project.

**Comment by joshuagarr** [comment]
Some type of customization, however limited, would be very useful.  In particular I would find great value in having the ability to select what actions trigger notifications.

**Comment by homebysix** [comment]
The ability to choose which events trigger notifications is built into AutoPkgr 1.4, which just shipped. Give it a try and open a new issue if you have questions/problems. Thanks!

**Comment by everetteallen** [comment]
Thanks for the feature!  It would be nice if for each action trigger we could "override" the default target email address, subject and body text for that notification.   Example is that the subject now says New software available ... from <name of autopkgr machine>.  Except that makes no sense when the software is really available to test from Munki/Casper/etc server esp. now that the trigger is like Software has been imported to Munki/JSS/etc.

**Comment by homebysix** [comment]
@everetteallen We're working on an interface that lets you customize the notification template itself. I don't think it will be granular per-action, but it's a step in that direction.

Do you have any suggestions for a more generic subject line we could use?

**Comment by everetteallen** [comment]
On the generic subject line, would help me if we just left of the name of the host running autopkgr. So would be like "New software is available for testing".  Or even if you were able to indicate which plugin was in use then like "New software is available for testing from Muki" or "New software is available for testing from Casper", etc.

**Comment by homebysix** [comment]
That's tricky, because a single AutoPkgr instance could potentially be linked to both Casper and Munki.

I'll open a separate issue for this and solicit ideas.

**Comment by everetteallen** [comment]
So just so I get these in, two other ideas:
The hack just add a plist or even "localization" file into the app bundle that allows changing the email subject and body.
or
Move the notification configuration the "Folder and Integration" tab and treat it like a plug in.  This would give more room for making customizations based on action trigger for each type.  Then allow 3 configuration items per action trigger - target email, email subject, email body.
