### ISSUE TITLE
One failed recipe stops them all

### ISSUE THREAD

**Issue by jmb03012** [lindegroup/autopkgr#203]
Noticed that when executing AutoPkgr if multiple recipes are added and one in the middle for instance encounters an error, it will throw up an error which of course stops the remaining recipes from running, but also dismissing that error results in a full process stop (just like a Finder copy error on a single file).

Anyway to have it set to continue on error?  We would of course want to be notified, and of course have it all logged, but that way the balance of the recipes would continue to run and one bad egg doesn't ruin the whole dozen.

**Comment by eahrold** [comment]
@jmb03012 looks like they're making some progress on this upstream, which is where it needed to be.
https://github.com/autopkg/autopkg/pull/147
