### ISSUE TITLE
Real single log file 

### ISSUE THREAD

**Issue by Darkomen78** [lindegroup/autopkgr#218]
Hi !

Would it be possible to output a real single autopkgr.log file ?
I want to show detail of autopkgr process with GeekTool, and grep system.log ins't really great, specally for the last line when new download items are listed.

**Comment by homebysix** [comment]
I think the various options available now are sufficient:

1. Open Console.app and filter for AutoPkgr.
2. Check only the "AutoPkgr" entry in the Senders pane of Console.app:
    ![screen shot 2015-02-06 at 10 26 37 am](https://cloud.githubusercontent.com/assets/7801391/6084973/c39111d4-adea-11e4-8be5-f942655ac619.png)
3. `syslog -k Sender AutoPkgr` or something similar.

I can't think of a reason to split the log output to another file or to a TextView that isn't satisfied by the above.
