### ISSUE TITLE
Passwords to file distribution points sent in plain text in error emails

### ISSUE THREAD

**Issue by homebysix** [lindegroup/autopkgr#227]
As reported by Galen Richards:

> I'm not sure which modules are responsible for displaying and/or sending error messages but in terms of security it would definitely be good to strip out or mask distribution point passwords prior to display/email.

I definitely agree. Can we do this?

**Comment by homebysix** [comment]
Is there a way we can use the password stored in AutoPkgr.keychain to do a find/replace on the strings in the email message?

Equivalent to `sed 's/saved-password/[redacted]/g'`?

**Comment by eahrold** [comment]
I just realized the problem we're going to have here is that in most cases, the DP information is actually pulled from the JSS, not configured in AutoPkgr, which means that AutoPkgr doesn't know what the `saved-password` is in this circumstance. The only password stored in the keychain is the email account, but that wouldn't show up in any error.

I'd rather take a more general approach and use regex to match everything between `://` and `@` in a given string like `afp://user:password@pretendco.com` or `https://u2:p2@pretendco.com`

I'm trying tease this out, but it's not quite right yet. 
Mind taking a look. https://regex101.com/r/eZ1gT7/58

**Comment by homebysix** [comment]
@eahrold Does this password masking work for failures too, or just errors?
