### ISSUE TITLE
Improvements to first-run experience

### ISSUE THREAD

**Issue by ghost** [lindegroup/autopkgr#23]
Instead of throwing new users into the buttons-and-checkboxes interface, perhaps we could model the first run on the Mac OS X setup assistant, or the Dropbox setup assistant.

1. First page: welcome to AutoPkgr, one-click install of all needed components.
2. Second page: a selection of common applications and their icons, with easy "Subscribe" buttons underneath. Also, a search box for finding additional applications. (The repositories would be added invisibly in the background.)
3. Third page: Setting up the schedule for checking apps. Logical defaults, and the ability to adjust as necessary.
4. Fourth page: Setting up email notifications. As easy as possible (see #16).
5. Fifth page: Thank you! You're all set.

Then the menu bar icon stays while the app disappears. Choosing Configure brings back the standard buttons-and-checkboxes configuration window we currently see.

**Comment by homebysix** [comment]
Will rethink this when 2.0 is closer to reality.
