### ISSUE TITLE
Error Running recipes. No matched files Use of undefined key in variable substitution.

### ISSUE THREAD

**Issue by angelahan17** [lindegroup/autopkgr#240]
This is the error I get after run 'Check Apps Now' (after updating recipe repos)

The following error occured:

Error running recipes
No matched files Use of undefined key in variable substitution: u'PKG' Error processing path '%PKG%' with glob. No matched files

Most of my munki recipes/apps get updated though, but I noticed some new ones I checked didn't get added to the repo.

I'm not sure where to start looking to troubleshoot. Any help?

**Comment by soulsurfer42** [comment]
I had a similar problem - Autopkgr returned this:
`A Python exception occurred during the execution of autopkg, see the console log for more details. [ERROR] UnboundLocalError: local variable 'version' referenced before assignment `

The verbose console output led me to the source of the troubles: the recipe Filezilla.munki appears to be broken, namely in line 89 of the script.

Removing the recipe solved the issue.
