### ISSUE TITLE
Detect missing recipes and remove them from recipe_list.txt

### ISSUE THREAD

**Issue by homebysix** [lindegroup/autopkgr#247]
When a subscribed recipe is removed (either by the repo author or by removal of the repo itself), AutoPkgr should detect this and remove the recipe form recipe_list.txt.

The autopkg error looks like this:
```
Error running recipes
No valid recipe found for GNUBash.download A Python exception occurred during the execution of autopkg, see the console log for more details. [ERROR] IndexError: list index out of range
```

AutoPkgr should remove the recipe and output (in the email notification) something like this:
```
Error running recipes
No valid recipe found for GNUBash.download. It has been automatically removed from your recipe list in order to prevent recurring errors.
```

**Comment by eahrold** [comment]
@homebysix, 
I've got this feature worked out.  It used some methods developed in Search Feature PR, #246. Are you working on that at all, or have any suggestions? If no, I'll push this enhancement into that PR.

If you are working on that, I can stash and apply once your done.

Thanks,
Eldon

**Comment by homebysix** [comment]
I'm not working on it at the moment — go ahead and push. Thanks!
