### ISSUE TITLE
SecOSStatusWith error

### ISSUE THREAD

**Issue by diwanicki** [lindegroup/autopkgr#252]
I'm getting the following entries in the system log when AutoPkgr 1.1.3 starts and when it completes a check:

```
SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))
```
Mac OS X 10.9.5 Server 3.2.1

**Comment by eahrold** [comment]
@diwanicki this is the same as #174. It's looks menacing, but is not. It's bug that shows up when accessing the keychain item for the password used to send e-mails.  It happens at launch to populate the text filed, then subsequently when sending.

**Comment by diwanicki** [comment]
ok, I'll close this then as a dup - didn't find the other issue, but did look :)
