### ISSUE TITLE
Logs not modal dialogs for errors please...

### ISSUE THREAD

**Issue by everetteallen** [lindegroup/autopkgr#254]
So this may be an ER but I am trying to run Autopkgr over very long periods of time(months and years) on a headless, unattended machine.  Frequently I get modal dialogs like the one in the attached screen shot and recipe processing stops.  It would be better for me it these errors went to a log and I was notified but the recipe should be skipped and processing continue.
Thanks!
![remote desktop picture january 26 2015 at 1 12 13 pm est](https://cloud.githubusercontent.com/assets/5263924/5905340/8b58d864-a55d-11e4-9831-f1cb811eaf49.png)

**Comment by homebysix** [comment]
Hi @everetteallen,

These errors won't appear if you close the AutoPkgr configuration window. That's the state I usually let it run in.

You can always bring the configuration window back by clicking the suitcase icon in the menu bar and choosing Configure.

Elliot

**Comment by eahrold** [comment]
Hey @everetteallen, 

Also we're closing in on the 1.2 release that will move the "Schedule" to a LaunchD and provide much better "Headless" performance, including surviving restarts, and not needing to be logged in for AutoPkgr to run. It also changes how repos are auto-updated and will do so prior to each run instead on only when AutoPkgr initially launches, so even when left unattended for months most everything will stay up-to-date.

If you're up to it, we'd love your feedback. (it also adds the JDS style checkbox as suggested in #174 ; ) )

https://github.com/eahrold/autopkgr/releases/tag/v1.2-beta4

Thanks,
Eldon

**Comment by everetteallen** [comment]
Eldon,
Have been running the beta for several days now with window closed and having good results.

**Comment by eahrold** [comment]
Hey @everetteallen,
Thanks for getting back, and great to hear it working!
We're doing some final touch ups and hopefully we'll be able to release 1.2 soon.
If you do run into anything else in the beta, let us know so we can fix prior.

Any chance you've tested/noticed whether it's functioning as expected at log-in window as well? 

-- Eldon
