### ISSUE TITLE
Error Mounting SMB Share on OS X Server

### ISSUE THREAD

**Issue by ahambidg** [lindegroup/autopkgr#256]
First and foremost, thank you for your hard work on this tool; it's incredibly useful and I'm grateful to all of you who create & contribute.  :)

However, I am seeing an error when I try to mount a secondary fileshare (SMB) hosted on a second server in my Casper environment.  I'm not sure if I should be posting this here or in the JSS-Importer tool; if I should be posting it there, please let me know and I'll move it!  Picture below:

![autopkgr_error](https://cloud.githubusercontent.com/assets/8161968/5928097/19da28a2-a646-11e4-94d5-9403e3e6ebe3.jpg)

I can use both shares in Casper Admin, and mount the shares using the UN/PW given to AutoPkgr.  Thoughts?

**Comment by eahrold** [comment]
You may want to try overriding the port so it's 445. That's SMB over TCP rather than NetBIOS which uses 139. Depending how you have things set up you'll need to do this either on your JSS if you're using auto-detected DP's or in the AutoPkgr configDP window.

**Comment by homebysix** [comment]
Hi @ahambidg, did Eldon's advice work for you?

**Comment by l3ftb3hind** [comment]
This did work for me.  Thank you.
