### ISSUE TITLE
Option to automatically delete older versions of packages

### ISSUE THREAD

**Issue by bgrande12** [lindegroup/autopkgr#258]
It would be nice to have the option to automatically delete older versions of packages that are updated with autopkgr. It's been mentioned that keeping older versions may be useful, but I think it would be nice to have the option to automatically delete older versions of packages that we choose.

**Comment by homebysix** [comment]
@benjaminluo Would an option like this be useful to you?
![screen shot 2015-02-06 at 10 08 01 am](https://cloud.githubusercontent.com/assets/7801391/6084704/1c600994-ade8-11e4-8da4-fe1af7dfc28b.png)

**Comment by benjaminluo** [comment]
@homebysix That's exactly what I was looking for and then some.

**Comment by homebysix** [comment]
@eahrold If I add that to the GUI, is it something you could code up? (Probably for 1.2.1 or after.)

**Comment by eahrold** [comment]
I could give it a shot, but I think it may be fairly complicated since each recipe handles things slightly differently.

Any suggestions on exactly what should be removed? Just items in the `../[recipe]/downloads` folder?
Or include items in the `receipts` folder too?

I'll think about this, but @benjaminluo, @homebysix if you have suggestions on the actual algorithm weigh in, and I'll handle the implementation. (if you can figure it out in shell I'll objective-c-ify it)

**Comment by homebysix** [comment]
For .pkg recipes it should be pretty straightforward. In shell, the logic would be like this:
```
cd ~/Library/AutoPkg/Cache/com.github.reponame.pkg.AppName
TOTAL_PACKAGES="$(find . -maxdepth 1 -name "*.pkg" | wc -l)"
NUMBER_TO_KEEP=3

echo "Keep these .pkg files:"
find . -maxdepth 1 -name "*.pkg" | tail -$NUMBER_TO_KEEP

echo "Delete these .pkg files:"
find . -maxdepth 1 -name "*.pkg" | head -$(bc <<< "$TOTAL_PACKAGES - $NUMBER_TO_KEEP")
```

For .munki and .download recipes, it's trickier. I'll think about that.

**Comment by charliwest** [comment]
Is adding this for the JSSImporter possible to look into as well? That would be great to keep the dp's a bit cleaner.

**Comment by eahrold** [comment]
Yes definitely. 
If we can figure out how to implement this, it should cover everything since JSS recipes are most often pkg recipes with a post processor.

**Comment by homebysix** [comment]
Here's a cleanup script for removing old Munki stuff. Maybe we could do something similar (configurable, and off by default of course).

https://grpugh.wordpress.com/2015/04/24/munki-how-to-remove-cruft/

**Comment by tbridge** [comment]
I would +1 this issue, I think this could be superbly helpful.

**Comment by nitramabuar** [comment]
+1, would love this option very much

**Comment by securitygeneration** [comment]
Was looking for an autopkg native way to do this today, but having autopkgr handle it would be great too.
