### ISSUE TITLE
1.2 - Recipe conversion dialog should appear in front of other windows

### ISSUE THREAD

**Issue by homebysix** [lindegroup/autopkgr#259]
LGRecipes.m — line 484
According to James, we want to "make it key and order it front."

**Comment by eahrold** [comment]
Actually since this is only ever called during 
```
- (void)applicationDidFinishLaunching:(NSNotification *)aNotification
```
It will always be ordered front, and since it's a NSAlert it will automatically become the key window.

@futureimperfect  are you experiencing different behavior?
