### ISSUE TITLE
Ability to pause AutoPkg scheduled runs for X hours.

### ISSUE THREAD

**Issue by homebysix** [lindegroup/autopkgr#261]
I really like the way CrashPlan allows you to defer backups for a couple hours. Would be great if we could do something similar with AutoPkg runs.

![crashplan-pause](https://cloud.githubusercontent.com/assets/7801391/6087486/e33c920e-ae00-11e4-85df-0037ce801fd0.jpg)

**Comment by eahrold** [comment]
@homebysix, is this still a concern now that we have more granular scheduling?

**Comment by homebysix** [comment]
Yes, I'd say it's still a "nice to have."
