### ISSUE TITLE
Autopkgr feature / enhancement request - Track changes, RollBack

### ISSUE THREAD

**Issue by gerardweese** [lindegroup/autopkgr#262]
This is a bit of a fantasy request but I thought I would put it out there. 

It would be nice if Autopkgr could help me track the changes between app version updates and as long as I'm wishing for unicorns I might as well ask for the ability to roll back changes on a per-app basis. 

-Gerard

**Comment by homebysix** [comment]
What kind of changes would you like to track? Like Firefox release notes, that kind of thing?

Or are you referring to changes in AutoPkgr itself?

**Comment by eahrold** [comment]
Rolling back seems to be more a feature of for the distribution system  (casper / munki) rather than something useful in AutoPkg. Even if you were to roll back something in AutoPkg, on a subsequent run it would just get the most current version again.

**Comment by gerardweese** [comment]
@homebysix @eahrold Excellent points. I forget the underlying pieces AutoPkgr works with. Now that I think about it I can't see a way AutoPkgr can be used to help with this issue, and that it is more a of Casper / Munki and for my part python-jss feature request.

**Comment by homebysix** [comment]
Right. If it's the actual app deployments you want to roll back, then AutoPkgr/AutoPkg won't have anything to do with it. Instead, you'll configure that in Munki or Casper. (On both platforms, rollbacks aren't as simple as they could be, but that's neither here nor there.)
