### ISSUE TITLE
The ability to save recipe lists as "presets"

### ISSUE THREAD

**Issue by gerardweese** [lindegroup/autopkgr#263]
Often I want, or need to, uncheck all recipes to troubleshoot a new one. It would be nice if I could have a saved preset of recipes I'm currently subscribed to. The ability to  uncheck all and be able to revert back to a saved preset would be helpful. 

-Gerard

**Comment by eahrold** [comment]
This is a real interesting idea, and would be fun to code.

A while back I proposed the ability to run a single recipe, would something like that address this need, or is there a use case for multiple preset recipe groups?

**Comment by homebysix** [comment]
I like this idea. And I can think of a use case for running distinct "sets" of recipes. (Of course it would be useful to run one at a time too, but that's less of a pain point since it's so easy to open Terminal and type `autopkg run Firefox.pkg`.)
