### ISSUE TITLE
Setting up JSS importer 404 error

### ISSUE THREAD

**Issue by mpudenz** [lindegroup/autopkgr#265]
Trying to get my Autopkgr set up for testing in Self Service. When I click the "Check Apps Now" button I get the following error. Would any one have any advice?

A Python exception occurred during the execution of autopkg, see the console log for more details.
[ERROR] jss.exceptions.JSSGetError: JSS Error. Response Code: 404	Response"

**Comment by eahrold** [comment]
It may be this https://github.com/lindegroup/autopkgr/issues/221#issuecomment-67843201

We're about to release 1.2 which should address that, but if you want to try the [beta release](https://github.com/lindegroup/autopkgr/releases/tag/v1.2-rc1) and see if it helps, any feedback is appreciated.

**Comment by mpudenz** [comment]
The new version fixed this issue for us. Thank you!
