### ISSUE TITLE
Add a simple web server to check status remotely.

### ISSUE THREAD

**Issue by eahrold** [lindegroup/autopkgr#267]
I've been playing around with this project https://github.com/robbiehanson/CocoaHTTPServer and think it may be fairly easy to include.

It could be useful to have AutoPkgr run a simple web server so you can remotely check on AutoPkg status, see what recipes are schedule, what repos are included, etc...

@homebysix, @futureimperfect what do you think? Worth while?

**Comment by homebysix** [comment]
I feel like this might be out of scope. What information would it provide that you wouldn't be able to get through the app's UI?

People that want remote access to continuous-integration tools are more likely to pair autopkg with Jenkins, IMHO.

**Comment by futureimperfect** [comment]
Right, but some people may feel less inclined to use a CI service if all they're using it for is to schedule AutoPkg runs, (and if AutoPkgr offers similar functionality).

I'm all for it if it's relatively simple to build/maintain. Oh and secure.

-- 
James Barclay

**Comment by eahrold** [comment]
And the scope could even be smaller than that. What go me thinking of this feature was today I wanted to check if I had Office 2011 updates enabled on a remote machine, but didn't want to VNC in. I really just wanted a current configuration overview page.

The cocoaHTTPServer supports SSL / DigestAuth and most of the basic security features, so I think we're good there. I'll look into that more.

Here's a rough-out using good ol' reliable bootstrap...

![status-overview](https://cloud.githubusercontent.com/assets/3740088/6161767/be2bc734-b23b-11e4-9473-0a9a7ff23b57.png)

**Comment by homebysix** [comment]
OK, that's pretty cool. I suppose if it's easy to implement, and there's an "on/off" button somewhere, then what's the harm.

Will you need any HTML/CSS framework created? I can tackle that.

**Comment by eahrold** [comment]
ON/OFF, setting port number, and selecting SSL certificate is what we'll probably need.
And definitely better CSS/HTML. 

I'll put up a branch after I have a little bit more of the back-end ironed out.

**Comment by jgstew** [comment]
I'd say this should be off by default.
