### ISSUE TITLE
Firefox version not being parsed correctly in debug log.

### ISSUE THREAD

**Issue by homebysix** [lindegroup/autopkgr#270]
Tiny issue: When AutoPkgr runs my Firefox.jss recipe, I see this in the logs:
```
2/13/15 11:42:37.002 AM AutoPkgr[95417]: [DEBUG] Found app and version: Firefox:2035.0.1
```
It's probably trying to get the Firefox version from the URL of the file: `Firefox%2035.0.1.dmg`. We should treat the `%20` as a space and the version should be parsed as 35.0.1.

**Comment by eahrold** [comment]
Brilliant!
That's exactly what I was missing.
