### ISSUE TITLE
Check for (AutoPkgr) Updates and About AutoPkgr Unavailable Without Dock Icon

### ISSUE THREAD

**Issue by foigus** [lindegroup/autopkgr#275]
With the "Hide AutoPkgr in Dock" option set, it is impossible to manually check for AutoPkgr updates and access the "About" box.  Both of these options are under the AutoPkgr menu when AutoPkgr is running with the Dock icon visible (i.e. is _not_ running facelessly), but are inaccessible once the Dock icon is hidden and AutoPkgr is relaunched.

**Comment by eahrold** [comment]
@foigus good point. Hopefully we'll have an `Advanced` tab in an upcoming release for these and some other elements such as proxy configuration.

**Comment by homebysix** [comment]
There will be a "Check for AutoPkgr Updates..." item in AutoPkgr's menu item in 1.3, which will be available later today.
