### ISSUE TITLE
No matched files

### ISSUE THREAD

**Issue by bengreeno** [lindegroup/autopkgr#280]
Since upgrading to version 1.2 I get an error stating "Error running recipes. No matched files." I've attached the screenshot of this error.
![screen shot 2015-02-16 at 12 04 53 pm](https://cloud.githubusercontent.com/assets/9385714/6218139/b3f5d2ca-b5e0-11e4-8139-c81e1d79d981.png)

**Comment by eahrold** [comment]
@bengreeno , try unchecking the checking a single recipe from the recipe/repos tab.

If that doesn't help, please enable verbose logging from the menu, and see if you see any messages in the console log that could indicate what files it is unable to find.

Thanks,

Eldon

**Comment by eahrold** [comment]
@bengreeno did you get to the bottom of this?

Thanks,
Eldon

**Comment by bengreeno** [comment]
I think so. I realized I still had AutoPkgr set as a startup item. I believe this may have had something to do with it. I'm still checking to see if it's still happening. I'll follow up tomorrow. Although, time-based check for updates have not been working since the update. 



Ben Greeno | bengreeno@me.com | 847.630.4216

**Comment by ssmurphy** [comment]
I ssh into the system and ran this command.

sudo sh /Library/Application\ Support/JAMF/4.8.0.1816.sh -u


Steve Murphy
Associate Systems Engineer
Apple & NYC Infrastructure Services
Macintosh, OS X, iOS

Mast Global Technologies
Three Limited Parkway
Columbus, OH 43230
Phone, 614.415.5775
Cell, 614.747.6397
smurphy@lb.com<applewebdata://94793838-30D7-4577-8F29-CAD5E666ADD9/ssmurphy@limitedbrands.com>

PLEASE NOTE: My email address has changed to ssmurphy@lb.com<mailto:ssmurphy@lb.com>

**Comment by ssmurphy** [comment]
Disregard last email. Sent to the wrong address.

Steve Murphy
Associate Systems Engineer
Apple & NYC Infrastructure Services
Macintosh, OS X, iOS

Mast Global Technologies
Three Limited Parkway
Columbus, OH 43230
Phone, 614.415.5775
Cell, 614.747.6397
smurphy@lb.com<applewebdata://94793838-30D7-4577-8F29-CAD5E666ADD9/ssmurphy@limitedbrands.com>

PLEASE NOTE: My email address has changed to ssmurphy@lb.com<mailto:ssmurphy@lb.com>

**Comment by eahrold** [comment]
@bengreeno, 

There are a few things which could be stopping the time based checks. First you may need to re-enable the check-box. The other thing is the email password may no longer be available. 

If neither of those things help, check that you actually have the launch daemon running 

```
sudo launchctl list | grep com.lindegroup.AutoPkgr.schedule
```
should return this 
```
-	0	com.lindegroup.AutoPkgr.schedule
```

Keep us posted...
Thanks.

**Comment by bengreeno** [comment]
I disabled and re-enabled the checkbox. Also, I sent a test email to make sure that was working. The script resulted in 




- 0 com.lindegroup.AutoPkgr.schedule




I’ll let it run overnight again and see how it goes.


Ben Greeno | bengreeno@me.com | 847.630.4216

**Comment by eahrold** [comment]
You should be good to go then. 
You can also manually invoke the background run like this
```
/Applications/AutoPkgr.app/Contents/MacOS/AutoPkgr -runInBackground YES
```
And make sure everything looks good with that.

**Comment by bengreeno** [comment]
Sounds good. Thanks!


Ben Greeno | bengreeno@me.com | 847.630.4216
