### ISSUE TITLE
Error Code 2

### ISSUE THREAD

**Issue by DenyVL** [lindegroup/autopkgr#282]
I am quite new using autopkgr. 
Installed munki, xcode, Xcode tools, autopkgr 1.2. 
Followed the installation guides, settings seams to be good, BUT, still got these error messages...

makepkginfo execution failed with error code 2: No such file or directory

Any idea?
Thx
Lajos

**Comment by eahrold** [comment]
Not sure why, but you _may_ need to reinstall munki, seems similar to this: https://github.com/autopkg/autopkg/issues/23

What do you get when you run this?
```
/usr/bin/which makepkginfo
```

**Comment by DenyVL** [comment]
Dunno, will try it and let u know

**Comment by DenyVL** [comment]
Hi,

I fixed it, it is all good now...

thx a lot
Lajos

**Comment by GrahamPayton** [comment]
I am getting the same error.  Can you post how you fixed it please?

Thanks in advance

**Comment by homebysix** [comment]
@DenyVL, do you mind sharing what the fix was? Thanks!

**Comment by ToddToddTodd** [comment]
I'm receiving the same error "makepkginfo execution failed with error code 2: No such file or directory". @DenyVL, any chance you can share your solution?

**Comment by eahrold** [comment]
@ToddToddTodd, are you experiencing this from both manual runs and scheduled runs?
If it's happening only during scheduled runs try doing this

```
sudo killall cfprefsd
```
That may fix the issue.
Keep us posted. Thanks.

**Comment by DenyVL** [comment]
Sorry guy for the late reply...
What I have done, I tried /usr/bin/which makepkginfo but nothing showed up. 
After that I have installed git-2.2.1-intel-universal-mavericks.dmg and it worked. I think It was not installed before. When you install AutoPkgr it says that Git has been installed, but in my case maybe it did not. Dunno. But after that it worked.

**Comment by eahrold** [comment]
Did you reinstall munki too?

 I just went over the MunkiImporter.py code from autopkglib and the path for `makepkginfo` is [hard coded](https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/MunkiImporter.py#L401) and the error would be the exact thing you would see if it couldn't locate the `/usr/local/munki/makepkginfo` file  [(see here)](https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/MunkiImporter.py#L416).

**Comment by DenyVL** [comment]
Yes

**Comment by jumpkick** [comment]
So, I just got this error a few minutes ago.  

I installed autopkgr and used munkiadmin.install.   After munkiadmin was installed I set-up munki_repo in /Users/Shared/munk_repo.  

Switching back to AutoPkgr I was greeted with an error that said something about munk repo was undefined, so I added /Users/Shared/munki_repo to the Munki Integration section and that error was resolved.  

Next I tried to rerun and I got the error described in this bug.   I have two systems that I installed AutoPkgr on (the other does not have any recipes installed), neither can which for makepkginfo...  However on my development system I can mdfind it in the munki github repo checkout here
~/git/munki/code/client/makepkginfo

**Comment by jumpkick** [comment]
When I run "which git" I get:
/usr/bin/git
which is a stub that prompts me to install XCode.

Could it be a path issue where  /usr/local/git/bin/git is not being called to install makepkginfo?

**Comment by jumpkick** [comment]
my best guess at this is it is the same bug as autopkg#23, specifically 

~/Library/AutoPkg/Cache/com.github.autopkg.munki.makecatalogs/receipts/source/munki/code/tools/make_munki_mpkg.sh

does

    GIT=`which git`

Which likely causes the following to fail because it's resolving git to the Xcode stub, unless XCode+git is installed.

    # Copy command line admin utilities.
    # edit this if list of tools changes!
    for TOOL in makecatalogs makepkginfo manifestutil munkiimport
    do
            cp -X "$MUNKIROOT/code/client/$TOOL" "$ADMINROOT/usr/local/munki/" 2>&1
    done

**Comment by jumpkick** [comment]
By running AutoPkgr from a console window, I have determined and can reproduce the error in the console by executing the following line that was logged in StdErr/StdOut:

     /usr/bin/python /usr/local/bin/autopkg run --recipe-list "/Users/ged/Library/Application Support/AutoPkgr/recipe_list.txt" --report-plist /var/folders/r1/06v25rcd2tn_hf2kcxjmzt040000gn/T/com.lindegroup.AutoPkgr/20150316180114 -v

This is where it dies:

    FileFinder
    FileFinder: Found file match: /Users/ged/Library/AutoPkg/Cache/com.github.autopkg.munki.munkitools2/unpack/munkitools_launchd-2.0.0.1969.pkg
    FlatPkgPacker
    FlatPkgPacker: Flattened /Users/ged/Library/AutoPkg/Cache/com.github.autopkg.munki.munkitools2/unpack/munkitools_launchd-2.0.0.1969.pkg to /Users/ged/Library/AutoPkg/Cache/com.github.autopkg.munki.munkitools2/repack/munkitools_launchd.pkg
    MunkiImporter
    makepkginfo execution failed with error code 2: No such file or directory
    Failed.
    Receipt written to /Users/ged/Library/AutoPkg/Cache/com.github.autopkg.munki.munkitools2/receipts/com.github.autopkg.munki-receipt-20150316-180223.plist
    Processing com.github.autopkg.munki.makecatalogs...
    MakeCatalogsProcessor
    MakeCatalogsProcessor: No need to rebuild catalogs.
    Receipt written to /Users/ged/Library/AutoPkg/Cache/com.github.autopkg.munki.makecatalogs/receipts/com.github.autopkg.munki-receipt-20150316-180223.plist

    The following recipes failed:
        com.github.autopkg.munki.munkitools2
            Error in com.github.autopkg.munki.munkitools2: Processor: MunkiImporter: Error: makepkginfo execution failed with error code 2: No such file or directory

    Nothing downloaded, packaged or imported.

    Report plist saved to /var/folders/r1/06v25rcd2tn_hf2kcxjmzt040000gn/T/com.lindegroup.AutoPkgr/20150316180114.

**Comment by eahrold** [comment]
munkiadmin is not the same as munkitools, and that's what you want 

Install the munki core from here.
https://github.com/munki/munki/releases/tag/v.2.2.3
