### ISSUE TITLE
GitHub version in email notification is being mis-reported

### ISSUE THREAD

**Issue by homebysix** [lindegroup/autopkgr#283]
I think the recipe versions may be getting mixed up in the email notifications. Here are some recent notifications I've received. Notice the version of GitHub seems to be inherited from the previous recipe in the list.

![screen shot 2015-02-19 at 1 53 20 pm](https://cloud.githubusercontent.com/assets/7801391/6276969/7696185c-b83f-11e4-841f-6c6a3dd34d87.png)

If I clear my AutoPkg cache and run `autopkg run GitHub.pkg`, the version is detected correctly:
```
Processing GitHub.pkg...

The following packages were built:
    Identifier               Version          Pkg path                        
    ----------               -------          --------                        
    com.github.GitHub        199              /Users/user/Library/AutoPkg/Cache/com.github.homebysix.pkg.GitHub/GitHub-199.pkg
```
What could be going on here?

(Worth noting: Because of GitHub's zany version naming scheme, I'm using CFBundleVersion instead of CFBundleShortVersionString in my [GitHub.pkg recipe](https://github.com/autopkg/homebysix-recipes/blob/master/GitHub/GitHub.pkg.recipe).)

**Comment by eahrold** [comment]
You running a build off the 1.2.1 branch. 
I just got this...

![screen shot 2015-02-19 at 9 48 11 pm](https://cloud.githubusercontent.com/assets/3740088/6281192/2a627f38-b881-11e4-93c7-6cf8ff6ea280.png)
 
with ...
com.github.homebysix.pkg.GitHub
com.github.autopkg.download.Adium

**Comment by homebysix** [comment]
Nope, I'm running 1.2. I'll try 1.2.1 and report back.

**Comment by homebysix** [comment]
This hasn't recurred, even in 1.2.
