### ISSUE TITLE
AutoPkgr cannot select recipe files

### ISSUE THREAD

**Issue by tbridge** [lindegroup/autopkgr#284]
I'm new to AutoPkgr, and installed it on my test Munki/AutoPkg master. The master is a 10.10.2 machine, with developers tools installed, and OS X Server 4. AutoPkg is 0.4.2 (current), and Munki is current (2.2.x). However, when I attempt to get AutoPkgr checking recipes and repos, I'm struggling to get it going.

These are my steps to reproduce:

1. Install AutoPkgr 1.2
2. Open AutoPkgr
3. See green dots by git & autopkg (good!)
4. Click Repos & Recipes tab
5. See none selected in either section. Check the master recipes file (https://github.com/autopkg/recipes.git) and it attempts to add it. I get an error.
6. Error presented: ERROR: /Library/Developer/CommandLineTools/usr/libexec/git-core/git-pull: line 11: git-sh-setup: No such file or directory
7. Click Try to repair settings. It does.
8. It says 5 problems found, "AutoPkgr was able to repair the AutoPkg preference file. No further action is required."
9. No recipes files is checked. Rinse, Repeat.

I've got two recipe files in my ~/Library/AutoPkg/RecipeRepos file, the main one, and com.github.autopkg.jessepeterson-recipes

No obvious log traces or errors that I can find in the logs. 

Halp?

**Comment by eahrold** [comment]
@tbridge,
looks like it may be an environmental issue...
I would start by installing the command line tools then running
```
defaults read com.github.autopkg GIT_PATH /usr/bin/git
```
see if that works out any better.

**Comment by tbridge** [comment]
Eldon,

The Command Line Tools *are* installed, which is why I was so confused:

brookland:Cache ladmin$ defaults read com.github.autopkg GIT_PATH
/Library/Developer/CommandLineTools/usr/bin/git

**Comment by eahrold** [comment]
Sorry, I mis-read the post, and thought it was using the git from the Xcode.app bundle.

That is strange, go to `/Library/Developer/CommandLineTools/usr/libexec/git-core/` and check if the git-sh-setup actually exists. If not you may be missing other components from there, there should be about 168. 

If you have nowhere near that many you should probably trying re-installing the Xcode command line tools. If you're only missing that file you can probably grab it from `/Applications/Xcode.app/Contents/Developer/usr/libexec/git-core/` folder and give it another test.

**Comment by tbridge** [comment]
Interesting - I've got several other git folders there, but not git-core.

    brookland:bin ladmin$ ls -al | grep git
    -rwxr-xr-x   1 root  admin   1596704 Nov 17 13:13 git
    -rwxr-xr-x   1 root  admin    163291 Sep 18 16:19 git-cvsserver
    lrwxr-xr-x   1 root  admin         3 Dec  3 09:22 git-receive-pack -> git
    -rwxr-xr-x   1 root  admin    787952 Nov 17 13:13 git-shell
    lrwxr-xr-x   1 root  admin         3 Dec  3 09:22 git-upload-archive -> git
    -rwxr-xr-x   1 root  admin    803104 Nov 17 13:13 git-upload-pack

I've got the Command Line Tools installed (I have the receipts...) but for whatever reason, I don't have a git-core.

**Comment by eahrold** [comment]
Actually you should check
`/Library/Developer/CommandLineTools/usr/libexec/git-core/`

looks like you may be at
`/usr/bin`

**Comment by tbridge** [comment]
Apologies, Eldon. See below:

    brookland:git-core ladmin$ pwd
    /Library/Developer/CommandLineTools/usr/libexec/git-core
    brookland:git-core ladmin$ ls -al | grep git-sh-setup
    -rw-r--r--    1 root  admin     8170 Sep 18 16:19 git-sh-setup

**Comment by eahrold** [comment]
Is there anything in that folder at all?

**Comment by tbridge** [comment]
It's a file, not a folder.

**Comment by eahrold** [comment]
Oh yeah. 

try running the `git-sh-setup` script, it may repair the env path causing the issue.

**Comment by tbridge** [comment]
So, when I do run the script:

    fatal: Not a git repository (or any of the parent directories): .git

**Comment by eahrold** [comment]
I just looked at that script a little close and it wasn't what I though it was.

Some how you've got something funny in your shell environment. So the next thing to check some of that.

```
which git
``` 

```
xcode-select -p
```
If that doesn't return `/Library/Developer/CommandLineTools` run

```
xcode-select -s /Library/Developer/CommandLineTools/
```

Did you try reinstalling the command line tools yet?

**Comment by tbridge** [comment]
OK.

    brookland:~ ladmin$ which git
    /usr/bin/git
    brookland:~ ladmin$ xcode-select -p
    /Applications/Xcode.app/Contents/Developer

Seeing that, I said:

    brookland:~ ladmin$ sudo xcode-select -s /Library/Developer/CommandLineTools/

But that didn't help, so I went and attempted to reinstall the command line tools:

    brookland:~ ladmin$ xcode-select --install
    xcode-select: error: command line tools are already installed, use "Software Update" to install updates

So, I'm kinda baffled.

**Comment by eahrold** [comment]
At this point you I would just install the official git from https://github.com/timcharper/git_osx_installer/releases/download/2.2.1/git-2.2.1-intel-universal-mavericks.dmg

Good news  a more secure version of git than you would get with Xcode. (see https://github.com/blog/1938-vulnerability-announced-update-your-git-clients)

Then change the git path for autopkg
```
defaults write com.github.autopkg GIT_PATH /usr/local/git/bin/git 
```

I think there's also a setup script in the DMG you may want to run.

-- Eldon

**Comment by homebysix** [comment]
@tbridge Did installing the official git fix this? We had another report of the same issue, and I believe that worked.

**Comment by eahrold** [comment]
@tbridge 
So apple does an interesting things with where it locates git, it uses a sort of redirector to switch between the git in Xcode and that of the CLI tools. 

Since actually calling that executable triggers the "Install Command line tools" dialog we tried to circumvent it by just hard coding the full path to the specific git i.e. `/Library/Developer/CommandLineTools/usr/bin/git` or `/Applications/Xcode.app/Contents/Developer/usr/bin/git` depending on what we find installed. 
But now I'm thinking maybe we should set it to `/usr/bin/git`if either path is discovered.

So to test my theory would you mind doing 
```
defaults write com.github.autopkg GIT_PATH /usr/bin/git
```
And letting us know if that fixes this.


Thanks...

**Comment by eahrold** [comment]
@homebysix, I found a _possible_ fix for this, however I was unable to reproduce the issue, so can't verify the solution.

Basically it boils down to 10.10 passing in duplicate environment keys to GUI applications, one of which is the PATH key. Then git modifies the first instance of that key, but the spawned python process uses the second instance, which lacks the modifications git has made. 

Here's another example of the same problem (and the solution)
http://tex.stackexchange.com/questions/208181/why-did-my-tex-related-gui-program-stop-working-in-mac-os-x-yosemite/208182#208182

Here's a link to a little application I made to test whether it's happening https://dl.dropboxusercontent.com/u/120270/EnvDupeChecker.zip

@tbridge would you mind running this as well to verify you're seeing duplicates keys. 

I'm guessing Git 2.2.1 has changed the way it handles variables getting injected to the PATH which is why we don't see this using the official git (I've got to look into that code more though).

So the big question is it worth trying to sneak in to 1.2.1 or should we hold off until we see more issues crop up?

**Comment by tbridge** [comment]
I am seeing duplicate keys:

####### Checking Environment Keys 2015-03-03 19:07:06 +0000 #######

PATH = /usr/bin:/bin:/usr/sbin:/sbin
USER = ladmin
[OSX 10.10 BUG] Found a duplicate env key PATH = /usr/bin:/bin:/usr/sbin:/sbin
LOGNAME = ladmin
SSH_AUTH_SOCK = /private/tmp/com.apple.launchd.jZGoW4yG1x/Listeners
Apple_PubSub_Socket_Render = /private/tmp/com.apple.launchd.j9x8mDoZYA/Render
HOME = /Users/ladmin
SHELL = /bin/bash
__CF_USER_TEXT_ENCODING = 0x1F5:0x0:0x0
TMPDIR = /var/folders/0f/7h6nd1954hvc7prr38lg9zww0000gn/T/
XPC_SERVICE_NAME = com.eeaapps.EnvDupeChecker.144304
[OSX 10.10 BUG] Found a duplicate env key SSH_AUTH_SOCK = /private/tmp/com.apple.launchd.jZGoW4yG1x/Listeners
[OSX 10.10 BUG] Found a duplicate env key Apple_PubSub_Socket_Render = /private/tmp/com.apple.launchd.j9x8mDoZYA/Render
XPC_FLAGS = 0x0
[OSX 10.10 BUG] Found a duplicate env key LOGNAME = ladmin
[OSX 10.10 BUG] Found a duplicate env key USER = ladmin
[OSX 10.10 BUG] Found a duplicate env key HOME = /Users/ladmin
[OSX 10.10 BUG] Found a duplicate env key SHELL = /bin/bash
[OSX 10.10 BUG] Found a duplicate env key TMPDIR = /var/folders/0f/7h6nd1954hvc7prr38lg9zww0000gn/T/

**Comment by tbridge** [comment]
And running ```defaults write com.github.autopkg GIT_PATH /usr/bin/git``` did not fix the issue.

**Comment by eahrold** [comment]
@tbridge thanks for doing this, it confirms some of my suspicions.
I've just built a version of AutoPkgr with the fix applied, mind giving that a test drive.

https://dl.dropboxusercontent.com/u/120270/AutoPkgr_dup_env_fix.zip

Keep an eye on the system log for duplicate key warnings, 

Thanks again for your help.

**Comment by tbridge** [comment]
This seemed to work, but I've now got a separate issue that I'll start in a second ticket.

**Comment by eahrold** [comment]
Great, the code is small enough we should be able to get this in.
