### ISSUE TITLE
Menu Doesn't Show the Most Recent Date and Time of AutoPkg(r) Run

### ISSUE THREAD

**Issue by foigus** [lindegroup/autopkgr#286]
I've set up AutoPkg + AutoPkgr on my server and while the automated runs (and notification emails) are occurring, the menubar doesn't show the most recent date.  system.log (with verbose logging enabled) includes the following:

Feb 22 08:08:25 server AutoPkgr[19760]: [DEBUG] Completed AutoPkg Task:
	  /usr/bin/python /usr/local/bin/autopkg run --recipe-list /Users/admin/Library/Application Support/AutoPkgr/recipe_list.txt --report-plist /var/folders/gw/p0rx4_x904bdnmx1c_26vs0m0000gn/T/com.lindegroup.AutoPkgr/20150222080642 -v

While the menu says:

![screen shot 2015-02-22 at 8 28 28 am](https://cloud.githubusercontent.com/assets/5042592/6318880/4737c35a-ba6d-11e4-8a12-e38947e1d566.png)

Not sure which logs/information are useful--let me know what is needed.
OS X 10.10.2 + Server 4.0.3
AutoPkg 0.4.2
AutoPkgr 1.2

**Comment by eahrold** [comment]
@foigus, 
Thanks for this report. I'll dig in and figure it out.

One quick question, does this update when you run manually?

**Comment by foigus** [comment]
When run from the menu bar icon or from inside the AutoPkgr preferences window, the date and time in the menu bar is updated to the appropriate time.
