### ISSUE TITLE
Unable to connect to JSS

### ISSUE THREAD

**Issue by myztikoot** [lindegroup/autopkgr#287]
When pressing connect in order to verify credentials the yellow icon next to the JSS URL field changes to red and the following happens in the Console:

[DEBUG] Got authentication challenge
[DEBUG] Error [11]: Error getting distribution points   The Casper server's response could not be correctly interpreted

Github, Autopkg, and JSSImporter all show installed. I've tried several different username's and passwords for the API user, but they all result in the same behavior. I have also attempted to add distribution points manually with no difference in the error as well.

**Comment by esantiago** [comment]
Having the same issue. Still looking for solution.

**Comment by eahrold** [comment]
@myztikoot, @esantiago 
Sorry for the delay, I missed this issue originally...

Do either of you have usernames / passwords with special characters? There are a few special characters we may not be handling correctly. If so would you mind posting the characters you are using (only the special characters in any random order).

Thanks

**Comment by esantiago** [comment]
Hi,

No special characters in the password. 
Just a mix of Upper case and lowercase letters with numbers.

**Comment by esantiago** [comment]
A couple details.
Currently running OSX 10.10.2
JSS version 9.7 running on windows server 2012
File share distribution point is an SMB Share.
API user is an AD user- All admin rights given on JSS.

**Comment by homebysix** [comment]
@esantiago @myztikoot — What happens if you run one or two .jss recipes by themselves at the command line:
```
autopkg run Skype.jss Evernote.jss -v
```
I'd be interested to see whether that succeeds. If so, try the same recipes again in AutoPkgr, with verbose logging turned on (hold Option while clicking on the menu bar icon to activate verbose logging). Then filter for AutoPkgr in Console.app and see what results you find.

**Comment by rougegoat** [comment]
I'm having the same issue(OSX 10.10.3, JAMF 9.72, AutoPKG 0.4.2, Git 2.2.1, JSSImporter0.3.8, AutoPKGr 1.2.2).  All of these programs are at their newly installed state with Git, AutoPKG, and JSSImporter installed by AutoPKGr.  When I attempt to run "autopkg run -v VLC.jss" from terminal, it says it needs values for API_USERNAME, JSS_URL, and API_PASSWORD.  I set these values using the appropriate commands

> defaults write com.github.autopkg API_USERNAME api-account-name
> defaults write com.github.autopkg JSS_URL https://yourserver.example.com:8443/
> defaults write com.github.autopkg API_PASSWORD api-account-password

Now the error I am receiving is

> socket.gaierror: [Errno 8] nodename nor servname provided, or not known

Additionally, when AutoPKGr is opened, it shows a green dot indicating that the Casper integration is successful, but clicking on "Connect" results in a failure and no error message from AutoPKGr.  Console shows the same debug issues though.

**Comment by eahrold** [comment]
@rougegoat, 
When you click "connect" there should be something in the log.
If not turn on "Verbose Logs" in the menu and  try to "connect" again.

With that enabled you should see something like this...

```
AutoPkgr[99002:9f07] [DEBUG] Got certificate verification challenge
2015-05-06 15:14:11.808 AutoPkgr[99002:303] [DEBUG] Response: <NSHTTPURLResponse: 0x600000233100> { URL: https://yourjss.jamfcloud.com/JSSResource/distributionpoints } { status code: 401, headers {
    "Accept-Ranges" = bytes;
    "Cache-Control" = "no-store, no-cache, must-revalidate, max-age=0, post-check=0, pre-check=0";
    Connection = "keep-alive";
    "Content-Length" = 424;
    "Content-Type" = "text/html;charset=UTF-8";
    Date = "Wed, 06 May 2015 20:14:11 GMT";
    Server = "Restlet-Framework/2.1.7";
    "Www-Authenticate" = "Basic realm=\"Restful JSS Access -- Please supply your credentials\"";
    "X-FRAME-OPTIONS" = SAMEORIGIN;
} }
2015-05-06 15:14:11.809 AutoPkgr[99002:303] Error: Request failed: unauthorized (401)
2015-05-06 15:14:11.809 AutoPkgr[99002:303] [DEBUG] Error [401]: User authorization failed. 
 Please make you have entered the correct username and password for the connection.
```

Post back with whatever you get...

**Comment by rougegoat** [comment]
The only two errors from AutoPkgr in the system.log that seem relevant are:

> 4:04:55 PM AutoPkgr: [DEBUG] Got authentication challenge
...
4:04:55 PM AutoPkgr:
[DEBUG] Error [11]: Error getting distribution points
The Casper Server's response could not be correctly interpreted

I am seeing several errors saying something like

> 4:11:04 PM secd:
 securityd_xpc_dictionary_handler AutoPkgr [2270] copy_matching The operation couldn't be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)

or

> 4:11:04 PM AutoPkgr:
SecOSStatusWith error:[-34018] The operation couldn't be completed.  (OSStatus error -34018 - Remote error : The operation couldn,Ãôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))

From what I've read, these are email related and pop up on OSX 10.9 and 10.10 installs due to how they sandbox things.  I believe they aren't relevant, but they are in the logs.

If there is supposed to be more detail than that, there is a good chance that the Verbose Logs option doesn't actually trigger them.  Is there another way to force them on?

**Comment by rougegoat** [comment]
Adding more annoyances, the command line version started working without issues.  The AutoPkgr app is still failing to connect and logging those two [DEBUG] items.

**Comment by eahrold** [comment]
If the CLI version is working AutoPkgr will work too, and there's no need to "connect" (all that does is set the defaults when there is no error.)

I'm not sure why the response isn't getting serialized properly, that's pretty strange. If i put up a build later would you be willing to test.

**Comment by rougegoat** [comment]
Oh man I feel so stupid right now.  This entire time I've been using the "connect" button as my sole test.  My first attempt to actually run a .jss build worked flawlessly.  It figures the rabbit hole was shallow and I just brought a shovel to it.

I'd be glad to run a test build tomorrow when I'm at a machine I can wipe.

**Comment by eahrold** [comment]
@rougegoat, 
Here's a build that give a lot more information when you click "connect" and hopefully we'll get to the bottom of things...

https://dl.dropboxusercontent.com/u/120270/AutoPkgr/AutoPkgr-Verbose-JSS.zip

with verbose log turned on you'll see messages like this...
```
5/7/15 9:22:59.509 AM AutoPkgr[35799]: [DEBUG] Response From JSS: <NSHTTPURLResponse: 0x608000420b40> { URL: https://yourjss.jamfcloud.com/JSSResource/distributionpoints } { status code: 200, headers {
    "Accept-Ranges" = bytes;
    "Cache-Control" = "no-store, no-cache, must-revalidate, max-age=0, post-check=0, pre-check=0";
    Connection = "keep-alive";
    "Content-Length" = 163;
    "Content-Type" = "text/xml;charset=UTF-8";
    Date = "Thu, 07 May 2015 14:22:59 GMT";
    Server = "Restlet-Framework/2.1.7";
    Vary = "Accept-Charset,Accept-Encoding,Accept-Language,Accept";
    "X-FRAME-OPTIONS" = SAMEORIGIN;
} }
5/7/15 9:22:59.510 AM AutoPkgr[35799]: [DEBUG] Response String From JSS: <?xml version="1.0" encoding="UTF-8"?><distribution_points><size>1</size><distribution_point><id>4</id><name>test</name></distribution_point></distribution_points>
5/7/15 9:22:59.511 AM AutoPkgr[35799]: [DEBUG] Object Class of response From JSS: _NSInlineData
```

post those back and hopefully we can make some sense.

**Comment by rougegoat** [comment]
Same setup as before.  Here are the new bits:

```
5/7/15 10:16:34.135 AM AutoPkgr[24540]: [DEBUG] Got authentication challenge
5/7/15 10:16:34.191 AM AutoPkgr[24540]: [DEBUG] Response From JSS: <NSHTTPURLResponse: 0x7f96007b6760> { URL: https://<redacted-JSS-URL>:8443/JSSResource/distributionpoints } { status code: 200, headers {
    "Accept-Ranges" = bytes;
    "Cache-Control" = "no-store, no-cache, must-revalidate, max-age=0, post-check=0, pre-check=0";
    "Content-Length" = 49;
    "Content-Type" = "text/plain;charset=UTF-8";
    Date = "Thu, 07 May 2015 15:16:33 GMT";
    Server = "Restlet-Framework/2.1.7";
    Vary = "Accept-Charset, Accept-Encoding, Accept-Language, Accept";
    "X-FRAME-OPTIONS" = SAMEORIGIN;
} }
5/7/15 10:16:34.192 AM AutoPkgr[24540]: [DEBUG] Response String From JSS: {"distribution_points":[{"id":2,"name":"Titan"}]}
5/7/15 10:16:34.192 AM AutoPkgr[24540]: [DEBUG] Object Class of response From JSS: _NSInlineData
5/7/15 10:16:34.192 AM AutoPkgr[24540]: [DEBUG] Error [11]: Error getting distribution points 
 The Casper server's response could not be correctly interpreted.
```

Curious that it shows our only Distribution Point as ID 2.  Could that be a cause of the issue?

**Comment by eahrold** [comment]
No it's not the ID, those just perpetually update. You may have had a different on long ago, then added another

Could be the issue is that you're getting is the plain content type -> `"Content-Type" = "text/plain;charset=UTF-8";` rather than what I would expect it should really be `"Content-Type" = "text/xml;charset=UTF-8";` and the parser we're currently using isn't able to make sense of it.
`

But even more so, the object getting sent in is JSON not XML. We should be handling that, but I'll dig in more. Must be a difference between the cloud JSS and local JSS.

I'll keep you updated once I think I solve this issue.

**Comment by eahrold** [comment]
@rougegoat 
Just put up another build that should handle a JSON object as a fallback.

https://dl.dropboxusercontent.com/u/120270/AutoPkgr/AutoPkgr-JSON-JSS.zip

Post any new logs back.
Thanks.

**Comment by rougegoat** [comment]
That one's not opening at all.  I tried it from terminal as well and this is the error:

```
LSOpenURLsWithRole() failed with error -10810 for the file /Users/<redacted>/Downloads/AutoPkgr.app.
```

**Comment by eahrold** [comment]
You're right, I've recompiled, here you go...
https://dl.dropboxusercontent.com/u/120270/AutoPkgr/AutoPkgr-JSON-JSS.zip

**Comment by rougegoat** [comment]
Greenlight first try.

```
5/7/15 12:03:32.552 PM AutoPkgr[25716]: [DEBUG] Got authentication challenge
5/7/15 12:03:32.612 PM AutoPkgr[25716]: [DEBUG] Response From JSS: <NSHTTPURLResponse: 0x7fb683c1c380> { URL: https://<redacted-jss-url>:8443/JSSResource/distributionpoints } { status code: 200, headers {
    "Accept-Ranges" = bytes;
    "Cache-Control" = "no-store, no-cache, must-revalidate, max-age=0, post-check=0, pre-check=0";
    "Content-Length" = 49;
    "Content-Type" = "text/plain;charset=UTF-8";
    Date = "Thu, 07 May 2015 17:03:32 GMT";
    Server = "Restlet-Framework/2.1.7";
    Vary = "Accept-Charset, Accept-Encoding, Accept-Language, Accept";
    "X-FRAME-OPTIONS" = SAMEORIGIN;
} }
5/7/15 12:03:32.612 PM AutoPkgr[25716]: [DEBUG] Response String From JSS: {"distribution_points":[{"id":2,"name":"Titan"}]}
5/7/15 12:03:32.613 PM AutoPkgr[25716]: [DEBUG] Object Class of response From JSS: _NSInlineData
5/7/15 12:03:32.613 PM AutoPkgr[25716]: [DEBUG] data object not XML, trying to pars as JSON
```

**Comment by eahrold** [comment]
It prompted you for the DP's password?

**Comment by rougegoat** [comment]
It did not.  I've noticed that it doesn't work if I list a specific distribution point but works fine if I never specify one.  Here's the log data when I run VLC.jss after I manually enter our afp distribution point:

```
5/7/15 12:28:27.077 PM AutoPkgr[25716]: [DEBUG] Completed AutoPkg Task:
  /usr/bin/python /usr/local/bin/autopkg version
5/7/15 12:28:27.077 PM AutoPkgr[25716]: [DEVEL] Dealloc Error Handler
5/7/15 12:28:27.491 PM AutoPkgr[25716]: Processing com.github.autopkg.jss.VLC...
5/7/15 12:28:49.656 PM AutoPkgr[25716]: [DEBUG] Found app and version: VLC:2.2.1
5/7/15 12:29:40.129 PM AutoPkgr[25716]: (FULL AUTOPKG TRACEBACK) 
  File "/usr/local/bin/autopkg", line 1469, in <module>

    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 1463, in main

    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1287, in run_recipes

    autopackager.process(recipe)
  File "/Library/AutoPkg/autopkglib/__init__.py", line 466, in process

    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 295, in process

    self.main()
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 761, in main

    self.j.distribution_points.mount()
  File "/Library/Python/2.7/site-packages/python_jss-0.5.9-py2.7.egg/jss/distribution_points.py", line 240, in mount

    child.mount()
  File "/Library/Python/2.7/site-packages/python_jss-0.5.9-py2.7.egg/jss/distribution_points.py", line 333, in mount

    if not self.is_mounted():
  File "/Library/Python/2.7/site-packages/python_jss-0.5.9-py2.7.egg/jss/distribution_points.py", line 380, in is_mounted

    valid_mount_strings = self._get_valid_mount_strings()
  File "/Library/Python/2.7/site-packages/python_jss-0.5.9-py2.7.egg/jss/distribution_points.py", line 459, in _get_valid_mount_strings

    ip_address = socket.gethostbyname(URL)

socket.gaierror: [Errno 8] nodename nor servname provided, or not known
5/7/15 12:29:40.130 PM AutoPkgr[25716]: Error [1] Error running recipes 
 A Python exception occurred during the execution of autopkg, see the system log for more details.

[ERROR] socket.gaierror: [Errno 8] nodename nor servname provided, or not known
5/7/15 12:29:40.130 PM AutoPkgr[25716]: [DEBUG] Completed AutoPkg Task:
  /usr/bin/python /usr/local/bin/autopkg run --recipe-list /Users/<redacted>/Library/Application Support/AutoPkgr/recipe_list.txt --report-plist /var/folders/qr/r8d62wh9575fr_kx4v2mp_1wz311mr/T/com.lindegroup.AutoPkgr/20150507122827 -v
5/7/15 12:29:40.131 PM AutoPkgr[25716]: [DEVEL] Dealloc Error Handler
5/7/15 12:29:40.720 PM AutoPkgr[25716]: [DEBUG] Using Git from Xcode Application.
5/7/15 12:29:43.424 PM AutoPkgr[25716]: [DEBUG] Activated AutoPkgr configuration window.
```

**Comment by eahrold** [comment]
@rougegoat, 
I think I've got things solved on our end. Using this build, you should be prompted to enter your password for your DP, and it will use the DP listed on your JSS. 

https://dl.dropboxusercontent.com/u/120270/AutoPkgr/AutoPkgr-SerializeJSON.zip

That being said, you may have something else going on. This error `socket.gaierror: [Errno 8] nodename nor servname provided, or not known` really looks like the JSSImporter can't access the JSS. Are you using proxies in your environment?

**Comment by rougegoat** [comment]
Success.  Adds it correctly and everything.  A test job shows that it does work in practice, so my other weird issue with it is resolved.

```
5/8/15 9:44:21.276 AM AutoPkgr[3927]: [DEBUG] Got authentication challenge
5/8/15 9:44:21.324 AM AutoPkgr[3927]: [DEBUG] Serialized Dictionary: [__NSCFDictionary] {
    "distribution_points" =     (
                {
            id = 2;
            name = Titan;
        }
    );
}
5/8/15 9:44:21.334 AM AutoPkgr[3927]: Prompting for password for distribution point: Titan
```
