### ISSUE TITLE
Error running recipes

### ISSUE THREAD

**Issue by jyoung88** [lindegroup/autopkgr#289]
We have been trying get AutoPkgr up and running. During our JAMF JumpStart we had it working on temporary VM. Now that it has moved to its permanent home on a Mac Mini Server we have not been able to get it to import jss recipes. It will download pkg recipes just fine. We have double and tripped checked our api account and connections to mount the shares. We have downloaded the CA Certificate from jss and added the to System Keychain on the Mac Mini Server. Please advise.

Originally we were getting this error. 

/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
mount_afp: the volume is already mounted
A Python exception occurred during the execution of autopkg, see the console log for more details.

[ERROR] subprocess.CalledProcessError: Command '['mount', '-t', 'afp', 'afp://my username and password@reaper-lab.noc.sbc.edu:548/CasperShare', '/Volumes/ReaperLabCasperShare']' returned non-zero exit status 58

But we ran this and the steps listed on this page are now getting something very different.  

defaults write com.github.autopkg JSS_VERIFY_SSL -bool false

see: https://github.com/lindegroup/autopkgr/issues/226

**New Error**

/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connection.py:251: SecurityWarning: Certificate has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SecurityWarning
mount_afp: the volume is already mounted
A Python exception occurred during the execution of autopkg, see the console log for more details.

[ERROR] subprocess.CalledProcessError: Command '['mount', '-t', 'afp', 'afp://my username and password:reaper-facstaff@reaper-lab.noc.sbc.edu:548/CasperShare', '/Volumes/ReaperLabCasperShare']' returned non-zero exit status 58

**Comment by futureimperfect** [comment]
Hi @jyoung88,

Do you have the Casper share mounted on the server you're running AutoPkgr on? The JSSImporter processor may fail if this is already mounted, since it tries to mount it automatically. It could be that you have Casper Admin running, which mounts the share. If this is the case try unmounting the share and running again.

Thanks!

-- 
James Barclay

**Comment by jyoung88** [comment]
Nope. No share mounted. Even restarted server to make sure i did not have it mounted on one of my other machines.

**Comment by eahrold** [comment]
This may be a typo due to retraction, but the url formatting is a little off here...

 `afp://my username and password:reaper-facstaff@reaper-lab.noc.sbc.edu:548/CasperShare`

Just to be sure the error says

`afp://myusername:mypassword@reaper-lab.noc.sbc.edu:548/CasperShare`

not

``afp://mypassword:reaper-facstaff@reaper-lab.noc.sbc.edu:548/CasperShare`
`
where the password comes first.

**Comment by eahrold** [comment]
Also, I'm not sure if you're running proxies but this thread contains discussion of a similar exit code (58)
#194

**Comment by jyoung88** [comment]
it was my typo on the username password format. We do not use proxies. I have scrapped it from he Mac Mini I was using and putting it in VMware Fusion on a spare iMac in my office. Will update once it is done installing.

**Comment by eahrold** [comment]
The error 58 really looks like an "already mounted" error. Casper admin wasn't set to open at login was it?

**Comment by jyoung88** [comment]
Fresh install of OS X 10.10 Server, loaded TextWrangler and AutoPkgr in a new vm. First run of AutoPkgr to grab the .pkg works fine. Go back in and deselect the .pkg and select the .jss version and get this - 

A Python exception occurred during the execution of autopkg, see the console log for more details.

[ERROR] jss.contrib.requests.exceptions.SSLError: [Errno 1] _ssl.c:507: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

Ran this from Terminal defaults write com.github.autopkg JSS_VERIFY_SSL -bool false
and now get the original error message (see below). Before I ran a second time I verified that the share had not been mounted. 

/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
mount_afp: the volume is already mounted
A Python exception occurred during the execution of autopkg, see the console log for more details.

[ERROR] subprocess.CalledProcessError: Command '['mount', '-t', 'afp', 'afp://username:password@reaper-lab.noc.sbc.edu:548/CasperShare', '/Volumes/ReaperLabCasperShare']' returned non-zero exit status 58

**Comment by eahrold** [comment]
Hey @jyoung88,
So the AFP mount error has nothing to do with the `InsecureRequestWarning` what so ever.

Since you're making it far enough in the AutoPkg run to see this,  `[ERROR] subprocess.CalledProcessError: Command ...` your JSS reachable, working correctly, and the SSL errors can be ignored.

I'm guessing for some reason the share is not getting successfully un-mounted, or a folder still incorrectly hanging on in the `/Volumes/` directory.

Check your `/Volumes/` folder and see if there is anything there that shouldn't be.

**Comment by jyoung88** [comment]
Checked before running and only thing in was the volume of the vm. No shares. Ran and got same error.

**Comment by eahrold** [comment]
After you get that error, if you try to connect to your file server using Finder is the `CasperShare ` share grayed out?

**Comment by eahrold** [comment]
@jyoung88,
So I've put a test script up here...
https://gist.github.com/eahrold/cbff74461bba8e8e4c0b#file-afp_mount_test-py

Let me know if you get the same result when running this as when run using AutoPkg(r)...

**Comment by jyoung88** [comment]
CasperShare is grayed out after error when accessing from Finder. 

I also unmounted the drive and typed in afp://username:password@reaper-facstaff.noc.sbc.edu:548\CasperShare in Finder>Go To Server and it mounted just fine. Went to Terminal and did a sudo diskutil unmount CasperShare to throw it out. Go back to /Volumes and nothing there. 

Ran the script and it mounted and unmounted fine. While mounted if I go to /Volumes is shows up as CasperShare. 

Go back to AutoPkgr, selected the VLC.pkg and .jss from com.github.autopkg. Tell it to run and get this now - 

/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html

InsecureRequestWarning)

A Python exception occurred during the execution of autopkg, see the console log for more details.

[ERROR] Unable to complete file upload. File contents does not match file type.

Now if I go back to /Volumes i see ReaperFacStaffCasperShare instead of just CasperShare when I ran it manually from Connect to Server and from the .py file. 

I tried this for VLC and Handbrake and got same error. 

One change I did make was I changed our password with had a dash in it. Removed that and double-click in the password field on Folders & Integration and inserted the new password. 

I was able to successfully get the iStat pkg and jss file from com.justinrummel. I now see iStat.jss in my Packages folder.

**Comment by eahrold** [comment]
So now it's an even different error. And I actually have no idea why this is happening
```
[ERROR] Unable to complete file upload. File contents does not match file type.
```
Did you also have a JDS configured?

**Comment by jyoung88** [comment]
No JDS

**Comment by JonMunford** [comment]
I'm getting the

[ERROR] Unable to complete file upload. File contents does not match file type.

and have been for a few weeks?  Did you find a solution to that one?

**Comment by jyoung88** [comment]
I'm still stuck on this one

-Jeff




On Sun, Mar 1, 2015 at 4:06 PM -0800, "Jon Munford" <notifications@github.com> wrote:












I'm getting the



[ERROR] Unable to complete file upload. File contents does not match file type.



and have been for a few weeks?  Did you find a solution to that one?

**Comment by eahrold** [comment]
@jyoung88 @JonMunford, 
You may want to head over the the [JSSImporter](https://github.com/sheagcraig/JSSImporter) page and post this issue there. Shea's really great at knowing what to ask.

Also if there's an actual traceback in the log would you mind posting it...

**Comment by JonMunford** [comment]
I'll give that a try thanks.

Mine is definitely related to Java8 as the message goes away when i take it off of my list.

Thanks!

**Comment by homebysix** [comment]
Yep, looks like this is a known incompatibility between JSSImporter and Casper 9.65. There is a workaround, if you'd care to try:

1. Override the self_service_icon key in your .jss recipe:
```
                    <key>self_service_icon</key>
                    <string></string>
```
2. Run the recipe. A policy will be created with no icon.
3. Log into the JSS and manually add the icon, making sure to use the .png file from your RecipeOverrides folder.
4. The error should not recur for subsequent runs (since the icon will already exist).

Hopefully a permanent fix is on the way.
