### ISSUE TITLE
Auto to Some

### ISSUE THREAD

**Issue by mgrevtech** [lindegroup/autopkgr#290]
@eahrold 
Hey Eldon, so I have a question regarding the "Level 2: Auto to Some" method. Level 1 works fine for me at the moment, with a couple of reciple errors here and there.
But I am kind of confused about how Level 2 works, does it mean that I could setup updates to run automatically for one group, say, the 'Testing' Group and then make updates available through self-service for any other groups that I want to, without any changes to the existing setup as done in Level 1.
According to the documentation for Level 2, it is mentioned that I have to edit the PolicyTemplate.xml file and remove the contents of the self_service section. So this is what is confuses me, how would this step affect my existing setup of Level 1? Or how should I be proceeding, if I still want to keep self-service updates available for the 'groups' that I already have without auto-updating for them.

**Comment by eahrold** [comment]
Hey@mgrevtech,
@homebysix is actually the JSS expert among us. Elliot, any suggestions?

**Comment by homebysix** [comment]
Hi @mgrevtech. Yes to all of the above!

If you follow the Level 2 instructions verbatim, you'll end up modifying your existing Self Service policies to become non-Self Service "auto update" policies. However, you can have both Self Service and auto update policies running side by side. The secret to this is that you can create multiple copies of the template .xml files, and also multiple copies of recipes, and customize them each as necessary.

So, for example: In one of my JSS environments, I have Firefox automatically updating (using the modified `PolicyTemplate.xml` file, as detailed in the [Level 2 instructions](https://github.com/homebysix/auto-update-magic#level-2-auto-to-some). In addition, I have a `Firefox-SelfService.jss.recipe` and a `PolicyTemplate-SelfService.xml` file working together to keep Firefox's Self Service policy up to date, as detailed in the (brand new) "[Bonus: Creating both Self Service and Auto Update policies](https://github.com/homebysix/auto-update-magic#bonus-creating-both-self-service-and-auto-update-policies)" section.

It definitely takes a bit of tweaking to get it going the first time. FWIW, I've been heavily utilizing @sheagcraig's [JSSRecipeCreator](https://github.com/sheagcraig/JSSRecipeCreator) to create .jss recipes, and then I modify them manually as needed. (By removing the Smart Group related items, in the case of a Self Service policy scoped to all computers.)

Does that help?

**Comment by mgrevtech** [comment]
Hey @homebysix
Perfecto! Thats like words out of my mouth. That's exactly what I had in mind except something like Firefox-1.jss, Firefox-2.jss and so on. But I wasn't sure if it would work and didn't want to mess up the whole setup, maybe I should have tested it out first. I will give this one a try and let you know.

Thanks a lot for letting the secret out :) and thanks for adding the new bonus section. Keep them coming!
