### ISSUE TITLE
Which git install is used?

### ISSUE THREAD

**Issue by fridomac** [lindegroup/autopkgr#291]
Hello! I installed Autopkgr (and Munki beforehand) through the "Munki-in-a-box"-script (lazy, I know :-)

If I now try to add recipe repos, I get the following:

ERROR: /Library/Developer/CommandLineTools/usr/libexec/git-core/git-pull: line 11: git-sh-setup: No such file or directory

although command line git pull works fine.

Can I somehow set which git binary to use?

Bye, Frido.

**Comment by eahrold** [comment]
@fridomac,
We actually just had a [similar report](https://github.com/lindegroup/autopkgr/issues/284#issuecomment-75338871) from @tbridge.

I just tried reproducing on a clean install of 10.10, but was unable to do so. 
I'll have to leave you with the same advice as I did him.

Install the official git from https://github.com/timcharper/git_osx_installer/releases/download/2.2.1/git-2.2.1-intel-universal-mavericks.dmg

Then run
```
defaults write com.github.autopkg GIT_PATH /usr/local/git/bin/git
```

**Comment by fridomac** [comment]
Then it is the autopkg git config that is somehow wonky, thanks, worked perfectly!

**Comment by eahrold** [comment]
@fridomac 
I'm glad installing the official git fixed this.

I do have one favor. I'm trying to see if using the default path osx uses for git corrects this issue...
Can you do 
```
defaults write com.github.autopkg GIT_PATH /usr/bin/git
```
And letting us know if that works too.

Thanks.

**Comment by eahrold** [comment]
@fridomac there's a continued discussion here https://github.com/lindegroup/autopkgr/issues/284#issuecomment-77007740 

Would you mind taking a look and reporting back.

Thanks,

Eldon

**Comment by fridomac** [comment]
Hello,

Sorry, was away from the office for a few days. 

This worked, too. Will check out the discussion in the link you sent, too.

Thanks again,

Fridolin.

Von meinem iPad gesendet

**Comment by eahrold** [comment]
Great,
Thanks for the update.
