### ISSUE TITLE
Email notifications that group recipe types

### ISSUE THREAD

**Issue by vincentw8460** [lindegroup/autopkgr#292]
I'm not sure if this has been asked before, but would it be possible to have the email notifications sent by AutoPkgr separate the new software by install type?

Say I have two recipes:
   * Add Thunderbird to a Munki repo

![screen shot 2015-02-26 at 12 32 02 am](https://cloud.githubusercontent.com/assets/6693452/6387369/e2fd31dc-bd4f-11e4-83f2-6f4d6d0ad9cc.png)

   * Install the Atom text editor onto the machine

![screen shot 2015-02-26 at 12 32 17 am](https://cloud.githubusercontent.com/assets/6693452/6387371/e8c4b3a6-bd4f-11e4-951b-67dd83ba1a64.png)

The email notification will tell me that there is new software available for testing like so:

```
The following software is now available for testing:

Thunderbird: 31.5.0
Atom: 0.183.0
```

Since those recipes do different things, would it be possible to have it the email message discern that?

```
The following software is now available for testing:

--- New Munki Software ---
Thunderbird: 31.5.0

--- New Installed Software ---
Atom: 0.183.0
```

**Comment by eahrold** [comment]
This is done on our side, but it requires AutoPkg 0.4.3.
