### ISSUE TITLE
Python UnicodeEncodeError with umlauts in recipe overrides

### ISSUE THREAD

**Issue by emilholt** [lindegroup/autopkgr#293]
Since version 1.2 we haven't been able to to use AutoPkgr as long as we have any eight bit ascii characters in our recipe overrides (for example an "ä" in a description field).
AutoPkgr throws this error:

A Python exception occurred during the execution of autopkg, see the console log for more details.

[ERROR] UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 43: ordinal not in range(128)

Running the same recipes and overrides just using autopkg from a shell works just fine.

**Comment by eahrold** [comment]
@emilholt, 
When you do `autopkg run` from a shell are you using the `--recipe-list` argument or are you just listing multiple single recipes?

**Comment by eahrold** [comment]
Also would it be possible for you to post a specific override you're having trouble with? I've not been able to reproduce.

**Comment by emilholt** [comment]
I've just been running `autopkg run --verbose Firefox.jss`

The Firefox.jss.recipie override looks like this:

```<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>Identifier</key>
        <string>local.jss.Firefox</string>
        <key>Input</key>
        <dict>
                <key>CATEGORY</key>
                <string>Webbläsare och internetverktyg</string>
                <key>DESCRIPTION</key>
                <string>Webbläsare.</string>
                <key>GROUP_NAME</key>
                <string>%NAME%-update-smart</string>
                <key>GROUP_TEMPLATE</key>
                <string>%RECIPE_DIR%/SmartGroupTemplate.xml</string>
                <key>ICON</key>
                <string>%RECIPE_DIR%/Firefox.png</string>
                <key>LOCALE</key>
                <string>sv_SE</string>
                <key>NAME</key>
                <string>Firefox</string>
                <key>POLICY_CATEGORY</key>
                <string>Testing</string>
                <key>POLICY_TEMPLATE</key>
                <string>%RECIPE_DIR%/PolicyTemplateNoSelfService.xml</string>
                <key>RELEASE</key>
                <string>latest</string>
        </dict>
        <key>ParentRecipe</key>
        <string>com.github.autopkg.jss.Firefox_EN</string>
</dict>
</plist>```

**Comment by eahrold** [comment]
Thanks,
Give it a try like this,

`autopkg run --verbose --recipe-list ~/Library/Application\ Support/AutoPkgr/recipe_list.txt`

And I'll test the override.

**Comment by emilholt** [comment]
`autopkg run --verbose --recipe-list ~/Library/Application\ Support/AutoPkgr/recipe_list.txt` went through without a hitch.

Thanks for your help!

**Comment by eahrold** [comment]
And now, without changing anything does AutoPkgr fail?

**Comment by emilholt** [comment]
Yup. While processing local.Firefox.jss.recipe:
![screen shot 2015-02-26 at 16 12 03](https://cloud.githubusercontent.com/assets/9348098/6394520/5009de1a-bdd2-11e4-8e84-58b2cbc25cf1.png)

**Comment by eahrold** [comment]
There should be a great big traceback in you system.log, mind posting that.

**Comment by emilholt** [comment]
Sure thing:


    Feb 26 16:11:37 macserv1 AutoPkgr[6880]: Processing local.jss.Firefox...
    Feb 26 16:11:39 macserv1 kernel[0]: hfs: summary table not allowed on FS with block size of 2048
    Feb 26 16:11:39 macserv1 kernel[0]: hfs: could not initialize summary table for Firefox
    Feb 26 16:11:39 macserv1 kernel[0]: hfs: mounted Firefox on device disk1s2
    Feb 26 16:11:40 macserv1 kernel[0]: hfs: unmount initiated on Firefox on device disk1s2
    Feb 26 16:11:40 macserv1 kernel[0]: hfs: summary table not allowed on FS with block size of 2048
    Feb 26 16:11:40 macserv1 kernel[0]: hfs: could not initialize summary table for Firefox
    Feb 26 16:11:40 macserv1 kernel[0]: hfs: mounted Firefox on device disk1s2
    Feb 26 16:11:53 macserv1 kernel[0]: hfs: unmount initiated on Firefox on device disk1s2
    Feb 26 16:11:53 macserv1 AutoPkgr[6880]: (FULL AUTOPKG TRACEBACK) 
	  File "/usr/local/bin/autopkg", line 1469, in <module>
	    sys.exit(main(sys.argv))
	  File "/usr/local/bin/autopkg", line 1463, in main
	    exit(subcommands[verb]['function'](argv))
	  File "/usr/local/bin/autopkg", line 1287, in run_recipes
	    autopackager.process(recipe)
	  File "/Library/AutoPkg/autopkglib/__init__.py", line 466, in process
	    self.env = processor.process()
	  File "/Library/AutoPkg/autopkglib/__init__.py", line 295, in process
	    self.main()
	  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 589, in main
	    self.category = self.handle_category("category")
	  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 253, in handle_category
	    (category_type, category_name))
	  File "/Library/AutoPkg/autopkglib/__init__.py", line 225, in output
	    print "%s: %s" % (self.__class__.__name__, msg)
	UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 43: ordinal not in range(128)`

**Comment by eahrold** [comment]
From this it looks like it may actually be the `CATEGORY` key causing the problem. However this still doesn't answer the question why it's only happening in AutoPkgr. It's most likely some environmental key set for your system that's not getting picked up by AutoPkgr. I'll do some more digging and see what I uncover.

Thanks for the report and keep you posted.
-- Eldon

**Comment by eahrold** [comment]
@emilholt,

if you feel like tinkering I think I found a fix.
You'll need to edit `/Library/AutoPkg/autopkglib/__init__.py`

Find line 225 which is the last line of this
```
    def output(self, msg, verbose_level=1):
        """Print a message if verbosity is >= verbose_level"""
        if self.env.get('verbose', 0) >= verbose_level:
            print "%s: %s" % (self.__class__.__name__, msg)
```

and change that line to this
```
            print "%s: %s" % (self.__class__.__name__.encode('utf-8'), msg.encode('utf-8'))
```

which is adding `.encode('utf-8')` to the end of both `self.__class__.__name__` and `msg`

I don't know how much experience with python you have, so make sure you exactly 12 spaces before the `print "...`

If this fixes it for you I'll get in touch with the autopkg team to see they have any ideas about best way to address this (what I have here is a very specific fix for only Processors, and the explicit encoding may make more sense higher up in the code chain).

Thanks.

**Comment by emilholt** [comment]
That worked like a charm, kept whitespace in mind while editing, thank you!

**Comment by eahrold** [comment]
Great!
I've got a pull request in for the change, so hopefully you won't need to modify that file after the next autopkg update.

**Comment by eahrold** [comment]
@emilholt 
I just closed the PR for the changes to the autopkg core, since it only happens with AutoPkgr (even though can be solved by altering autopkg) I'll keep this open and try to address the issue here.

**Comment by emilholt** [comment]
Just wanted to give a heads up that this bug keeps reappearing with every update to AutoPkgr (now with 0.6.0). The fix didn't make it upstream?
