### ISSUE TITLE
URLs aren't clickable in email notification errors

### ISSUE THREAD

**Issue by homebysix** [lindegroup/autopkgr#294]
The URLs in an email like this aren't clickable in many email apps because of the trailing colon.

> The following errors occurred:
> Couldn't download http://fpdownload.macromedia.com/get/shockwave/default/english/macosx/latest/Shockwave_Installer_Full_64bit.dmg: [Errno 54] Connection reset by peer
> Can't download http://fpdownload2.macromedia.com/get/flashplayer/update/current/xml/version_en_mac_pl.xml: HTTP Error 408: Request Time-out
> Couldn't download http://arduino.cc/download_handler.php?f=/arduino-1.6.0-macosx.zip:
> Couldn't download http://handbrake.fr/rotation.php?file=HandBrake-0.10.0-MacOSX.6_GUI_x86_64.dmg&update=true:

I think we should separate the URL from the colon in some way. Perhaps like this:

> Couldn't download http://handbrake.fr/rotation.php?file=HandBrake-0.10.0-MacOSX.6_GUI_x86_64.dmg&update=true (HTTP Error 408: Request Time-out)

**Comment by homebysix** [comment]
@eahrold I feel like the fix for this one is in [here](https://github.com/lindegroup/autopkgr/blob/master/AutoPkgr/Models/Email%20%26%20Notifications/LGAutoPkgReport.m#L278-L317) somewhere, but I can't see it.

In Pythonic terms, I want to change `"%s: %s" % (url, error)` to `"%s (%s)" % (url, error)`

**Comment by eahrold** [comment]
The report doesn't break it out into a nice `url` and `error` object, it's all one string.

```
Can't download http://fpdownload2.macromedia.com/get/flashplayer/update/current/xml/version_en_mac_pl.xml: HTTP Error 408: Request Time-out
```

You'd have to analyze the entire string, and only strip it for an actual URL.  We'd have to use a regex.

**Comment by homebysix** [comment]
Ugh, that's annoying. Even in the GitHub notification I received just now, the URL produces a 404 because of the trailing colon.

![screen shot 2015-08-14 at 9 20 38 am](https://cloud.githubusercontent.com/assets/7801391/9278477/d66d131a-4265-11e5-8ae0-42bbc9de535b.png)

Is it something we might suggest autopkg change, or is it a urllib2 thing?

Elliot

**Comment by eahrold** [comment]
https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/URLDownloader.py#L245

**Comment by homebysix** [comment]
https://github.com/autopkg/autopkg/pull/215

**Comment by eahrold** [comment]
Fixed upstream.
