### ISSUE TITLE
No valid recipe found

### ISSUE THREAD

**Issue by golbiga** [lindegroup/autopkgr#296]
I started receiving errors for certain recipes. 

The following errors occurred:
Could not find parent recipe for com.github.golbiga.jss.FirefoxAutoconfig
No valid recipe found for com.github.golbiga.jss.FirefoxAutoconfig. It has been automatically removed from your recipe list in order to prevent recurring errors.

Could not find parent recipe for com.github.sheagcraig.jss.pycharm
No valid recipe found for com.github.sheagcraig.jss.pycharm. It has been automatically removed from your recipe list in order to prevent recurring errors.

If i run these two recipes manually I do not receive any errors. As well these errors do not always occur, but once they do the recipes are removed from the recipe_list.txt. I've tried removing repos and re-adding them and the recipes. I've also edited the recipe_list.txt manualy with no luck. I'm not noticing any errors within Console.app as well. I ran, `/usr/bin/python /usr/local/bin/autopkg run --recipe-list ~/Library/Application\ Support/AutoPkgr/recipe_list.txt --report-plist /tmp/autopkg-test.xml` on the same system and the output has no errors.

**Comment by ungerjm** [comment]
I am seeing the same issue with my FirefoxAutoConfig recipe. I am running version Version 1.2 (683) on 10.9.5.

"Could not find parent recipe for local.jss.FirefoxAutoconfig

No valid recipe found for local.jss.FirefoxAutoconfig. It has been automatically removed from your recipe list in order to prevent recurring errors."

This morning I unchecked it and then rechecked it in the list.  It ran twice without error, I manually triggered the run in Autopkgr.  Then during the regularly scheduled update, the error appeared again.  I am also able to run it from Terminal without error.

Thanks!

**Comment by eahrold** [comment]
@ungerjm,
Can you confirm whether it's happening every time a scheduled run occurs, or is that random too?

**Comment by ungerjm** [comment]
@eahrold I can update you after the next scheduled run.  Should I deselect and reselect it again?  Or leave as is?

When it had errors over the weekend, I only got the error once, I believe it removed from the recipe list after that, so the error did not appear again until I made changes this morning.

**Comment by eahrold** [comment]
Do make sure it's in the recipe_list.txt file.

**Comment by golbiga** [comment]
I just adjusted my schedule to run every hour and re-added the firefox & pycharm recipes. I'll know in a hour if it fails or not.

**Comment by eahrold** [comment]
Thanks, I'm really curious to figure out why this is happening. It's only happening with these few recipes correct, not all the others.

**Comment by ungerjm** [comment]
confirmed it is in the txt file and adjusted the schedule to 1 hr as well.

And yes, this is the only recipe I'm seeing it on.  I am not using the other recipe, pycharm that @golbiga mentioned.

**Comment by golbiga** [comment]
Just got the errors on my next scheduled run.

The following errors occurred:
Could not find parent recipe for com.github.golbiga.jss.FirefoxAutoconfig

No valid recipe found for com.github.golbiga.jss.FirefoxAutoconfig. It has been automatically removed from your recipe list in order to prevent recurring errors.

Could not find parent recipe for com.github.sheagcraig.jss.pycharm

No valid recipe found for com.github.sheagcraig.jss.pycharm. It has been automatically removed from your recipe list in order to prevent recurring errors.

**Comment by eahrold** [comment]
Crazy, do you have "Check for repo updates when AutoPkgr starts" enabled. 
If so, try disabling that, re-enable the recipes, and see what happens after the next scheduled run.

**Comment by golbiga** [comment]
Happened again with those two recipes with "Check for repo updates when AutoPkgr starts". I can run them manually and no issues.

**Comment by eahrold** [comment]
OK, I'm digging, 

Also you can trigger the background run in the exact the same way the LaunchDaemon does by running
```
/Applications/AutoPkgr/Contents/MacOS/AutoPkgr -runInBackground YES
```
See if that produces the same results.

**Comment by ungerjm** [comment]
I too got the same errors on the scheduled run.  I'm away from my machine
and can't try the launch daemon now, but I'm happy to do it later.

**Comment by golbiga** [comment]
It does not fail when i trigger the background run.

**Comment by golbiga** [comment]
I forgot to leave out that I'm also running 1.2 on 10.9.5, not sure if it has anything to do with this.

**Comment by eahrold** [comment]
Ok, I'm about 73% sure I found the culprit. Let me know if this fixes things...
```
sudo killall cfprefsd
```

**Comment by golbiga** [comment]
Ok, i just re-enabled the receipes and restarts cfprefsd. I'll know on the next scheduled run.

**Comment by golbiga** [comment]
No errors, that looks like it fixed the issue.

**Comment by eahrold** [comment]
Yep, that''s what I was afraid of. 

Basically the defaults, even though synchronized and written to disk are not getting picked up when triggered by launchd, even though the launchd job is run as a user.

We should be putting up a 1.2.1 release soon, and we'll make sure to get the fix for this in.

**Comment by golbiga** [comment]
Thanks!
