### ISSUE TITLE
Could not mount distribution point

### ISSUE THREAD

**Issue by mgrevtech** [lindegroup/autopkgr#297]
@homebysix 
Attached are two log files from JSS, one for the Auto Update policy and one for Firefox AutoUpdate policy that I have setup, as an example.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Executing Policy Auto Update APPS...
Running script auto_update_magic.sh...
Script exit code: 0
Script result: Checking for apps that would block the Firefox update... /Library/Application Support/JAMF/tmp/auto_update_magic.sh: line 111: pgrep: command not found Firefox is not running. No apps are blocking the Firefox update. Calling policy trigger autoupdate-Firefox. Checking for policies triggered by "autoupdate-Firefox"... Executing Policy Auto Update Firefox 36.0... Mounting Casper Share to /Volumes/CasperShare 1... Error: Could not mount distribution point "Casper Share". Running Recon... Retrieving inventory preferences from https://casper.lanlocal.com:8443/... Locating hard drive information... Finding extension attributes... Locating applications... Locating accounts... Searching path: /Applications Locating software updates... Locating hardware information (Mac OS X 10.6.8)... Submitting data to https://casper.lanlocal.com:8443/... 2727 Submitting log to https://casper.lanlocal.com:8443/*******************************[TRIM]***********************************Checking for apps that would block the AdobeFlashPlayer update... /Library/Application Support/JAMF/tmp/auto_update_magic.sh: line 111: pgrep: command not found AdobeFlashPlayer is not running. No apps are blocking the AdobeFlashPlayer update. Calling policy trigger autoupdate-AdobeFlashPlayer. Checking for policies triggered by "autoupdate-AdobeFlashPlayer"... No policies were found for the "autoupdate-AdobeFlashPlayer" trigger.*****************************************[TRIM]***********************************Checking for apps that would block the iMovie update... /Library/Application Support/JAMF/tmp/auto_update_magic.sh: line 111: pgrep: command not found iMovie is not running. No apps are blocking the iMovie update. Calling policy trigger autoupdate-iMovie. Checking for policies triggered by "autoupdate-iMovie"... No policies were found for the "autoupdate-iMovie" trigger.
Running Recon...
Retrieving inventory preferences from https://casper.lanlocal.com:8443/...
Locating accounts...
Searching path: /Applications
Locating software updates...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Executing Policy Auto Update Firefox 36.0...
Mounting Casper Share to /Volumes/CasperShare 1...
Error: Could not mount distribution point "Casper Share".
Running Recon...
Retrieving inventory preferences from https://casper.lanlocal.com:8443/...
Locating accounts...
Searching path: /Applications
Locating software updates...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

So for some reason, NONE of the AutoUpdate policies work for any of the Apps like Firefox, Chrome, Java, etc. EXCEPT for AdobeFlashPlayer autoupdate, which works without any errors at all. I keep getting the same errors for all those Apps for all the computers in those specific groups, not even one computer is getting installed successfully. Again Flash is perfect.

Looking at the JSS logs tells me that the Policies for the non-working updates are not able to make the clients mount to the casper share. Searching for a related issue on the JAMF nation forums (https://jamfnation.jamfsoftware.com/discussion.html?id=10178) brings up issues regarding clients not able to mount casper shares if they have already been mounted on the same client for some reason (like another previous policy run), like a phantom share.

My probable theory is that AdobeFlash autoupdate works because -
1) they are using a different trigger like 'Check-in' only, compared to other apps which uses the auto-%RECIPE% trigger.
2) I am guessing the AdobeFlash policy is the first one to run, so they may have no issues as to the above mentioned phantom casper shares being already mounted.

My JSS server is windows-based (SMB). Your thoughts please?

**Comment by homebysix** [comment]
Hi @mgrevtech,

The following error tells me that something else has already mounted a volume called "CasperShare" on the target Mac.
```
Mounting Casper Share to /Volumes/CasperShare 1...
Error: Could not mount distribution point "Casper Share".
```
Could this Mac be running Casper Admin? Be sure to quit Casper Admin before autopkg runs.

If Casper Admin is not a factor, then it's likely that something is causing the sharepoint to fail to unmount after a successful recipe run, and the subsequent recipe then fails.

You can try removing AdobeFlashPlayer.jss from your recipe list to see whether the next policy (alphabetically) succeeds, to test this theory.

**Comment by mgrevtech** [comment]
Ok that theory did not work out. Rest of the apps still fails without AdobeFlashPlayer.jss

Do you mean the 'client macs' that I am runnning the policies on or the mac that I have on which autopkgr runs? My mac does have casper admin on it but it never runs while I am working on Autopkg. And I do a restart usually before running autopkg just to make sure.

What could be causing the mount points to fail on the clients? How would I diagnose?

**Comment by eahrold** [comment]
@mgrevtech, has this been solved by the latest JSSImporter.

**Comment by mgrevtech** [comment]
@eahrold Hey eldon, I had to enable HTTP distribution on our JSS eventually to workaround this issue. So I could not tell you for sure if it is fixed with SMB or not. When I get a chance, I could give it a try and turn off HTTP.
Anyways, Autopkgr has been working smoothly for me ever since. And with latest JSSimporter.
Thanks for following up on this!

**Comment by eahrold** [comment]
@mgrevtech I'm fairly sure it should be fixed now. I'll close this issue and if you do get a chance to test and are still experiencing the issue just re-open with any new details. 

Thanks.
