### ISSUE TITLE
Error running recipes

### ISSUE THREAD

**Issue by jimmymac641** [lindegroup/autopkgr#304]
A Python exception occurred during the execution of autopkg, see the console log for more details (pasted below).

[ERROR] jss.contrib.requests.exceptions.SSLError: [Errno 1]_ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed.
is the message returned from AutoPkgr, the jss has a self certificate which one would think should be sufficient. Included below is a paste of the console logs in the hopes that this might provide some helpful insight into this issue.

2015-03-05 9:03:16.348 AM AutoPkgr[72563]: (FULL AUTOPKG TRACEBACK) 
  File "/usr/local/bin/autopkg", line 1469, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 1463, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1287, in run_recipes
    autopackager.process(recipe)
  File "/Library/AutoPkg/autopkglib/__init__.py", line 466, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 295, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 642, in main
    suppress_warnings=suppress_warnings)
  File "/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/jss.py", line 154, in __init__
    self.distribution_points = distribution_points.DistributionPoints(self)
  File "/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/distribution_points.py", line 90, in __init__
    self.dp_info = self.jss.DistributionPoint().retrieve_all()
  File "/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/jss.py", line 311, in DistributionPoint
    return self.factory.get_object(DistributionPoint, data)
  File "/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/jss.py", line 462, in get_object
    result = self.jss.get(url)
  File "/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/jss.py", line 184, in get
    response = self.session.get(url)
  File "/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/sessions.py", line 473, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
jss.contrib.requests.exceptions.SSLError: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

**Comment by eahrold** [comment]
Usually AutoPkgr will set JSS_VERIFY_SSL key correctly. Couple of questions. 
1. Were you presented with a popup dialog to accept your certificate when you first configured the JSS with AutoPkgr?
2. What do you get when you do
   ```defaults read com.github.autopkg JSS_VERIFY_SSL```

**Comment by jimmymac641** [comment]
I can't remember it was a few months ago when I installed version 1.01 maybe and yesterday when I revisited this I noticed it was up to version 1.2 which is what I installed.
The reply of the query is a single integer 1

**Comment by eahrold** [comment]
OK, mind giving this a try. Go to the Folders & Integration tab and click "Connect" in the JSS config section.

You should be prompted with a Confirmation dialog. If you click "continue" the defaults read should return 0.

If it does not let us know, and you can always just set the key manually
```
defaults write com.github.autopkg JSS_VERIFY_SSL -bool False
```

Thanks

**Comment by jimmymac641** [comment]
So clicking "Connect" spawns the "Distribution Point Password Required" dialogue asking "Please enter read/write password for the "JSSshare" distribution point. If you intend to configure manually just click "Cancel"" to which I have 2 choices "Cancel" or "OK" If I choose cancel it deletes the distribution points I have. But the defaults read command at that point does indeed return a zero value. If however I provide my credentials and have at least one of my distribution points mounted the following error is generated save for the obvious xxxing out where appropriate the message is untouched.

2015-03-05 10:17:28.389 AM AutoPkgr[72563]: [DEBUG] Error [1] Error running recipes 
 /Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
mount_smbfs: server rejected the connection: Authentication error
A Python exception occurred during the execution of autopkg, see the console log for more details.

[ERROR] subprocess.CalledProcessError: Command '['mount', '-t', 'smbfs', '//XXXXJSS;xxxxjssa:xxxxxxxxxx@jss.xxxx.xxxxxxxxxxx.ca:139/JSS', '/Volumes/JSSshare-L-smbJSS']' returned non-zero exit status 77

**Comment by eahrold** [comment]
So the SSL warnings are just nagging now, not an actual error, and those can be fixed this way #243 

But now yo have a different error. 

The subprocess error is probably similar to they #236.
Special characters in the password should be fine, do you have any special characters in your username?

**Comment by jimmymac641** [comment]
So based on the suggestion the link to issue #243 I did the defaults write command to suppress warnings and contrarily it actually gave me more output than the previous error log. I am only attempting 1 package (Firefox.jss) and only have 2 repositories selected for my initial tests so I don't know where the seemingly repeated warnings are being generated from.

2015-03-05 1:12:29.169 PM AutoPkgr[735]: (FULL AUTOPKG TRACEBACK) 
  File "/usr/local/bin/autopkg", line 1469, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 1463, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1287, in run_recipes
    autopackager.process(recipe)
  File "/Library/AutoPkg/autopkglib/__init__.py", line 466, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 295, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 674, in main
    self.handle_icon()
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 559, in handle_icon
    icon.save()
  File "/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/jss.py", line 1181, in save
    self.jss._error_handler(JSSPostError, response)
  File "/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/jss.py", line 174, in _error_handler
    raise exception
jss.exceptions.JSSPostError: JSS Error. Response Code: 409	Response" Conflict
Unable to complete file upload.  File contents does not match file type.
2015-03-05 1:12:29.170 PM AutoPkgr[735]: [DEBUG] Error [1] Error running recipes 
 /Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
A Python exception occurred during the execution of autopkg, see the console log for more details.

[ERROR] Unable to complete file upload.  File contents does not match file type.

As was referenced in issue #236 I attempted to manually mount the share which was successful but was still seeing the same error output pasted above. Also from that post I manually ran autopkg run --recipe-list ~/Library/Application\ Support/AutoPkgr/recipe_list.txt --report-plist=/tmp/test.plist with this output

mfcfmac22:~ mfadmin$ autopkg run --recipe-list ~/Library/Application\ Support/AutoPkgr/recipe_list.txt --report-plist=/tmp/test.plist
Processing com.github.autopkg.jss.Firefox_EN...
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 1469, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 1463, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1287, in run_recipes
    autopackager.process(recipe)
  File "/Library/AutoPkg/autopkglib/__init__.py", line 466, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 295, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 674, in main
    self.handle_icon()
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 559, in handle_icon
    icon.save()
  File "/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/jss.py", line 1181, in save
    self.jss._error_handler(JSSPostError, response)
  File "/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/jss.py", line 174, in _error_handler
    raise exception
jss.exceptions.JSSPostError: JSS Error. Response Code: 409	Response" Conflict
Unable to complete file upload.  File contents does not match file type.

Which by all accounts looks like the equivalent output to me.

Also when the warnings are generated within the Autopkgr framework the dialogue extends beyond depth of display giving unsuspecting users no way of dismissing the dialogue. Obviously a return or enter on the keyboard is the way to dismiss it but that is not entirely intuitive sometimes.

Thanks with all of your assistance thus far.

**Comment by homebysix** [comment]
The `Unable to complete file upload. File contents does not match file type.` error makes me think it's having trouble uploading the Self Service icon file. Are you running Casper 9.65 by chance? If so, see this: https://groups.google.com/d/msg/autopkgr-discuss/_N5iXe4maFk/cJakARACZaAJ

Basically: skip the icon upload the first time (by overriding the key/value pair) and then upload the icon manually using the JSS web interface. Subsequent runs shouldn't produce the error.

**Comment by jimmymac641** [comment]
Actually running 9.64 but I will have a read and do as you suggest.

Thanks

**Comment by jimmymac641** [comment]
So in an attempt to circumvent a duplication or pre-existing condition error. I chose an application that we do not currently have packaged nor a policy for. One that has never been deployed here at all (Handbrake) The results seem to be similar.

2015-03-05 2:51:48.855 PM AutoPkgr[735]: (FULL AUTOPKG TRACEBACK) 
  File "/usr/local/bin/autopkg", line 1469, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 1463, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1287, in run_recipes
    autopackager.process(recipe)
  File "/Library/AutoPkg/autopkglib/__init__.py", line 466, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 295, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 674, in main
    self.handle_icon()
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 559, in handle_icon
    icon.save()
  File "/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/jss.py", line 1181, in save
    self.jss._error_handler(JSSPostError, response)
  File "/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/jss.py", line 174, in _error_handler
    raise exception
jss.exceptions.JSSPostError: JSS Error. Response Code: 409	Response" Conflict
Unable to complete file upload.  File contents does not match file type.
2015-03-05 2:51:49.719 PM sshd[4283]: error: PAM: authentication error for root from 103.41.124.108 via 129.97.6.22
2015-03-05 2:51:48.856 PM AutoPkgr[735]: [DEBUG] Error [1] Error running recipes 
 /Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
A Python exception occurred during the execution of autopkg, see the console log for more details.

[ERROR] Unable to complete file upload.  File contents does not match file type.

**Comment by jimmymac641** [comment]
Just an update to the Handbrake experiment. Running "run autopkg -vvv handbrake.download" and "run autopkg -vvv handbrake.pkg" execute without incident and the resultant package is added to Casper as expected. It is only when running the "run autopkg -vvv handbrake.jss" do I receive the error messages posted above.

**Comment by eahrold** [comment]
That would make sense. You're definitely experiencing a JSSImporter issue.

Did you do what Elliot suggested for the handbreak.jss override too?

**Comment by homebysix** [comment]
@jimmymac641 and just a clarification on this:

>Running "run autopkg -vvv handbrake.download" and "run autopkg -vvv handbrake.pkg" execute without incident and the resultant package is added to Casper as expected.

I wouldn't expect a .download or .pkg recipe to add anything to Casper. Only .jss recipes do that.

**Comment by jimmymac641** [comment]
I ended up sourcing and uploading the PNG manually and when testing a final time I am still left with this error message from AutoPkgr.

Thoughts?

2015-03-06 2:21:35.189 PM AutoPkgr[29325]: (FULL AUTOPKG TRACEBACK) 
  File "/usr/local/bin/autopkg", line 1469, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 1463, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1287, in run_recipes
    autopackager.process(recipe)
  File "/Library/AutoPkg/autopkglib/__init__.py", line 466, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 295, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 642, in main
    suppress_warnings=suppress_warnings)
  File "/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/jss.py", line 154, in __init__
    self.distribution_points = distribution_points.DistributionPoints(self)
  File "/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/distribution_points.py", line 90, in __init__
    self.dp_info = self.jss.DistributionPoint().retrieve_all()
  File "/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/jss.py", line 311, in DistributionPoint
    return self.factory.get_object(DistributionPoint, data)
  File "/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/jss.py", line 462, in get_object
    result = self.jss.get(url)
  File "/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/jss.py", line 184, in get
    response = self.session.get(url)
  File "/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/sessions.py", line 473, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
jss.contrib.requests.exceptions.SSLError: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
2015-03-06 2:21:35.190 PM AutoPkgr[29325]: [DEBUG] Error [1] Error running recipes 
 A Python exception occurred during the execution of autopkg, see the console log for more details.

[ERROR] jss.contrib.requests.exceptions.SSLError: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

**Comment by homebysix** [comment]
@jimmymac641 I know you already ran `defaults write com.github.autopkg JSS_VERIFY_SSL -bool False` but it might be good to try that one more time.

If that doesn't fix it, I'd recommend waiting just a while. A little birdie tells me that JSSImporter is about to get an update.

**Comment by jimmymac641** [comment]
Thanks for the assistance and heads up on the impending update. There was on other thing I am noticing the packages that uploaded/listed in Casper Admin, I notice there is no associated Checksum. Is this expected behaviour?

**Comment by homebysix** [comment]
Hi @jimmymac641. You may want to run the command @sheagcraig mentioned here to get the latest python-jss: https://twitter.com/shea_craig/status/573954102171860992

And yes, packages uploaded to Casper Admin will not have a checksum. That should not prevent deployment.

**Comment by jimmymac641** [comment]
Today, I attempted a fresh install of Autopkgr on a different computer and it detected the instance of Github installed and prompted to install Autopkg, however it did not subsequently prompt me to install the JSSImporter. I was trying download a different application this time (Evernote) because it was not one that we already had packaged. Even with verbose logging I only got a simple message "Error running recipes" I went autopkg and manually ran "autopkg run -vvv Evernote.download" followed by "autopkg run -vvv Evernote.pkg" both ran without issue when I ran the third command "autopkg run -vvv Evernote.jss" I received the following output
"Processing Evernote.jss...
Failed.
Receipt written to /tmp/receipts/Evernote-receipt-20150309-105134.plist
The following recipes failed:
Evernote.jss
Unknown processor 'JSSImporter'.
Nothing downloaded, packaged or imported."

I was expecting to have Autopkgr prompt me to allow installation of JSSImporter but that did not happen. Is this something that is common place or am I missing something?

**Comment by futureimperfect** [comment]
Hi @jimmymac641,

Do you have any JSS recipes selected in the Repos and Recipes tab? Also, what happens when you try checking an additional JSS recipe?

Thanks!

-- 
James Barclay

**Comment by jimmymac641** [comment]
Yes as above you can see that I initially tried with the Evernote.jss recipe, which caused me to run them manually from autopkg when the fail occurred in Autopkgr. I can try different .jss recipes if you think it is worth trying, however I'm trying to pick software that we don't currently have packaged or have never tested before so that the tests are pristine. I have tried Handbrake and Audacity but I can remove them from the Casper Admin and test those again if you think the results will be different than using Evernote as the guinea pig.

**Comment by eahrold** [comment]
It looks as thought you haven't installed JSSImporter on this new machine. Did you enter your JSS credentials in the `Folders & Integration` tab?

**Comment by jimmymac641** [comment]
Yes the credentials were there but the button was still yellow. I went and clicked connect and it did eventually turn green and ask to install the JSSImporter. 

Thank you I will now continue testing.

**Comment by jimmymac641** [comment]
This was result of testing "Handbrake" again

2015-03-09 12:21:17.624 PM AutoPkgr[14539]: [DEBUG] Error [3] Error running recipes 
 Couldn't download http://handbrake.fr/rotation.php?file=HandBrake-0.10.0-MacOSX.6_GUI_x86_64.dmg&update=true: HTTP Error 404: Not Found
Couldn't download http://handbrake.fr/rotation.php?file=HandBrake-0.10.0-MacOSX.6_GUI_x86_64.dmg&update=true: HTTP Error 404: Not Found
Couldn't download http://handbrake.fr/rotation.php?file=HandBrake-0.10.0-MacOSX.6_GUI_x86_64.dmg&update=true: HTTP Error 404: Not Found

**Comment by eahrold** [comment]
And in fact that link _is_ bad which means the recipe is in need of updating _or_ handbreak.fr fixes the link. So this is expected behavior. AutoPkgr is accurately reporting the results of the autopkg run.

**Comment by jimmymac641** [comment]
Strange, something must have happened over the weekend. I was not getting URL errors on Friday when testing that particular package. 
Thanks for the confirmation though.

**Comment by eahrold** [comment]
I actually see this exact thing quite often with handbreak, it should sort itself out in a day or two.

**Comment by homebysix** [comment]
Yeah, the Handbrake recipe is erroring out on several of my boxes right now.

**Comment by jimmymac641** [comment]
Just tried this out and Handbrake seems to be working once again. The problem now seems to be the policies don't seem to be populating on the scoped computers in Self Service, This however requires feedback from JAMF. Once I've worked through this with my JAMF rep I will comment again so the ticket may be marked as completed.
