### ISSUE TITLE
Email notification just show version number

### ISSUE THREAD

**Issue by SteveKueng** [lindegroup/autopkgr#307]
When I get a mail notification form autopkgr there are only version numbers and no software names like in the screenshot below:

![screen shot 2015-03-06 at 08 51 01](https://cloud.githubusercontent.com/assets/5426904/6521914/f509fba0-c3dd-11e4-98f2-0601a4937aeb.png)

**Comment by homebysix** [comment]
Hi @SteveKueng. What recipe did you run to produce this output? I'm guessing the %NAME% of the recipe is set to SW, so that's something that could be fixed with an override.

**Comment by SteveKueng** [comment]
hmm... that makes sense...
all our package names start with "SW_"
so the problem is the parsing... Is it possible to do change the parsing mechanism?

**Comment by homebysix** [comment]
Ah, I see. We're stopping at the underscore. @eahrold something we can do about this?

**Comment by eahrold** [comment]
We've been splitting at the underscore to handle situations like this...

------------------------------------------------------------------------

__The following software is now available for testing:__

__expander_5543:__ 5543
__Office2011-1448Update_EN-US:__ 1448

------------------------------------------------------------------------

Although maybe the above is OK if we catch more situations.

@homebysix when you get some time I've put up a DontBreakOnUnderscore branch, could you run it through your recipes and see if there are any adverse effects on the generated report?

Thanks

**Comment by homebysix** [comment]
I don't have any recipes with wandering underscores, but maybe @SteveKueng could give that branch a try? Steve, let me know if you want me to compile a release for you.

**Comment by SteveKueng** [comment]
Compile a release for me and I'll test it as soon as possible :)

**Comment by eahrold** [comment]
@homebysix, more I'm wondering if it breaks any current recipes (those we've been handling correctly to this point). I only ask because I think you run a wider range of recipes than I do.

If you don't see any real "breakage" and you're fine with the results showing up like illustrated above, I'd be fine making this change.
