### ISSUE TITLE
Feature Request: Allow "Check for Update" in Menu item

### ISSUE THREAD

**Issue by justinrummel** [lindegroup/autopkgr#312]
There is no way to force AutoPkgr to check for an update if you hide the dock icon.  You must unhide and then select AutoPkgr Menu Item => Check For Updates.

Suggestion is to include the option for "Check for Updates" in the Menu Item, or have a button to do this in the Preferences section. 

 - Justin

**Comment by eahrold** [comment]
@homebysix, we should really get this put in 1.3, any thoughts on where to put it?

**Comment by homebysix** [comment]
@eahrold How about "Check for AutoPkgr Updates..." right under "AutoPkgr Preferences..." since they will both spawn new windows.

**Comment by eahrold** [comment]
Done d02c4e1
