### ISSUE TITLE
Repos update, and then nothing happens

### ISSUE THREAD

**Issue by homebysix** [lindegroup/autopkgr#313]
I've seen this happen 2 or 3 times during my use of 1.2.1:

1. Launch AutoPkgr and click the menu bar icon > Run AutoPkg Now.
2. Observe that the repositories all update.
3. Observe that the progress gets stuck on the last repository, and does not continue to "Processing [recipe name]..."

Canceling and re-running seems to resolve this most times, but it would be nice to get to the bottom of it. No errors in the log output, just the standard repo-update stuff.

**Comment by Tecnico1931** [comment]
+1

**Comment by eahrold** [comment]
Does it seem to not doing the `autopkg run ...`, or just not updating the status in the menu?

**Comment by jumpkick** [comment]
I'm having a problem with "Run AutoPkg Now" as well...    It stalls at "Running Selected AutoPkg recipes"

Checked verbose logs, then ran as follows:
cd /Applications/AutoPkgr.app/Contents/MacOS && /AutoPkgr 

Gets stuck here:
  2015-03-18 13:36:39.858 AutoPkgr[5801:176306] [DEBUG] Completed AutoPkg Task:
    /usr/bin/python /usr/local/bin/autopkg version
  2015-03-18 13:37:35.372 AutoPkgr[5801:176306] [DEBUG] Received 'Check Now' menulet command.
  2015-03-18 13:37:35.669 AutoPkgr[5801:176306] [DEBUG] Completed AutoPkg Task:
    /usr/bin/python /usr/local/bin/autopkg version

If I run "/usr/bin/python /usr/local/bin/autopkg version" manually in a terminal I get "0.4.2"

**Comment by eahrold** [comment]
@jumpkick, is it possible you're having this issue?
https://github.com/lindegroup/autopkgr/issues/230

**Comment by homebysix** [comment]
@eahrold It seems not to be doing `autopkg run` at all. The status in the menu sticks, but I don't see packages appear in the Cache folder.

@jumpkick I'm with Eldon, I think that sounds like a different issue than the one @Tecnico1931 and I are having.

**Comment by jumpkick** [comment]
@eahrold @homebysix you guys are right it's #230.  I quit chrome and I was able to get AutoPkgr to run autopkg.   My bad, sorry about that.

**Comment by eahrold** [comment]
@homebysix, @Tecnico1931  what's the last `[DEBUG]` message you see before things seem to stall out?

**Comment by eahrold** [comment]
@homebysix, were you able to get more info on this?

**Comment by homebysix** [comment]
Nope, hasn't happened since.

**Comment by homebysix** [comment]
I finally saw this happen again while testing 1.2.2. Here's what I did:

1. Opened AutoPkgr.
2. Clicked "Update Repos Now," waited until completion.
3. Click "Run AutoPkg Now."

The app got stuck at the following:
![screen shot 2015-04-16 at 11 35 41 am](https://cloud.githubusercontent.com/assets/7801391/7188475/e72fc3d8-e42c-11e4-843b-3f600b0443a7.png)

Here's the log output, including debug logs:
```
4/16/15 11:25:51.787 AM AutoPkgr[7019]: Welcome to AutoPkgr!
4/16/15 11:25:51.791 AM AutoPkgr[7019]: [DEBUG] Verbose logging is active. To deactivate, option-click the AutoPkgr menu icon and uncheck Verbose Logs.
4/16/15 11:25:51.791 AM AutoPkgr[7019]: [DEBUG] Starting AutoPkgr menu bar icon...
4/16/15 11:25:53.047 AM WindowServer[199]: disable_update_timeout: UI updates were forcibly disabled by application "AutoPkgr" for over 1.00 seconds. Server has re-enabled them.
4/16/15 11:25:53.068 AM WindowServer[199]: common_reenable_update: UI updates were finally reenabled by application "AutoPkgr" after 1.02 seconds (server forcibly re-enabled them after 1.00 seconds)
4/16/15 11:25:53.074 AM AutoPkgr[7019]: [DEBUG] AutoPkgr menu bar icon started.
4/16/15 11:26:03.536 AM AutoPkgr[7019]: [DEBUG] Populating configuration window settings based on user defaults, if they exist.
4/16/15 11:26:03.640 AM AutoPkgr[7019]: [DEBUG] Activated AutoPkgr configuration window.
4/16/15 11:26:03.641 AM AutoPkgr[7019]: [DEBUG] Using Git installed via Xcode command line tools.
4/16/15 11:26:03.741 AM AutoPkgr[7019]: [DEBUG] Completed AutoPkg Task:
  /usr/bin/python /usr/local/bin/autopkg repo-list
4/16/15 11:26:03.951 AM AutoPkgr[7019]: Bartender: Loaded BartenderHelperEightyEight
4/16/15 11:26:04.119 AM com.lindegroup.AutoPkgr.helper[7022]:  securityd_message_with_reply_sync Failed to talk to secd after 4 attempts.
4/16/15 11:26:04.128 AM com.lindegroup.AutoPkgr.helper[7022]:  SecOSStatusWith error:[-25291] The operation couldn’t be completed. (com.apple.security.xpc error 3 - <connection: 0x7f8148624710> { name = com.apple.securityd.xpc, listener = false, pid = 0, euid = 4294967295, egid = 4294967295, asid = 4294967295 }: Connection invalid)
4/16/15 11:26:04.355 AM secd[391]:  securityd_xpc_dictionary_handler AutoPkgr[7019] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
4/16/15 11:26:04.356 AM AutoPkgr[7019]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))
4/16/15 11:26:04.722 AM AutoPkgr[7019]: [DEBUG] The JSS is responding and API user credentials seem valid.
4/16/15 11:26:04.723 AM AutoPkgr[7019]: Stopping Port Test.
4/16/15 11:26:35.392 AM AutoPkgr[7019]: [DEBUG] Using Git installed via Xcode command line tools.
4/16/15 11:26:36.908 AM AutoPkgr[7019]: [DEBUG] Using Git installed via Xcode command line tools.
4/16/15 11:26:39.169 AM AutoPkgr[7019]: [DEBUG] Completed AutoPkg Task:
  /usr/bin/python /usr/local/bin/autopkg version
4/16/15 11:33:26.388 AM AutoPkgr[7019]: [DEBUG] Activated AutoPkgr configuration window.
4/16/15 11:34:27.875 AM AutoPkgr[7019]: [DEBUG] Activated AutoPkgr configuration window.
```

I don't see anything in the logs about either `autopkg repo-update` or `autopkg run` finishing. Any ideas, @eahrold ?

**Comment by homebysix** [comment]
I may have found a clue in Activity Monitor. Here's what it looked like while AutoPkgr was running:
![screen shot 2015-04-16 at 12 40 42 pm](https://cloud.githubusercontent.com/assets/7801391/7189760/f618bd7e-e435-11e4-94c4-1170881f2a1e.png)

And here's what it look like after I quit AutoPkgr:
![screen shot 2015-04-16 at 12 41 00 pm](https://cloud.githubusercontent.com/assets/7801391/7189764/fdf5b010-e435-11e4-8a99-d1ec9369e49f.png)

Could it be that the app isn't quitting cleanly?

**Comment by eahrold** [comment]
Could the second process is be a hung background run that's having the exact same issue as the main app and stalling out on 'autopkg run`.

And you're not running Chrome? It looks like it's hanging at the exact same place as [above](https://github.com/lindegroup/autopkgr/issues/313#issuecomment-83079979)

How reproducible is this for you at this time? Doing it constantly?

**Comment by homebysix** [comment]
Dammit, I thought I had proved that Chrome was uninvolved. However, you're right — when I quit Chrome, it started working again.

OK, let's focus on #230. I'll open this up if I get it to misbehave without Chrome running.
