### ISSUE TITLE
Truncation of Package names in email notifications

### ISSUE THREAD

**Issue by everetteallen** [lindegroup/autopkgr#315]
I am seeing packages that I name with dashes (-) in them have the name truncated at the first dash in the email text.
Example email---
The following software is now available for testing:

UNCSystem: 36.0.1
---
Package name:
UNCSystem-AutoPKGR-Firefox-36.0.1.pkg

For the record the prefix is a string added in an override recipe.

Maybe there is an email template I need to adjust?

**Comment by homebysix** [comment]
Hi @everetteallen -

We're using the %VERSION% information if autopkg provides it (which is usually the case if a .pkg recipe has run). However, when that's not available, we're falling back on other methods to parse the version.

Munki's standard nomenclature is SoftwarePackageName-1.2.3 with the name and version separated by a dash. @eahrold might be able to say for sure, but I suspect we're trying to parse for that format as one of our fallback options.

**Comment by eahrold** [comment]
@everetteallen this is the same as Here #307.
This branch should fix that issue https://github.com/lindegroup/autopkgr/tree/v1.2.2-DontBreakOnUnderscore.

@homebysix did you have a chance to test drive that branch to see if the results were OK by you?

**Comment by everetteallen** [comment]
Looks like this fixes my issue. Any timing on 1.2.2 ?  This is the last issue keeping me from moving to production package pump.

**Comment by eahrold** [comment]
@everetteallen,
So AutoPkg 0.4.3 is currently in the works which includes an overhaul to the `--report-plist` we use to generate the e-mail text.  We may put out a smaller 1.2.2 than originally planned to get ahead of that change, but it's hard to say exactly when. 

@homebysix what do you think, want to try for next week?

**Comment by homebysix** [comment]
@eahrold Sounds good to me. Let's keep 1.2.2 limited to just the `--report-plist` change.
