### ISSUE TITLE
Error when trying to re run workflow

### ISSUE THREAD

**Issue by mtaylor934** [lindegroup/autopkgr#317]
Hi,

I'll begin by saying this might just be something I am doing wrong or not know how to do.

Just investigating the Self Service safe method and was able to get it working. Had a few questions / issues:

1) The username and password required for the JSSImporter, does this account also need to exist in AD with read/write permissions for the DP?
2) Successfully ran the workflow for one Adobe Flash Player package. I ticked 10 more .jss recipes and tried to run again, but then get an error detailing object already exists. Cleared JSS of anything related (except Testing group) and still get the error. Have included it below. Will this happen every time unless each package has an update?

But apart from the above, this is an absolutely brilliant workflow. Kudos to everyone who contributed!

![image](https://cloud.githubusercontent.com/assets/11530159/6771788/5e30f396-d13e-11e4-8c72-d26b73683cc0.png)

**Comment by jhowe-sgs** [comment]
I am seeing similar behavior.

Mac OS X 10.9.5
Git 1.9.5
AutoPkg 0.4.2
AutoPkgr 1.2.1

Steps to reproduce.

1. Open AutoPkgr Preferences...
2. Click on **"Repos & Recipes"**
3. Enable https://github.com/autopkg/recipes.git
  * Enable AdobeFlashPlayer.download
  * Enable GoogleChrome.download
  * Enable Handbrake.download
  * Enable Silverlight.download
  * Enable TextWrangler.download
  * Enable Thunderbird.download
  * Enable VLC.download
4. Click on **Schedule**
5. Click on **"Update Repos Now"**

Expected:

All specified download sources are checked. Process exits normally.

Actual: 

A window pops up with **"Running selected AutoPkg recipes."**. Runs indefinitely until process is cancelled.

**Comment by homebysix** [comment]
Hi @mtaylor934,

The username and password required for JSSImporter is for an account with access to the Casper API. Check out [step 2 here](https://github.com/lindegroup/autopkgr#integration-with-casper) to see the specific permissions the account requires.

The account should not need to exist anywhere else. As long as the JSS knows the credentials, it will pass them along to the API user.

I notice you're using python-jss 0.5.7. That probably means your JSSImporter is out of date. If you quit and relaunch AutoPkgr, it should prompt you to install the JSSImporter update. (Or you can download it manually from [here](https://github.com/sheagcraig/JSSImporter/releases/latest).)

Also try running this from Terminal to see if you get the same error:
```
autopkg run AdobeFlashPlayer.jss -v
```

**Comment by mtaylor934** [comment]
Thanks for the reply.

It seems the process if falling over at a couple of different stages.

1)  If a recipe tries to run and the targeted software has not updated since last time, you will get the Object Conflict error (have tested new recipes to work fine, but reoccurring ones do not).  Is there a setting I am missing for this? (this is in regard to your tip to run the recipe manually)

2)  When the JSS Importer tries to mount the Dist. Point, I get an authentication error.  Is this process pulling the credentials of the logged in user (the account I am using is local)?  I have verified this can be fixed by mounting the share first using AD credentials, however as the share unmounts afterwards and does not use the same credentials next time this is not a permanent solution.

3)  I have been able to get past steps 1 and 2, to the point where a package and category is created in Casper.  However, this is no longer creating policies targeting the smart group.  I have verified the set up in JSS, however we have upgraded to Casper 9.65 since I last attempted so I am assuming this has broken something.

I have verified my JSSImporter is v0.3.7 (the most recent).  Is there something else needing an upgrade perhaps? (Python is only v2.7.6 etc).

Thanks again for your help.

**Comment by homebysix** [comment]
Hi @mtaylor934,

Regarding __1)__ When a .jss recipe runs for the first time, the `-v` output will look something like this:
```
JSSImporter
JSSImporter: Category type: category-'Digital Media' already exists according to JSS, moving on...
JSSImporter: Category type: policy_category-'Testing' already exists according to JSS, moving on...
JSSImporter: Copying /Users/elliot/Library/AutoPkg/Cache/com.github.autopkg.jss.FlashPlayerExtractPackage/AdobeFlashPlayer-17.0.0.169.pkg to all distribution points.
JSSImporter: Copied /Users/elliot/Library/AutoPkg/Cache/com.github.autopkg.jss.FlashPlayerExtractPackage/AdobeFlashPlayer-17.0.0.169.pkg
JSSImporter: ComputerExtensionAttribute: AdobeFlashVersion created.
JSSImporter: ComputerGroup: AdobeFlashPlayerUpdate-smart created.
JSSImporter: Policy: Install Latest AdobeFlashPlayer created.
JSSImporter: Icon uploaded to JSS.
Receipt written to /Users/elliot/Library/AutoPkg/Cache/com.github.autopkg.jss.FlashPlayerExtractPackage/receipts/AdobeFlashPlayer-receipt-20150424-113434.plist
```
On subsequent runs, you'll see "Package upload not needed." The processor will also skip other unneeded steps, like uploading the icon and creating the smart group:
```
JSSImporter
JSSImporter: Category type: category-'Digital Media' already exists according to JSS, moving on...
JSSImporter: Category type: policy_category-'Testing' already exists according to JSS, moving on...
JSSImporter: Pkg-object already exists according to JSS, moving on...
JSSImporter: Package upload not needed.
JSSImporter: ComputerExtensionAttribute: AdobeFlashVersion updated.
JSSImporter: ComputerGroup: AdobeFlashPlayerUpdate-smart updated.
JSSImporter: Policy: Install Latest AdobeFlashPlayer updated.
JSSImporter: Icon matches existing icon, moving on...
Receipt written to /Users/elliot/Library/AutoPkg/Cache/com.github.autopkg.jss.FlashPlayerExtractPackage/receipts/AdobeFlashPlayer-receipt-20150424-113505.plist
```
I'd be curious to see the JSSImporter output from your `autopkg run AdobeFlashPlayer.jss -v` to see whether it looks like either of the above.

Regarding __2)__ The sharepoint credentials are separate from the API credentials. Sounds like you need to put your AD credentials in the sharepoint connection information. In AutoPkgr, go to Folders & Integration, click on your sharepoint, and click the Edit Selected button. Try putting your AD credentials there to see whether it connects without any problems next time.

Regarding __3)__ I don't have a 9.65 JSS to test on at the moment, but AdobeFlashPlayer.jss works fine on my test 9.7 environment. So, first take a look at your .jss recipe overrides to make sure they are pointing to the correct SmartGroupTemplate.xml file, make sure the SmartGroupTemplate.xml is present in your RecipeOverrides folder, and inspect the SmartGroupTemplate.xml file to make sure it's set up the way you want. If all those things are good (and especially if they were working unchanged when you were on a previous version of the JSS) then it could very well be 9.65-related.

**Comment by homebysix** [comment]
Hi @mtaylor934 — any news on this issue?
