### ISSUE TITLE
"This class is not key value coding-compliant for the key Service Description"

### ISSUE THREAD

**Issue by homebysix** [lindegroup/autopkgr#319]
Saw this exception in my logs today:
```
[...]
3/26/15 2:47:15.493 PM AutoPkgr[8131]: Attempting git pull for /Users/elliot/Library/AutoPkg/RecipeRepos/com.github.autopkg.nmcspadden-recipes...
3/26/15 2:47:17.413 PM AutoPkgr[8131]: Attempting git pull for /Users/elliot/Library/AutoPkg/RecipeRepos/com.github.autopkg.jps3-recipes...
3/26/15 2:47:18.126 PM AutoPkgr[8131]: Attempting git pull for /Users/elliot/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes...
3/26/15 2:48:45.581 PM AutoPkgr[8131]: Exception Raised: [<AHLaunchJob 0x7f86724a6550> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key Service Description.
3/26/15 2:48:51.347 PM AutoPkgr[8131]: Processing com.github.autopkg.munki.firefox-rc-en_US...
3/26/15 2:48:58.147 PM AutoPkgr[8131]: Processing com.github.autopkg.munki.google-chrome...
3/26/15 2:49:02.642 PM AutoPkgr[8131]: Processing com.github.autopkg.munki.FlashPlayerNoRepackage...
[...]
```
Any ideas where that's happening?

**Comment by eahrold** [comment]
I this this is that Carbon Copy Cloner launchd.plist issue. Are you running CCC on this machine?

**Comment by eahrold** [comment]
@homebysix, was this during background run or when triggered manually?

**Comment by homebysix** [comment]
The CCC app is installed, but no schedules are active. `sudo launchctl list | grep ccc` shows no results.

**Comment by homebysix** [comment]
This happened when manually clicking Run AutoPkg Now from the configuration window (not the menu).

**Comment by eahrold** [comment]
Would you mind going over your launchd.plist files and seeing if any have a key called `Service Description` with a space. I'm guessing you have one with an incorrect key that should be `ServiceDescription` with no space, and changing this would put a band-aid on the issue.

Also I'm pretty sure it's unrelated to the autopkg run, and actually happens because of the firstResponder in the UI. 

Either way, I'll touch up the AHLaunchJob framework to make it a bit more fault tolerant for LaunchD.plist with unknown keys.

Thanks.

**Comment by homebysix** [comment]
Sure enough:
```
$ grep -R "Service Description" /Library/LaunchDaemons/
/Library/LaunchDaemons//com.meraki.agentd.plist:        <key>Service Description</key>
```
I'll back up the original, change it to `ServiceDescription`, and unload/reload it.

**Comment by eahrold** [comment]
I just went over the AHLaunchJob class and realized I'm already catching the exception, and just logging it https://github.com/eahrold/AHLaunchCtl/blob/master/AHLaunchCtl/AHLaunchJob.m#L297-L302

So it's not that crucial, I'll put a debug wrapper around it so it doesn't log on release builds.
