### ISSUE TITLE
Update Repos Now timeouts with simple download recipes

### ISSUE THREAD

**Issue by jhowe-sgs** [lindegroup/autopkgr#321]
I am currently seeing this behavior. It also appears that scheduled process are not running either ( I noticed when I missed a Chrome update ).

Mac OS X 10.9.5
Git 1.9.5
AutoPkg 0.4.2
AutoPkgr 1.2.1

Steps to reproduce.

1. Open AutoPkgr Preferences...
2. Click on **"Repos & Recipes"**
3. Enable https://github.com/autopkg/recipes.git
  * Enable AdobeFlashPlayer.download
  * Enable GoogleChrome.download
  * Enable Handbrake.download
  * Enable Silverlight.download
  * Enable TextWrangler.download
  * Enable Thunderbird.download
  * Enable VLC.download
4. Click on **Schedule**
5. Click on **"Update Repos Now"**

Expected:

All specified download sources are checked. Process exits normally.

Actual: 

A window pops up with **"Running selected AutoPkg recipes."**. Runs indefinitely until process is cancelled.

**Comment by eahrold** [comment]
@jhowe-sgs, Could it be the same as issue #230?

**Comment by jhowe-sgs** [comment]
Yes, quit Google Chrome 41.0.2272.89 and "Update Repos Now" processes correctly.

Reinstalled Chrome Version 41.0.2272.104 (64-bit) and Autopkgr runs as expected.

That's evil Google Chrome.

**Comment by eahrold** [comment]
That's funny you say that.
The branch I use to try and solve this issue is this...
https://github.com/eahrold/autopkgr/tree/v1.2-evil-chrome

**Comment by jhowe-sgs** [comment]
Did I say Chrome Version 41.0.2272 fixed this? It crept back again. I leave my browser running for several days at a time. I noticed I wasn't getting updates again. Quick Chrome, and update work again. Some sort of long running Chrome cron evil?

**Comment by eahrold** [comment]
Not surprising, same with #230, and it's been perplexing. Once I am able to reproduce it on one of my dev machines I should be able to fix it, but until then I'm not sure what else to do. If you come up with any specific conditions which reproduce it such as specific open tabs, logged in accounts, etc... please let us know and keep trying to make it happen.

But I'll start by trying to leave chrome open for longer periods of time, and see if that rattles any cages.

Thanks...

**Comment by jhowe-sgs** [comment]
I tend to hyper-browse as well ( multiple windows open with multiple tabs ). What happened to Chrome sandboxing everything?

**Comment by eahrold** [comment]
@jhowe-sgs, 
Any more info you can provide please post to  #230.
