### ISSUE TITLE
Error running update

### ISSUE THREAD

**Issue by parm75** [lindegroup/autopkgr#323]
Hi, Can anyone explain why I get this error??

Thanks

Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 1469, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 1463, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1287, in run_recipes
    autopackager.process(recipe)
  File "/Library/AutoPkg/autopkglib/__init__.py", line 466, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 295, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 711, in main
    self.policy = self.handle_policy()
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 609, in handle_policy
    added_env="jss_policy_updated")
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 469, in _update_or_create_new
    recipe_object = obj_cls.from_string(self.j, template)
  File "/Library/Python/2.7/site-packages/python_jss-0.5.9-py2.7.egg/jss/jss.py", line 794, in from_string
    root = ElementTree.fromstring(xml_string)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 9, column 42

**Comment by homebysix** [comment]
HI @parm75, do you know what recipe triggered this error? You can run this command in Terminal to find out:
```
/usr/bin/python /usr/local/bin/autopkg run --recipe-list ~/Library/Application\ Support/AutoPkgr/recipe_list.txt --report-plist /tmp/autopkg-test.xml
```

**Comment by parm75** [comment]
Hi @homebysix,

I only have one as we are testing autopkgr and autopkg. It'll be Firefox

thanks

PArm

**Comment by homebysix** [comment]
Which `Firefox.jss` recipe is it? The default is [Shea Craig's recipe](https://github.com/sheagcraig/jss-recipes/blob/master/Firefox.jss.recipe), but there are also `Firefox.jss` recipes available in novaksam-recipes and rtrouton-recipes.

And you've got the latest version (1.2.1) of AutoPkgr? Which version of Casper?

**Comment by parm75** [comment]
So: 
Casper is 9.65
Autopkgr is 1.2.1
the recipe is Shea's
Thanks

**Comment by homebysix** [comment]
How are your distribution points set up? For example, they could be file share distribution points, JDSs, or cloud distribution points.

**Comment by parm75** [comment]
they are all FDP's. I'm only targeting one at the moment, the other two are not listed in autopkgr window.

**Comment by homebysix** [comment]
Did the error happen again when you ran the `autopkg` command above in Terminal? Or did that one go through OK?

**Comment by parm75** [comment]
yup, same error in terminal.

**Comment by homebysix** [comment]
If it also happens at the Terminal, I suspect it's not related to AutoPkgr. Maybe if we summon the wisdom of @sheagcraig, he can suggest how we can troubleshoot the Python traceback.

**Comment by sheagcraig** [comment]
The traceback says: ```xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 9, column 42``` while it's trying to build a new policy.

Since this recipe works just fine here, I imagine that something that has been injected into it is causing invalid XML. I would look for any non alphanumeric characters in any of the values that would end up in the policy.

Are you using any overrides?

Can you post the sanitized (i.e. remove passwords, urls, etc) results of an ```autopkg run -vvvv Firefox.jss``` run?

**Comment by parm75** [comment]
Hi, I am using overrides, here is the run details:

MACTEST2:~ cusdb$ autopkg run -vvvv Firefox.jss
Processing Firefox.jss...
{u'API_PASSWORD': u'@V620hpr',
 u'API_USERNAME': u'autoupdate',
 'AUTOPKG_VERSION': u'0.4.2',
 u'CATEGORY': u'Productivity',
 u'DESCRIPTION': u'Web Browser.',
 u'GIT_PATH': u'/usr/local/git/bin/git',
 u'GROUP_NAME': u'Firefox-update-smart',
 u'GROUP_TEMPLATE': u'/Users/cusdb/Library/AutoPkg/RecipeOverrides/SmartGroupTemplate.xml',
 u'ICON': u'/Users/cusdb/Library/AutoPkg/RecipeOverrides/Firefox.png',
 u'JSS_REPOS': [{
    name = casperdp3;
    password = "@V620hprCdp3";
}],
 u'JSS_URL': u'https://jss01.lifesci.warwick.ac.uk:8443',
 u'JSS_VERIFY_SSL': False,
 u'LOCALE': u'en_US',
 u'NAME': u'Firefox',
 'PARENT_RECIPES': [u'/Users/cusdb/Library/AutoPkg/RecipeRepos/com.github.sheagcraig.jss-recipes/Firefox.jss.recipe',
                    u'/Users/cusdb/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/Mozilla/Firefox.pkg.recipe',
                    u'/Users/cusdb/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/Mozilla/Firefox.download.recipe'],
 u'POLICY_CATEGORY': u'Auto Update',
 u'POLICY_TEMPLATE': u'/Users/cusdb/Library/AutoPkg/RecipeOverrides/PolicyTemplate.xml',
 'RECIPE_CACHE_DIR': u'/Users/cusdb/Library/AutoPkg/Cache/local.jss.Firefox',
 'RECIPE_DIR': '/Users/cusdb/Library/AutoPkg/RecipeOverrides',
 'RECIPE_OVERRIDE_DIRS': ['~/Library/AutoPkg/RecipeOverrides'],
 'RECIPE_PATH': '/Users/cusdb/Library/AutoPkg/RecipeOverrides/Firefox.jss.recipe',
 u'RECIPE_REPOS': {u'/Users/cusdb/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes': {
    URL = "https://github.com/autopkg/recipes.git";
},
                   u'/Users/cusdb/Library/AutoPkg/RecipeRepos/com.github.sheagcraig.jss-recipes': {
    URL = "https://github.com/sheagcraig/jss-recipes.git";
}},
 u'RECIPE_SEARCH_DIRS': [u'.',
                         u'/Users/cusdb/Library/AutoPkg/RecipeRepos/com.github.sheagcraig.jss-recipes',
                         u'/Users/cusdb/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes',
                         '/Users/cusdb/Library/AutoPkg/RecipeOverrides',
                         u'/Users/cusdb/Library/AutoPkg/RecipeRepos/com.github.sheagcraig.jss-recipes',
                         u'/Users/cusdb/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/Mozilla'],
 u'RELEASE': u'latest',
 'verbose': 4}
MozillaURLProvider
{'Input': {'locale': u'en_US',
           'product_name': u'firefox',
           'release': u'latest'}}
MozillaURLProvider: Found URL http://ftp.mozilla.org/pub/mozilla.org/firefox/releases/latest/mac/en-US/Firefox%2037.0.dmg
{'Output': {'url': u'http://ftp.mozilla.org/pub/mozilla.org/firefox/releases/latest/mac/en-US/Firefox%2037.0.dmg'}}
URLDownloader
{'Input': {'filename': u'Firefox.dmg',
           'url': u'http://ftp.mozilla.org/pub/mozilla.org/firefox/releases/latest/mac/en-US/Firefox%2037.0.dmg'}}
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing /Users/cusdb/Library/AutoPkg/Cache/local.jss.Firefox/downloads/Firefox.dmg
{'Output': {'pathname': u'/Users/cusdb/Library/AutoPkg/Cache/local.jss.Firefox/downloads/Firefox.dmg'}}
EndOfCheckPhase
{'Input': {}}
{'Output': {}}
AppDmgVersioner
{'Input': {'dmg_path': u'/Users/cusdb/Library/AutoPkg/Cache/local.jss.Firefox/downloads/Firefox.dmg'}}
AppDmgVersioner: Mounted disk image /Users/cusdb/Library/AutoPkg/Cache/local.jss.Firefox/downloads/Firefox.dmg
AppDmgVersioner: BundleID: org.mozilla.firefox
AppDmgVersioner: Version: 37.0
{'Output': {'app_name': u'Firefox.app',
            'bundleid': u'org.mozilla.firefox',
            'version': u'37.0'}}
PkgRootCreator
{'Input': {'pkgdirs': {
    Applications = 0775;
},
           'pkgroot': u'/Users/cusdb/Library/AutoPkg/Cache/local.jss.Firefox/Firefox'}}
PkgRootCreator: Created /Users/cusdb/Library/AutoPkg/Cache/local.jss.Firefox/Firefox
PkgRootCreator: Creating Applications
PkgRootCreator: Created /Users/cusdb/Library/AutoPkg/Cache/local.jss.Firefox/Firefox/Applications
{'Output': {}}
Copier
{'Input': {'destination_path': u'/Users/cusdb/Library/AutoPkg/Cache/local.jss.Firefox/Firefox/Applications/Firefox.app',
           'source_path': u'/Users/cusdb/Library/AutoPkg/Cache/local.jss.Firefox/downloads/Firefox.dmg/Firefox.app'}}
Copier: Mounted disk image /Users/cusdb/Library/AutoPkg/Cache/local.jss.Firefox/downloads/Firefox.dmg
Copier: Copied /private/tmp/dmg.UqAFPg/Firefox.app to /Users/cusdb/Library/AutoPkg/Cache/local.jss.Firefox/Firefox/Applications/Firefox.app
{'Output': {}}
PkgCreator
{'Input': {'pkg_request': {
    chown =     (
                {
            group = admin;
            path = Applications;
            user = root;
        }
    );
    id = "org.mozilla.firefox.pkg";
    options = "purge_ds_store";
    pkgdir = "/Users/cusdb/Library/AutoPkg/Cache/local.jss.Firefox";
}}}
PkgCreator: Package already exists at path /Users/cusdb/Library/AutoPkg/Cache/local.jss.Firefox/Firefox-37.0.pkg.
PkgCreator: Existing package matches version and identifier, not building.
{'Output': {'pkg_path': u'/Users/cusdb/Library/AutoPkg/Cache/local.jss.Firefox/Firefox-37.0.pkg'}}
JSSImporter
{'Input': {'API_PASSWORD': u'@V620hpr',
           'API_USERNAME': u'autoupdate',
           'JSS_REPOS': [{
    name = casperdp3;
    password = "@V620hprCdp3";
}],
           'JSS_URL': u'https://jss01.lifesci.warwick.ac.uk:8443',
           'JSS_VERIFY_SSL': False,
           'category': u'Productivity',
           'groups': (
        {
        name = "Firefox-update-smart";
        smart = 1;
        "template_path" = "/Users/cusdb/Library/AutoPkg/RecipeOverrides/SmartGroupTemplate.xml";
    }
),
           'pkg_path': u'/Users/cusdb/Library/AutoPkg/Cache/local.jss.Firefox/Firefox-37.0.pkg',
           'policy_category': u'Auto Update',
           'policy_template': u'/Users/cusdb/Library/AutoPkg/RecipeOverrides/PolicyTemplate.xml',
           'prod_name': u'Firefox',
           'self_service_description': u'Web Browser.',
           'self_service_icon': u'/Users/cusdb/Library/AutoPkg/RecipeOverrides/Firefox.png',
           'version': u'37.0'}}
JSSImporter: No value supplied for JSS_MIGRATED, setting default value of: False
JSSImporter: No value supplied for JSS_SUPPRESS_WARNINGS, setting default value of: False
/Library/Python/2.7/site-packages/python_jss-0.5.9-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.9-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.9-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.9-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.9-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
JSSImporter: Category type: category-'Productivity' already exists according to JSS, moving on...
/Library/Python/2.7/site-packages/python_jss-0.5.9-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
JSSImporter: Category type: policy_category-'Auto Update' already exists according to JSS, moving on...
/Library/Python/2.7/site-packages/python_jss-0.5.9-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
JSSImporter: Pkg-object already exists according to JSS, moving on...
JSSImporter: Package upload not needed.
/Library/Python/2.7/site-packages/python_jss-0.5.9-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.9-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.9-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
JSSImporter: ComputerGroup: Firefox-update-smart updated.
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 1469, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 1463, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1287, in run_recipes
    autopackager.process(recipe)
  File "/Library/AutoPkg/autopkglib/__init__.py", line 466, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 295, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 711, in main
    self.policy = self.handle_policy()
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 609, in handle_policy
    added_env="jss_policy_updated")
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 469, in _update_or_create_new
    recipe_object = obj_cls.from_string(self.j, template)
  File "/Library/Python/2.7/site-packages/python_jss-0.5.9-py2.7.egg/jss/jss.py", line 794, in from_string
    root = ElementTree.fromstring(xml_string)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 9, column 42

**Comment by parm75** [comment]
MACTEST2:~ cusdb$ autopkg run -vvvv Firefox.jss
Processing Firefox.jss...
{u'API_PASSWORD': u'xxxxx',
 u'API_USERNAME': u'xxxxx',
 'AUTOPKG_VERSION': u'0.4.2',
 u'CATEGORY': u'Productivity',
 u'DESCRIPTION': u'Web Browser.',
 u'GIT_PATH': u'/usr/local/git/bin/git',
 u'GROUP_NAME': u'Firefox-update-smart',
 u'GROUP_TEMPLATE': u'/Users/cusdb/Library/AutoPkg/RecipeOverrides/SmartGroupTemplate.xml',
 u'ICON': u'/Users/cusdb/Library/AutoPkg/RecipeOverrides/Firefox.png',
 u'JSS_REPOS': [{
    name = xxxxxx;
    password = "xxxxx";
}],
 u'JSS_URL': u'xxxxx',
 u'JSS_VERIFY_SSL': False,
 u'LOCALE': u'en_US',
 u'NAME': u'Firefox',
 'PARENT_RECIPES': [u'/Users/cusdb/Library/AutoPkg/RecipeRepos/com.github.sheagcraig.jss-recipes/Firefox.jss.recipe',
                    u'/Users/cusdb/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/Mozilla/Firefox.pkg.recipe',
                    u'/Users/cusdb/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/Mozilla/Firefox.download.recipe'],
 u'POLICY_CATEGORY': u'Auto Update',
 u'POLICY_TEMPLATE': u'/Users/cusdb/Library/AutoPkg/RecipeOverrides/PolicyTemplate.xml',
 'RECIPE_CACHE_DIR': u'/Users/cusdb/Library/AutoPkg/Cache/local.jss.Firefox',
 'RECIPE_DIR': '/Users/cusdb/Library/AutoPkg/RecipeOverrides',
 'RECIPE_OVERRIDE_DIRS': ['~/Library/AutoPkg/RecipeOverrides'],
 'RECIPE_PATH': '/Users/cusdb/Library/AutoPkg/RecipeOverrides/Firefox.jss.recipe',
 u'RECIPE_REPOS': {u'/Users/cusdb/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes': {
    URL = "https://github.com/autopkg/recipes.git";
},
                   u'/Users/cusdb/Library/AutoPkg/RecipeRepos/com.github.sheagcraig.jss-recipes': {
    URL = "https://github.com/sheagcraig/jss-recipes.git";
}},
 u'RECIPE_SEARCH_DIRS': [u'.',
                         u'/Users/cusdb/Library/AutoPkg/RecipeRepos/com.github.sheagcraig.jss-recipes',
                         u'/Users/cusdb/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes',
                         '/Users/cusdb/Library/AutoPkg/RecipeOverrides',
                         u'/Users/cusdb/Library/AutoPkg/RecipeRepos/com.github.sheagcraig.jss-recipes',
                         u'/Users/cusdb/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/Mozilla'],
 u'RELEASE': u'latest',
 'verbose': 4}
MozillaURLProvider
{'Input': {'locale': u'en_US',
           'product_name': u'firefox',
           'release': u'latest'}}
MozillaURLProvider: Found URL http://ftp.mozilla.org/pub/mozilla.org/firefox/releases/latest/mac/en-US/Firefox%2037.0.dmg
{'Output': {'url': u'http://ftp.mozilla.org/pub/mozilla.org/firefox/releases/latest/mac/en-US/Firefox%2037.0.dmg'}}
URLDownloader
{'Input': {'filename': u'Firefox.dmg',
           'url': u'http://ftp.mozilla.org/pub/mozilla.org/firefox/releases/latest/mac/en-US/Firefox%2037.0.dmg'}}
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing /Users/cusdb/Library/AutoPkg/Cache/local.jss.Firefox/downloads/Firefox.dmg
{'Output': {'pathname': u'/Users/cusdb/Library/AutoPkg/Cache/local.jss.Firefox/downloads/Firefox.dmg'}}
EndOfCheckPhase
{'Input': {}}
{'Output': {}}
AppDmgVersioner
{'Input': {'dmg_path': u'/Users/cusdb/Library/AutoPkg/Cache/local.jss.Firefox/downloads/Firefox.dmg'}}
AppDmgVersioner: Mounted disk image /Users/cusdb/Library/AutoPkg/Cache/local.jss.Firefox/downloads/Firefox.dmg
AppDmgVersioner: BundleID: org.mozilla.firefox
AppDmgVersioner: Version: 37.0
{'Output': {'app_name': u'Firefox.app',
            'bundleid': u'org.mozilla.firefox',
            'version': u'37.0'}}
PkgRootCreator
{'Input': {'pkgdirs': {
    Applications = 0775;
},
           'pkgroot': u'/Users/cusdb/Library/AutoPkg/Cache/local.jss.Firefox/Firefox'}}
PkgRootCreator: Created /Users/cusdb/Library/AutoPkg/Cache/local.jss.Firefox/Firefox
PkgRootCreator: Creating Applications
PkgRootCreator: Created /Users/cusdb/Library/AutoPkg/Cache/local.jss.Firefox/Firefox/Applications
{'Output': {}}
Copier
{'Input': {'destination_path': u'/Users/cusdb/Library/AutoPkg/Cache/local.jss.Firefox/Firefox/Applications/Firefox.app',
           'source_path': u'/Users/cusdb/Library/AutoPkg/Cache/local.jss.Firefox/downloads/Firefox.dmg/Firefox.app'}}
Copier: Mounted disk image /Users/cusdb/Library/AutoPkg/Cache/local.jss.Firefox/downloads/Firefox.dmg
Copier: Copied /private/tmp/dmg.UqAFPg/Firefox.app to /Users/cusdb/Library/AutoPkg/Cache/local.jss.Firefox/Firefox/Applications/Firefox.app
{'Output': {}}
PkgCreator
{'Input': {'pkg_request': {
    chown =     (
                {
            group = admin;
            path = Applications;
            user = root;
        }
    );
    id = "org.mozilla.firefox.pkg";
    options = "purge_ds_store";
    pkgdir = "/Users/cusdb/Library/AutoPkg/Cache/local.jss.Firefox";
}}}
PkgCreator: Package already exists at path /Users/cusdb/Library/AutoPkg/Cache/local.jss.Firefox/Firefox-37.0.pkg.
PkgCreator: Existing package matches version and identifier, not building.
{'Output': {'pkg_path': u'/Users/cusdb/Library/AutoPkg/Cache/local.jss.Firefox/Firefox-37.0.pkg'}}
JSSImporter
{'Input': {'API_PASSWORD': u'xxxxx',
           'API_USERNAME': u'xxxxx',
           'JSS_REPOS': [{
    name = xxxxx;
    password = "xxxxx";
}],
           'JSS_URL': u'xxxxx',
           'JSS_VERIFY_SSL': False,
           'category': u'Productivity',
           'groups': (
        {
        name = "Firefox-update-smart";
        smart = 1;
        "template_path" = "/Users/cusdb/Library/AutoPkg/RecipeOverrides/SmartGroupTemplate.xml";
    }
),
           'pkg_path': u'/Users/cusdb/Library/AutoPkg/Cache/local.jss.Firefox/Firefox-37.0.pkg',
           'policy_category': u'Auto Update',
           'policy_template': u'/Users/cusdb/Library/AutoPkg/RecipeOverrides/PolicyTemplate.xml',
           'prod_name': u'Firefox',
           'self_service_description': u'Web Browser.',
           'self_service_icon': u'/Users/cusdb/Library/AutoPkg/RecipeOverrides/Firefox.png',
           'version': u'37.0'}}
JSSImporter: No value supplied for JSS_MIGRATED, setting default value of: False
JSSImporter: No value supplied for JSS_SUPPRESS_WARNINGS, setting default value of: False
/Library/Python/2.7/site-packages/python_jss-0.5.9-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.9-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.9-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.9-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.9-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
JSSImporter: Category type: category-'Productivity' already exists according to JSS, moving on...
/Library/Python/2.7/site-packages/python_jss-0.5.9-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
JSSImporter: Category type: policy_category-'Auto Update' already exists according to JSS, moving on...
/Library/Python/2.7/site-packages/python_jss-0.5.9-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
JSSImporter: Pkg-object already exists according to JSS, moving on...
JSSImporter: Package upload not needed.
/Library/Python/2.7/site-packages/python_jss-0.5.9-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.9-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/python_jss-0.5.9-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
JSSImporter: ComputerGroup: Firefox-update-smart updated.
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 1469, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 1463, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1287, in run_recipes
    autopackager.process(recipe)
  File "/Library/AutoPkg/autopkglib/__init__.py", line 466, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 295, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 711, in main
    self.policy = self.handle_policy()
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 609, in handle_policy
    added_env="jss_policy_updated")
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 469, in _update_or_create_new
    recipe_object = obj_cls.from_string(self.j, template)
  File "/Library/Python/2.7/site-packages/python_jss-0.5.9-py2.7.egg/jss/jss.py", line 794, in from_string
    root = ElementTree.fromstring(xml_string)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 9, column 42

**Comment by parm75** [comment]
We are using overrides as per @homebysix instructions on https://github.com/homebysix/auto-update-magic

**Comment by sheagcraig** [comment]
@parm75 Thanks for the info.

Can you also show me your policy template file; specifically the one here: ```/Users/cusdb/Library/AutoPkg/RecipeOverrides/PolicyTemplate.xml```

The error actually says "line 9, column 42". Is that broken in some way?

I think it's actually failing when trying to parse that XML file as XML, so I (hope) there's something exactly there (L9, C42) that is messed up!

**Comment by homebysix** [comment]
@parm75, I highly recommend changing the password for the "autoupdate" API user and the "casperdp3" distribution point user. Everybody on this thread received the passwords in plaintext when you submitted a pre-sanitized version of the response above.

**Comment by parm75** [comment]
ok, found it, typo in that line. There was a back slash instead of a forward slash.
Thanks for the help guys.
