### ISSUE TITLE
What would you call AutoPkgr?

### ISSUE THREAD

**Issue by homebysix** [lindegroup/autopkgr#328]
The fact that AutoPkgr and AutoPkg have such similar names is obviously intentional, but has caused some confusion among admins who are new to the AutoPkg ecosystem. Since these admins are AutoPkgr's exact target audience, we should do everything possible to _reduce_ confusion. This may include, at some point, changing the name of AutoPkgr.

For now, we're just brainstorming. But if anybody has super awesome name suggestions, we'll consider them!

**Comment by poundbangbash** [comment]
Just riffing here..take em or leave em.

PkgManager
PkgReporter
PkgBank
UpdateFactory
AutoMinion
AutoPkg Monitor


VersionTracker v3
Executive Vice President of AutoPkg (all the credit, none of the work)
Packager's Clearing House

**Comment by gerardweese** [comment]
AutoPkgRecipeManager
AutoPkgRecipeScheduler

**Comment by homebysix** [comment]
I think we're trying to get away from names with "AutoPkg" in them, to make it clear that we're not associated with the AutoPkg core team.

**Comment by n8felton** [comment]
PackagingPro
PkgPro

Going off the current icon:
Baggage
Baggage Check[er|r]

Going off "Jenkins" and "Alfred": http://en.wikipedia.org/wiki/List_of_fictional_butlers

I know you're trying to avoid "AutoPkg" but in the spirit of "MunkiAdmin"; AutoPkgAdmin
(Personally at that point I like AutoPkgr better)

**Comment by futureimperfect** [comment]
ANA: AutoPkgr's Not AutoPkg!
PARDIS: Packaging and Relative Dimension in Space

**Comment by erikng** [comment]
Mirror

**Comment by ctdawe** [comment]
How about something associated with recipes?

Sous Chef
Line Cook
Prep Kitchen
Mise En Place

**Comment by wildeep** [comment]
PackagePuller - it 'pulls' packages from a source, to you.

Ribbit - It sticks out its sticky tongue and gets fresh packages from far away

**Comment by poundbangbash** [comment]
Package Traffic Control

Minutes - (double meaning: take the minutes of the pkg meeting though not a very google-able name & it takes minutes to run thru the recipes and alert)

**Comment by gjpalau** [comment]
Minion 
Patches 
Zazu 
Nugget (new / get) 
Impulse
PackageDrop

**Comment by gregneagle** [comment]
Bruce

**Comment by poundbangbash** [comment]
Dealr

**Comment by oleary-bruce** [comment]
Yes...fame & fortune at last!

On Sep 25, 2015, at 5:09 PM, Greg Neagle <notifications@github.com<mailto:notifications@github.com>> wrote:


Bruce

**Comment by futureimperfect** [comment]
Composer

-- 
James Barclay

**Comment by gregneagle** [comment]
PackageMakeR

**Comment by n8felton** [comment]
> PackageMakeR

Oh god. Please no.

**Comment by n8felton** [comment]
Git-R-Done

**Comment by smashism** [comment]
Hmm… something that not only covers the fact that it helps get packaged but also provides a means to send said packages to management frameworks.

Package Path
Package Minder
AppManager
Package Admin
Admin's BFF

Why not brand it? Maybe LindePkgr or Linde Admin Helper.

**Comment by poundbangbash** [comment]
Bookie

**Comment by jgstew** [comment]
AutoPackager

**Comment by pexner** [comment]
Emballage
(Why not? We also use Bonjour, Rendezvous,...)

**Comment by aschwanb** [comment]
I like UpdateFactory, but it's not exclusively about updates. How about PkgFactory?

**Comment by gregneagle** [comment]
Packagey McPackageFace

**Comment by pexner** [comment]
ConveyorBelt

**Comment by gmarnin** [comment]
AutoFetch or AutoFetcher

**Comment by n8felton** [comment]
AutoRepo
Repo Man
Repo Robot
Push, Pop or Push Pop (https://en.wikipedia.org/wiki/Stack_(abstract_data_type))

**Comment by jgstew** [comment]
AutoPkgUI

**Comment by poundbangbash** [comment]
"AutoPkg Admin" like Munki has a Munki Admin and Munki Web Admin
