### ISSUE TITLE
Error running recipes - Python exception.

### ISSUE THREAD

**Issue by jameslbrown** [lindegroup/autopkgr#329]
Have just started getting this error:

A Python exception occurred during the execution of autopkg, see the console log for more details.
[ERROR] xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 0

Log shows:
15/4/2015 10:55:40.075 am AutoPkgr[90541]: Processing com.github.autopkg.pkg.Office2011Updates...
15/4/2015 10:55:40.761 am AutoPkgr[90541]: (FULL AUTOPKG TRACEBACK) 
  File "/usr/local/bin/autopkg", line 1469, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 1463, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1287, in run_recipes
    autopackager.process(recipe)
  File "/Library/AutoPkg/autopkglib/__init__.py", line 466, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 295, in process
    self.main()
  File "/Users/jlbrown/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/MSOffice2011Updates/MSOffice2011UpdateInfoProvider.py", line 260, in main
    self.get_mso2011update_info()
  File "/Users/jlbrown/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/MSOffice2011Updates/MSOffice2011UpdateInfoProvider.py", line 205, in get_mso2011update_info
    metadata = plistlib.readPlistFromString(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 103, in readPlistFromString
    return readPlist(StringIO(data))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 78, in readPlist
    rootObject = p.parse(pathOrFile)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 406, in parse
    parser.ParseFile(fileobj)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 0
15/4/2015 10:55:40.762 am AutoPkgr[90541]: [DEBUG] Error [1] Error running recipes 
 A Python exception occurred during the execution of autopkg, see the console log for more details.

[ERROR] xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 0
15/4/2015 10:55:40.765 am AutoPkgr[90541]: [DEBUG] Nothing new was downloaded.
15/4/2015 10:55:40.765 am AutoPkgr[90541]: [DEBUG] Completed AutoPkg Task:
  /usr/bin/python /usr/local/bin/autopkg run --recipe-list /Users/jlbrown/Library/Application Support/AutoPkgr/recipe_list.txt --report-plist /var/folders/m5/2dx4g7mn3xb5yt7384grzhmm0000gn/T/com.lindegroup.AutoPkgr/20150415105509 -v
15/4/2015 10:55:43.073 am AutoPkgr[90541]: [DEBUG] Using Git installed via Xcode command line tools.
15/4/2015 10:55:43.516 am AutoPkgr[90541]: [DEBUG] SSL/TLS is _not_ enabled for mail.bordo.com.au.
15/4/2015 10:55:43.569 am com.lindegroup.AutoPkgr.helper[90544]:  securityd_message_with_reply_sync Failed to talk to secd after 4 attempts.
15/4/2015 10:55:43.569 am com.lindegroup.AutoPkgr.helper[90544]:  SecOSStatusWith error:[-25291] The operation couldn’t be completed. (com.apple.security.xpc error 3 - <connection: 0x7fd3d3d08800> { name = com.apple.securityd.xpc, listener = false, pid = 0, euid = 4294967295, egid = 4294967295, asid = 4294967295 }: Connection invalid)
15/4/2015 10:55:43.618 am AutoPkgr[90541]: [DEBUG] [-25293] The user name or passphrase you entered is not correct.
15/4/2015 10:55:43.619 am AutoPkgr[90541]: An error occurred when attempting to retrieve the keychain entry for jlbrown@bordo.com.au. Error: The user name or passphrase you entered is not correct.

Running version 1.2.1 of AutoPkgr, 0.4.2 of AutoPkg and 2.3.2 of Git. Mac OS X 10.10.3

Any suggestions?

Thanks,

James.

**Comment by poundbangbash** [comment]
Make sure you update the recipe repos. There were some changes in some of them today due to changes in the software offerings. I believe the office downloader was one. 
'autopkg repo-update all' will do it. 

-Eric

**Comment by eahrold** [comment]
@jameslbrown, there are two distance errors here.
The first ( Python exception) could be outdated recipe as @poundbangbash suggested. 

The keychain error is completely separate, does sending a test e-mail succeed?

**Comment by jameslbrown** [comment]
Thanks for the replies.

Running 'Update Repos Now' from the Schedule tab in AutoPkgr didn't fix the problem. Running 'autopkg repo-update all' just tells me 'Already up-to-date.'

Re keychain error, first time I saw this was when looking at the logs for Python exception. I receive emails from AutoPkgr fine.

James.

**Comment by eahrold** [comment]
@jameslbrown, are you using an override or are you running the base recipe?

**Comment by jameslbrown** [comment]
Just the built-in ones:

MSOffice2011Updates.pkg com.github.autopkg.pkg.Office2011Updates

from https://github.com/autopkg/recipes.git

James.

**Comment by eahrold** [comment]
This is the page that is supposedly is corrupt, does it look correct to you?
http://www.microsoft.com/mac/autoupdate/0409MSOf14.xml

**Comment by jameslbrown** [comment]
I'm really not qualified to say! :-(

**Comment by eahrold** [comment]
No problem,

For now I'd just disable it for a day or so and see if it gets fixed.
If it's not resolved then, you should start an issue on the [AutoPkg Recipe issue board](https://github.com/autopkg/recipes/issues), they may have more insight as to what's causing this particular error.
