### ISSUE TITLE
GUI mis-counts completed recipes when you Run AutoPkg Now

### ISSUE THREAD

**Issue by jazzace** [lindegroup/autopkgr#333]
If you opt to Run AutoPkg Now (button in Schedule tab), the resulting progress bar correctly reports the number of total recipes but over-reports the number of recipes completed. Examples attached (the one with "StopProcessingIf" in it may give a clue as to what extra messages are being counted as recipes). This bug seems to have appeared in the 1.2 release and is still present in 1.2.1. Tested on both 10.9.5 (13F1077) and 10.10.3 (14D136).
![stop-processing-if](https://cloud.githubusercontent.com/assets/4193278/7212044/f81a2268-e51e-11e4-93c2-4853ee0bdb19.png)

![miscounting-recipes](https://cloud.githubusercontent.com/assets/4193278/7211941/a9cd668e-e51d-11e4-95ff-188f5667e87d.png)

**Comment by eahrold** [comment]
@jazzace, 
Thanks for the report. 

Currently the increment is based on a string from the AutoPkg stdout containing the word "Processing", we should definitely switch that to a string that begins with with "Processing ".

I suspect it will help. I'll update this ASAP.
Thanks again.

**Comment by homebysix** [comment]
Yeah, looks like this is definitely related to the StopProcessingIf processor, which I see in the AppStoreApp series of recipes:
```
        <dict>
            <key>Processor</key>
            <string>StopProcessingIf</string>
            <key>comment</key>
            <string>If a package has already been built with this version and ID (and "force_pkg_build" is False), we're done.</string>
            <key>Arguments</key>
            <dict>
                <key>predicate</key>
                <string>pkg_build_matches == YES</string>
            </dict>
        </dict>
```
Thanks @eahrold for handling it!
