### ISSUE TITLE
FileWave integration

### ISSUE THREAD

**Issue by homebysix** [lindegroup/autopkgr#339]
A portion of FileWave users have expressed interest in seeing AutoPkgr integrate with FileWave for automatic import of newly packaged software. I'm currently researching the scope of this request, and will have more details soon.

**Comment by johncclayton** [comment]
Hi.  I'm helping with the research - more news soon.

**Comment by eahrold** [comment]
Hey guys, 

Just to go on record, we should really consider that this is probably best handled at the AutoPkg level, i.e a FileWaveImporter shared processor. Any actual importing would be outside of the scope of AutoPkgr.

The good news on our side is I am currently revamping the LGTools class, making it an Abstract Class, which will allow us to easily add and manage new "tools" like this via subclassing.

**Comment by homebysix** [comment]
@eahrold That's exactly what I was thinking. If somebody writes a FileWaveImporter shared processor, then our job will be pretty straightforward. More details coming soon from @johncclayton I believe.

**Comment by johncclayton** [comment]
I've got the command line basics done, now I'll write a shared importer - just reading docs about this now.

**Comment by homebysix** [comment]
Fantastic! There are a couple of good working examples in [AbsoluteManageExport](https://github.com/tburgin/AbsoluteManageExport) and [JSSImporter](https://github.com/sheagcraig/JSSImporter). And I think the [standard workflow](https://github.com/autopkg/jss-recipes#standard-workflow-for-jss-recipes) for JSS recipes is worth emulating.

**Comment by johncclayton** [comment]
I'll see how far those bring me :-) thanks. News soon...

**Comment by eahrold** [comment]
@johncclayton I'm guessing this is your dev site https://github.com/fw-dev?

If you are also planning on doing the AutoPkgr integration it's not up to master yet, so make sure to check out the highest 1.3-x branch for all of that (right now it's here https://github.com/lindegroup/autopkgr/tree/v1.3-rc2).

And see the [LGIntegration+Protocols.h](https://github.com/lindegroup/autopkgr/blob/v1.3-rc2/AutoPkgr/LGIntegration%2BProtocols.h) and [LGIntegrationTemplate.h,m](https://github.com/lindegroup/autopkgr/blob/v1.3-rc2/AutoPkgr/LGIntegrationTemplate.m) for implementation details.

But we could handle that aspect. 
Keep us posted.

**Comment by homebysix** [comment]
I'd recommend that @johncclayton creates the FileWaveImporter in Python first and gets it to the point of being command-line functional. Then @eahrold and can I work on integrating it with AutoPkgr's UI.

**Comment by johncclayton** [comment]
Thats the plan.  To make any of this work you'll need v10 of the FileWave Admin product - which hasn't been released yet.

**Comment by gjpalau** [comment]
Yay! Thanks @johncclayton and @homebysix

**Comment by eahrold** [comment]
@johncclayton is this ready to go on your end?

**Comment by poundbangbash** [comment]
There is a beta for Filewave 10 due out soon. http://us5.campaign-archive1.com/?u=bda862933dd437357dcb7faf8&id=8f02f839d5&e=57cbb61618

**Comment by johncclayton** [comment]
Want to join the beta to find out more?  Ask me... johnc@filewave.com

**Comment by homebysix** [comment]
Work has begun on putting the FileWave integration UI into AutoPkgr. (#462)

**Comment by homebysix** [comment]
@johncclayton, I have a question about the default values for the FileWaveImporter settings:

>FW_SERVER_HOST - defaults to 'localhost', can be hostname or IP address
>FW_SERVER_PORT - defaults to 20016
>FW_ADMIN_USER - defaults to 'fwadmin', its the name of the account that will be used to connect
>FW_ADMIN_PASSWORD - defaults to 'filewave', its the password of the FW_ADMIN_USER account

I'm concerned that having the hostname default to localhost implies that it's OK to run AutoPkg/AutoPkgr on their primary FileWave server Mac, which I don't think is a great idea. Do you agree?

Is the port of all FileWave servers 20016 by default? Can this port be changed by the FileWave administrator?

Should we encourage people to create a separate FileWave administrator account called `autopkg` or something like that, and limit its capabilities to allow it only to upload packages? Is that possible?

**Comment by homebysix** [comment]
AutoPkgr 1.4 is now available: https://github.com/lindegroup/autopkgr/releases/latest

Closing this thread, but don't hesitate to open a new thread to discuss enhancements to FileWave integration.
