### ISSUE TITLE
Improve appearance and behavior of "Last AutoPkg Run" status in menu

### ISSUE THREAD

**Issue by homebysix** [lindegroup/autopkgr#340]
### Part 1:

It seems that the status item in the menu only "listens" for updates from AutoPkg after the menu bar is showing. Therefore, it's possible to click on the menu and have it show "Last AutoPkg Run" even while an AutoPkg run is currently in progress.

Steps to reproduce:

1. Start an AutoPkg run by clicking Run AutoPkg Now (in either the Schedule tab or the menulet).
2. Mid-way through the run, toggle the menu between active and hidden.
3. Notice that when the menu re-appears, it reverts back to "Last AutoPkg Run:" status instead of correctly showing the status of the current run. The menu doesn't update again until the next recipe is processed (which can be several minutes, in the case of some recipes).

Desired behavior: The menu bar should always show the current status, even if it's activated mid-run. I would expect to see something like "(2/10) Processing com.github.autopkg.Firefox..." immediately, if that recipe is currently being processed.

### Part 2:

It would be nice if the "Last AutoPkg Run" date/time format more closely resembled Time Machine's. For example:

- Last AutoPkg Run: Today, 10:08 PM
- Last AutoPkg Run: Yesterday, 4:12 PM
- Last AutoPkg Run: April 21, 2015
- Last AutoPkg Run: None

We don't need to know the exact seconds of the recent run times, nor do we need to know the exact time of AutoPkg runs before "yesterday."

**Comment by eahrold** [comment]
I've got the fix for part 1 stashed. I'll push that soon.

Part 2 should be an easy enough fix, and just a matter of adjusting the NSDateFormater to the desired style.

```Objective-c
[dateFormatter setDoesRelativeDateFormatting:YES]
```

**Comment by homebysix** [comment]
I changed to the "short" date format in order to remove seconds. Is there something we can do to remove the time altogether, if the run happened earlier than "yesterday?" Time Machine follows that pattern:
![mac-timem-barentertime](https://cloud.githubusercontent.com/assets/7801391/7358521/b53f3b6c-ecea-11e4-88ea-0cec4987861f.png)
![time-machine-enter](https://cloud.githubusercontent.com/assets/7801391/7358524/bb0ff57c-ecea-11e4-80c7-9107afd3d2ac.png)
![backup_2_0](https://cloud.githubusercontent.com/assets/7801391/7358527/c12f93d6-ecea-11e4-9f6b-b5e366649fa7.png)

**Comment by homebysix** [comment]
Looks like the current beta branch relative dates aren't working quite right. My status says "Today, 2:30 PM" even though it's only 9:39 AM right now.

Feature request: Ability to run AutoPkg in the FUTURE! :-)

![screen shot 2015-04-28 at 9 39 25 am](https://cloud.githubusercontent.com/assets/7801391/7375031/af0f5772-ed8a-11e4-8790-048b418af947.png)

**Comment by eahrold** [comment]
OK. 
I think I got it figured out.
What's happening is the date gets set from the `[NSDate date]` as a string into defaults. So when it was written it was "Today, 2:30" but that was actually yesterday at 2:30 I'm guessing. 

I'll switch it around to set it as a date and then read it as a string which should solve this.

**Comment by homebysix** [comment]
I think as a result of this, my AutoPkgr helper tool also failed to trigger any AutoPkg runs today. Probably because it was expecting to parse a datetime and found a string instead? Not sure.

I'll test to see if your commit changes that tomorrow. Thanks!

**Comment by eahrold** [comment]
Just for clarity AutoPkgr helper tool isn't responsible for triggering the AutoPkg run, launchd is.
The only thing the helper tool does is create the launchd.plist and then load it, i.e. the /Library/LaunchDaemon/com.lindegroup.AutoPkgr.schedule.plist 
 
I'd be surprised if this was actually causing that issue because the LGDefaults class should handle the possibility of the object that is passed in being either a NSDate or an NSString, so there may be another culprit. Keep me posted if any other symptoms persist.

**Comment by homebysix** [comment]
Yeah, the scheduler seems to have quit. It's been stuck on "Today, 2:30 PM" for two days now, and no entries in the log to indicate background runs.

**Comment by eahrold** [comment]
Run this and see if you have an stalled background run...
`ps -e -o command= | grep runInBackground`

the run this and see if the autopkg run actually stalled tool...
`ps -e -o command= | grep autopkg`

if either of these is stalled gist me a sample of it...

**Comment by homebysix** [comment]
False alarm. The scheduled run stall is related to #230. Ugh.
