### ISSUE TITLE
Customization of the Email Template?

### ISSUE THREAD

**Issue by everetteallen** [lindegroup/autopkgr#341]
It would be a wonderful enhancement if the emails that are sent could be customized from templates.
On the other hand maybe there should be an email processor for autopkg...

**Comment by homebysix** [comment]
I agree, an email template could be nice. It could be an .html file in ~/Library/Application Support/AutoPkgr that has variables like %NAME% and %VERSION% in it.

That being said, I'm working to make the default emails as attractive as possible. Open to suggestions!

**Comment by homebysix** [comment]
(Also see #184.)
