### ISSUE TITLE
Enhancement: Utilize `autopkg info` command

### ISSUE THREAD

**Issue by homebysix** [lindegroup/autopkgr#342]
Tonight in IRC @timsutton mentioned a great feature idea. AutoPkg has an "info" verb that we're not using yet, but which might be useful to expose in AutoPkgr.

For example, `autopkg info Firefox.pkg` produces:

```
Description:         Downloads Firefox disk image and builds a package.
                     Values for RELEASE correspond to directories here: http://download-origin.cdn.mozilla.net/pub/mozilla.org/firefox/releases/
                     Some useful values are: 'latest', 'latest-10.0esr', 'latest-esr', 'latest-3.6', 'latest-beta'
                     LOCALE corresponds to directories at http://download-origin.cdn.mozilla.net/pub/mozilla.org/firefox/releases/$RELEASE/mac/
                     Examples include 'en-US', 'de', 'ja-JP-mac', 'sv-SE', and 'zh-TW'
                     No idea if all Firefox builds are available in all the same localizations, so you may need to verify that any particular
                     combination is offered.
Identifier:          com.github.autopkg.pkg.Firefox_EN
Munki import recipe: False
Has check phase:     True
Builds package:      True
Recipe file path:    /Users/elliot/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/Mozilla/Firefox.pkg.recipe
Parent recipe(s):    /Users/elliot/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/Mozilla/Firefox.download.recipe
Input values: 
 
    LOCALE = "en_US";
    NAME = Firefox;
    RELEASE = latest;
```

My ideal GUI for this would be something in line with what iTunes does when you display file properties. The properties aren't editable, so they're just displayed in a neatly formatted key/value list.
![screen shot 2015-04-28 at 9 47 42 pm](https://cloud.githubusercontent.com/assets/7801391/7384921/be476b1a-edf0-11e4-939a-885babd4639e.png)

**Comment by homebysix** [comment]
(Also see #357.)

**Comment by eahrold** [comment]
@homebysix, I'm making some progress on this It's ready for you to work on the UI. https://github.com/lindegroup/autopkgr/tree/v1.3.0-info-panel

Do what you want with the LGAutoPkgInfoPanel.xib and I'll update code once you're done.

**Comment by eahrold** [comment]
Using NSPopover instead at this branch https://github.com/lindegroup/autopkgr/tree/v1.3.0-info-popover.
