### ISSUE TITLE
Some default values in overrides

### ISSUE THREAD

**Issue by mikaellofgren** [lindegroup/autopkgr#343]
Hi
It would be great to have some default (empty) values for overrides.
We often change Locale, munch_repo_subdir, catalog
<key>LOCALE</key>
        <string>en_US</string>

<key>MUNKI_REPO_SUBDIR</key>
        <string>apps/firefox</string>

<key>catalogs</key>
                <string>testing</string>

regards
Mikael

**Comment by homebysix** [comment]
I've thought about this, and I think it's outside of AutoPkgr's scope. However, [Easy Rider](https://github.com/sheagcraig/easy_rider) has you covered!
