### ISSUE TITLE
Enhancement: Integrate with MacPatch

### ISSUE THREAD

**Issue by homebysix** [lindegroup/autopkgr#347]
A [MacPatchImporterProcessor](https://github.com/SMSG-MAC-DEV/MacPatch-AutoPKG) was recently released. Let's explore how easy/difficult it would be to make that part of AutoPkgr's integration options.

**Comment by eahrold** [comment]
Sounds good...
I'm doing an overhaul of the LGTools, making it an abstract class. 
Once we get that done we should be able to redesign the UI for all of the new tools we're considering (FileWave, AbsoluteMange, etc...)

We should probably move to individual panels to "Configure" for each of the tools, and  check boxes / buttons to enable / configure on the integration tab.

**Comment by homebysix** [comment]
Yep, that's just what I was thinking. I may add a couple more integration requests as they come to me. Hopefully they'll all be relatively straightforward to implement once that LGTools class is present.

**Comment by homebysix** [comment]
AutoPkgr 1.3 release candidate 1 is available on our releases page. Anybody who wants to try out the MacPatch integration in a test environment, we'd love to hear your feedback!

https://github.com/lindegroup/autopkgr/releases
