### ISSUE TITLE
AFP error -5023

### ISSUE THREAD

**Issue by mpudenz** [lindegroup/autopkgr#348]
We started to get this error after the latest update to the JSS importer. 
Git 2.2.1
AutoPKGR 0.4.2
JSS Importer 0.3.8

Any help would be great!

mount_afp: AFPMountURL returned error -5023, errno is -5023
A Python exception occurred during the execution of autopkg, see the console log for more details.

[ERROR] subprocess.CalledProcessError: Command '['mount', '-t', 'afp', 'afp://CasperAdmin:*******@casper.xxxxxxxx.xxxxxx:548/CasperShare', '/Volumes/CasperShare']' returned non-zero exit status 97

**Comment by eahrold** [comment]
@mpudenz I'm guessing your password has special characters in it. Mind posting which special characters it contains. They need not be in order, just interested in whether JSSImporter needs to encode characters it's not currently.

Thanks.

**Comment by mpudenz** [comment]
@eahrold I have changed the password for the AutoPKGR in JSS to only contain letters with out caps. I have changed the password in on the JSS importer as well. I can connect to the casper distribution point but I am still getting the same error. I do get a pop up that says the Certificate on the Casper server is not valid would this cause this issue? Any suggestions would be great, thank you!

**Comment by mpudenz** [comment]
@eahrold I was able to uninstall and reinstall AutoPkgr with the new password and it worked. Just and FYI I had an @ sign in the old password. Thanks for all the help!

**Comment by eahrold** [comment]
No your error is regarding the Distribution points, that 

I thought we had the @ sign encoded for this, but that would possibly explain. 
but most likely this was happening

`afp://username:thep@ssword@my.server.com`

So to the mounter splits at the first @ sign and sets the url to `ssword@my.server.com` and the password is looks like `thep`

I'll go over JSSImporter again and see if for some reason this is set.

Were you by chance using a version of JSSImporter < 0.5  before your upgrade to 0.5.8?
Had you yourself url-encoded your password originally?

**Comment by mpudenz** [comment]
I am not real sure what version we were on before the update. I am guessing the latest one since we use it often and try to keep things up to date. 

We had not url-encoded the password originally.
