### ISSUE TITLE
Test email fails unless you "tab out" of the Password field

### ISSUE THREAD

**Issue by homebysix** [lindegroup/autopkgr#352]
I'm assuming that the contents of the "Password" field don't actually get written to the keychain until the user types their password and then tabs or clicks out of the Password field. Unfortunately, simply clicking the Send Test Email button is not sufficient to trigger the password getting written to the keychain, and that could result in an unnecessary error message being displayed.

Steps to reproduce:

1. Open a fresh copy of AutoPkgr (with no previous keychain entries saved).
2. Navigate to the email notification settings and fill out all fields with correct values.
3. After typing the Password field, do not press Tab or Enter. Simply click Send Test Email:
    ![screen shot 2015-05-08 at 9 24 25 am](https://cloud.githubusercontent.com/assets/7801391/7542582/cc22629c-f572-11e4-8dc3-8805e2850b76.png)
4. Notice the error message that appears:
    ![screen shot 2015-05-08 at 9 24 31 am](https://cloud.githubusercontent.com/assets/7801391/7542589/d3f211d4-f572-11e4-9e34-c2f5d3a19b4e.png)

Expected behavior: Clicking the Send Test Email button forces the contents of the Password field to be written to the keychain before the test begins.

Can we make that happen?

**Comment by eahrold** [comment]
I don't like that (null) in the alert panel either. I'll fix both.
