### ISSUE TITLE
Repos listed both with and without .git extension

### ISSUE THREAD

**Issue by homebysix** [lindegroup/autopkgr#355]
Seems like AutoPkgr started preferring repos with the .git extension included at some point. For all the repos I added before that point, I now see duplicate listings.

![screen shot 2015-05-13 at 6 49 42 am](https://cloud.githubusercontent.com/assets/7801391/7614351/1effc208-f94b-11e4-9100-24440c7a33de.png)

Removing the non-.git repo and re-adding the .git repo solves the problem, but shouldn't AutoPkgr detect that they're one and the same?

**Comment by eahrold** [comment]
Have you got a sense of when this may have happened? I'm having a hard time finding the culprit.
Looks like AutoPkgr has used the .git extension since it's inception.
Is there any chance at all you added those either via the cli or using the `Add a repo URL manually` text field?

**Comment by homebysix** [comment]
I might have added a couple repos manually, but this is affecting more than just those repos.

Here's my whole repo list. All the non-.git repos are listed together at the bottom.

![repo-list](https://cloud.githubusercontent.com/assets/7801391/7616651/f224730e-f95a-11e4-90be-38db77868e51.png)

**Comment by homebysix** [comment]
I haven't seen this happen since May. Tentatively calling it fixed.
