### ISSUE TITLE
Enhancement: Integration with Slack

### ISSUE THREAD

**Issue by homebysix** [lindegroup/autopkgr#358]
Ability to receive alerts in a Slack channel instead of (or in addition to) email.

https://slack.com/integrations

**Comment by weswhet** [comment]
+1

**Comment by eahrold** [comment]
I like the idea of going the web hook road, do we want to add any other abilities like specifying channel or overriding the username?

https://api.slack.com/incoming-webhooks

**Comment by homebysix** [comment]
@eahrold, I think @jsenick is working on something over in the v1.3.0-alpha2-slack branch. I added the UI, just need him to wire up the underpinnings.

**Comment by eahrold** [comment]
@jsenick, 
We're probably going to need to add some sort of notification coordinator class, that will send all of the various types of notifications after a run is complete, and then spit our a completed signal, after all of the notifications have been sent. 

I was thinking that the the slack, email, and HipChat, etc... notification services should be `NSOperation` subclasses, and we can have a `NSOperationManager` class that we add the notification services instance to that has a completion block property.

And maybe we should do our own super, 
```Objective-c
@interface LGNotificatonService : NSOperation

// If the service is enabled, most likely spits back a NSUserDefault key. If not enabled no need to create an instance.
+ (BOOL)isEnabled;

// Whether the service should report integrations, since getting integrations status can be a slightly expensive network operation, if enabled services don't report them, we have a key that we can check with.
+ (BOOL)reportsIntegrations;

// Main body of the message.
@property (copy, nonatomic) NSString *message;

// Error reported when message cannot be sent.
@property (copy, nonatomic, readonly) NSError *error;

// Completion block when executed on sending.
@property (copy, nonatomic) void (^notificatonComplete)(NSError *);

// An independant trigger usable for sending test messages.
- (void)send;

@end
```
Then subclass each of the specific notification services, e.g `LGSlaxNotificaitonServie`, `LGEmailNotificationService`. That way we'll have a consistent way to add more services moving forward.

If you have something else in mind let me know, I'd love to spit-ball some ideas.

**Comment by eahrold** [comment]
@jsenick, 
The backbone is complete, and I've stubbed out a `LGSlackNotification` class that you should be able to get working pretty easily.  I was having a few serializer issues, but I think that was because I wasn't going to an actually web hook address and slack was redirecting bad responses to an HTML page rather than sending back json data.

Anyway let me know if you have any questions.

**Comment by eahrold** [comment]
See: https://github.com/lindegroup/autopkgr/tree/v1.3.0-beta1

**Comment by weswhet** [comment]
Is there a useable beta build.dmg to test out?

**Comment by homebysix** [comment]
Soon. We're working out a few bugs that make it decidedly non-usable at the moment.

**Comment by homebysix** [comment]
AutoPkgr 1.3 release candidate 1 is available on our releases page. Anybody who wants to try out the Slack integration in a test environment, we'd love to hear your feedback!

https://github.com/lindegroup/autopkgr/releases
