### ISSUE TITLE
Enhancement: Integration with HipChat

### ISSUE THREAD

**Issue by homebysix** [lindegroup/autopkgr#359]
Ability to receive notifications via HipChat instead of by email.

https://www.hipchat.com/integrations

**Comment by eahrold** [comment]
See: https://github.com/lindegroup/autopkgr/tree/v1.3.0-beta1

**Comment by homebysix** [comment]
AutoPkgr 1.3 release candidate 1 is available on our releases page. Anybody who wants to try out the HipChat integration in a test environment, we'd love to hear your feedback!

https://github.com/lindegroup/autopkgr/releases
