### ISSUE TITLE
AutoPkg not installed

### ISSUE THREAD

**Issue by Malamutt** [lindegroup/autopkgr#362]
Doing a clean install for the first time.  Git 2.3.2 installed.  I am running the Install AutoPkg and it is not showing installed through autopkgr.

Any insight? 10.10.3 installed and installed autopkg-0.4.2 as well.  Am I missing a step?

**Comment by eahrold** [comment]
Tuen on verbose logs and see if anything suspect appears there. do you ever get an authentication dialog when installing?

**Comment by eahrold** [comment]
@Malamutt were you ever able to figure out what was happening?
