### ISSUE TITLE
AutoPkgr used to run a couple of months ago, and it was great, I was happy, all was well with the world...now I get a message Error running recipes: 

### ISSUE THREAD

**Issue by ivyacres** [lindegroup/autopkgr#365]
/Library/Python/2.7/site-packages/python_jss-0.5.9-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

mount_afp: AFPMountURL returned error -5023, errno is -5023

A Python exception occurred during the execution of autopkg, see the system log for more details.

[ERROR] : Command '['mount', '-t', 'afp', 'afp://casperadmin:*******@Acs-Casper.anamosa.k12.ia.us:548/CasperShare', '/Volumes/CasperShare']' returned non-zero exit status 97

Any one have a clue what I may be doing wrong, or what I need to fix?

**Comment by eahrold** [comment]
@ivyacres 
You may be seeing the same thing as one of these issues #348, #231. They both implicate an issue with the encoding of the username / password. You say it was running a month ago, when did you notice it stopped running?

**Comment by ivyacres** [comment]
We nuked and paved the server due to Auto Backup issues with the JSS
database last month; and reinstalled OS X 10.10.3 and JSS, MySQL, and
TomCat and restored JSS backup. The passwords have not changed, but reading
your other issues - maybe something is not working right - my password
contains two capital letters, lower case letters and numbers.

*Roy B. Carter, MCSE, MCP+I, A+, Network+, CCT*

*Director of Technology*

*Anamosa Community Schools*

*209 Sadie St.*

*Anamosa, IA 52205*

*rcarter@anamosa.k12.ia.us <rcarter@anamosa.k12.ia.us>*

*(319)462-3594 ext. 230 (Tech Office @ HS)*

*(319)480-1985 cell *



On Wed, Jun 10, 2015 at 10:04 AM, Eldon Ahrold <notifications@github.com>
wrote:

> @ivyacres <https://github.com/ivyacres>
> You may be seeing the same thing as one of these issues #348
> <https://github.com/lindegroup/autopkgr/issues/348>, #231
> <https://github.com/lindegroup/autopkgr/issues/231>. They both implicate
> an issue with the encoding of the username / password. You say it was
> running a month ago, when did you notice it stopped running?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lindegroup/autopkgr/issues/365#issuecomment-110787700>
> .
>

-- 


This email and any attachments to it may be confidential and are intended solely for the use of the individual to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of Anamosa Community Schools.
If you are not the intended recipient of this email, you must neither take any action based upon its contents, nor copy or show it to anyone.
Please contact the sender if you believe you have received this email in error.

**Comment by eahrold** [comment]
And just to check they look OK when you do this?
`defaults read com.github.autopkg JSS_REPOS`

Are you "Using Master JDS" or configuring the Shares manually in AutoPkgr?

**Comment by ivyacres** [comment]
Password was wrong in one of the Shares...Thanks!

*Roy B. Carter, MCSE, MCP+I, A+, Network+, CCT*

*Director of Technology*

*Anamosa Community Schools*

*209 Sadie St.*

*Anamosa, IA 52205*

*rcarter@anamosa.k12.ia.us <rcarter@anamosa.k12.ia.us>*

*(319)462-3594 ext. 230 (Tech Office @ HS)*

*(319)480-1985 cell *



On Wed, Jun 10, 2015 at 11:20 AM, Eldon Ahrold <notifications@github.com>
wrote:

> And just to check they look OK when you do this?
> defaults read com.github.autopkg JSS_REPOS
>
> Are you "Using Master JDS" or configuring the Shares manually in AutoPkgr?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lindegroup/autopkgr/issues/365#issuecomment-110820416>
> .
>

-- 


This email and any attachments to it may be confidential and are intended solely for the use of the individual to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of Anamosa Community Schools.
If you are not the intended recipient of this email, you must neither take any action based upon its contents, nor copy or show it to anyone.
Please contact the sender if you believe you have received this email in error.

**Comment by eahrold** [comment]
Great. That's often a pain point when masking passwords with bullets.

**Comment by ivyacres** [comment]
ran further with corrected password, then errored again with this message:
/Library/Python/2.7/site-packages/python_jss-0.5.9-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:769:
InsecureRequestWarning: Unverified HTTPS request is being made. Adding
certificate verification is strongly advised. See:
https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

mount_afp: AFPMountURL returned error -5023, errno is -5023

A Python exception occurred during the execution of autopkg, see the system
log for more details.

[ERROR] : Command '['mount', '-t', 'afp', 'afp://casperadmin:*******@
Acs-Casper.anamosa.k12.ia.us:548/CasperShare', '/Volumes/CasperShare']'
returned non-zero exit status 97

*Roy B. Carter, MCSE, MCP+I, A+, Network+, CCT*

*Director of Technology*

*Anamosa Community Schools*

*209 Sadie St.*

*Anamosa, IA 52205*

*rcarter@anamosa.k12.ia.us <rcarter@anamosa.k12.ia.us>*

*(319)462-3594 ext. 230 (Tech Office @ HS)*

*(319)480-1985 cell *



On Wed, Jun 10, 2015 at 12:38 PM, Eldon Ahrold <notifications@github.com>
wrote:

> Great. That's often a pain point when masking passwords with bullets.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lindegroup/autopkgr/issues/365#issuecomment-110847074>
> .
>

-- 


This email and any attachments to it may be confidential and are intended solely for the use of the individual to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of Anamosa Community Schools.
If you are not the intended recipient of this email, you must neither take any action based upon its contents, nor copy or show it to anyone.
Please contact the sender if you believe you have received this email in error.

**Comment by eahrold** [comment]
Do you have "Using Master JDS" checked, or just configuring the Shares manually in AutoPkgr?

**Comment by ivyacres** [comment]
I do not have that checked..should I?


*Roy B. Carter, MCSE, MCP+I, A+, Network+, CCT*

*Director of Technology*

*Anamosa Community Schools*

*209 Sadie St.*

*Anamosa, IA 52205*

*rcarter@anamosa.k12.ia.us <rcarter@anamosa.k12.ia.us>*

*(319)462-3594 ext. 230 (Tech Office @ HS)*

*(319)480-1985 cell *



On Wed, Jun 10, 2015 at 12:42 PM, Eldon Ahrold <notifications@github.com>
wrote:

> Do you have "Using Master JDS" checked, or just configuring the Shares
> manually in AutoPkgr?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lindegroup/autopkgr/issues/365#issuecomment-110848299>
> .
>

-- 


This email and any attachments to it may be confidential and are intended solely for the use of the individual to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of Anamosa Community Schools.
If you are not the intended recipient of this email, you must neither take any action based upon its contents, nor copy or show it to anyone.
Please contact the sender if you believe you have received this email in error.

**Comment by ivyacres** [comment]
checked it, reconnected, still errorred out...

*Roy B. Carter, MCSE, MCP+I, A+, Network+, CCT*

*Director of Technology*

*Anamosa Community Schools*

*209 Sadie St.*

*Anamosa, IA 52205*

*rcarter@anamosa.k12.ia.us <rcarter@anamosa.k12.ia.us>*

*(319)462-3594 ext. 230 (Tech Office @ HS)*

*(319)480-1985 cell *



On Wed, Jun 10, 2015 at 12:55 PM, Roy B. Carter <rcarter@anamosa.k12.ia.us>
wrote:

> I do not have that checked..should I?
>
>
> *Roy B. Carter, MCSE, MCP+I, A+, Network+, CCT*
>
> *Director of Technology*
>
> *Anamosa Community Schools*
>
> *209 Sadie St.*
>
> *Anamosa, IA 52205*
>
> *rcarter@anamosa.k12.ia.us <rcarter@anamosa.k12.ia.us>*
>
> *(319)462-3594 ext. 230 <%28319%29462-3594%20ext.%20230> (Tech Office @
> HS)*
>
> *(319)480-1985 <%28319%29480-1985> cell *
>
>
>
> On Wed, Jun 10, 2015 at 12:42 PM, Eldon Ahrold <notifications@github.com>
> wrote:
>
>> Do you have "Using Master JDS" checked, or just configuring the Shares
>> manually in AutoPkgr?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/lindegroup/autopkgr/issues/365#issuecomment-110848299>
>> .
>>
>
>

-- 


This email and any attachments to it may be confidential and are intended solely for the use of the individual to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of Anamosa Community Schools.
If you are not the intended recipient of this email, you must neither take any action based upon its contents, nor copy or show it to anyone.
Please contact the sender if you believe you have received this email in error.

**Comment by eahrold** [comment]
Not necessarily, just trying to isolate the issue.

Are the the Distribution Points `<From JSS>` or did you explicitly set them up as AFP?

**Comment by ivyacres** [comment]
Distribution Points are from JSS

*Roy B. Carter, MCSE, MCP+I, A+, Network+, CCT*

*Director of Technology*

*Anamosa Community Schools*

*209 Sadie St.*

*Anamosa, IA 52205*

*rcarter@anamosa.k12.ia.us <rcarter@anamosa.k12.ia.us>*

*(319)462-3594 ext. 230 (Tech Office @ HS)*

*(319)480-1985 cell *



On Wed, Jun 10, 2015 at 1:00 PM, Eldon Ahrold <notifications@github.com>
wrote:

> Not necessarily, just trying to isolate the issue.
>
> Are the the Distribution Points <From JSS> or did you explicitly set them
> up as AFP?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lindegroup/autopkgr/issues/365#issuecomment-110856458>
> .
>

-- 


This email and any attachments to it may be confidential and are intended solely for the use of the individual to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of Anamosa Community Schools.
If you are not the intended recipient of this email, you must neither take any action based upon its contents, nor copy or show it to anyone.
Please contact the sender if you believe you have received this email in error.

**Comment by eahrold** [comment]
Try removing those and configuring explicitly. It may be using an incorrect user name acquired from the JSS.

**Comment by ivyacres** [comment]
same

*Roy B. Carter, MCSE, MCP+I, A+, Network+, CCT*

*Director of Technology*

*Anamosa Community Schools*

*209 Sadie St.*

*Anamosa, IA 52205*

*rcarter@anamosa.k12.ia.us <rcarter@anamosa.k12.ia.us>*

*(319)462-3594 ext. 230 (Tech Office @ HS)*

*(319)480-1985 cell *



On Wed, Jun 10, 2015 at 1:31 PM, Eldon Ahrold <notifications@github.com>
wrote:

> Try removing those and configuring explicitly. It may be using an
> incorrect user name acquired from the JSS.
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lindegroup/autopkgr/issues/365#issuecomment-110865939>
> .
>

-- 


This email and any attachments to it may be confidential and are intended solely for the use of the individual to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of Anamosa Community Schools.
If you are not the intended recipient of this email, you must neither take any action based upon its contents, nor copy or show it to anyone.
Please contact the sender if you believe you have received this email in error.

**Comment by eahrold** [comment]
The one last thing you may want to try is using the IP address rather than the DNS.
(Oh yeah, are you per chance using proxies?)

The next step is to head over to https://github.com/sheagcraig/python-jss and post there since it's a python-jss issue, @sheagcraig is really helpful and may have some other suggestions.

**Comment by sheagcraig** [comment]
Is it possible that the AFP password needs to be escaped further?

Also, recently I did a bugfix update to python-jss that handles an AFP mounting issue, although I don't think it should be related. Can't hurt to
`sudo easy_install -U python-jss` though to be sure.

**Comment by eahrold** [comment]
I also put together this to do some simple testing. Once upon a time it was similar to what python-jss did, and it may help you debug.

https://gist.github.com/eahrold/cbff74461bba8e8e4c0b

**Comment by eahrold** [comment]
@ivyacres, I wanted to checkin in and see if you were able to figure out anything else regarding this issue. 

Thanks.

**Comment by ivyacres** [comment]
No, never figured it out...

*Roy B. Carter, MCSE, MCP+I, A+, Network+, CCT*

*Director of Technology*

*Anamosa Community Schools*

*209 Sadie St.*

*Anamosa, IA 52205*

*rcarter@anamosa.k12.ia.us <rcarter@anamosa.k12.ia.us>*

*(319)462-3594 ext. 230 (Tech Office @ HS)*

*(319)480-1985 cell *



On Tue, Jun 16, 2015 at 8:46 AM, Eldon Ahrold <notifications@github.com>
wrote:

> @ivyacres <https://github.com/ivyacres>, I wanted to checkin in and see
> if you were able to figure out anything else regarding this issue.
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lindegroup/autopkgr/issues/365#issuecomment-112435625>
> .
>

-- 


This email and any attachments to it may be confidential and are intended solely for the use of the individual to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of Anamosa Community Schools.
If you are not the intended recipient of this email, you must neither take any action based upon its contents, nor copy or show it to anyone.
Please contact the sender if you believe you have received this email in error.
