### ISSUE TITLE
Emails don't stop despite unchecking the "send email" box

### ISSUE THREAD

**Issue by homebysix** [lindegroup/autopkgr#366]
Recently I wanted to trim my inbox, so I unchecked the "send email notifications" box in AutoPkgr at three separate client locations. Despite this, I'm continuing to receive email from all three.

On one of them, I just unchecked and rechecked the "Run AutoPkg every __ hours" box in order to reload the helper. We'll see if that fixes it.

**Comment by eahrold** [comment]
This is already inadvertently fixed in 1.3-alpha.

**Comment by homebysix** [comment]
Woo hoo!
