### ISSUE TITLE
System password not being accepted

### ISSUE THREAD

**Issue by smithkyle** [lindegroup/autopkgr#368]
I'm setting up autopkgr on OS X Server 10.9.5, and it will not accept my system password at any of the system password dialog boxes, i.e.:

![screen shot 2015-07-01 at 1 21 34 pm](https://cloud.githubusercontent.com/assets/328670/8464023/216664a0-1ff4-11e5-995e-abfe3f1d3e38.png)

The password was also not accepted at either of the dialogs for installing JSSImporter or updating autopkg.

I previously had autopkgr 1.1x (I think) installed, but had never really used it, so today updated to 1.4.3 by downloading the DMG and copying the app into the same location (it's in a subfolder of /Applications). 

I thought the issue might be with the keychain, so I checked the login keychain and saw an entry for AutoPkgr. When I edited it, the "account" field was empty, and there was no password. I attempted to manually edit it (trying both Master Account and the actual admin username for "account", and adding the password), but the dialogs still would not accept my password. Following this, I tried:
- restarting autopkgr (no change)
- removing the keychain entry and manually creating it, giving access to autopkgr (no change)
- restarting autopkgr again (no change)
- using option + click on the menu bar icon to uninstall autopkgr and all tools, then deleting the .app from /Applications
- Re-installing autopkgr into the subfolder of /Applications
  - On first opening the freshly installed application, I was prompted for system credentials to install the helper tools - my admin username/password WAS accepted here!
  - upon trying to enable auto updates per the screenshot above, however, the same username/password was not accepted...
  - used option + click again to uninstall & delete app
- re-installed in /Applications
  - same results as above: username/password accepted to install helper tools, but not on subsequent dialogs.

Tried watching system.log and turning on verbose logging in autopkgr, but nothing related came up at all.

Any help would be greatly appreciated!

**Comment by smithkyle** [comment]
Hmm...so restarted the server after an update, and tried it again and now it accepted the admin username/password...

**Comment by eahrold** [comment]
@smithkyle, thanks for the report. Since a restart fixed it let's just chalk it up to a glitch in securityd for now (which is rare, but not unheard of). If you experience this again please re-open the issue and we'll dig in.

Thanks.
