### ISSUE TITLE
Easier Contributing - Opening Discussion

### ISSUE THREAD

**Issue by eahrold** [lindegroup/autopkgr#374]
@homebysix, @futureimperfect 
Currently it's somewhat difficult for people to contribute to AutoPkgr.

This is primarily due to the fact that the code signing certificate for development (Debug) builds is the same for release builds (i.e the Linde Group's Certificate ).

If a new contributor download and tried to build, when the build failed due to them not having the certificate, there's not clear a well documented way forward. 

Here's what I propose:
1. Create a generic code signing certificate called **AutoPkgr Open Source Certificate.crt** and include it in the repo root. 
2. Set Xcode project's Debug builds to use that certificate rather
3. Provide **How to contribute** docs that out-line these steps
   - From the root of this repo double click the **AutoPkgr Open Source Certificate.crt** and add it to your keychain
   - Remove the release version of the helper tool from `/Library/PrivilegedHelperTools/com.lindegroup.AutoPkgr.helper`
   - Build, Clean, and Rebuild the Project.
     - This will update the codesigning information in App & Helper's info.plist to reflect using the dev cert.
   - When done developing make sure to remove the current open source signed version from `/Library/PrivilegedHelperTools/com.lindegroup.AutoPkgr.helper`
   - Reopen the release build of AutoPkgr and reinstall the helper tool signed with the Linde Group's cert.

What do you think?

**Comment by homebysix** [comment]
I'm interested in returning to this discussion. I have more [improvement ideas](https://github.com/lindegroup/autopkgr/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Aenhancement+author%3Ahomebysix) than Obj-C know-how, and getting more people to contribute is important to the longevity of AutoPkgr.

The open source certificate idea outlined above makes sense to me. @eahrold, is there any security risk? Ideally I'd like people who build and run an unofficial version of AutoPkgr to get the "app is from an unknown developer" message from Gatekeeper (bypassable with a right-click > Open, of course). Will we need to build any logic into AutoPkgr that detects and replaces the helper tool if it's signed with the development cert?

In addition, we could really use a more automated testing/release process. It's very manual right now. Ensuring that each new feature branch means some automatic testing requirements would take a lot of pressure off the people who merge in the branches (mostly me at this point).
