### ISSUE TITLE
AutoPkgr doesn't remember its previous window size and position

### ISSUE THREAD

**Issue by homebysix** [lindegroup/autopkgr#375]
Minor thing, but would be cool to fix. I saw this in 10.10, haven't tried on 10.9 yet. I'm using 1.3-rc1.

Steps to reproduce:

1. Open AutoPkgr.
2. Size and position the window as desired.
3. Quit/relaunch AutoPkgr.
4. Notice window is at its original size and position.

Expected behavior: window size and position remains as previously set.

**Comment by eahrold** [comment]
I just put up a window-persistance branch. Mind giving that test.

**Comment by poundbangbash** [comment]
Does that branch include remembering sort selection?  With 1.3-rc1 the sort defaults back after quitting and relaunching.

**Comment by eahrold** [comment]
Definitely not, but great point.

I need to check the API's and see if there's a good way to save that persistence. Currently, specifically with the repos, It's hard coded to initially sort by star count, but I'm guessing you can bind that to defaults.

**Comment by homebysix** [comment]
Good catch @poundbangbash. Persistent sorting would be great.

**Comment by eahrold** [comment]
Just pushed another commit. Table view sort descriptors should save now.

**Comment by homebysix** [comment]
Works great! That was super fast @eahrold.
