### ISSUE TITLE
Version (null) reported in Notification Center

### ISSUE THREAD

**Issue by poundbangbash** [lindegroup/autopkgr#376]
This is running on 10.10.4.
When using new recipes (no existing recipes have updates so I can't confirm those) I'm consistently getting (null) version reported.  It doesn't matter if it's .munki or .pkg recipes.
It processes the recipe properly but Notification Center reported it had downloaded the version was (null).

![screen shot 2015-07-17 at 5 12 26 pm](https://cloud.githubusercontent.com/assets/1416288/8758372/f8da2e92-2ca8-11e5-9d88-1bde3881ff25.png)

As an aside, when I run the individual recipe via the contextual menu I'm not getting an email notification upon completion, just the OS X Notification Center notice.  I don't know if that expected behavior since it's a deliberate action taken on the system itself but I thought I'd mention it.

**Comment by eahrold** [comment]
Thanks for the (null) report, I'll look into that.

But you're right, currently we don't send e-mail / slack / hip chat reports for one-off runs. 
It was just a decision, not sure if it's the best one but it is expected behavior currently.

And you're running AutoPkg 0.5.0 correct?

**Comment by homebysix** [comment]
I can confirm that with 1.3-rc1, AutoPkg 0.5.0, I'm also seeing (null) notifications.

**Comment by eahrold** [comment]
@poundbangbash found it. Thanks. Just pushed fix to rc2.
