### ISSUE TITLE
Error when running any recipe: 'ascii' codec can't encode character u'\u2019' in position 115: ordinal not in range(128)

### ISSUE THREAD

**Issue by homebysix** [lindegroup/autopkgr#380]
I think this is very likely an issue specific to my Mac since I'm testing and tweaking AutoPkg/AutoPkgr so often, but as of today, any recipe runs in AutoPkgr are met with the above error.

Running the usual troubleshooting command in the Terminal succeeds, no errors:
```
/usr/bin/python /usr/local/bin/autopkg run --recipe-list ~/Library/Application\ Support/AutoPkgr/recipe_list.txt --report-plist /tmp/autopkg-output.xml
```

From the system log, here's the full traceback. It looks like there's a curly quote somewhere, but it doesn't tell me which file to look in specifically.
```
7/20/15 9:20:58.559 AM AutoPkgr[40280]: (FULL AUTOPKG TRACEBACK) 
  File "/usr/local/bin/autopkg", line 1651, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 1645, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1419, in run_recipes
    search_github=make_suggestions)
  File "/usr/local/bin/autopkg", line 331, in load_recipe
    search_github=search_github)
  File "/usr/local/bin/autopkg", line 235, in locate_recipe
    recipe_file = find_recipe(name, override_dirs + recipe_dirs)
  File "/usr/local/bin/autopkg", line 190, in find_recipe
    return (find_recipe_by_identifier(id_or_name, search_dirs) or
  File "/Library/AutoPkg/autopkglib/__init__.py", line 142, in find_recipe_by_identifier
    if get_identifer_from_recipe_file(match) == identifier:
  File "/Library/AutoPkg/autopkglib/__init__.py", line 125, in get_identifer_from_recipe_file
    "WARNING: plist error for %s: %s" % (filename, unicode(err)))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 115: ordinal not in range(128)
```
That particular unicode character (2019) is "right single quotation mark."

**Comment by homebysix** [comment]
OK, this seems to have been a development issue. I updated the pods, and the error stopped happening. Good times.

**Comment by eahrold** [comment]
That's strange... I figured it was the same as #360, #293.

The only solution I've found so far to handle those using AutoPkgr was to actually rewrite the override using UTF-8 explicitly, but doing that makes me a bit queazy without some sort of built-in backup mechanism.

Guess I'm glad it resolved. But a bit curious as I'm not sure which pod would have fixed that.

**Comment by homebysix** [comment]
Yeah, I agree. If it happens again I'll see if I can get more information.

**Comment by homebysix** [comment]
OK @eahrold, I've sensed a pattern.

- If I "Build" in Xcode and run all recipes, it works fine.
- If I "Archive" or if I run the built product while Xcode is closed, I get the encoding error:
![screen shot 2015-07-22 at 11 16 57 am](https://cloud.githubusercontent.com/assets/7801391/8833408/40f2a6ec-3063-11e5-8073-437336f5ec2e.png)

Also, there are a few lingering build warnings, and one of them is related to encoding:
![screen shot 2015-07-22 at 11 10 53 am](https://cloud.githubusercontent.com/assets/7801391/8833537/17ac7046-3064-11e5-950a-879edd70cae8.png)

Also interesting that git seems not to detect the LocalizableJSSImporter.strings file as a text file, but shows it as a binary blob instead.

Or maybe these things are all unrelated.

**Comment by eahrold** [comment]
Yeah the UTF-16 .strings file thing is annoying, but totally unrelated to the python exception.
I'll fix that and see if I can figure out the env variable is causing the issue. 

Did you figure out what recipe/override is causing the problem? If an override can email me a copy?

**Comment by homebysix** [comment]
It's not recipe specific. I removed all my repos and recipes, then just added the default repo with Firefox.pkg, and I still got the error (even before the recipe tried to run, I think).

**Comment by eahrold** [comment]
That's strange, what do you get when you do  ```defaults read com.github.autopkg RECIPE_SEARCH_DIRS```

Also it could be similar to [this](http://stackoverflow.com/questions/28533365/wrong-encoding-when-running-a-ruby-script-on-build-phases-on-xcode) so update the `-configureEnvironment` by adding
```objective-c
- (void)configureEnvironment
{
    [self addEnvironmentVariable:@"en_US.UTF-8" forKey:@"LANG"];

```
To L583 of LGAutoPkgTask.m

**Comment by homebysix** [comment]
Here are my recipe search dirs:
```
(
    ".",
    "/Users/elliot/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes",
    "/Users/elliot/Library/AutoPkg/RecipeRepos/com.github.autopkg.sheagcraig-recipes",
    "/Users/elliot/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes",
    "/Users/elliot/Library/AutoPkg/RecipeRepos/com.github.autopkg.jleggat-recipes",
    "/Users/elliot/Library/AutoPkg/RecipeRepos/com.github.autopkg.keeleysam-recipes",
    "/Users/elliot/Library/AutoPkg/RecipeRepos/com.github.autopkg.jaharmi-recipes",
    "/Users/elliot/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes"
)
```
Adding the `addEnvironmentVariable` line to LGAutoPkgTask.m doesn't change the behavior.

**Comment by eahrold** [comment]
I just had another thought. When AutoPkg "loads" all the recipes, which it does before a run, I think it traverse two directories deep on any given "SEARCH_DIR" and try to load any recipe like object it finds. With AutoPkgr the '.' in the above list would be the user's home directory when running outside of Xcode, but would the path to the build folder when running inside.

Now I'm remembering I stumbled into a similar issue where I was doing a curl on a recipe from GitHub and it was going into my Downloads folder, but the recipe was not correctly encoded and caused a similar warning. Removing the recipe from the downloads folder fixed the issue. Soooo, is there any chance autopkg is finding a recipe on your desktop, downloads, or there about 2 deep that could be holding the right quote?

If so this should fix the issue, but may have unexpected consequences. 
Add this at L296 in the -main of LGAutoPkgTask.m
```objective-c
self.task.currentDirectoryPath = NSTemporaryDirectory();
```

**Comment by homebysix** [comment]
I can't find any recipes lower than 5 levels deep.
```
Elliots-MacBook-Pro:~ elliot$ find . -iname "*.recipe" -maxdepth 4 2>/dev/null | wc -l
       0
Elliots-MacBook-Pro:~ elliot$ find . -iname "*.recipe" -maxdepth 5 2>/dev/null | wc -l
     193
```
But adding the line above DID seem to fix the problem.

**Comment by eahrold** [comment]
It may look for .plist files too. 
Anyway just asked about the CWD and looks like we can safely change it to the temp dir.
https://github.com/autopkg/autopkg/issues/199

Go ahead an commit it.

**Comment by homebysix** [comment]
No plists either: `find . -iname "*.plist" -maxdepth 2 2>/dev/null | wc -l` returns zero.

I'll commit it.
