### ISSUE TITLE
Support pre/post processor feature

### ISSUE THREAD

**Issue by ygini** [lindegroup/autopkgr#384]
It could be useful to add support for autopkg pre and post processor feature (https://github.com/autopkg/autopkg/wiki/PreAndPostProcessorSupport) when recipes are run from AutoPkgr.

Especially, adding a checkbox to run MunkiSetDefaultCatalog as pre processor for all .munki recipe could be really helpful to keep a munki_repo correctly organized.

**Comment by eahrold** [comment]
@ygini I haven't looked too closely at that part of the autopkg code yet, what's the syntax for passing in multiple `--pre/--post` processors?

Is it like this? 
```
autopkg run --pre MunkiSetDefaultCatalog --pre SomeOtherProcessor --pre OneLastPreProcessor myRecipe.munki
```

**Comment by ygini** [comment]
@eahrold yes, exactly.

For example, MunkiSetDefaultCatalog is made to look at the upcoming processors options to find the munki import one and change the target catalog.

The --pre is used here to add MunkiSetDefaultCatalog at the beginning of the recipe.

**Comment by eahrold** [comment]
@ygini, I put this up a commit that updates the core to handle this  7b5f7ab5f7318a8032b515072a9da881f8d33046

Currently the UI has only got the ability to enable MunkiSetDefaultCatalog as a preprocessor, but if that works as expected we should be able to add a token field to include an unlimited number of processors.

If you're up to it, I've put a build up here
https://www.dropbox.com/s/p8b2uh6j7k7m9il/AutoPkgr-MunkiSetDefaultCatalog.zip?dl=0

The checkbox is in the Munki tools area of the Folders & Integrations tab.

Let me know how it works for you.

If you're not running 1.3 pre-release you'll probably need to uninstall after you're done testing, to downgrade the privileged helper tool for v1.2.3.

Thanks

**Comment by homebysix** [comment]
Also see #346.

**Comment by eahrold** [comment]
@ygini, did you have a chance to check this out?

**Comment by ygini** [comment]
@eahrold sorry for the delay. Yes, it works as excepted.

**Comment by homebysix** [comment]
AutoPkgr 1.4 is now available: https://github.com/lindegroup/autopkgr/releases/latest

**Comment by ygini** [comment]
The settings at this time is just a checkbox to run MunkiSetDefaultCatalog. It should be an array for and an other for post to let the end use choose what ever he want to do.

**Comment by eahrold** [comment]
It's in the Configure AutoPkg section...

<img width="638" alt="pre-post" src="https://cloud.githubusercontent.com/assets/3740088/13467732/24579256-e065-11e5-908e-e94619323a03.png">

**Comment by homebysix** [comment]
@ygini, is that what you mean?

**Comment by macmule** [comment]
Awesome!

So is this a comma separated list of the processor names? Of full path to them?

**Comment by homebysix** [comment]
@macmule, as you type a comma they will automatically form "tokens," just like the To: and Cc: fields in Mail.app.

![screen shot 2016-05-03 at 8 32 38 am](https://cloud.githubusercontent.com/assets/7801391/14988643/b440978a-1109-11e6-8cdd-ad2db404678c.png)
