### ISSUE TITLE
Wrong "From" address in email alerts

### ISSUE THREAD

**Issue by jbaker10** [lindegroup/autopkgr#387]
When originally setting up AutoPkgr notifications, we entered an email address into the "From:" field. After a few weeks we decided to change the email to a different one. After doing so, if you click the "Send Test Email" button it will work properly and come from the _new_ email address that was just entered into the From field. However, it will eventually default back to that originally entered email address.

Example:
Day 1 - Enter joe@fake.com into the From field
Day 7 - Enter team@fake.com into the From field and test sending email, works
Day 9 - AutoPkgr runs and detects a new package, sends out email to the recipients but comes From joe@fake.com
Day 9 - Open AutoPkgr GUI and under Notifications in the From field, it shows joe@fake.com

I don't know the exact timeline of how quickly it switches back, but seems to be at most a day. We have tried entering the new email into From, quitting the app, relaunching it and the new email will still be present. Then if you come back the next day, it will have reverted to the old email. I have tried uninstalling and reinstalling AutoPkgr as well (however I only removed the .app, not sure if there is a way to uninstall and remove all prefs as well). I have also not tried switching the email address, and then rebooting the machine, but maybe that would clear the cache, not sure.

Let me know if you need any other feedback or information.

**Comment by eahrold** [comment]
Are you running the 1.3-pre-release. We're handling it better in there it may be worth a test.

**Comment by jbaker10** [comment]
Yes we are. I installed that from the Github when it first came out because @homebysix mentioned it in Slack. Unfortunately it seems to still be occurring.

**Comment by eahrold** [comment]
Thanks, I'll take a closer look.

**Comment by jbaker10** [comment]
Thank _you_!

**Comment by eahrold** [comment]
What does the raw email look like? I'm curious if it's an issue of multiple From fields getting all mixed up when displaying in your client viewer of choice.
e.g
-------------------------------------------------------------------------------------------
From: AutoPkgr Notification < joe@fake.com>
X-Google-Original-From: AutoPkgr Notification < team@fake.com>
-------------------------------------------------------------------------------------------

**Comment by jbaker10** [comment]
No the raw also shows the first email put in, aka joe@fake.com. It doesn't show the team@fake.com anywhere.

**Comment by jbaker10** [comment]
The only thing I could think (from the Exchange side) is that although we're sending through an unauthenticated SMTP relay, the email I am trying to have it send from (team@fake.com) is not a real email in the system (AD) whereas the initial email (joe@fake.com) was. Now when sending the test email after changing to team@fake.com, it will come through fine, so it doesn't seem like the relay is catching the email and bouncing it back, but it was just a thought.

**Comment by eahrold** [comment]
So it's directly hooked up to defaults, what do you get when you do 
```
defaults read com.lindegroup.AutoPkgr SMTPFrom
```

Then change it to something else in AutoPkgr GUI and see if it updates when you run the command again

**Comment by eahrold** [comment]
Do you have anything specified in the "Username" section of "Use Authentication"? Could that be overriding it?

**Comment by jbaker10** [comment]
No there is nothing in the User Authentication fields. Unfortunately I am not in our office today and am unable to get into the server to check what you're asking :disappointed: therefore I won't be able to answer your second to last question until the AM (EST). My apologies.

**Comment by eahrold** [comment]
No problem. Just keep us posted.

**Comment by jbaker10** [comment]
Hey guys, sorry to take forever to get back to you. I just ran the defaults command and it spits out the email that I see in the "From" field. So when I logged in just now, it was back to joe@fake.com and defaults spit that out. After I changed it and ran the command right after, it spit out team@fake.com.

**Comment by eahrold** [comment]
And when a message is sent, does that reflect the change?

**Comment by jbaker10** [comment]
If a test message is sent right after changing it, yes it will show the new email. And then will somehow be reverted back.

**Comment by jbaker10** [comment]
And just verified that the raw email from team@fake.com doesn't have any traces of joe@fake.com, so its really coming from the right sender.

**Comment by eahrold** [comment]
And it's just reverting at random?

**Comment by jbaker10** [comment]
From what I can tell yes, the machine doesn't reboot in between that time or anything. I can't honestly say I've monitored closely enough to look for a real trend, but within a day it reverts. Normally I change it, restart AutoPkgr, the new email is still there, and then a few days later we get an alert about new software and it comes from the old sender.

**Comment by eahrold** [comment]
But you'll get emails from scheduled runs with the correct address a few times? Or is it possible the run triggered from the GUI is using the correct addr, but the scheduled run is always using an incorrect one?

The two run in slightly different context, the schedule is managed by launchd and has a more confined environment and may not be picking up on the changes (though we thought we had that fixed.)

For S&G's disable the schedule, set the correct From address, then re-enable the schedule.

**Comment by jbaker10** [comment]
Correct the scheduled emails are always coming from the incorrect address,
whereas the GUI triggered emails will use the new one. That's a good
suggestion, I will try that in just a moment.

**Comment by eahrold** [comment]
OOOH before yo do does the 

```/Library/LaunchDaemons/com.lindegroup.AutoPkgr.schedule.plist```

Have a key in it 

```<key>__CFPREFERENCES_AVOID_DAEMON</key>```

**Comment by jbaker10** [comment]
Heres the output I get from a ```defaults read```
```
{
    Label = "com.lindegroup.AutoPkgr.schedule";

    Program = "/Applications/AutoPkgr.app/Contents/MacOS/AutoPkgr";

    ProgramArguments =     (

        "/Applications/AutoPkgr.app/Contents/MacOS/AutoPkgr",

        "-runInBackground",

        YES

    );

    SessionCreate = 1;

    StartInterval = 86400;

    UserName = nimhmshqmacserveradmin;

}
```
So it wouldn't seem like it

**Comment by eahrold** [comment]
Excellent, now we may be getting somewhere.  
I'm guessing you've probably had this schedule running since v1.2.1, and we solved the problem I think in 1.2.2. Once you disable and reenable the schedule you should see this in there
```
 EnvironmentVariables =     {
        "__CFPREFERENCES_AVOID_DAEMON" = 1;
    };
```
And all will right itself with the world.

**Comment by jbaker10** [comment]
Boom! Sure do! And I just got an error that a scheduled run was already running (after I tried to trigger it manually) and it came from the team@fake.com!

I think you have resolved it good sir! Really appreciate the help!

**Comment by eahrold** [comment]
Thanks for sticking it out. You bring a good point to light in that we should check and update the schedule if needed when new versions are released.
