### ISSUE TITLE
Github API Token Generator fails with 2 factor authentication

### ISSUE THREAD

**Issue by MScottBlake** [lindegroup/autopkgr#393]
If you have 2 factor authentication enabled on GitHub, AutoPkgr is not able to authenticate in order to generate an API Token through the following form.
<img width="504" alt="screenshot 2015-07-24 22 31 31" src="https://cloud.githubusercontent.com/assets/945258/8887524/c66b19e8-3253-11e5-951d-0b3c622af538.png">

This is the error that is displayed even with correct credentials.
<img width="532" alt="screenshot 2015-07-24 22 30 11" src="https://cloud.githubusercontent.com/assets/945258/8887522/a558973a-3253-11e5-8104-f60b31490f4f.png">

**Comment by eahrold** [comment]
Great point. 

We just replicated the function built into autopkg for that i.e. `autopkg search -t [query]`
Are you seeing a similar thing when you run that?

Either way we should be able to built it out to support 2 factor auth.

**Comment by MScottBlake** [comment]
When I run `autopkg search -t adium.jss`, it prompts me for my GitHub username and password, then displays this traceback:
```
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 1651, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 1645, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 868, in search_recipes
    results = do_gh_code_search(query, use_token=options.use_token)
  File "/usr/local/bin/autopkg", line 782, in do_gh_code_search
    gh_session.setup_token()
  File "/Library/AutoPkg/autopkglib/github/__init__.py", line 72, in setup_token
    json_resp = urllib2.urlopen(req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 401: Unauthorized
```

**Comment by eahrold** [comment]
That's what I figured. 
I'm reading up on it now https://developer.github.com/v3/auth/#working-with-two-factor-authentication
Looks pretty straight forward.

**Comment by eahrold** [comment]
@MScottBlake, I think I've got 2FA working on this branch https://github.com/lindegroup/autopkgr/tree/gh-two-factor-auth are you able to build and test?

I've tested it with SMS and TOTP using  [DUO](https://guide.duosecurity.com/iphone), but any extra feedback you could give would be great. 

If you can't build, I'd be happy to compile and upload one for testing.

Thanks

**Comment by MScottBlake** [comment]
I haven't tried to build in almost a year. No idea if I'm able to do so.

**Comment by eahrold** [comment]
I know, we've missed you.
 
It's still using the Linde Group's codesigning identity but it's easy to change that if you've got your own.
You just need to change it in both the the AutoPkgr & com.lindegroup.AutoPkgr.helper target.
Then there's a build phase script that will update the info.plist and launchd.plist for SMJobBless.

![target-cs](https://cloud.githubusercontent.com/assets/3740088/8891312/cec16a98-32e9-11e5-99da-a8886dc8c507.png)

We also put in a status menu item to "Reinstall Helper" when you click option, and you should be good to go after that.

I've been wanting to make it easier for people to contribute by including a generic certificate that would be used when building debug builds, but haven't got too much traction on that discussion yet.

Either way, here's a built you can try out  https://www.dropbox.com/s/bo3s45l7fjhp9tx/AutoPkgr-2FA.zip?dl=0

**Comment by MScottBlake** [comment]
That build worked like a charm with TOTP. I'm on Android, so I use the Google Authenticator (but that shouldn't matter).

**Comment by homebysix** [comment]
Queued up for 1.3.1.
