### ISSUE TITLE
Variable settings for recipes

### ISSUE THREAD

**Issue by ygini** [lindegroup/autopkgr#394]
Maybe I didn't find it, but it could be useful to add a way to set recipes variable to something useful (without having to override the recipe).

A simple right clic / edit input variable with a pop and a NSTableView should be good enough.

**Comment by eahrold** [comment]
@ygini you're talking more pre/post processor support correct?

**Comment by ygini** [comment]
No, I talk about -k option. 
It could be interesting to have a way to set it (but maybe I've missed something).

**Comment by eahrold** [comment]
OK that is interesting. I haven't tested, but it looks like you should work OK with a recipe-list, just applies the same k=v to all. We could do something similar with each --pre, --post and --keys, like a token field.

**Comment by ygini** [comment]
Variable are recipe specific. Not generic to all. 
For example you must use it with Office recipe to set the good locale for non US resident.

**Comment by eahrold** [comment]
Right, but it will apply the k/v to any recipe in a list that can handle that particular input.

From `autopkg run --help`
```
  -k KEY=VALUE, --key=KEY=VALUE
                        Provide key/value pairs for recipe input. Caution:
                        values specified here will be applied to all recipes.
```

**Comment by ygini** [comment]
That mean you do a single run for all recipe ?
My recommendation would be to separate them. 
Way more reliable when you've a lot of recipe. And more tunable when you play with variables.

**Comment by eahrold** [comment]
Correct, AutoPkgr does a single run using the `--recipe-list` arg. The main reason we haven't separated them is we use the output from  `--report-plist` to generate the notification reports, which aggregates everything.

We could handle this by doing one-offs instead of a recipe-list, then collecting the xml data from the results, then reassembling it, but that would be a pretty big reworking of the code.

Something to consider though. 

For discussion, what would upsides and downsides be setting for adding `--key` for multiple recipes?

**Comment by ygini** [comment]
Regarding the fact that everything is automated with AutoPkgr, I see only a major downside: conflicting value for same variable. 

For example, most recipe has a proper behavior and use variable for target munki catalog. Most of them use MUNKI_CATALOG as variable name. 

I might want to send some recipe result to one catalog and some to an other. 

If the variable are shared, I can't. 

The perfect solution would be both global and local variable.

In the same way, the pre-post-processor must have a global and local settings. 

You may want to set a pre processor for every recipe to run your antivirus on every downloaded item but you want to use MunkiDefaultCatalog only for recipe without proper MUNKI_CATALOG handling.

**Comment by shawnhonsberger** [comment]
Overrides are the standard recommendation for variables, rather than running recipes directly.
