### ISSUE TITLE
Confusing Dialog

### ISSUE THREAD

**Issue by MScottBlake** [lindegroup/autopkgr#395]
What do these buttons actually do? Probably need to add some clarifying text.

<img width="532" alt="screenshot 2015-07-27 09 01 30" src="https://cloud.githubusercontent.com/assets/945258/8906662/4df1ecca-343e-11e5-8156-bd7deb89cafc.png">

**Comment by eahrold** [comment]
Huh, it sure is...
That's the window for an interactive [Y/N] prompt,
It suppose to be grabbing the last stdout string and using that to construct the message. 
Normally it's should be more like this

![interactive-prompt](https://cloud.githubusercontent.com/assets/3740088/8906934/2738836a-3438-11e5-8aa4-477eb3f2cb92.png)

Not sure why it would be what you have.
At what point in time during the execution did you get this window?

**Comment by MScottBlake** [comment]
That occurred during a scheduled run, I'm not sure precisely when.

**Comment by eahrold** [comment]
Aha. I just realized what happened. One of the predicates we check against for an interactive prompt is `ENDSWITH @"Password"`, which also caught "1Password" leading to the dialog. 

I'll get that worked out. Are you seeing this repeatedly or was it just a one time thing?

**Comment by MScottBlake** [comment]
I get that message and one other every time the recipe runs.

**Comment by eahrold** [comment]
What's the other?

**Comment by MScottBlake** [comment]
Here are the two popups.
<img width="532" alt="screenshot 2015-08-08 19 58 05" src="https://cloud.githubusercontent.com/assets/945258/9152849/e22d4d12-3e07-11e5-90c4-6013e5c7c556.png"><img width="532" alt="screenshot 2015-08-08 19 58 06" src="https://cloud.githubusercontent.com/assets/945258/9152850/e22f487e-3e07-11e5-98b2-0a70a90363e6.png">

**Comment by eahrold** [comment]
Hey @MScottBlake, 
Here's a build you can test [AutoPkgr Interactive Fix](https://dl.dropboxusercontent.com/u/120270/AutoPkgr/AutoPkgr-Interactive-Fix.zip). It should take care of all these prompts.
 
Thanks for pointing this out.

**Comment by MScottBlake** [comment]
Seems to have done the trick, although I can't perform _for-real_ tests from home.
