### ISSUE TITLE
Adding SSH git repo's

### ISSUE THREAD

**Issue by laapsaap** [lindegroup/autopkgr#396]
Hi,

Is it possible to add non http/https git repositories to autopkgr?  Our internal git repo is only accessible to ssh://  + key

I tried to put the git repo in /RecipeRepo as a poor attempt, hoping for a miracle :)

**Comment by eahrold** [comment]
@laapsaap For now you may be able to add it directly using autopkg (not sure if you've tried that yet). If you can AutoPkgr will see all of recipes just fine.

`autopkg repo-add ssh:// + key` 

Let us know if that works for your environment, and we'll see about adding it in.

Thanks

**Comment by homebysix** [comment]
Hi @laapsaap — did you get a chance to test @eahrold's suggestion above?
