### ISSUE TITLE
Only run on certain vlan

### ISSUE THREAD

**Issue by MScottBlake** [lindegroup/autopkgr#398]
I may be in the minority here, but I don't have an extra port in my office to run autopkg on a dedicated machine, so I need to use my laptop which travels home with me.

It would be great if there was another checkbox on the Schedule tab to tell AutoPkgr to only run if there is a network adapter with an IP address within a given range.

**Comment by homebysix** [comment]
Yeah, that's a pretty narrow use case. What about setting AutoPkgr to run every day at a certain time? Or finding a Mac onsite to run from?

**Comment by MScottBlake** [comment]
I know it's narrow and therefore not expecting the moon. I currently have it set to run Monday mornings, but lo and behold, I was home this morning while my wife had an appointment. I quit AutoPkgr so it wouldn't run since I know I wouldn't be in the office, but forgot that it runs anyway.

**Comment by eahrold** [comment]
That's maybe a throwback to this https://github.com/lindegroup/autopkgr/issues/261
