### ISSUE TITLE
JSS Importer GUI will not verify

### ISSUE THREAD

**Issue by websterba** [lindegroup/autopkgr#401]
After upgrading to version 1.3 the JSS Importer stopped working. When I put in my JSS URL and API Username and password now and click the "Verify" button nothing happens and the indicator light stays red. I have verified that the JSS URL is correct and the API username and password is correct and have attempted this on multiple boxes to no avail.

**Comment by eahrold** [comment]
@websterba If you roll back to AutoPkgr 1.2.3 does that seem to work?  In 1.2.3 you will need to click "Connect" to actually test the credentials (even if the light is green initially).

**Comment by websterba** [comment]
@eahrold It does authenticate when I roll back to 1.2.3 and I get the prompts asking for me to add the Distribution Points.

**Comment by homebysix** [comment]
@websterba - Not sure what would have changed to either (a) break this between 1.2.3 or (b) fix it in 1.3.1, but FWIW 1.3.1 just landed. You may want to try it out and see whether the issue persists.

**Comment by homebysix** [comment]
@websterba — Is this working for you on 1.3.1?

**Comment by websterba** [comment]
Yes it is.
