### ISSUE TITLE
AutoPgkr working with Proxy is not possible

### ISSUE THREAD

**Issue by snowwalker1988** [lindegroup/autopkgr#414]
I updated AutoPkgr from version 1.2.3 to version 1.3.0 and after that it was not possible to add or update repos. 

I used very well version 1.2.3.
We used this in an proxy environment and I set the proxy to use the system proxies configured in the system preferences with terminal.
All worked very good.

After installation of version 1.3.0 I could not add or update repos anymore, because autopkgr could not connect to github.
The new possibility to set the proxies does not work. If I now set the proxy to use the system proxies configured in the system preferences I can not add repos.
And after saving proxy settings in the new possibility so set the proxy the checkbox in front of the configuration is not checked.
Is there a problem with the part for proxy setting?

**Comment by eahrold** [comment]
We have fixed an issue with the proxy setting "sticking" and that will be included in 1.3.1 (due out soon)
In the mean time, you can follow the same procedure as 1.2.3 writing to defaults directly

In 1.2.3 had you specified `HTTP_PROXY` and `HTTPS_PROXY` or were you `usingSystemProxies` in that version too?

**Comment by jmb03012** [comment]
@eahrold we had the same issue, the solution for the "sticking" we are aware of (Elliot actually already gave me a beta to test, just havent had a chance yet), but we to can no longer add repos.  When you and i spoke about it the other day I believe I remember you saying you found a line of code on your end that wasnt set for the repo add to respect the proxy and you guys would be fixing it.  Conversation is still in slack history if you need to refer back to it.

**Comment by jmb03012** [comment]
Update: Beta 1.3.1 fixed repo add under proxy issue for us, proxy settings now "sticking" as well, just tested.

**Comment by eahrold** [comment]
Awesome.
Thanks for testing this out.

**Comment by snowwalker1988** [comment]
@eahrold : Also writing to defaults with usingSystemProxies did not work in version 1.3.0.
After installing the older version 1.2.3 it worked very well. We use a proxy without credentials and use in system settings a proxy.pac or if it is necessary direct the one of the proxies like proxy.domain.com:8080.
So to your question also in version 1.2.3 we were using usingSystemProxies.
If version 1.3.1 is out, I will test the version for us.

**Comment by eahrold** [comment]
@snowwalker1988 here's the current testing build. Will you please try it out and see if this resolves your issue? 

Thanks,

 https://dl.dropboxusercontent.com/u/120270/AutoPkgr/AutoPkgr-Interactive-Fix.zip

**Comment by snowwalker1988** [comment]
@eahrold  Thanks for the testing build. This version resolves our issue with the proxies and works fine.

But I saw one another thing in this version:
The status in Repos & Recipes tab will only change to green, when I disable the checkbox in front of the repo and enable it then. Before this only this wait symbols are running.

**Comment by eahrold** [comment]
@snowwalker1988 Here's another build to test. This one should handle git requests with proxies better.
https://www.dropbox.com/s/wd9otznsq28ptwj/AutoPkgr-Git-Proxies-Fix.zip?dl=0

Let us know if the status spinners work correctly with this.

**Comment by snowwalker1988** [comment]
@eahrold Yes now it works better. The status spinners work correctly with this.
Very fine. Thanks.
Can you say when version 1.3.1 would be offical?

**Comment by homebysix** [comment]
This fix is queued up for 1.3.1, which we hope to release soon.
