### ISSUE TITLE
AutoPkgr Does Not Run In El Capitan (10.11) beta 5 or 6

### ISSUE THREAD

**Issue by tbridge** [lindegroup/autopkgr#415]
Currently, if you attempt to schedule a regular run, or perform a manual run of autopkg with autopkgr, the application fails to perform this task.

When it fails, the application says:

**"Only one instance of AutoPkg can be run at a time"**
"A scheduled AutoPkg run may be running in the background. Please wait for it to complete."

In the logs, I see:

```8/6/15 10:51:52.171 AM secd[277]:  securityd_xpc_dictionary_handler AutoPkgr[13074] copy_matching Error Domain=NSOSStatusErrorDomain Code=-34018 "client has neither application-identifier nor keychain-access-groups entitlements" UserInfo={NSDescription=client has neither application-identifier nor keychain-access-groups entitlements}```
```8/6/15 10:51:52.171 AM AutoPkgr[13074]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)```

This appears to be an issue where the Application and its helper lack the necessary entitlements to complete the run.

**Comment by tbridge** [comment]
Full log trace:

8/6/15 10:51:31.689 AM AutoPkgr[13074]: Welcome to AutoPkgr!
8/6/15 10:51:31.818 AM AutoPkgr[13074]: Sparkle: ===== AutoPkgr =====
8/6/15 10:51:32.794 AM com.lindegroup.AutoPkgr.helper[4646]:  securityd_message_with_reply_sync Failed to talk to secd after 4 attempts.
8/6/15 10:51:32.795 AM com.lindegroup.AutoPkgr.helper[4646]:  SecOSStatusWith error:[-25291] The operation couldn’t be completed. (com.apple.security.xpc error 3 - <connection: 0x7ff8a5916110> { name = com.apple.securityd.xpc, listener = false, pid = 0, euid = 4294967295, egid = 4294967295, asid = 4294967295 }: Connection invalid)
8/6/15 10:51:32.837 AM secd[277]:  securityd_xpc_dictionary_handler AutoPkgr[13074] copy_matching Error Domain=NSOSStatusErrorDomain Code=-34018 "client has neither application-identifier nor keychain-access-groups entitlements" UserInfo={NSDescription=client has neither application-identifier nor keychain-access-groups entitlements}
8/6/15 10:51:32.838 AM AutoPkgr[13074]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
8/6/15 10:51:33.705 AM AutoPkgr[13074]: Bartender: Loaded BartenderHelperNinetyFour
8/6/15 10:51:52.146 AM com.lindegroup.AutoPkgr.helper[4646]:  securityd_message_with_reply_sync Failed to talk to secd after 4 attempts.
8/6/15 10:51:52.146 AM com.lindegroup.AutoPkgr.helper[4646]:  SecOSStatusWith error:[-25291] The operation couldn’t be completed. (com.apple.security.xpc error 3 - <connection: 0x7ff8a5916110> { name = com.apple.securityd.xpc, listener = false, pid = 0, euid = 4294967295, egid = 4294967295, asid = 4294967295 }: Connection invalid)
8/6/15 10:51:52.166 AM com.lindegroup.AutoPkgr.helper[4646]:  securityd_message_with_reply_sync Failed to talk to secd after 4 attempts.
8/6/15 10:51:52.166 AM com.lindegroup.AutoPkgr.helper[4646]:  SecOSStatusWith error:[-25291] The operation couldn’t be completed. (com.apple.security.xpc error 3 - <connection: 0x7ff8a5916110> { name = com.apple.securityd.xpc, listener = false, pid = 0, euid = 4294967295, egid = 4294967295, asid = 4294967295 }: Connection invalid)
8/6/15 10:51:52.171 AM secd[277]:  securityd_xpc_dictionary_handler AutoPkgr[13074] copy_matching Error Domain=NSOSStatusErrorDomain Code=-34018 "client has neither application-identifier nor keychain-access-groups entitlements" UserInfo={NSDescription=client has neither application-identifier nor keychain-access-groups entitlements}
8/6/15 10:51:52.171 AM AutoPkgr[13074]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
8/6/15 10:51:52.191 AM secd[277]:  securityd_xpc_dictionary_handler AutoPkgr[13074] copy_matching Error Domain=NSOSStatusErrorDomain Code=-34018 "client has neither application-identifier nor keychain-access-groups entitlements" UserInfo={NSDescription=client has neither application-identifier nor keychain-access-groups entitlements}
8/6/15 10:51:52.191 AM AutoPkgr[13074]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
8/6/15 10:52:50.133 AM AutoPkgr[13074]: Attempting git pull for /Users/tom/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes...
8/6/15 10:52:56.164 AM AutoPkgr[13074]: Attempting git pull for /Users/tom/Library/AutoPkg/RecipeRepos/com.github.autopkg.jleggat-recipes...
8/6/15 10:52:56.499 AM AutoPkgr[13074]: Already up-to-date.

**Comment by eahrold** [comment]
@tbridge do you get emails about the failed run? Also do you have bullets in the email password field?

**Comment by tbridge** [comment]
Yes, I get an email that the run has failed, and I get an error report in the Slack channel assigned. I do have bullets in the email password field.

Tom

**Comment by eahrold** [comment]
@tbridge Can you give this built a go when you get a chance.
https://www.dropbox.com/s/dw0kmxecxtcl1g6/AutoPkgr-Mulitple-Instance-Diagnostics.zip?dl=0

Once `Verbose Logs` is enabled in the menu item you should see a log message like this
```
8/9/15 9:09:44.327 PM AutoPkgr[49111]: [DEBUG] Another autopkg run recipe process detected: (
    "PID: 49286 Name Python User:eldon Command: /usr/bin/python /usr/local/bin/autopkg run --recipe-list /Volumes/myHome/Users/eldon/Library/Application Support/AutoPkgr/recipe_list.txt"
)
```

Let me know what the results turn up. And see if the process with that PIDis actually running.

Thanks.

**Comment by tbridge** [comment]
Hi Eldon,

	What I saw was:

8/9/15 10:18:42.638 PM AutoPkgr[31659]: [DEBUG] Another autopkg run recipe process detected: (
    "PID: 13436 Name Python User:tom\nCommand: /usr/bin/python /usr/local/bin/autopkg run --recipe-list /Users/tom/Library/Application Support/AutoPkgr/recipe_list.txt --report-plist /var/folders/tk/qhvvt21x7z3fzt125dpgjlym0000gn/T/com.lindegroup.AutoPkgr/20150809105744 -v"
)


	There was a process 13436 that was a Python process. Killing it is letting things run now.

	I’m not sure what would bring a stuck process like that back between reboots, though?

Tom

**Comment by eahrold** [comment]
That is strange. It's possible it's referring to a hung background run. Is there any way a 1Password is part of you're recipe list?

**Comment by tbridge** [comment]
No. My run was:

AdobeFlashPlayer.install
AdobeReaderDC.install
AutoPkgr.install
Dropbox.download
Firefox.install
GoogleChrome.install
MSOffice2011Updates.pkg
MunkiAdmin.install
OracleJava8.download
munkitools2.munki

Prior to recently, I also had BBEdit.install and TextWrangler.install there, but those recipes are having issues with SSL.

Tom

**Comment by eahrold** [comment]
The 1Password thing was a stab in the dark.

When you do reboot how quick does the stray instance comes up? Does it coincide with the schedule or is it immediate, or when you first launch AutoPkgr?

**Comment by eahrold** [comment]
@tbridge is this fixed now?

**Comment by tbridge** [comment]
Hi Eldon,

I Believe so.

Best,

Tom
