### ISSUE TITLE
"Enable scheduled AutoPkg runs" checkbox not sticking

### ISSUE THREAD

**Issue by jmb03012** [lindegroup/autopkgr#416]
Similar issue to the proxies, applies but doesnt readily show.

Checking off the box will prompt for credentials, and then I can tell that whatever option I have the radio button ticked for gets applied because the daemons change and so does the time value in the menubar icon, but the checkbox remains unchecked.  Unchecking the box will remove the setting and of course the box remains unchecked.  Rechecking will enable again but still remains unchecked.

I am running 1.3.1-beta1 on a 10.10.4 box.  This beta did however fix the sticking issue with the proxy radio buttons, so the root cause for this appears to be different.

**Comment by eahrold** [comment]
Do you see anything in your logs similar to #413 with the reference to `[__NSCFDictionary dictionary]`?

**Comment by jmb03012** [comment]
No I do not.

**Comment by eahrold** [comment]
@homebysix did you give her a debug build or a release build?

**Comment by homebysix** [comment]
@eahrold - It's an Xcode "archive" build of the current 1.3.1-beta branch.

**Comment by eahrold** [comment]
@jmb03012 is there any way you can see if the issue persists on another machine in your environment.
There's nothing glaring with the code in the way the proxy issue was.

And to be clear you check the check box and the `/Library/LaunchDaemon/com.lindegroup.AutoPkgr.schedule.plist` will get created (or update) correctly, but the check box remains unchecked. Then you click the unchecked checkbox and the launchd.plist gets removed?

**Comment by jmb03012** [comment]
@eahrold 
She is a he =)

And I took a closer look at whats happening and to be more accurate, `/Library/LaunchDaemon/com.lindegroup.AutoPkgr.schedule.plist` was created but regardless of what I do with the checkbox under schedule or the radio buttons it doesnt appear to be changing.  

The only thing that changes is obvoiusly whatever I changed in the GUI execpt for the checkbox which never checks, and when I make a change a ! appears in the menubar icon which if I click on shows the new scheduled value.

I did just try to throw away the launchdaemon to see if changing the schedule values would cause one to be re-created, and if so what if anyhthing in the XML would change.  Upon rebooting the computer and logging in, I was prompted to reinstall the helper tool which I did.  Verified a new helper launchdaemon was created that looked identical to the previous one.  Set it from 24 to 8 hours and checked off enable scheduled autopkg runs, entered creds when prompted, but checkbox remains unchecked and plist remains unchanged.

**Comment by eahrold** [comment]
@jmb03012 sorry, I realized that. The username looked similar to Jennifer who filed an issue a ways back, I thought you were the same.

when you do 
```
sudo launchctl list com.lindegroup.AutoPkgr.schedule
```
Is it actually loaded?

**Comment by eahrold** [comment]
And if you went back to the release version, is it working in that?

**Comment by jmb03012** [comment]
@eahrold no, and i tried toggling it on and off a few times checking in between just now but it never shows as loaded.

reply@reply.github.com At: Aug  7 2015 16:36:00" data-digest="From: reply@reply.github.com At: Aug  7 2015 16:36:00" style="">

**Comment by eahrold** [comment]
But if you remove the file, it will created the file the first time you check the box if it's not there?

**Comment by jmb03012** [comment]
no, just tested with 1.3.0 release, same results.

reply@reply.github.com At: Aug  7 2015 16:36:30" data-digest="From: reply@reply.github.com At: Aug  7 2015 16:36:30" style="">

**Comment by jmb03012** [comment]
yes

reply@reply.github.com At: Aug  7 2015 16:47:35" data-digest="From: reply@reply.github.com At: Aug  7 2015 16:47:35" style="">

**Comment by eahrold** [comment]
Ok, Thanks.
That points me to somewhere very specific.

**Comment by jmb03012** [comment]
do tell

reply@reply.github.com At: Aug  7 2015 16:51:59" data-digest="From: reply@reply.github.com At: Aug  7 2015 16:51:59" style="">

**Comment by eahrold** [comment]
Something in this general area...
https://github.com/eahrold/AHLaunchCtl/blob/master/AHLaunchCtl/AHServiceManagement.m#L187-L267

**Comment by jmb03012** [comment]
@eahrold Any updates on this?

I did leave my AutoPkgr box set to run every 8 hours last week and just checked it for the first time this morning.  The daemon is there, and the GUI and menubar icon show its set for 8 hours, but nothing has run.  It shows in the menu the last run was 8/7 which was the last time I ran it manually so the schedule is definitely not working.

**Comment by eahrold** [comment]
Try manually loading the launchd.plist
```
sudo launchctl load /Library/LaunchDaemons/com.lindegroup.AutoPkgr.schedule.plist
```

Maybe there's something wrong with the actual file. 

```
sudo launchctl list com.lindegroup.AutoPkgr.schedule
```
Post back the results.

**Comment by jmb03012** [comment]
So attempting to load the plist shows that its already loaded.  Attempting to list the file though interestingly results in an error that it couldn't find the service "com.lindegroup.AutoPkgr.schedule" even though it said that the operation was already in progress.

The actual XML doesn't look right though as despite the GUI and the menubar icon showing that the scheduled is enabled and set for every 8 hours, `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>com.lindegroup.AutoPkgr.helper</string>
	<key>MachServices</key>
	<dict>
		<key>com.lindegroup.AutoPkgr.helper</key>
		<true/>
	</dict>
	<key>Program</key>
	<string>/Library/PrivilegedHelperTools/com.lindegroup.AutoPkgr.helper</string>
	<key>ProgramArguments</key>
	<array>
		<string>/Library/PrivilegedHelperTools/com.lindegroup.AutoPkgr.helper</string>
	</array>
</dict>
</plist>`

**Comment by eahrold** [comment]
@jmb03012 that xml is the launchd for the privileged helper tool, not the schedule.

The schedule is `/Library/LaunchDaemons/com.lindegroup.AutoPkgr.schedule.plist`
The helper is `/Library/LaunchDaemons/com.lindegroup.AutoPkgr.helper.plist`

Do you see both files? Are both jobs loaded?

**Comment by jmb03012** [comment]
ugh totally my bad, sorry only one cup of coffee in so far.

No, only the helper propertly list exists, no schedule is present.  This was the same case on this machine before we reimaged and tested with the new beta as well.

**Comment by eahrold** [comment]
OK, So when you click on the check box to enable the schedule do you get this authentication dialog?
![auth-dialog](https://cloud.githubusercontent.com/assets/3740088/9228102/7b64f922-40dc-11e5-8491-8266157679ba.png)

**Comment by jmb03012** [comment]
Yes

reply@reply.github.com At: Aug 12 2015 11:26:07" data-digest="From: reply@reply.github.com At: Aug 12 2015 11:26:07" style="">

**Comment by eahrold** [comment]
Have you "Reinstalled Helper Tool"? 
If no, press option while the status menu item is highlighted and that option should come up.

**Comment by jmb03012** [comment]
I have only done so when flipping between different versions to test, when the window pops up prompting you to do so upon initial launch.  I will try now though on that box via the method you described.

reply@reply.github.com At: Aug 12 2015 11:53:11" data-digest="From: reply@reply.github.com At: Aug 12 2015 11:53:11" style="">

**Comment by jmb03012** [comment]
So doing as you suggested prompted for my creds, provided them, watched the helper plist dissapear from LaunchDaemons, got prompted for creds again, provided them, helper plist added back to LaunchDaemons, still no schedule plist, clicked Schedule tab, clicked check box to enabled scheduled AutoPkgr runs, got prompted for creds, provided creds, no change to LaunchDaemons, changed value from default of Every 24 hours to Every 8 hours, no changes to LaunchDaemons, but menubar icon does show 8 now instead of 24 and like before the menubar icon has an ! point over it which dissappears when i click it (this happens everytime i change or enable/disable schedule value).  Still no schedule plist though.

reply@reply.github.com At: Aug 12 2015 11:53:11" data-digest="From: reply@reply.github.com At: Aug 12 2015 11:53:11" style="">

**Comment by eahrold** [comment]
Hey @jmb03012,
Here's a build that will hopefully provide us with more info as to the cause.
I didn't tick-up the helper build number so you'll want to do the reinstall helper again.

https://www.dropbox.com/s/1jp1hiy5cc3sfj1/AutoPkgr-Debug-Schedule-LaunchD.zip?dl=0

**Comment by homebysix** [comment]
Queued up for 1.3.1.
