### ISSUE TITLE
Slack integration not sending list of what failed

### ISSUE THREAD

**Issue by bahhhhh** [lindegroup/autopkgr#417]
AutoPkgr isn't sending me a list of what has failed during its checks. All it sends is "Failures occurred while running AutoPkg:"

Would it be possible to add a list of items that failed during the check?

![screen shot 2015-08-06 at 1 23 11 pm](https://cloud.githubusercontent.com/assets/4534172/9118445/678b6e42-3c3e-11e5-9a8e-aeff77b918ab.png)

**Comment by eahrold** [comment]
Yes in fact I think in the next version we could even put a full report into slack.

**Comment by homebysix** [comment]
This is queued up for 1.3.1.
