### ISSUE TITLE
Integration check displays prerelease versions.

### ISSUE THREAD

**Issue by chrisgrande** [lindegroup/autopkgr#419]
autopkgr/AutoPkgr/Utility/LGGitHubJSONLoader.m
Doesn't take into account when a release has the "prerelease" key set to true.

I'm thinking it should either ignore them, tag the release as a prerelease in the UI or have a preference to give the user the option to download prerelease versions.

![munki_prerelease](https://cloud.githubusercontent.com/assets/825577/9140441/4267dddc-3cff-11e5-9728-fe4d00e9f375.png)

**Comment by homebysix** [comment]
@chrisgrande Good catch, thank you!

@eahrold I think we should ignore pre-releases for now (because it seems easier) and then maybe for a future version we can add a preference option in the integrations' "Configure" panel.

**Comment by eahrold** [comment]
Agreed. But I think we should ignore them all together, not even add an option. If someone wants a prerelease, self-install.

**Comment by homebysix** [comment]
@eahrold Yes, I suppose AutoPkgr should stay uninvolved in prereleases. Otherwise that's one more thing we have to troubleshoot for.
