### ISSUE TITLE
Screen redraw issue in Folders & Integration tab

### ISSUE THREAD

**Issue by jazzace** [lindegroup/autopkgr#420]
I have had this happen more than once, which is why I am creating an issue for it, but I have not been able to deduce the circumstances such that it can be reliably recreated. Hopefully someone else will have noticed this as well and can provide some more detail. First, a picture of the problem:
![screen shot 2015-08-06 at 9 17 15 am](https://cloud.githubusercontent.com/assets/4193278/9146047/956c6892-3d16-11e5-97ba-c519d11abbf0.png)
Based on this screenshot, it should be clear that this is version 1.3. My recollection is that I had AutoPkgr open with the Recipes & Repos tab selected and that it had been left open during a scheduled run (set up in the Schedule tab). When I then selected the Folders & Integration tab, the screen redraw problem on the Choose… buttons for Cache and Repos appeared. Moving to another tab and then back I believe solved the problem.

I should also note that the previous instance of this problem that I encountered had the exact same chunks of the Choose buttons missing.

Mac mini server (Late 2012) model, OS X 10.10.4

**Comment by homebysix** [comment]
@jazzace I noticed that happened to me once as well, but I could never reproduce it so I chalked it up to my own Mac.

I'll check out the structure of that tab to make sure everything is kosher.

**Comment by eahrold** [comment]
I've seen it too.

**Comment by futureimperfect** [comment]
Me too.

-- 
James Barclay

**Comment by homebysix** [comment]
@futureimperfect @eahrold I can't find what would be causing this. All the constraints seem OK, and the objects aren't overlapping at all. Any ideas?

**Comment by eahrold** [comment]
Nope, I tried a number of view redraw tricks but that didn't help either.
