### ISSUE TITLE
Slack/HipChat webhook URL not saving in El Cap

### ISSUE THREAD

**Issue by mbulmer** [lindegroup/autopkgr#424]
Running the latest El Capitan developer preview (currently DP6), it appears AutoPkgr is no longer saving the Slack webhook URL when entered. When I paste in the URL and click Save and Close, the "Send notifications to Slack channel" option is still checked, but when clicking the "Configure..." button, the URL field is empty again.

The "Send Test" button results in a pop-up message stating "The user name or passphrase you entered is not correct."

I've verified permissions on the AutoPkgr preference file are correct. Anything else I should check? Thanks in advance!

EDIT: Same issue with HipChat. We don't have a HipChat instance to test with but the behavior with the URL/token not being saved is the same.

**Comment by eahrold** [comment]
Try doing the same with hip chat in the API Token field (you can just use a dummy account), and see if that sticks.

**Comment by mbulmer** [comment]
Same issue. The channel name sticks but the API token clears itself upon saving. The "Send Test" button produces the same error.

**Comment by eahrold** [comment]
@mbulmer so I've got a few of questions that may help narrow down the issue.

1. Is this an upgrade from 10.10 where AutoPkgr was previously installed, or is it a fresh install?
1. Did an AutoPkgr keychain get created?
1. If so do you see keychain items for both Slack / HipChat in the AutoPkgr keychain?

Thanks

-- Eldon

**Comment by eahrold** [comment]
@mbulmer, I've got something I'd like for you to try when you get a chance.

Quit AutoPkgr, remove the binary located at `/Library/PrivilegedHelperTools/com.lindegroup.AutoPkgr.helper`, then relaunch AutoPkgr. 

You should be prompted to install the helper tool again.

Hopefully that will just fix it.

If not enable "Verbose Logs" from the status menu and look for these messages in the system.log
```
AutoPkgr[475]: [DEBUG] Couldn’t communicate with a helper application.
```
or 
```
com.lindegroup.AutoPkgr.helper[77355]: [ERROR] Helper Tool codesign stats: (null)
```

Let us know what you get, 
Thanks.

**Comment by mbulmer** [comment]
Sorry for the slow reply. Yes, this is an upgrade from 10.10 where AutoPkgr was already installed and configured. I didn't see any keychain entries.

Your fix did indeed do the trick. Thanks! :+1:

**Comment by eahrold** [comment]
Awesome. Any change you fond any log entries before the fix that looked like either of the above?

**Comment by mbulmer** [comment]
Sadly I did not, as I hadn't enabled verbose logs prior to attempting the first fix. I can try upgrading another machine that has AutoPkgr installed and see if I can repro if that helps.

**Comment by eahrold** [comment]
Thanks,
If that is something you have time to do, it would be greatly apericiated. Any feedback on how common this issue will be upon upgrading to 10.11 is definatley helpful.

Fingers crossed, it was a fluke, but you're already the second person to have this happen, so I'm not holding my breath.
