### ISSUE TITLE
Email alerts stopped working after upgrade to 1.3

### ISSUE THREAD

**Issue by amandaw33** [lindegroup/autopkgr#425]
Our email alerts worked ok until upgrading to 1.3.  We use exchange and our admin whitelists server IP that Autopkgr resides on which allows smtp to work without auth.

Here's output with verbose on when I search console for autopkgr when I open the app.  There is no additional errors in console when I try to send a test message, it just spins and spins in the app.

--
8/12/15 9:00:02.207 AM com.lindegroup.AutoPkgr.helper[2297]:  securityd_message_with_reply_sync Failed to talk to secd after 4 attempts.
8/12/15 9:00:02.211 AM com.lindegroup.AutoPkgr.helper[2297]:  SecOSStatusWith error:[-25291] The operation couldn’t be completed. (com.apple.security.xpc error 3 - <connection: 0x7fbfaa92ff30> { name = com.apple.securityd.xpc, listener = false, pid = 0, euid = 4294967295, egid = 4294967295, asid = 4294967295 }: Connection invalid)
8/12/15 9:00:02.266 AM secd[406]:  securityd_xpc_dictionary_handler AutoPkgr[2296] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
8/12/15 9:00:02.267 AM AutoPkgr[2296]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))
8/12/15 9:00:02.269 AM AutoPkgr[2296]: Error getting password for (null) [-25300]: The specified item could not be found in the keychain.

**Comment by eahrold** [comment]
So the fact that you're seeing this `Error getting password for (null) [-25300]` points to an issue reading the defaults, and particularly the auth username. What do you get when you do 
```
 defaults read com.lindegroup.AutoPkgr SMTPUsername
```

**Comment by amandaw33** [comment]
2015-08-12 10:03:36.440 defaults[2986:28620] 
The domain/default pair of (com.lindegroup.Autopkgr, SMTPUsername) does not exist

**Comment by eahrold** [comment]
That's exactly the issue. It's hard to say why that's not getting saved correctly. Try re-entering that in AutoPkgr and see if it takes. If not try writing setting that value via the CLI, then see if emailing starts to work.

**Comment by amandaw33** [comment]
there is no username though because there's no auth, or am I misunderstanding?

**Comment by eahrold** [comment]
I guess I'm misunderstanding. 
I thought you needed auth _unless_ your server was white listed.

So you're intended setup is that you don't ever need auth?

**Comment by amandaw33** [comment]
exactly.  the server is whitelisted, so no auth is needed, just IP address and port.

**Comment by eahrold** [comment]
Any chance the `Use Authentication` check box is checked?

**Comment by amandaw33** [comment]
it's not.

**Comment by eahrold** [comment]
I think I found it.
Try
```
defaults read com.lindegroup.AutoPkgr SMTPAuthenticationEnabled 
```
I'm guessing it'll return 1

Then do 
```
defaults write com.lindegroup.AutoPkgr SMTPAuthenticationEnabled -bool False
```
It and see if that fixes the issue.

**Comment by amandaw33** [comment]
When I run the read I get The domain/default pair of (/Users/jssadmin/Library/Preferences/com.lindegroup.AutoPkgr, SMTPAuthenticationEnabled) does not exist

Assume you still want me to run the write command to make it exist?

**Comment by eahrold** [comment]
Check and un-check the check box for that. Then see what that returns.

**Comment by amandaw33** [comment]
Checked and unchecked, now the read returns 0.  Test email fails still.  Let me know if you want new logs

**Comment by eahrold** [comment]
Are you still seeing this?
```
Error getting password for (null) 
```

**Comment by amandaw33** [comment]
yup 

8/12/15 10:55:48.100 AM AutoPkgr[3574]: Error getting password for (null) [-25300]: The specified item could not be found in the keychain.

**Comment by eahrold** [comment]
OK give this build a try...
https://www.dropbox.com/s/12cjpgvpsceo9i8/AutoPkgr-Non-Auth-Email-Fix.zip?dl=0

**Comment by amandaw33** [comment]
No more (null) error but test email doesn't go through.  Verbose logging shows "test email button clicked" though which I didn't notice before.

**Comment by eahrold** [comment]
Ok, I found one more conditional that may be causing the issue. Here's another build. 
https://www.dropbox.com/s/jsx1hute95y4mwh/AutoPkgr-Non-Auth-Email-Fix2.zip?dl=0

**Comment by amandaw33** [comment]
That did it, working!  Thank you so much for taking the time!

**Comment by eahrold** [comment]
Thank you for spending the time working this out with me. I'm glad that solved it.
