### ISSUE TITLE
New Python Error

### ISSUE THREAD

**Issue by JonMunford** [lindegroup/autopkgr#426]
I started getting this python error yesterday.  Any thoughts?

The following errors occurred:

A Python exception occurred during the execution of autopkg, see the system log for more details.
[ERROR] jss.exceptions.JSSPutError: Response Code: 500	Response: Internal Server Error. The server encountered an unexpected condition which prevented it from fulfilling the request
This report was generated by AutoPkgr

Here's the Log

Aug 12 08:34:20 autopackager.new-london.k12.ia.us AutoPkgr[285]: Processing local.jss.GoogleChrome...
Aug 12 08:34:21 autopackager.new-london.k12.ia.us apsd[69]: Certificate not yet generated
Aug 12 08:34:22 autopackager kernel[0]: hfs: summary table not allowed on FS with block size of 2048
Aug 12 08:34:22 autopackager kernel[0]: hfs: could not initialize summary table for Google Chrome
Aug 12 08:34:22 autopackager kernel[0]: hfs: mounted Google Chrome on device disk1s2
Aug 12 08:34:23 autopackager.new-london.k12.ia.us mdworker[474]: (ImportBailout.Error:1325) Asked to exit for Diskarb
Aug 12 08:34:23 autopackager.new-london.k12.ia.us mdworker[457]: (ImportBailout.Error:1325) Asked to exit for Diskarb
Aug 12 08:34:23 autopackager.new-london.k12.ia.us mdworker[473]: (ImportBailout.Error:1325) Asked to exit for Diskarb
Aug 12 08:34:23 autopackager kernel[0]: hfs: unmount initiated on Google Chrome on device disk1s2
Aug 12 08:34:24 autopackager kernel[0]: hfs: summary table not allowed on FS with block size of 2048
Aug 12 08:34:24 autopackager kernel[0]: hfs: could not initialize summary table for Google Chrome
Aug 12 08:34:24 autopackager kernel[0]: hfs: mounted Google Chrome on device disk1s2
Aug 12 08:34:24 autopackager.new-london.k12.ia.us apsd[69]: Certificate not yet generated
Aug 12 08:34:32 --- last message repeated 2 times ---
Aug 12 08:34:32 autopackager.new-london.k12.ia.us cloudphotosd[334]: Wait for push token timeout after 160s
Aug 12 08:34:34 autopackager.new-london.k12.ia.us apsd[69]: Certificate not yet generated
Aug 12 08:34:48 --- last message repeated 4 times ---
Aug 12 08:34:48 autopackager.new-london.k12.ia.us mdworker[520]: (ImportBailout.Error:1325) Asked to exit for Diskarb
Aug 12 08:34:48 autopackager.new-london.k12.ia.us mdworker[521]: (ImportBailout.Error:1325) Asked to exit for Diskarb
Aug 12 08:34:48 autopackager kernel[0]: hfs: unmount initiated on Google Chrome on device disk1s2
Aug 12 08:34:50 autopackager.new-london.k12.ia.us apsd[69]: Certificate not yet generated
Aug 12 08:34:51 autopackager.new-london.k12.ia.us AutoPkgr[285]: (FULL AUTOPKG TRACEBACK) 
	  File "/usr/local/bin/autopkg", line 1651, in <module>
	
	    sys.exit(main(sys.argv))
	  File "/usr/local/bin/autopkg", line 1645, in main
	
	    exit(subcommands[verb]['function'](argv))
	  File "/usr/local/bin/autopkg", line 1458, in run_recipes
	
	    autopackager.process(recipe)
	  File "/Library/AutoPkg/autopkglib/__init__.py", line 470, in process
	
	    self.env = processor.process()
	  File "/Library/AutoPkg/autopkglib/__init__.py", line 299, in process
	
	    self.main()
	  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 919, in main
	
	    self.groups = self.handle_groups()
	  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 431, in handle_groups
	
	    computer_group = self._add_or_update_smart_group(group)
	  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 472, in _add_or_update_smart_group
	
	    update_env="jss_group_updated", added_env="jss_group_added")
	  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 526, in _update_or_create_new
	
	    self.j.put(url, recipe_object)
	  File "/Library/Python/2.7/site-packages/python_jss-1.2.0-py2.7.egg/jss/jss.py", line 270, in put
	
	    self._error_handler(JSSPutError, response)
	  File "/Library/Python/2.7/site-packages/python_jss-1.2.0-py2.7.egg/jss/jss.py", line 185, in _error_handler
	
	    raise exception
	jss.exceptions.JSSPutError: Response Code: 500	Response: Internal Server Error. The server encountered an unexpected condition which prevented it from fulfilling the request
Aug 12 08:34:53 autopackager.new-london.k12.ia.us apsd[69]: Certificate not yet generated

Thanks Guys for all you do.

**Comment by homebysix** [comment]
Hi Iowa! Could you try opening Terminal and running `autopkg run -v GoogleChrome.jss`? Post the output of that back here, minus any sensitive information.

**Comment by JonMunford** [comment]
autopackager:jss administrator$ autopkg run -v GoogleChrome.jss
Processing GoogleChrome.jss...
URLDownloader
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing /Users/administrator/Library/AutoPkg/Cache/local.jss.GoogleChrome/downloads/GoogleChrome.dmg
EndOfCheckPhase
AppDmgVersioner
AppDmgVersioner: Mounted disk image /Users/administrator/Library/AutoPkg/Cache/local.jss.GoogleChrome/downloads/GoogleChrome.dmg
AppDmgVersioner: BundleID: com.google.Chrome
AppDmgVersioner: Version: 44.0.2403.155
PkgRootCreator
PkgRootCreator: Created /Users/administrator/Library/AutoPkg/Cache/local.jss.GoogleChrome/GoogleChrome
PkgRootCreator: Created /Users/administrator/Library/AutoPkg/Cache/local.jss.GoogleChrome/GoogleChrome/Applications
Copier
Copier: Mounted disk image /Users/administrator/Library/AutoPkg/Cache/local.jss.GoogleChrome/downloads/GoogleChrome.dmg
Copier: Copied /private/tmp/dmg.a4FDah/Google Chrome.app to /Users/administrator/Library/AutoPkg/Cache/local.jss.GoogleChrome/GoogleChrome/Applications/Google Chrome.app
PkgCreator
PkgCreator: Package already exists at path /Users/administrator/Library/AutoPkg/Cache/local.jss.GoogleChrome/GoogleChrome-44.0.2403.155.pkg.
PkgCreator: Existing package matches version and identifier, not building.
JSSImporter
JSSImporter: Category type: category-'Browsers' already exists according to JSS, moving on...
JSSImporter: Category type: policy_category-'Auto Update' already exists according to JSS, moving on...
JSSImporter: Pkg-object already exists according to JSS, moving on...
JSSImporter: Package upload not needed.
JSSImporter: Found file: /Users/administrator/Library/AutoPkg/RecipeOverrides/AutoUpdateSmartGroupTemplate.xml
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 1651, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 1645, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1458, in run_recipes
    autopackager.process(recipe)
  File "/Library/AutoPkg/autopkglib/__init__.py", line 470, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 299, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 919, in main
    self.groups = self.handle_groups()
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 431, in handle_groups
    computer_group = self._add_or_update_smart_group(group)
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 472, in _add_or_update_smart_group
    update_env="jss_group_updated", added_env="jss_group_added")
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 526, in _update_or_create_new
    self.j.put(url, recipe_object)
  File "/Library/Python/2.7/site-packages/python_jss-1.2.0-py2.7.egg/jss/jss.py", line 270, in put
    self._error_handler(JSSPutError, response)
  File "/Library/Python/2.7/site-packages/python_jss-1.2.0-py2.7.egg/jss/jss.py", line 185, in _error_handler
    raise exception
jss.exceptions.JSSPutError: Response Code: 500	Response: Internal Server Error. The server encountered an unexpected condition which prevented it from fulfilling the request

**Comment by homebysix** [comment]
@JonMunford, because this is happening in Terminal, I'm afraid it's an issue with JSSImporter or python-jss rather than AutoPkgr. You might want to paste the log above into a new issue for [JSSImporter](https://github.com/sheagcraig/JSSImporter/issues) and see what Shea says.

Once that's fixed, I'm guessing your AutoPkgr recipes will work as expected.
