### ISSUE TITLE
GUI crash with space in path

### ISSUE THREAD

**Issue by swy** [lindegroup/autopkgr#435]
Using an iMac with boot volume and my user home on separate disks.  When AutoPkg loads, it quits unexpectedly with the following error:

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Failed to set working directory to /Volumes/BigMac with error 20'
terminating with uncaught exception of type NSException
abort() called

/Volumes/BigMac 1TB is the disk that holds my home directory.

**Comment by homebysix** [comment]
This fix is queued up for 1.3.2. Thanks @swy!

**Comment by swy** [comment]
Sweet.  Beats renaming my drive that holds ~/.  :)

**Comment by eahrold** [comment]
@swy, Absolutely. I'm just dumbfounded we didn't see this sooner.
It was something that definitely needed fixed.

Here's a build to tide you over until the official release comes out.
https://www.dropbox.com/s/lqxje30ywfvwy3k/AutoPkgr-path-fix.zip?dl=0

**Comment by swy** [comment]
It wasn't always like this.  I've had that naming convention and ~/ over there for for a while, and have done autopkgr on my personal gear for many months, but specifically when I updated and received this crash- not thoroughly documented.  It's my home gear, I don't pay as close attention.
