### ISSUE TITLE
"Error removing repo" error

### ISSUE THREAD

**Issue by leoos** [lindegroup/autopkgr#436]
The functionality mentioned in the notes for version 1.2 of holding down the option key seems to have disappeared.

I moved my Mac home folder from one location to another on a different drive.

AutoPkgr still thinks my recipes etc are in the old home folder location
![errormsg](https://cloud.githubusercontent.com/assets/6201014/9517669/796fc5ce-4ca9-11e5-80b3-743145e08f8e.jpg)
I have set the folders correctly in the Folders and Integration tab without success
![screen shot 2015-08-27 at 10 47 05](https://cloud.githubusercontent.com/assets/6201014/9517685/8d974054-4ca9-11e5-829b-8d03d6c49163.png)
I'm wondering how to do a complete uninstall and reinstall to fix this. Or is there another way I could fix this easily.

**Comment by eahrold** [comment]
@leoos,
Thanks for the report. We've been seeing this a lot lately.

The uninstall function is still there, but that won't fix this issue.
What you need to do is quit AutoPkgr, then run these two commands in the terminal.

`
defaults delete com.github.autopkg RECIPE_REPOS
defaults delete com.github.autopkg RECIPE_SEARCH_DIRS
`

Relaunch AutoPkg, and re-enable the repos you use.

**Comment by homebysix** [comment]
@leoos Try seeing which repos are listed in `autopkg repo-list`. I'm guessing there won't be any, so you'll need to add some. You can do this by checking the boxes for the repos you need in the Repos & Recipes tab in AutoPkgr. Specifically, you'll want to add any repos which contain the parent recipes for your overrides.

**Comment by David5182** [comment]
@eahrold 
Thank you,  I too had the "Error removing repo" issue.
Your fixed worked for me as well.
