### ISSUE TITLE
Feature Request: Ability to customize the name displayed in Slack integration

### ISSUE THREAD

**Issue by kitzy** [lindegroup/autopkgr#437]
I'd like the ability to customize the name displayed in the Slack integration. I have a few AutoPkgr instances all reporting to the same Slack channel, and it's difficult to tell them apart because they're all called AutoPkgr. If I could name one AutoPkgr-prod and another AutoPkgr-dev, that would make things so much easier for me.

**Comment by homebysix** [comment]
@eahrold It looks like we can just change [this](https://github.com/lindegroup/autopkgr/blob/master/AutoPkgr/Models/Email%20%26%20Notifications/LGSlackNotification.m#L103) to a variable, then link it up to the box I added in cd730c2141509775084dacf77d821f1b6a9e7ea1.

**Comment by eahrold** [comment]
Sounds good.
