### ISSUE TITLE
Slack notification errors

### ISSUE THREAD

**Issue by efranklin** [lindegroup/autopkgr#438]
I just setup AutoPkgr to run hourly and integrated with a Slack channel. I receive this error every hour, "An error occurred while running AutoPkg:"

I've enabled verbose logging and this is the only errors I see. 

8/28/15 10:18:58.876 AM com.lindegroup.AutoPkgr.helper[2506]:  securityd_message_with_reply_sync Failed to talk to secd after 4 attempts.
8/28/15 10:18:58.876 AM com.lindegroup.AutoPkgr.helper[2506]:  SecOSStatusWith error:[-25291] The operation couldn’t be completed. (com.apple.security.xpc error 3 - <connection: 0x7fe63bd1b460> { name = com.apple.securityd.xpc, listener = false, pid = 0, euid = 4294967295, egid = 4294967295, asid = 4294967295 }: Connection invalid)
8/28/15 10:18:58.908 AM com.lindegroup.AutoPkgr.helper[2506]: Sending keychain key to AutoPkgr.
8/28/15 10:18:58.922 AM secd[243]:  securityd_xpc_dictionary_handler AutoPkgr[313] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
8/28/15 10:18:58.923 AM AutoPkgr[313]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))

Suggestions?

**Comment by homebysix** [comment]
@efranklin The `Failed to talk to secd` message makes me think there's something wrong with the security daemon. Are you able to try restarting the Mac, then running the recipes again?

**Comment by efranklin** [comment]
I've restarted the Mac and I'm still getting the same error. 

I also found a new error that just started happening. I'm now also getting this error only in the logs:
8/28/15 11:43:31.648 AM AutoPkgr[290]: Error [1] Error running recipes 
 No valid recipe found for com.github.arubdesu.munki.MSOneNote2016

I don't have that recipe selected.

**Comment by efranklin** [comment]
The errors have stopped. Not sure what fixed it but here is what I did.

I added com.github.autopkg.munki.MSOneNote2016 and removed com.github.arubdesu.munki.MSOneNote2016 from the recipe_list.txt file in Application Support/AutoPkgr

I've run manually run AutoPkgr a couple of times without any errors. 

Thank you for your help.
