### ISSUE TITLE
[Enhancement] Easier Backup of AutoPkgr Configuration

### ISSUE THREAD

**Issue by rougegoat** [lindegroup/autopkgr#442]
I started digging around and backing things up for standard "What if the server exploded four times and you no longer worked here to fix it?" type of hypotheticals.  I noticed there was no obvious way to backup AutoPkgr's configuration(which repos, selected recipes, plugins, servers, etc).  I couldn't find a good way to export/import the settings.  I ended up just backing up our overrides and updating our "How to set up AutoPkgr from scratch" documentation.

I can see a bunch of different reasons why one would want to backup the configuration of AutoPkgr.  This tool is super handy, but also kind of a pain to set up if you're new to things.  Are there any plans for implementing a backup and restore system in AutoPkgr?

**Comment by homebysix** [comment]
AutoPkgr itself is straightforward to back up. Here are the files you may want to include:

- /Library/LaunchDaemons/com.lindegroup.AutoPkgr.helper.plist
- /Library/LaunchDaemons/com.lindegroup.AutoPkgr.schedule.plist
- /Library/PrivilegedHelperTools/com.lindegroup.AutoPkgr.helper
- __~/Library/Application Support/AutoPkgr__
- ~/Library/Keychains/AutoPkgr.keychain
- ~/Library/LaunchAgents/com.lindegroup.AutoPkgr.launcher.plist
- __~/Library/Preferences/com.lindegroup.AutoPkgr.plist__

(The ones in bold are the most crucial, as they're harder to re-create from scratch.)

The difficulty comes when you start to consider backing up the Git install, AutoPkg repos, JSSImporter configuration, etc. These are things I don't think it should be AutoPkgr's job to back up.

My go-to solution so far has been to use Carbon Copy Cloner or a similar utility to produce a nightly clone of the AutoPkgr Mac (which is usually also a Casper distribution point or Munki repo itself). I'm sure there are more granular ways to do this, but I haven't needed/wanted to consider them.

**Comment by rougegoat** [comment]
True enough.  I just figure any place that someone can find themselves confused is one where a potential new feature can be created.  Most of the time people won't need it, but it'd be nice to have.  I guess more of a sprinkle feature than a key feature.
