### ISSUE TITLE
AutoPkgr remains on "Adding default repo" message upon installing JSSImporter

### ISSUE THREAD

**Issue by homebysix** [lindegroup/autopkgr#443]
I've seen this in 1.3.1 on OS X 10.8 and 10.9, and testing on 10.10 now.

Steps to reproduce:

1. Open AutoPkgr on a fresh Mac.
2. Install Git and AutoPkg.
3. Switch to Folders & Integration tab, and click Install JSSImporter.
4. Observe that the install succeeds, but AutoPkgr sticks on this screen:

![screen shot 2015-09-02 at 8 32 21 am](https://cloud.githubusercontent.com/assets/7801391/9636168/f785183e-514e-11e5-8851-075490dc3aaa.png)

Expected behavior is for the sheet to disappear after the jss-recipes repo has been added.

**Comment by homebysix** [comment]
Confirmed, this happens on 10.10 as well. And it seems to happen regardless of whether I add the `autopkg/recipes` or `autopkg/jss-recipes` repos prior to JSSImporter installation.

**Comment by rtrouton** [comment]
I just saw this on a newly-built 10.10.5 VM running AutoPkgr 1.3.1, JSSImporter and AutoPkg 0.5.1.

**Comment by homebysix** [comment]
@eahrold - Got time to look into this one? It's not a big deal for people with existing AutoPkgr setups, but for people downloading a fresh copy and connecting to a JSS, it's a negative first impression.

I might even push out 1.3.2 just for this, if it's fixable.

**Comment by eahrold** [comment]
Done.

**Comment by homebysix** [comment]
Thanks Eldon! On track for 1.3.2.

**Comment by eahrold** [comment]
Great!
