### ISSUE TITLE
"Reveal Recipe in Finder" contextual menu option in recipes table

### ISSUE THREAD

**Issue by magnusviri** [lindegroup/autopkgr#444]
I'd like to request changes for the Repos & Recipes tab.
- Add "Select All" and "Deselect All" for the Repos? (Selecting all takes forever right now)
- Add "Hide unselected" for repos and recipes? (If I've got all repos selected, the recipes list is giant and once I've selected my repos I'm unlikely go to go find new ones and I'd just want to view the status of the ones I have selected)
- Show stars (the same star show in the repo list) in the recipes list next to "Recipe Identifier"? (to allow judging between 2 similar recipes)
- Add a "Reveal in Finder" or some other way to view a recipe? (to help judge between 2 similar recipes)

**Comment by homebysix** [comment]
Hi @magnusviri!

- "Select All" and "Deselect All" is being discussed in this thread: https://github.com/lindegroup/autopkgr/issues/434
- Regarding "hide selected," I think that would be confusing for organizations who have multiple IT people administering AutoPkgr. Why not use the built-in filter function to trim down the list, if scrolling is cumbersome?
- If you find yourself judging between two similar recipes, I'd urge you to inspect the recipes themselves and see what they do. Stars are not a reliable indicator of which one you should choose.
- "Reveal in Finder" is a great idea! Maybe for the repos too.

**Comment by magnusviri** [comment]
On Sep 4, 2015, at 10:05 AM, Elliot Jordan <notifications@github.com> wrote:

> Hi @magnusviri!
> 
> 	� "Select All" and "Deselect All" is being discussed in this thread: #434

Sounds like you guys are already on it.

> 	� Regarding "hide selected," I think that would be confusing for organizations who have multiple IT people administering AutoPkgr. Why not use the built-in filter function to trim down the list, if scrolling is cumbersome?

I think you�re right.  I can also sort by the check box column (I didn�t think of that before I submitted the comment).

> 	� If you find yourself judging between two similar recipes, I'd urge you to inspect the recipes themselves and see what they do. Stars are not a reliable indicator of which one you should choose.

You�ve already got stars in the Repo list.  I have no idea what those stars actually represent, I assume it means someone has �favorited� it or something like that somewhere.  If a recipe comes from a repo with 20 stars and a recipe with the same name comes from a repo with no stars, it might be helpful to see that next to the repo identifier.  If the stars aren�t an indication of anything, why have them in the Repo list?

James

**Comment by homebysix** [comment]
Hi @magnusviri,

The stars represent the number of people who have clicked the "Star" button at the top of the repo's GitHub page:
![screen shot 2015-09-04 at 9 23 56 am](https://cloud.githubusercontent.com/assets/7801391/9688852/b74b6a2c-52e6-11e5-9a03-ea734f021a7d.png)

As such, it's mostly a popularity contest, and older repos tend to have more stars than newer repos, even if the newer ones are improved in some way.

The stars are meant to be a fun and simple way to determine which popular repos you might want to learn more about. But I don't think associating a recipe with the star count of its repo is useful.

**Comment by magnusviri** [comment]
I am just trying out autopkg and autopkgr for the first time now, so I have lots of ideas as I use it.  I thought I�d throw another one out.  I don�t use munki or Absolute.  It would be nice to be able to permanently exclude them from the recipe list, that is, a reverse filter.

James

**Comment by homebysix** [comment]
@magnusviri When we were originally designing AutoPkgr, we thought briefly about checkboxes that allow you to specify which "types" of recipes you want to see. You'd be able to select download, pkg, and JSS recipes, for example, and exclude others.

However, we ultimately rejected that idea because recipe "types" are arbitrary. I can publish a recipe called `Firefox.definitelynotmunki`, which is actually a JSS recipe, and AutoPkg/AutoPkgr won't complain at all.

Also, we don't have any way to predict what "types" will be available in the future. If we don't update AutoPkgr to allow selection/exclusion of a new "type," then AutoPkgr looks like it's not keeping up with the times. And if we do update for each new "type," then we're trapped in a constant care-and-feeding cycle.

Better to filter for the recipes you want, rather than exclude the ones you don't, IMHO.

**Comment by magnusviri** [comment]
One thing that might indicate general quality of a recipe is when it was last updated.  Maybe there could be a column for that.

James

**Comment by homebysix** [comment]
How would you define "quality?" I think we want to stay away from editorialization and allow AutoPkgr users to inspect the recipes directly to determine the quality of a recipe. As such, your Reveal in Finder suggestion is a good one.

**Comment by magnusviri** [comment]
> Better to filter for the recipes you want, rather than exclude the ones you don't, IMHO.

I guess that makes sense and works.  I�m not sure how hard it would be to put booleans in the filter field, like ".pkg .download�.

> How would you define "quality?" I think we want to stay away from editorialization and allow AutoPkgr users to inspect the recipes directly to determine the quality of a recipe. As such, your Reveal in Finder suggestion is a good one.

Maybe quality is the wrong word.  I�m just using AutoPkgr for the first time.  As a first time user I�m looking at this giant list of recipes. I have no way of judging one from another except by opening the recipe file, and I know I�m going to have to learn how to read it, but right now I don�t know anything about it.  I�ve selected a bunch I think I might want but they�re generating errors.

AutoPkg and AutoPkgr is basically an App Store.  I don�t know if you guys view it as such, but that�s what it is.  Right now it�s very hard to figure anything out.  Honestly, if this were all Terminal based I wouldn�t even think to ask any of these things, but AutoPkgr takes something that is time consuming and makes it so quick and easy that it is too easy to think the app should do even more work.

The last modified date idea was inspired by the idea that some of these repos might be years old, especially if an admin who made the repo quit his job or quit using autopkg.  A last modified date would help someone like me deduce if it is going to work.

Anyway, I think you guys have done an amazing job.  I know you�re giving this away freely and it�s not a trivial product.  Thank you for what you�re giving away to help others do their jobs easier.

James

**Comment by ygini** [comment]
+1 for Reveal in Finder

**Comment by workflowsguy** [comment]
+1 for "Reveal in Finder"
Currently, in a recipe's "Get Info" window, the display of the path is truncated and can't even be selected for Copy & Paste
