### ISSUE TITLE
directory not found for option

### ISSUE THREAD

**Issue by hac** [lindegroup/autopkgr#445]
Hello, I have downloaded the source code, changed the certificates and installed the cocoapods. When I try to install I get these two errors:

ld: warning: directory not found for option '-L/Users/scoobs/Library/Developer/Xcode/DerivedData/AutoPkgr-gvffmulnnaejibfmmwfptzyobmbb/Build/Products/Debug'
ld: library not found for -lMailCore
clang: error: linker command failed with exit code 1 (use -v to see invocation)

when building AutoPkgr.helper

Thank you!

**Comment by homebysix** [comment]
Hi @hac — did you install CocoaPods and run `pod install` on the repo?

**Comment by homebysix** [comment]
Hi @hac — are you still having this issue? You may want to try the `twitter-notifications` branch, as some pod changes were made there.
