### ISSUE TITLE
Python Exception occured

### ISSUE THREAD

**Issue by esantiago** [lindegroup/autopkgr#451]
ascii' codec can't encode character u'\u2019' in position 189: ordinal not in range(128)

**Comment by eahrold** [comment]
@esantiago this is due to a curly quote in one of your overrides. Look through all of them and correct it. 

In general you should try and avoid using rtf text editors like Microsoft word or even textedit and stick to one for programming like Textmate2 or Atom.

**Comment by esantiago** [comment]
I checked all of my overrides and tested a couple non-override recipes and they spit out the same error.
"/
I haven't made any changes in a while. Any other places I should look?

**Comment by esantiago** [comment]
Found it!!! @eahrold 
 I had a repository which was unchecked - Didn't show that skype.jss recipe was culprit.
Even though the repo was unchecked The skype.jss.local still ran. Removed override and remade it. Solved all my problems.
THANKS!!!
