### ISSUE TITLE
Not sending notice to Slack

### ISSUE THREAD

**Issue by mholtrlc** [lindegroup/autopkgr#452]
I'm not getting a notice in Slack of updated software but it pops up in the OS X Notification Bar.  I turned on verbose logging and don't see any errors coming up. I also get the test notification when I click "Send Test"

**Comment by mholtrlc** [comment]
same result with hipchat and email notice

**Comment by eahrold** [comment]
@mholtrlc sorry I haven't responded sooner. I'm just a little stumped on what could be causing this. The fact that it's happening with all three, but not user notifications made me think it was a keychain thing, but the fact that you can send a test notification means it's not that.

Turn on verbose logging and see if that gets you any additional clues as to the culprit.

Thanks

**Comment by mholtrlc** [comment]
It actually started working on it's own, not sure what changed.

Thanks!

**Comment by eahrold** [comment]
Hmm it may have been a network issue. Do you use any proxies?

**Comment by mholtrlc** [comment]
nope no proxies or anything special

[image: Real Life Church] <http://www.reallifechurch.org>

Michael Holt / IT Administrator
(661) 705-4711/ mholt@reallifechurch.org

Real Life Church Office: (661) 775-7401
23841 Newhall Ranch Rd
Valencia, CA 91355
http://www.reallifechurch.org

This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
Any unauthorized disclosure, dissemination, distribution, copying or the
taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they
can be intercepted, amended, or contain viruses. Anyone who communicates
with us by e-mail is deemed to have accepted these risks. Company Name is
not responsible for errors or omissions in this message and denies any
responsibility for any damage arising from the use of e-mail. Any opinion
and other statement contained in this message and any attachment are solely
those of the author and do not necessarily represent those of the company.
