### ISSUE TITLE
errors on scheduled runs after upgrade to 10.10

### ISSUE THREAD

**Issue by henningkessler** [lindegroup/autopkgr#453]
Hello,

first of all thanks for this wonderful application :-). 

My issue is that after I upgraded my deployment machine to 10.10 I had problems with some certificates which where somehow duplicated in the upgrade process. After the upgrade any certificate request for URLs of Google or Oracle was throwing errors and so did Autopkgr.

		Couldn't download https://dl.google.com/googletalk/googletalkplugin/GoogleVoiceAndVideoSetup.dmg (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>)

		Couldn't download https://dl.google.com/drive/installgoogledrive.dmg (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>)

		Couldn't download http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jre-8u60-macosx-x64.dmg (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>)

		Couldn't download https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>)

 I resolved the issue by deleting the duplicated certificate and after that i could run autopkg from the command line and manually from the application without any error. Only if Autpkgr is running a as background task the error seams to persist?

 This is what the system.log shows:

		Sep 28 09:10:35 themachine AutoPkgr[32839]: Running AutoPkgr in background...
		Sep 28 09:10:36 themachine AutoPkgr[32839]: Attempting git pull for /Users/master707/Library/AutoPkg/RecipeRepos/com.github.autopkg.jessepeterson-recipes...
		Sep 28 09:10:37 themachine AutoPkgr[32839]: Already up-to-date.
			Attempting git pull for /Users/master707/Library/AutoPkg/RecipeRepos/com.github.autopkg.jps3-recipes...
		Sep 28 09:10:37 themachine AutoPkgr[32839]: Already up-to-date.
			Attempting git pull for /Users/master707/Library/AutoPkg/RecipeRepos/com.github.autopkg.munkireport-recipes...
		Sep 28 09:10:38 themachine AutoPkgr[32839]: Already up-to-date.
			Attempting git pull for /Users/master707/Library/AutoPkg/RecipeRepos/com.github.autopkg.mosen-recipes...
		Sep 28 09:10:39 themachine AutoPkgr[32839]: Already up-to-date.
			Attempting git pull for /Users/master707/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes...
		Sep 28 09:10:40 themachine AutoPkgr[32839]: Already up-to-date.
			Attempting git pull for /Users/master707/Library/AutoPkg/RecipeRepos/com.github.autopkg.joshua-d-miller-recipes...
		Sep 28 09:10:41 themachine AutoPkgr[32839]: Already up-to-date.
			Attempting git pull for /Users/master707/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes...
		Sep 28 09:10:41 themachine AutoPkgr[32839]: Already up-to-date.
			Attempting git pull for /Users/master707/Library/AutoPkg/RecipeRepos/com.github.autopkg.hjuutilainen-recipes...
		Sep 28 09:10:42 themachine AutoPkgr[32839]: Already up-to-date.
			Attempting git pull for /Users/master707/Library/AutoPkg/RecipeRepos/com.github.autopkg.dankeller-recipes...
		Sep 28 09:10:43 themachine AutoPkgr[32839]: Already up-to-date.
			Attempting git pull for /Users/master707/Library/AutoPkg/RecipeRepos/com.github.autopkg.keeleysam-recipes...
		Sep 28 09:10:43 themachine AutoPkgr[32839]: Already up-to-date.
			Attempting git pull for /Users/master707/Library/AutoPkg/RecipeRepos/com.github.autopkg.sheagcraig-recipes...
		Sep 28 09:10:44 themachine AutoPkgr[32839]: Already up-to-date.
			Attempting git pull for /Users/master707/Library/AutoPkg/RecipeRepos/com.github.autopkg.arubdesu-recipes...
		Sep 28 09:10:45 themachine AutoPkgr[32839]: Already up-to-date.
			Attempting git pull for /Users/master707/Library/AutoPkg/RecipeRepos/com.github.autopkg.wardsparadox-recipes...
		Sep 28 09:10:46 themachine AutoPkgr[32839]: Processing local.munki.GoogleVoiceAndVideo...
		Sep 28 09:10:46 themachine AutoPkgr[32839]: Processing local.munki.GoogleEarth...
		Sep 28 09:11:11 themachine AutoPkgr[32839]: Processing local.munki.GoogleDrive...
		Sep 28 09:11:12 themachine AutoPkgr[32839]: Processing local.munki.OracleJava8...
		Sep 28 09:11:12 themachine AutoPkgr[32839]: Processing local.munki.FontExplorerXPro...
		Sep 28 09:11:16 themachine AutoPkgr[32839]: Processing local.munki.munkireport...
		Sep 28 09:11:18 themachine AutoPkgr[32839]: Processing local.munki.AdobeAcrobatProXUpdate...
		Sep 28 09:11:21 themachine AutoPkgr[32839]: Processing local.munki.MSExcel2016...
		Sep 28 09:11:30 themachine AutoPkgr[32839]: Processing local.munki.MSWord2016...
		Sep 28 09:11:38 themachine AutoPkgr[32839]: Processing local.munki.MSPowerPoint2016...
		Sep 28 09:11:45 themachine AutoPkgr[32839]: Processing local.munki.MSOutlook2016...
		Sep 28 09:11:51 themachine AutoPkgr[32839]: Processing local.munki.MSOneNote2016...
		Sep 28 09:11:55 themachine AutoPkgr[32839]: Processing local.munki.munkitools2...
		Sep 28 09:12:01 themachine AutoPkgr[32839]: Processing local.munki.munkitools...
		Sep 28 09:12:13 themachine AutoPkgr[32839]: Processing local.munki.WacomIntuosProDriver...
		Sep 28 09:12:27 themachine AutoPkgr[32839]: Processing local.munki.Viscosity...
		Sep 28 09:12:30 themachine AutoPkgr[32839]: Processing local.munki.VLC...
		Sep 28 09:13:00 themachine AutoPkgr[32839]: Processing local.munki.TextWrangler...
		Sep 28 09:13:07 themachine AutoPkgr[32839]: Processing local.munki.TeamViewerQS...
		Sep 28 09:13:12 themachine AutoPkgr[32839]: Processing local.munki.TeamViewer...
		Sep 28 09:13:19 themachine AutoPkgr[32839]: Processing local.munki.Silverlight...
		Sep 28 09:13:24 themachine AutoPkgr[32839]: Processing local.munki.Puppet...
		Sep 28 09:13:28 themachine AutoPkgr[32839]: Processing local.munki.Handbrake...
		Sep 28 09:13:32 themachine AutoPkgr[32839]: Processing local.munki.MSOffice2011Updates...
		Sep 28 09:13:39 themachine AutoPkgr[32839]: Processing local.munki.GoogleChrome...
		Sep 28 09:13:40 themachine AutoPkgr[32839]: Processing local.munki.Firefox...
		Sep 28 09:13:54 themachine AutoPkgr[32839]: Processing local.munki.Facter...
		Sep 28 09:13:58 themachine AutoPkgr[32839]: Processing local.munki.Evernote...
		Sep 28 09:14:26 themachine AutoPkgr[32839]: Processing local.munki.Dropbox...
		Sep 28 09:14:33 themachine AutoPkgr[32839]: Processing local.munki.AdobeFlashPlayerExtractPackage...
		Sep 28 09:14:52 themachine AutoPkgr[32839]: Processing local.munki.SketchUpMake...
		Sep 28 09:15:37 themachine AutoPkgr[32839]: Processing local.munki.SublimeText3...
		Sep 28 09:15:40 themachine AutoPkgr[32839]: Processing local.munki.Spotify...
		Sep 28 09:15:48 themachine AutoPkgr[32839]: Processing local.munki.Cyberduck...
		Sep 28 09:16:13 themachine AutoPkgr[32839]: Processing local.munki.AdwareMedic...
		Sep 28 09:16:24 themachine AutoPkgr[32839]: Processing com.github.autopkg.munki.makecatalogs...
		Sep 28 09:16:27 themachine nsurlstoraged[372]: realpath() returned NULL for /Users/master707/Library/Caches/com.lindegroup.AutoPkgr
		Sep 28 09:16:27 themachine nsurlstoraged[372]: The read-connection to the DB=/Users/master707/Library/Caches/com.lindegroup.AutoPkgr/Cache.db is NOT valid.  Unable to determine schema version.
		Sep 28 09:16:27 themachine nsurlstoraged[372]: realpath() returned NULL for /Users/master707/Library/Caches/com.lindegroup.AutoPkgr
		Sep 28 09:16:27 themachine nsurlstoraged[372]: ERROR: unable to determine file-system usage for FS-backed cache at /Users/master707/Library/Caches/com.lindegroup.AutoPkgr/fsCachedData. Errno=13
		Sep 28 09:16:29 themachine com.lindegroup.AutoPkgr.helper[30828]:  securityd_message_with_reply_sync Failed to talk to secd after 4 attempts.
		Sep 28 09:16:29 themachine com.lindegroup.AutoPkgr.helper[30828]:  SecOSStatusWith error:[-25291] The operation couldn’t be completed. (com.apple.security.xpc error 3 - <connection: 0x7fc860c38270> { name = com.apple.securityd.xpc, listener = false, pid = 0, euid = 4294967295, egid = 4294967295, asid = 4294967295 }: Connection invalid)
		Sep 28 09:16:29 themachine com.lindegroup.AutoPkgr.helper[30828]: Sending keychain key to AutoPkgr.
		Sep 28 09:16:29 themachine AutoPkgr[32839]:  securityd_message_with_reply_sync Failed to talk to secd after 4 attempts.
		Sep 28 09:16:29 themachine AutoPkgr[32839]:  SecOSStatusWith error:[-25291] The operation couldn’t be completed. (com.apple.security.xpc error 3 - <connection: 0x7faad0d3bd40> { name = com.apple.securityd.xpc, listener = false, pid = 0, euid = 4294967295, egid = 4294967295, asid = 4294967295 }: Connection invalid)
		Sep 28 09:16:30 themachine AutoPkgr[32839]: AutoPkgr background run complete.

There must some issue with the cache, right?

Regards

Henning

**Comment by homebysix** [comment]
Hi @henningkessler,

I think what you're seeing sounds like two separate issues — one with the certificates (which you've solved) and one with `realpath()`. Or do you think they're related somehow?

Elliot

**Comment by henningkessler** [comment]
Hi @homebysix ,

guess you are right. It seams to be like a stale cache issue. Should i just delete the cache in 
```
/Users/master707/Library/Caches/com.lindegroup.AutoPkgr
```

?

**Comment by homebysix** [comment]
Couldn't hurt. The cache is meant to be rebuildable, anyway.

**Comment by henningkessler** [comment]
well deleting the cache did not solve the issue. As next step I have deselected the recipes just to see what will happen...

**Comment by eahrold** [comment]
What are the symptoms now? Notifications not sending?

**Comment by henningkessler** [comment]
After deselecting almost all troublesome recipes the errors on those didn't show up on the next run but after reactivation the same errors reappeared too.

**Comment by homebysix** [comment]
Can you narrow it down to one or two recipes that cause the error to happen? If so, I'll try running the recipes and see whether the behavior differs on my end.

**Comment by eahrold** [comment]
I don't think it has to do with recepie runs. NSURLConnection makes me suspect something during notification sending. That's why I ask about symptoms.

**Comment by henningkessler** [comment]
I am also quite sure that this is no recipe issue as I can run them via command line AND manually with AutoPkgr without any issues. My next step was to restart the server and then gave it a run with:
		/Applications/AutoPkgr.app/Contents/MacOS/AutoPkgr -runInBackground YES

(same as in com.lindegroup.AutoPkgr.schedule.plist.)

Ended without any errors (but also no notification email?)

Henning

**Comment by henningkessler** [comment]
Well the next scheduled run there they are again, my unwanted friends ;-). Any idea what I could try now?

**Comment by homebysix** [comment]
You could try disabling notifications, then re-enable one notification at a time and run some recipes to figure out which notification type is causing the error.

If it's email, you might try sending through a different email address (or host) to see whether that makes any difference.

**Comment by henningkessler** [comment]
okay i will check that tomorrow. Thanks.

**Comment by henningkessler** [comment]
Well I deselected all recipes that produced errors then I switch notification off and on again, used another recipient for mail and activated the slack notificationd. After this I waited for the first schedule run which produced no errors.

Then i reactivated the error producing recipes and waited for another scheduled run. Unfortunately the errors reappeared an both notification methods...

**Comment by eahrold** [comment]
How much of that cache folder did you delete? The folder itself for just the contents?

**Comment by eahrold** [comment]
Also do sending test notifications work?

**Comment by henningkessler** [comment]
I guess i just deleted the folder contents not the folder itself. I am deleting it now. And I had no issues with sending test notifications.

**Comment by henningkessler** [comment]
deleting the folder did not solve my issue.

**Comment by henningkessler** [comment]
okay I now uninstalled AutoPkgr from the machine by 
- unloading the LaunchDaemons in /Library
- deleting the LaunchDaemons in /Library, 
- deleting the agent in ~/Library, 
- deleting the cache,
- deleting the preference file (killing cfprefsd after that), 
- deleting the helper tool in /Library/PrivilegedHelperTools 
- deleting the app.
After this I installed the app by dragging it into the Applications folder. Then i double-clicked it and authenticated as Administrator. The result of this operation is an error dialog:
```
The associated helper tool could not be installed, we must quit now.
```
in system.log i found these entries:
```
Oct  1 12:25:10 themachine AutoPkgr[14498]: Welcome to AutoPkgr!
Oct  1 12:25:15 themachine smd[282]: Could not bootstrap privileged helper job: 119: Service is disabled
```

**Comment by eahrold** [comment]
When you unloaded the com.lindegroup.Autopkgr.helper.plist did you use the -w flag? Doing so would cause this error and you would need to load it manually with the -w flag.

**Comment by henningkessler** [comment]
Hi Eldon,

thank you, that did solved the issue with installing the helper tool. I guess using the -w flag almost every time is a bad habit...

**Comment by henningkessler** [comment]
After a couple of other strange issues (smb file sharing seams to be borked) with my deployment server after upgrading to 10.10  I guess my issues with AutoPkgr are just symptoms of some deeper problems. Certain services have the same issue that they could work reliable with their cache ;-(.
