### ISSUE TITLE
CDNs result in 'version-flapping', unnecessary notifications

### ISSUE THREAD

**Issue by wildeep** [lindegroup/autopkgr#454]
I've had this issue specifically with the Dropbox.munki recipe.

AutoPKGr will fire, and ask for the latest version of Dropbox. Dropbox is distributed by a Content Distribution Network, and there exists a "propagation period" where queries return inconsistent results.

This inconsistency results in unnecessary notifications.

**Comment by homebysix** [comment]
This issue is not related to AutoPkgr, nor is it one that I think the AutoPkg authors are interested in solving. I'd recommend turning off the recipe until you know Dropbox's CDNs are synced back up, if the notifications bother you.
