### ISSUE TITLE
Autopkg removes recipe list but still displays selected recipes

### ISSUE THREAD

**Issue by WardsParadox** [lindegroup/autopkgr#455]
Instead of having to replace my RecipeList when the share where our autopkg repos and overrides exist disconnects, to just not run at the scheduled time. I also noticed that the recipe view will still show that all of the deactivated recipes are selected but upon a run will result in another error. Only after a repo update will the recipe list then flush.

**Comment by homebysix** [comment]
I recommend storing your autopkg repos and recipes on the same local volume as AutoPkgr, or somehow ensuring that the sharepoint they're stored on is mounted before AutoPkgr launches.

**Comment by WardsParadox** [comment]
So this same behavior exists with a local autopkg Recipe, Overrides etc. at least in terms of autopkgr displaying the list still shown as active.

**Comment by homebysix** [comment]
In that case, I guess I'm unclear about what the behavior is. The ~/Library/Preferences/com.lindegroup.AutoPkgr.plist file and the ~/Library/Application Support/AutoPkgr/recipe_list.txt files are both required to be present while AutoPkgr is running, in order for the recipe list to behave as expected.

Could you list the steps you followed to reproduce the problem behavior, and I'll try them in a VM?

**Comment by eahrold** [comment]
The only way AutoPkgr could ever know to  reload the table view to reflect manual changes to the recipe_list.txt is by doing and fsevent on that file. an interesting idea, but I'm not sure it's worth the overhead.
