### ISSUE TITLE
Recipes with the same title cannot be reliably selected to "Run This Recipe Only"

### ISSUE THREAD

**Issue by jazzace** [lindegroup/autopkgr#456]
This issue is similar to #447, but does not necessarily cause the dual spinning sprockets.

Steps to reproduce:
1. In the Repos & Recipes tab, load jazzace-recipes and mosen-recipes.
2. In the same tab, search/filter for i1Profiler recipes.
3. Bring up the contextual menu for (right-click on) mosen's i1Profiler.download recipe and select "Run This Recipe Only".
Result: The recipe that runs is the jazzace version, not the mosen version. A single update sprocket shows up in the GUI on the line with mosen's recipe while the jazzace recipe is running.

Probable cause: AutoPkgr lets AutoPkg resolve recipe name duplication using AutoPkg's rules. That is, it appears that in this example, AutoPkgr is executing the equivalent of `autopkg run i1Profiler.download` (which will choose the jazzace recipe) rather than `autopkg run ~/Library/AutoPkg/RecipeRepos/com.github.autopkg.mosen-recipes/XRite/i1Profiler.download` (or whatever the path to the RecipeRepos directory is, as set in the Folders & Integration tab).

**Comment by eahrold** [comment]
Fixed in 34e80a5f18beb232bdd12df7f163adbac5623c36, slated for 1.3.3

**Comment by homebysix** [comment]
1.3.3 was renamed to 1.4 and is now available: https://github.com/lindegroup/autopkgr/releases/latest
