### ISSUE TITLE
Slack Integration not saving URL

### ISSUE THREAD

**Issue by lopezzi** [lindegroup/autopkgr#459]
I saw in previous closed issues that others have had this where the Slack integration isn't saving the Webhook URL.  I'm having this issue now too.  I'm running El Cap 10.11.1.  I can paste my URL and hit "Save and Close", but if I click the "Configure..." button again, the field is blank.  Also, if I paste my URL in the field and hit the "Send Test" button, I get an error saying "The username or passphrase you entered is not correct."

I tried removing the com.lindegroup.AutoPkgr.helper out of the PrivilegedHelperTools folder and re-launched AutoPkgr, but the issue remains.

I turned on Verbose logging and the errors I see in system.log are:

com.lindegroup.AutoPkgr.helper[27468]:  SecOSStatusWith error:[-25291] The operation couldn’t be completed. (com.apple.security.xpc error 3 - <connection: 0x7fc0a8421a80> { name = com.apple.securityd.xpc, listener = false, pid = 0, euid = 4294967295, egid = 4294967295, asid = 4294967295 }: Connection invalid)
com.lindegroup.AutoPkgr.helper[27468]: Sending keychain key to AutoPkgr.
AutoPkgr[27441]: [DEBUG] [-25293] The user name or passphrase you entered is not correct.

Any help would be appreciated!!  Thanks so much!

**Comment by eahrold** [comment]
So the first thing I would try is to do now is 
1. Delete the AutoPkgr.keychain from Keychain access.
1. Quit Keychain access
1. Reenter the Slack password and click `Save & Close`
1. Go back into keychain access and see if the Keychain was successfully re-created and that there's an entry for `AutoPkgr Slack Bot`

Post back the results.

**Comment by lopezzi** [comment]
That looks to have worked!  It saved the Url and the test worked now!  Thanks so much!
