### ISSUE TITLE
ER: python-jss: Add Local Repositories

### ISSUE THREAD

**Issue by ftiff** [lindegroup/autopkgr#463]
python-jss added support for local repositories:
https://github.com/sheagcraig/python-jss/wiki/Configuration#configure-distribution-points-and-distribution-servers

I'd love to see support of these. My AutoPkgr is on my master distribution point. As it is running every night, I think it makes sense.

Here's how it works:
```
    "JSS_REPOS" =     (
                {
            "mount_point" = "/Users/Shared/JAMFDistrib";
            name = local;
            "share_name" = JAMFDistrib;
            type = Local;
        }
    );
```

`share_name` is not used, but has to be present.

**Comment by eahrold** [comment]
We're working on this in this branch
https://github.com/lindegroup/autopkgr/commits/v1.3.3-local-jss

**Comment by homebysix** [comment]
AutoPkgr 1.4 is now available: https://github.com/lindegroup/autopkgr/releases/latest
