### ISSUE TITLE
If a recipe is removed from a repo, AutoPkgr will continue to try and run it

### ISSUE THREAD

**Issue by kitzy** [lindegroup/autopkgr#465]
If a recipe is deleted from a repo (or renamed), the recipe will disappear from the list of available recipes in AutoPkgr, however AutoPkgr will continue to try to run the recipe. There is no way I can see in the GUI to disable a recipe once it's been removed from a repo.

**Comment by eahrold** [comment]
It should be automatically removed on the subsequent run.

**Comment by homebysix** [comment]
Eldon's right. You'll get an email like this:

![screen shot 2015-11-25 at 11 30 57 am](https://cloud.githubusercontent.com/assets/7801391/11407503/144ae308-9368-11e5-9795-2ca1522504dc.png)

**Comment by kitzy** [comment]
That does not appear to be the case when clicking "Run Recipes Now" in the Repos & Recipes pane. Is the removal only triggered when running automatically?

**Comment by homebysix** [comment]
@kitzy That's correct — many people click "Run Recipes Now" during testing, and we don't want to remove recipes from the recipe_list.txt that they may be in the process of troubleshooting.

During scheduled runs, on the other hand, the missing recipes would produce repeated errors if not removed.

**Comment by kitzy** [comment]
Awesome, that clears up my confusion. Thank you!
