### ISSUE TITLE
JSSImporter Failing After Switching to HTTPS for the CasperShare

### ISSUE THREAD

**Issue by bandoned** [lindegroup/autopkgr#466]
JSSImported Failing After Switching to HTTPS for the CasperShare. AFP is still enabled.

Same issues as : https://github.com/lindegroup/autopkgr/issues/287

Using version : AutoPkgr Version 1.3.2 (1104), JSS Importer 0.5.1, OSX 10.10.5.

I tried running `autopkg run -v VLC.jss` as done in the other thread.

And got `Error in com.github.autopkg.jss.VLC: Processor: JSSImporter: Error: [Errno 8] nodename nor servname provided, or not known`

Doing the settings in Configure JSSImporter and then hitting on save also causes AutoPkgr to crash.

**Comment by eahrold** [comment]
@bandoned Can you post the crash report from AutoPkgr?

**Comment by bandoned** [comment]
Not sure what you need. Is it this? On the console the only error is the Errno 8.
[autopkgr.txt](https://github.com/lindegroup/autopkgr/files/47002/autopkgr.txt)

**Comment by eahrold** [comment]
@bandoned I think we inadvertently fixed that crash issue on the 1.3.3 redesign of the JSSImporter https://www.dropbox.com/s/qshdk9vbqqfqaik/AutoPkgr-1.3.3beta3.dmg?dl=0

Not sure if it solves the Errno too, give it a try and let us know.

**Comment by bandoned** [comment]
It did not solve the Errno issue. But the Local feature looks interesting and maybe could be used. Would this be incorporated into the next release?

**Comment by homebysix** [comment]
@bandoned AutoPkgr 1.4 was just released. Could you try it out and let us know whether this is solved?

**Comment by myztikoot** [comment]
I am receiving this same error in the latest release of JSSImporter and Autopkgr.

Error in com.github.novaksam.jss.GoogleChrome: Processor: JSSImporter: Error: [Errno 8] nodename nor servname provided, or not known

**Comment by macmule** [comment]
FWIW, just had the issue & went over to JSSImporter & saw: https://github.com/sheagcraig/JSSImporter/issues/91

For me, the distribution point had a space before it's name in this test JSS. 

So @myztikoot it's worth verifying no unwanted spaces etc in the distribution point name etc in the JSS

**Comment by shawnhonsberger** [comment]
Try updating macOS and updating to the latest version of JSSImporter here: https://github.com/jssimporter/JSSImporter/releases.
