### ISSUE TITLE
"An SSL error has occurred and a secure connection to the server cannot be made"

### ISSUE THREAD

**Issue by homebysix** [lindegroup/autopkgr#467]
I'm seeing this error occur on a fresh 10.11.1 VM with newly installed AutoPkgr 1.4-rc1 trying to install either AutoPkg or Git.

![screen shot 2015-12-01 at 1 48 02 pm](https://cloud.githubusercontent.com/assets/7801391/11515321/3d2bdc68-9832-11e5-8147-acbfcf943fe4.png)

The only related message in the log that I can see is this one:
```
12/1/15 1:50:09.090 PM AutoPkgr[341]: NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)
```

**Comment by eahrold** [comment]
If you go to either of those github release pages in the VM w/ a browser, does the cert look valid?

**Comment by homebysix** [comment]
Yep, looks OK on both the releases page and the API page:

![screen shot 2015-12-01 at 2 03 47 pm](https://cloud.githubusercontent.com/assets/7801391/11515764/686b168a-9834-11e5-857f-ead8b2c07b92.png)

**Comment by homebysix** [comment]
Eldon confirmed that this is App Transport Security doing its job. The solution may be to add this to the Info.plist, but I'll investigate to see if there's a more granular option.
```
<key>NSAppTransportSecurity</key>
<dict>
  <key>NSAllowsArbitraryLoads</key>
      <true/>
</dict>
```

**Comment by futureimperfect** [comment]
I can confirm that there are more granular options, but I haven't had luck with anything other than NSAllowsArbitraryLoads.

https://developer.apple.com/library/prerelease/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW33

-- 
James Barclay

**Comment by homebysix** [comment]
Resolved by setting `NSAllowsArbitraryLoads` to True. (https://github.com/lindegroup/autopkgr/commit/e448fa637908dd06ee08b67a141394f0181439d4)
