### ISSUE TITLE
Provide separate "Cancel" and "Save" buttons in integration config panels

### ISSUE THREAD

**Issue by homebysix** [lindegroup/autopkgr#468]
Sometimes I pop open a config panel to see what the settings are, but don't want to make any changes. It would be nice to have a Cancel button to exit without saving.

Here's a situation I often encounter:
1. Open the JSSImporter config panel to view settings.
2. Press Escape to try to close the panel.
3. Observe that instead of closing the panel, Escape triggers the built-in OS X word completion, which alters the JSS URL.
4. I must press Command-Z to undo the change, then click "Save and Close."

The Cancel button would save me from applying those accidental changes.

**Comment by jgstew** [comment]
I wonder if you could instead capture ESC key presses and have it close the panel without making changes. 

Also, it seems if you press ESC twice, the URL reappears.

**Comment by homebysix** [comment]
My hope is that the ESC key would be the "key equivalent" for the Cancel button. Omitting the Cancel button entirely doesn't make it obvious that you can close without saving.

**Comment by jgstew** [comment]
This is true.

**Comment by ygini** [comment]
+1

In the 1.3.2 version missing the cancel button in all config pane is misleading.
