### ISSUE TITLE
Keychain password for Autopkgr

### ISSUE THREAD

**Issue by rrwitt** [lindegroup/autopkgr#469]
Does not recognize my passwords is there a defualt on this I do not know about?

Thanks
Ryan Witt

**Comment by eahrold** [comment]
The AutoPkgr keychain is actually not unlock-able. Is AutoPkgr prompting you to unlock it, or do you simply want to inspect it?

If the first, you'll just need to go into keychain access, and delete the AutoPkgr keychain and start fresh. 
If the second, unfortunately in our quest to make it as secure as possible while allowing it to be unlocked during background runs, inspectability was a causality.

**Comment by rrwitt** [comment]
It prompts me for it as I try to send a test email from notifications.  It prompts me for my keychain password for Autopkgr which it promptly shakes off any of my passwords.  Not really tying to inspect it.

**Comment by homebysix** [comment]
I encountered this while setting up AutoPkgr on a fresh Mac yesterday. I clicked Cancel on the password prompt and tried sending a test email again, and it worked.

@eahrold Could there be some kind of a race condition that causes AutoPkgr to access the contents of the keychain before it's unlocked?

**Comment by eahrold** [comment]
There shouldn't be a race condition, but I'll double check.
@rrwitt same thing after removing the AutoPkgr keychain and re-entering your password?

**Comment by fixmacs** [comment]
I ran into the same issue as rrwitt mentions above. I tried the suggestion homebysix mentioned above and it did allow the Send Test Email work.

**Comment by homebysix** [comment]
@MPIAE-IT reported in #476 that simply clicking Cancel did not work. In that case, what about removing ~/Library/Keychains/AutoPkgr.keychain, relaunching AutoPkgr, and re-entering the SMTP server information? When you do that, AutoPkgr should generate a fresh keychain.

**Comment by MPIAE-IT** [comment]
I tried this as well. Unfortunately it didn't help. Re-entering the smtp informations just brought up the keychain password popup. Canceling here brings up the same error messages.

**Comment by haircut** [comment]
I'm having this same issue. @homebysix 's recommendation to Cancel and retry works to send one test message but I don't reliably receive other emails from normal autopkg runs. What I've done:

- Delete `~/Library/Keychains/Autopkgr.keychain`, quit Autopkgr, re-open and reconfigure notifications
- Manually remove `/var/db/.AutopkgrKeys`
- Completely uninstall Autopkgr and all related files and preferences, then re-installed
- Tried both current 1.3.2 release and 1.4 RC2

**Comment by homebysix** [comment]
I encountered this again today when sending my first test email on a fresh AutoPkgr setup:

![screen shot 2016-03-04 at 5 43 41 pm](https://cloud.githubusercontent.com/assets/7801391/13544848/d15b272a-e230-11e5-94b1-394b22a9d3f8.png)

As I've seen before, clicking Cancel and trying again succeeded. Strange that it only happens the first time, though.

**Comment by 3xarc** [comment]
I can't get past it either - deleted keychain, clicked cancel several times etc etc. Nowt works.....

**Comment by homebysix** [comment]
@haircut and @3xarc, I'd be interested to hear whether this pre-release version fixes the keychain issues and notification issues you were seeing: https://github.com/lindegroup/autopkgr/releases/tag/v1.4.1-rc1

**Comment by homebysix** [comment]
I think we've got this resolved in 1.4.1, release date TBD.

**Comment by homebysix** [comment]
1.4.1 has been released. If you were experiencing this problem, please upgrade. Thanks!
