### ISSUE TITLE
Self-Hosted Hipchat preference setting

### ISSUE THREAD

**Issue by chilcote** [lindegroup/autopkgr#472]
Trying to integrate with a self-hosted hipchat, but it seems that the URL is hard coded.  It would be nice to be able to customize this. 

https://github.com/lindegroup/autopkgr/blob/dc6ce1450d1992b9954a4220c72b6a8bccfbdb5c/AutoPkgr/Models/Email%20%26%20Notifications/LGHipChatNotification.m#L96-L100

Unless I'm off track, and having a different issue, but when I enter my API key and the room name it's not working.

**Comment by quovadimus** [comment]
upvote.

**Comment by charliwest** [comment]
+1

**Comment by janorn** [comment]
https://github.com/lindegroup/autopkgr/blob/master/AutoPkgr/Models/Email%20%26%20Notifications/LGHipChatNotification.m#L25

Could this possibly be moved to a preference?

**Comment by charliwest** [comment]
Any update on this, would be a really nice feature

**Comment by tcwaddell** [comment]
This feature would be very helpful to me.

**Comment by jhbush** [comment]
+1
