### ISSUE TITLE
Add a QuickLook recipe feature!

### ISSUE THREAD

**Issue by sheagcraig** [lindegroup/autopkgr#473]
I frequently find myself confused by the "Set recipe editor" contextual menu item (which should be a preference, not a contextual menu item), as I often want to examine what a recipe does without leaving AutoPkgr. Being able to quicklook the selected recipe in the bottom pane would be outstanding!

**Comment by shawnhonsberger** [comment]
Closing as duplicate: https://github.com/lindegroup/autopkgr/issues/370
