### ISSUE TITLE
RecipeRepos added via Autopkgr append .git to the URL.  This breaks autopkg's ability to individually update a repo.

### ISSUE THREAD

**Issue by poundbangbash** [lindegroup/autopkgr#474]
Autopkgr 1.3.2, autopkg 0.5.2

When trying to manually update a recipe repo with `autopkg repo-update eholtam-recipes` after adding the repo via Autopkgr I get errors stating `ERROR: Can't find an installed repo for https://github.com/autopkg/eholtam-recipes`  

This appears to be due to the fact that all recipe repos being added by Autopkgr are including .git at the end of the URL.  Repos without .git at the end of the URL do not error when running `autopkg repo-update eholtam-recipes`

Below is a showing that arubdesu-recipes was added via `autopkg repo-add arubdesu-recipes` and does not have .git at the end of the URL.  eholtam-recipes was added with Autopkgr and does have .git in the URL.  arubdesu-recipes updates fine with `autopkg repo-update arubdesu-recipes`.  eholtam-recipes fails when trying `autopkg repo-update eholtam-recipes`

`
server:bin homeadmin$ autopkg repo-list
/Volumes/ExtHD/autopkg/RecipeRepos/com.github.autopkg.arubdesu-recipes (https://github.com/autopkg/arubdesu-recipes)
/Volumes/ExtHD/autopkg/RecipeRepos/com.github.autopkg.eholtam-recipes (https://github.com/autopkg/eholtam-recipes.git)
`

**Comment by eahrold** [comment]
@poundbangbash I think we sorted out the issue on slack a while back, so I'm going to close it out. Feel free to open it back up if you want further discussion.

For future lookers

`eholtam-recipes.git != eholtam-recipes`

just as 

`arubdesu-recipes != arubdesu-recipes.git`

If you add it one way, you've got to update it using the same name. And while autopkg doesn't have any logic regulating that, AutoPkgr will always make sure .git is appended to the path, no matter which GUI component you use (checkboxes or textfield).
