### ISSUE TITLE
Unable to set up E-Mail Notifications because of unknown Keychain Password?!?

### ISSUE THREAD

**Issue by MPIAE-IT** [lindegroup/autopkgr#476]
Hello Guys,

thanks for this great tool. But I have the problem that I am not able to set up E-Mail notifications in Autopkgr. My E-Mail Provider asks for authentication like many others. Unfortunately when I try to type in these informations and click "Send Test Email" a Keychain Windows appears and asks for a password. All known passwords are not working. I also tried the Serial of the computer.
If I click cancel a error message shows up:  
<pre><code>User canceled the operation.</code></pre>
And when I try to sent the test email again, like it was proposed in another thread, another Error Message Pops up: 
<pre><code>Unable to authenticate with the current session's credentials.</code></pre>

Autopkgr is installed on Mac OS X 10.11.3 virtualized on VM Ware ESXi 5.5

The system.log shows some errors. But they don't help me very much...
<pre><code>
 Marker - 27.01.2016, 15:32:21
Jan 27 15:32:56 mac-pkg AutoPkgr[8748]: Welcome to AutoPkgr!
Jan 27 15:32:58 mac-pkg com.lindegroup.AutoPkgr.helper[8749]:  securityd_message_with_reply_sync Failed to talk to secd after 4 attempts.
Jan 27 15:32:58 mac-pkg com.lindegroup.AutoPkgr.helper[8749]:  SecOSStatusWith error:[-25291] The operation couldn’t be completed. (com.apple.security.xpc error 3 - <connection: 0x7f9f19f25920> { name = com.apple.securityd.xpc, listener = false, pid = 0, euid = 4294967295, egid = 4294967295, asid = 4294967295 }: Connection invalid)
Jan 27 15:32:58 mac-pkg com.lindegroup.AutoPkgr.helper[8749]: Removing unusable keyFile...
Jan 27 15:32:58 mac-pkg com.lindegroup.AutoPkgr.helper[8749]: Sending keychain key to AutoPkgr.
Jan 27 15:32:58 mac-pkg secd[284]:  securityd_xpc_dictionary_handler AutoPkgr[8748] copy_matching Error Domain=NSOSStatusErrorDomain Code=-34018 "client has neither application-identifier nor keychain-access-groups entitlements" UserInfo={NSDescription=client has neither application-identifier nor keychain-access-groups entitlements}
Jan 27 15:32:58 mac-pkg AutoPkgr[8748]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
Jan 27 15:32:58 mac-pkg AutoPkgr[8748]: Error getting password for itsmfae [-25300]: The specified item could not be found in the keychain.
Jan 27 15:33:51 mac-pkg com.lindegroup.AutoPkgr.helper[8749]:  securityd_message_with_reply_sync Failed to talk to secd after 4 attempts.
Jan 27 15:33:51 mac-pkg com.lindegroup.AutoPkgr.helper[8749]:  SecOSStatusWith error:[-25291] The operation couldn’t be completed. (com.apple.security.xpc error 3 - <connection: 0x7f9f19f25920> { name = com.apple.securityd.xpc, listener = false, pid = 0, euid = 4294967295, egid = 4294967295, asid = 4294967295 }: Connection invalid)
Jan 27 15:33:51 mac-pkg com.lindegroup.AutoPkgr.helper[8749]: Sending keychain key to AutoPkgr.
Jan 27 15:33:51 mac-pkg com.lindegroup.AutoPkgr.helper[8749]:  securityd_message_with_reply_sync Failed to talk to secd after 4 attempts.
Jan 27 15:33:51 mac-pkg com.lindegroup.AutoPkgr.helper[8749]:  SecOSStatusWith error:[-25291] The operation couldn’t be completed. (com.apple.security.xpc error 3 - <connection: 0x7f9f19f25920> { name = com.apple.securityd.xpc, listener = false, pid = 0, euid = 4294967295, egid = 4294967295, asid = 4294967295 }: Connection invalid)
Jan 27 15:33:51 mac-pkg secd[284]:  securityd_xpc_dictionary_handler AutoPkgr[8748] copy_matching Error Domain=NSOSStatusErrorDomain Code=-34018 "client has neither application-identifier nor keychain-access-groups entitlements" UserInfo={NSDescription=client has neither application-identifier nor keychain-access-groups entitlements}
Jan 27 15:33:51 mac-pkg AutoPkgr[8748]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
Jan 27 15:33:51 mac-pkg com.lindegroup.AutoPkgr.helper[8749]: Sending keychain key to AutoPkgr.
Jan 27 15:33:51 mac-pkg secd[284]:  securityd_xpc_dictionary_handler AutoPkgr[8748] copy_matching Error Domain=NSOSStatusErrorDomain Code=-34018 "client has neither application-identifier nor keychain-access-groups entitlements" UserInfo={NSDescription=client has neither application-identifier nor keychain-access-groups entitlements}
Jan 27 15:33:51 mac-pkg AutoPkgr[8748]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
Jan 27 15:33:53 mac-pkg AutoPkgr[8748]: Error setting password [-128]: User canceled the operation.
Jan 27 15:34:12 mac-pkg com.lindegroup.AutoPkgr.helper[8749]:  securityd_message_with_reply_sync Failed to talk to secd after 4 attempts.
Jan 27 15:34:12 mac-pkg com.lindegroup.AutoPkgr.helper[8749]:  SecOSStatusWith error:[-25291] The operation couldn’t be completed. (com.apple.security.xpc error 3 - <connection: 0x7f9f19f25920> { name = com.apple.securityd.xpc, listener = false, pid = 0, euid = 4294967295, egid = 4294967295, asid = 4294967295 }: Connection invalid)
Jan 27 15:34:12 mac-pkg com.lindegroup.AutoPkgr.helper[8749]: Sending keychain key to AutoPkgr.
Jan 27 15:34:12 mac-pkg com.lindegroup.AutoPkgr.helper[8749]:  securityd_message_with_reply_sync Failed to talk to secd after 4 attempts.
Jan 27 15:34:12 mac-pkg com.lindegroup.AutoPkgr.helper[8749]:  SecOSStatusWith error:[-25291] The operation couldn’t be completed. (com.apple.security.xpc error 3 - <connection: 0x7f9f19f25920> { name = com.apple.securityd.xpc, listener = false, pid = 0, euid = 4294967295, egid = 4294967295, asid = 4294967295 }: Connection invalid)
Jan 27 15:34:12 mac-pkg secd[284]:  securityd_xpc_dictionary_handler AutoPkgr[8748] copy_matching Error Domain=NSOSStatusErrorDomain Code=-34018 "client has neither application-identifier nor keychain-access-groups entitlements" UserInfo={NSDescription=client has neither application-identifier nor keychain-access-groups entitlements}
Jan 27 15:34:12 mac-pkg AutoPkgr[8748]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
Jan 27 15:34:12 mac-pkg com.lindegroup.AutoPkgr.helper[8749]: Sending keychain key to AutoPkgr.
Jan 27 15:34:12 mac-pkg secd[284]:  securityd_xpc_dictionary_handler AutoPkgr[8748] copy_matching Error Domain=NSOSStatusErrorDomain Code=-34018 "client has neither application-identifier nor keychain-access-groups entitlements" UserInfo={NSDescription=client has neither application-identifier nor keychain-access-groups entitlements}
Jan 27 15:34:12 mac-pkg AutoPkgr[8748]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
Jan 27 15:34:12 mac-pkg com.lindegroup.AutoPkgr.helper[8749]:  securityd_message_with_reply_sync Failed to talk to secd after 4 attempts.
Jan 27 15:34:12 mac-pkg com.lindegroup.AutoPkgr.helper[8749]:  SecOSStatusWith error:[-25291] The operation couldn’t be completed. (com.apple.security.xpc error 3 - <connection: 0x7f9f19f25920> { name = com.apple.securityd.xpc, listener = false, pid = 0, euid = 4294967295, egid = 4294967295, asid = 4294967295 }: Connection invalid)
Jan 27 15:34:12 mac-pkg com.lindegroup.AutoPkgr.helper[8749]: Sending keychain key to AutoPkgr.
Jan 27 15:34:12 mac-pkg secd[284]:  securityd_xpc_dictionary_handler AutoPkgr[8748] copy_matching Error Domain=NSOSStatusErrorDomain Code=-34018 "client has neither application-identifier nor keychain-access-groups entitlements" UserInfo={NSDescription=client has neither application-identifier nor keychain-access-groups entitlements}
Jan 27 15:34:12 mac-pkg AutoPkgr[8748]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
Jan 27 15:34:13 mac-pkg AutoPkgr[8748]: GSSAPI Error:  Miscellaneous failure (see text (Server (krbtgt/GWDG.DE@AD.AESTHETICS.MPG.DE) unknown while looking up 'smtp/email.gwdg.de@GWDG.DE' (cached result, timeout in 370 sec))
Jan 27 15:34:13 mac-pkg AutoPkgr[8748]: Error sending email: Error Domain=MCOErrorDomain Code=5 "Unable to authenticate with the current session's credentials." UserInfo={NSLocalizedDescription=Unable to authenticate with the current session's credentials.}
</code></pre>

Thanks for having a look! Lenny

**Comment by homebysix** [comment]
Hi @MPIAE-IT,

Please check out #469, and specifically my suggestion [here](https://github.com/lindegroup/autopkgr/issues/469#issuecomment-165540729). That has always resolved this problem in my experience.

Thanks!

**Comment by MPIAE-IT** [comment]
Like I already stated in my post, I tried your suggestion to click cancel and send out a test email again. But that does not work! Or did I get something wrong?

**Comment by homebysix** [comment]
Hi @MPIAE-IT,

Since this is so closely related to #469, might I suggest we continue the conversation there? The reason I closed this thread is because it seems like a duplicate issue, and as you can see #469 remains open.

Thanks,

Elliot

**Comment by MPIAE-IT** [comment]
Ok my bad! I thought the other thread was closed. That was the reason for opening a new one. Otherwise I would've posted my problem there...
