### ISSUE TITLE
can't check a recipe, it automatically unchecks itself

### ISSUE THREAD

**Issue by jimmybaeyens** [lindegroup/autopkgr#477]
Hi guys!

how do i get software automatically into munkiadmin?

if i check a recipe, it automatically unchecks itself again? 

thanks in advance for helping out a newbie :-)

**Comment by homebysix** [comment]
HI @jimmybaeyens,

When you :white_check_mark: a recipe in AutoPkgr, the recipe's identifier should be added to the file at __~/Library/Application Support/AutoPkgr/recipe_list.txt__, and the recipe should be subsequently included in scheduled AutoPkg runs.

If the recipe you checked is a .munki recipe, and if the path to your Munki repo is configured (__Folders & Integration > Configure Munki Tools > Munki Repo__), then the recipe should add the software to your Munki repository using the settings specified in the recipe. If MunkiAdmin is running when the recipe runs, you may need to press __Command-R__ to reload the repo from disk.

If that doesn't succeed for some reason, let us know what version of AutoPkgr and OS X you're using, and which recipe you're adding (if the recipe is public), and I'll try to reproduce the issue. Thank you,

Elliot

**Comment by jimmybaeyens** [comment]
Hi Elliot,  
first of all thanks for responding! 

ok.. im using autopkgr 1.4-rc2 (1173) - munkiadmin 1.4.1  on osx 10.10.5 (with osx server 5.0.15 (15S4033))
- if i search /Library/Application Support/AutoPkgr/ that folder is empty, no recipe_list.txt in it.   Should that be made manually? 
- If i go to autopkgr/repos&recipes and select a recipe it also automatically unchecks itself... so thats the reason why there is no recipe_list.txt created...   
- my path to the munki repo is configured.. my repo is /Library/Server/Web/Data/Sites/Default/repo  
- you asked for which recipe isn't working.. well its all of them, using the autopkgr gui .

from the command line it seems to work but thats manually... 
autopkg run puppet.munki 
that starts processing... and if i reload in Munkiadmin the package is there 

i think the main issue here is that i can't select (check) recipes on the autopkgr gui .

thanks man!

**Comment by homebysix** [comment]
Hi @jimmybaeyens,

AutoPkgr 1.4-rc2 is still a pre-release version, and as such there are a few bugs. One such bug is that when you run it for the first time, it doesn't automatically create a recipe list for you. That'll be fixed in the final version.

In the meantime, could you try using the most recent production-ready release, [1.3.2](https://github.com/lindegroup/autopkgr/releases/tag/v1.3.2)? That should resolve the issue you're seeing.

Thanks!

**Comment by jimmybaeyens** [comment]
Hi Elliot...

when i install autopkgr 1.3.2 and run the recipes i have following error:

Error running recipes
A Python exception occurred during the execution of autopkg, see the system log for more details.
ERROR Errno 2 No such file or directory: '/users/gsadmin/library/application support/autopkgr/recipe_list.txt 

but if i set the correct repository then it functions!! so many thanks for helping me out here!

best regards,
Jimmy

**Comment by homebysix** [comment]
Sounds good! We'll make sure that's fixed before 1.4 is finalized.
