### ISSUE TITLE
1.4-rc2 does not automatically generate a recipe_list.txt

### ISSUE THREAD

**Issue by homebysix** [lindegroup/autopkgr#479]
Making this an official issue since it was mentioned in #477.

Steps to reproduce:

1. Install AutoPkgr 1.4-rc2 on a fresh Mac or VM.
2. Launch and install AutoPkg and Git.
3. Switch to Repos & Recipes tab and add a repo.
4. Try to check the box for any recipe, notice one of two things may happen: (a) The box unchecks immediately, or (b) AutoPkgr freezes and must be force quit.

Expected behavior: when you add your first recipe, a default recipe_list.txt "set" is created and the identifier of the recipe you selected is added to it.

**Comment by eahrold** [comment]
Fixed in d3644c
