### ISSUE TITLE
Add option to enable notifications for manual AutoPkg runs

### ISSUE THREAD

**Issue by jgstew** [lindegroup/autopkgr#480]
I'd like to have the option of having notifications get triggered when pressing the `Run Recipes Now` button.

Perhaps also the `Update Repos Now` button.

This shouldn't be the default behavior.

**Comment by homebysix** [comment]
In the meantime: The notifications _are_ triggered when you choose Run AutoPkg Now from the AutoPkgr menu item.

**Comment by jgstew** [comment]
Oh, that is interesting. I assumed it was only possible when triggered on a schedule.

**Comment by homebysix** [comment]
Notifications should be triggered when you click __Run Recipes Now__, but I don't think we need to send notifications when you click __Update Repos Now__.

Turns out this has been the default behavior for a while, but there were unrelated bugs that were preventing some notifications in 1.4.
