### ISSUE TITLE
JSSImporter Distribution Point: password prompt wraps on long passwords

### ISSUE THREAD

**Issue by dingoeater** [lindegroup/autopkgr#481]
When you click "Connect" in the JSSImporter Integration configuration panel, the "Distribution Point Password Required" prompt appears. Passwords over 48 characters cause the text display to wrap. This can cause confusion, especially when pasting passwords into the prompt.

Ideally the password field would just push text off screen to the left as more text is added, which is how passwords are treated in most OS X apps.

48 Character Password:
![48 charachter password](https://cloud.githubusercontent.com/assets/6790250/12767371/a75ea540-c9bd-11e5-80b3-7a28b7c4ea54.png)

49 Character Password:
![49 charachter password](https://cloud.githubusercontent.com/assets/6790250/12767375/ac2da332-c9bd-11e5-82bf-413e440379fb.png)

**Comment by homebysix** [comment]
I have this in my clipboard and don't know where to paste it:
```
setLineBreakMode:NSLineBreakByClipping
```

**Comment by eahrold** [comment]
@homebysix look right around here...

https://github.com/lindegroup/autopkgr/blob/master/AutoPkgr/Views-Controllers-XIB/Integration%20Views/LGJSSImporterIntegrationView.m#L250-251

**Comment by homebysix** [comment]
I think I got it! Thanks @eahrold. Will be included in #504.
