### ISSUE TITLE
MakeCatalogs with "Run This Recipe Only"

### ISSUE THREAD

**Issue by grahampugh** [lindegroup/autopkgr#485]
Hi,
Would it be possible for AutoPkg to automatically run "MakeCatalogs.munki" after a request to "Run This Recipe Only" on a .munki recipe? 

Cheers,
Graham

**Comment by eahrold** [comment]
Thanks Graham, 
We've actually got this queued up for 1.4

https://github.com/lindegroup/autopkgr/blob/v1.4-rc3/AutoPkgr/Views-Controllers-XIB/Recipes%20&%20Repos%20Table%20Controllers/LGRecipeTableViewController.m#L267-L281

The current beta release has some issues, but we should be able to put another, much more stable, beta up soon.

**Comment by grahampugh** [comment]
Hi Eldon

That's great! I only just came across the ability to make recipe overrides
in Autopkgr (excellent!) and this caused me to start wishing to run
individual recipes.

I also noticed some UI inconsistencies when making an override. Sometimes
it un-checks the recipe, sometimes it doesn't. If the list is sorted by the
"checked" column (so you can easily see which recipes are enabled), making
an override sometimes causes the item to move in the list (whether it gets
unchecked or not), and sometimes it doesn't.

Cheers,
Graham

**Comment by eahrold** [comment]
Yeah,we had to make some decisions on how to handle that.
This is how it works.

If a recipe is enabled, when you create an override, the recipe with the same "Recipe Name" will remain enabled, be it the override, if you used the same name as that of the parent, or the parent recipe if you set a new "Recipe Name" for the override

It's probably a little bit more complicated than it needs to be, but we just reasoned it out as best we could.

**Comment by grahampugh** [comment]
That's interesting. I didn't change the names of any of the recipes, but
some of them got unchecked, and others didn't. I'll have to see if I can
establish a pattern, e.g. in some cases I may have had another recipe of
the same type (e.g. Slack.install as well as Slack.munki). I don't remember
if that affected things.

Anyway, no big deal. It's still a great feature, so thanks!

Cheers,
Graham

**Comment by homebysix** [comment]
AutoPkgr 1.4 is now available: https://github.com/lindegroup/autopkgr/releases/latest
