### ISSUE TITLE
Check that munki repo is mounted before running

### ISSUE THREAD

**Issue by niccol** [lindegroup/autopkgr#487]
Our munki repo is not hosted on the same machine that Autopkgr is. Would it be possible to check if the repo is mounted before running?

**Comment by ygini** [comment]
+1

Having a smart way to mount network share point before AutoPKGr start would be great.

By smart I mean just specifying the network share URL with login and password as munki target. The app should be able to mount it by itself on a temporary and random path and use it as a target for munki scripts.

**Comment by eahrold** [comment]
Let's move the discussion over herehttps://github.com/lindegroup/autopkgr/issues/251

But OK, I've had some code to handle this for a while so I'll blow the dust off and get this rolled into a 1.4.x release. There's enough popular demand for it.
