### ISSUE TITLE
Change AbsoluteManageExport to new LANrevImporter

### ISSUE THREAD

**Issue by jbaker10** [lindegroup/autopkgr#488]
Hi all,

We have made some name changes to the previous `AbsoluteManageExport` to now be called `LANrevImporter` to be more inline with the future of the product.

We have also forked the project to the repo here where it will be maintained for the foreseeable future: https://github.com/jbaker10/LANrevImporter.

This _issue_ is more a request to change the included AMExport package to now be the LANrevImporter pkg.

Let me know if you have any questions or concerns!
Thanks,
Jeremy

**Comment by jbaker10** [comment]
Please see https://github.com/tburgin/AbsoluteManageExport/issues/2 for more context.

**Comment by homebysix** [comment]
AutoPkgr 1.4 is now available: https://github.com/lindegroup/autopkgr/releases/latest
