### ISSUE TITLE
Access to ~/Library/AutoPkg/Recipes ?

### ISSUE THREAD

**Issue by ygini** [lindegroup/autopkgr#491]
Hi

For what I see, AutoPKGr seems to ignore recipes stored in ~/Library/AutoPkg/Recipes.

Can we do something for that? Or is it my setup who's broken?

**Comment by ygini** [comment]
OK, it works but you've to do a repo update to refresh the view (even if it's local only) or restart the app.

**Comment by homebysix** [comment]
Yes, I think the underlying problem is that AutoPkgr doesn't refresh the recipe list unless you (a) make an override or (b) relaunch the app. A "refresh" button would be nice, wouldn't it? See #492.

**Comment by ygini** [comment]
Or an automatic refresh during recipe search?
