### ISSUE TITLE
Add a refresh button to the recipe list

### ISSUE THREAD

**Issue by homebysix** [lindegroup/autopkgr#492]
Currently, AutoPkgr doesn't refresh the list of recipes unless you (a) create an override or (b) relaunch the app.

In some situations, it would be convenient to refresh the recipe list on demand. A :arrows_counterclockwise: icon would make that easy to do.

Inspired by @ygini in #491.

**Comment by dingoeater** [comment]
Instead of a refresh button, could refreshes automatically occur every time a file is created or modified in  ~/Library/AutoPkg/ using fsevents: https://developer.apple.com/library/mac/documentation/Darwin/Conceptual/FSEvents_ProgGuide/UsingtheFSEventsFramework/UsingtheFSEventsFramework.html

**Comment by homebysix** [comment]
Good idea in theory, but:

- We'd need to look up the value of `CACHE_DIR` and exclude the Cache folder.
- That's more complex, and less likely to be implemented quickly.
- There's nothing stopping people from storing whatever they want in the ~/Library/AutoPkg folder, and we don't want AutoPkgr's performance to suffer based on the storage choices of its users.

Maybe a refresh button would be a good first step.

**Comment by ygini** [comment]
Or an automatic refresh during recipe search and when app enter in foreground ?

**Comment by eahrold** [comment]
At one point in time I branched this out using either fsevent  or GCD, I can't recall, and it really didn't seem to have any noticeable impact. Even @homebysix probably has less than 5k recipes and you probably wouldn't take a timeable hit until then. I'll see where I left off.
