### ISSUE TITLE
recipe_list.txt Discrepancy When Using both CLI & AutoPkgr GUI

### ISSUE THREAD

**Issue by foigus** [lindegroup/autopkgr#496]
Steps to Reproduce

1) Install AutoPkgr
2) Install AutoPkg and Git from AutoPkgr
3) Add the "recipes" repo
4) Check the box next to the recipe "com.github.autopkg.pkg.Adium"
5) Quit AutoPkgr
6) Run the following at the command line:

`autopkg make-override Adium.pkg`

7) Open AutoPkgr
8) Observe Adium.pkg is unchecked
9) Run the following at the command line:

```
$ cat ~/Library/Application\ Support/AutoPkgr/recipe_list.txt
com.github.autopkg.pkg.Adium
```

At this point `com.github.autopkg.pkg.Adium` is in recipe_list.txt, but cannot be removed from the list via the AutoPkgr GUI since AutoPkgr defers to displaying the override of a recipe "X" in the GUI rather than both recipe "X" and and its override.

**Comment by homebysix** [comment]
Resolution of this issue is planned for the next release! (Also see #551.)
