### ISSUE TITLE
Change subject line of AutoPkgr notification emails to be more descriptive

### ISSUE THREAD

**Issue by homebysix** [lindegroup/autopkgr#498]
(Continuation of a discussion in #184.)

The current email subject line is as follows:

> New software available for testing on `AutoPkgr Mac Hostname`

However, this might be misleading if AutoPkg is configured to import software to a Munki repo or a JSS. The software is actually available for testing from Munki/Casper, not from `AutoPkgr Mac Hostname`.

We could:
- (a) Remove the hostname from the subject line. More generally accurate but also harder to filter for consultants and others who run multiple AutoPkgr instances.
- (b) Specify Munki or Casper hostname, if it is known. We would need to determine what to do if we're importing simultaneously to both Munki and Casper (rare but possible).
- (c) Leave as-is and trust that administrators understand that the hostname refers to that of the AutoPkgr Mac.

**Comment by foigus** [comment]
Why not "AutoPkgr Software Update Notification from <autopkgr_hostname>"?

**Comment by homebysix** [comment]
I'm fond of the phrase "software available for testing" because it implies that administrative action is required before the software will actually get updated on endpoints.

**Comment by Prodeguerriero** [comment]
Hi there,

Sorry for necroposting on this one, but couldn't this something the user can edit as part of the Emailer template?
In my situation for example, I would replace "[...] on <hostname>" to "[...] from <hostname>", as the host does the work, but the file is then imported to a munki repo that is hosted elsewere.

Feel free to ignore if you don't think it's worth the effort, this is absolutely icing on the cake :P
