### ISSUE TITLE
Easy GUI configuration of VirusTotalAnalyzer

### ISSUE THREAD

**Issue by homebysix** [lindegroup/autopkgr#503]
Today I learned that Hannes has been working on a very interesting and useful AutoPkg processor called [VirusTotalAnalyzer](https://github.com/hjuutilainen/autopkg-virustotalanalyzer). It runs as a post-processor and checks downloaded files against the VirusTotal threat database.

If we incorporate the installation and configuration of VirusTotalAnalyzer into AutoPkgr, it would be a great way to reduce friction and encourage administrators to use the processor.

It would be pretty straightforward, very similar to what we did for MacPatchImporter.
- Add the repo.
- Add the post-processor to the existing list of post-processors.
- Provide fields in which the defaults settings could be configured.

Thoughts?

**Comment by homebysix** [comment]
https://github.com/lindegroup/autopkgr/commit/81270fd5686f51f03c7dfc610df48be4f42ca8c1 is my first attempt at adding this feature. I successfully built an interface and wired up some of the preferences, but it's not working because I'm not handling the NSInteger type properly, no doubt.

![screen shot 2016-03-07 at 2 01 32 pm](https://cloud.githubusercontent.com/assets/7801391/13584837/200d0e36-e46d-11e5-912a-ee8bfe8181b4.png)

**Comment by hjuutilainen** [comment]
Looking good!

For the integers: It wasn't you, it was me. They were incorrectly handled but should be usable now.

**Comment by hjuutilainen** [comment]
How would AutoPkgr handle the output? I could create a VIRUSTOTAL_DETAILED_REPORT variable which would output all the extra keys not included in the current report dictionary.

**Comment by homebysix** [comment]
@hjuutilainen Ideally, it would look something like this:

![screen shot 2016-03-09 at 10 51 39 am](https://cloud.githubusercontent.com/assets/7801391/13646653/3d552cb6-e5e5-11e5-88d4-5d493d9a4a22.png)

We may have to choose between obfuscating the detail link URL (as shown above) or potentially messing up the table with a super long URL.

**Comment by homebysix** [comment]
All set to be released with 1.4.2.

**Comment by hjuutilainen** [comment]
Nice! Feel free to ping me if you get support requests for this. I'll try to keep any future chances to the processor backwards compatible and create an issue for Autopkgr if I'm doing major changes.

For keeping the processor updated, I created a `v1.0` tag for the current master and will create tags for future releases.

**Comment by homebysix** [comment]
Included in 1.4.2, just released.
