### ISSUE TITLE
Excessive repo-list commands

### ISSUE THREAD

**Issue by homebysix** [lindegroup/autopkgr#505]
AutoPkgr seems to run at least three `autopkg repo-list` commands in a row after each `autopkg run`. You can see this in the logs, if verbose logging is enabled:

![screen shot 2016-03-08 at 9 08 03 am](https://cloud.githubusercontent.com/assets/7801391/13609357/7c461512-e50d-11e5-977e-d1b9b232b5a9.png)

Still trying to narrow down what causes this, and determine whether it also happens during scheduled background runs.

**Comment by eahrold** [comment]
Unfortunately to get an accurate result as to whether a repo is "enabled" I opted not to try an cache the results, so it has to run repo list for each enabled repo to verify. It's a pretty low cost exec, so I opted for it's 100% accuracy.

**Comment by homebysix** [comment]
I have lots of repos added, but the `repo-list` only ran three times.

```
$ ls ~/Library/AutoPkg/RecipeRepos/ | wc -l
      69
```

Could it be that it runs once per integration? I might only have three "integration" repos added.

**Comment by eahrold** [comment]
Ok, then the other possibility is it's running it to check for Integrations that are SharedProcessor types.

**Comment by eahrold** [comment]
And those are the repos it's checking whether they're installed.

**Comment by homebysix** [comment]
That sounds likely. Is it possible to do a single `repo-list` for all shared processors?
