### ISSUE TITLE
Removing a repository should also remove the associated recipes.

### ISSUE THREAD

**Issue by modestindustries** [lindegroup/autopkgr#506]
Enhancement request: Unchecking a repository should remove any associated, active recipes from ~/Library/Application Support/AutoPkgr/recipe_list.txt

Currently, checking a repository with multiple associated, checked recipes will leave the recipes active when AutoPkgr runs, yielding "No valid recipe" errors for each checked recipe. Feels like the more correct behaviour would be to remove those recipes to avoid the errors.

Current workaround is to re-check the repo, then manually uncheck the associated recipes, then uncheck the repo.

**Comment by modestindustries** [comment]
As a side note, the existing behaviour may also be the cause of a one-off crash, possibly due to an indexing issue in the recipes list after the repo is unchecked. Note that prior to the crash, the recipe list appeared to be corrupt, with odd, white space at the top of the list.

`Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000

Application Specific Information:
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array'
terminating with uncaught exception of type NSException
abort() called`

**Comment by eahrold** [comment]
Thanks I'll look into the crash.

**Comment by modestindustries** [comment]
I've got the complete crash report. Let me know if it would be helpful and I'll post it.
