### ISSUE TITLE
Change machine name to fully qualified domain name

### ISSUE THREAD

**Issue by tbridge** [lindegroup/autopkgr#509]
Hi all,

Right now, if I receive an email from AutoPkgr, it reads:

"New software available for testing on server"

Which would be great if I had one machine called server, but I have many machines with that short machine name. Would it be possible to get this changed to the results of `hostname` instead?

**Comment by homebysix** [comment]
For simplicity, let's combine this into https://github.com/lindegroup/autopkgr/issues/471. (Thanks @macmule)
