### ISSUE TITLE
Parent repository is not added when adding a recipe

### ISSUE THREAD

**Issue by klou** [lindegroup/autopkgr#518]
This one is interesting:
1. rtrouton's repo is not added
2. Search for and Add the MalwareBytesAntiMalware.munki recipe from aysiu (adding aysiu's repo automatically)
3. Attempt to create an override to this recipe

This fails, with the following console series of errors:

> 4/7/16 5:20:06.282 PM AutoPkgr[570]: Missing Parent Recipe
> 4/7/16 5:20:17.640 PM AutoPkgr[570]: (FULL AUTOPKG TRACEBACK) 
>   File "/usr/local/bin/autopkg", line 1662, in <module>
>     sys.exit(main(sys.argv))
>   File "/usr/local/bin/autopkg", line 1656, in main
> 
>     exit(subcommands[verb]['function'](argv))
>   File "/usr/local/bin/autopkg", line 1241, in make_override
> 
>     recipe_dirs=search_dirs)
>   File "/usr/local/bin/autopkg", line 348, in load_recipe
> 
>     search_github=search_github)
>   File "/usr/local/bin/autopkg", line 332, in load_recipe
> 
>     search_github=search_github)
>   File "/usr/local/bin/autopkg", line 248, in locate_recipe
> 
>     % (indef_article, name))
> EOFError: EOF when reading a line
> 4/7/16 5:20:17.641 PM AutoPkgr[570]: Error [1] Error creating recipe override file 
>  A Python exception occurred during the execution of autopkg, see the system log for more details.
> 
> [ERROR] EOFError: EOF when reading a line

Manually add the rtrouton repo (as aysiu's munki recipe probably uses rtrouton's download recipe), and it is successful.

**Comment by homebysix** [comment]
This is expected behavior. AutoPkgr does not attempt to determine which parent recipes are required. For now, that's the administrator's responsibility.
