### ISSUE TITLE
Autopkgr is not exporting Proxy Variables to Autopkg

### ISSUE THREAD

**Issue by lcompston** [lindegroup/autopkgr#519]
- Mac OS 10.11.4
- AutoPkgr 1.4 (1235)
- AutoPkg 0.6.1
- Munki Toos 2.6.1.2684

Every download is currently resulting in a 0kb disk image, and failing to mount with HDIUTIL, and failing Codesign as a result.

I have confirmed that AutoPkg is able to download the same recipe when I export the HTTP_Proxy variable when running under the same user account manually.

I have confirmed via our squid logs that Autopkgr retrieves the version details, but upon attempting to retrieve the file it generates the 0 byte file that is later renamed to match the DMG.

**Comment by eahrold** [comment]
@lcompston,
Thanks for the report. I've got a couple of questions though. 
1) With "Verbose Logs" turned on in AutoPkgr do you should see some log messages like below, do you?

```
2016-04-13 07:31:32.459 AutoPkgr[2040:66232] [DEBUG] Using HTTP_PROXY: http://myproxy.org:8080
2016-04-13 07:31:32.459 AutoPkgr[2040:66232] [DEBUG] Using HTTPS_PROXY: http://myproxy.org:8080
``` 

2) Are you using the `Use proxy settings in System Preferences` or manually setting them?

3) When you export the proxy values on the CLI, are HTTPS_PROXY and the ilk all caps, half caps, or it doesn't matter? (AutoPkgr uses all caps, and but devel we found the specs where vague as to whether this matters).

4) Try doing a `defaults read ~/Library/Preferences/com.lindegroup.AutoPkgr.plist HTTP_PROXY` (and HTTPS_PROXY) see if those look correct.

**Comment by lcompston** [comment]
Thanks for getting back to me regarding this.

In answer to your questions - here are the logs and settings.

1) With "Verbose Logs" turned on in AutoPkgr do you should see some log messages like below, do you?

20/04/2016 3:58:56.451 PM AutoPkgr[65326]: [DEBUG] Received 'Check Now' minuet command.

20/04/2016 3:58:57.409 PM AutoPkgr[65326]: [DEBUG] Completed AutoPkg Task:

  /usr/bin/python /usr/local/bin/autopkg repo-list

20/04/2016 3:58:57.410 PM AutoPkgr[65326]: [DEBUG] Using HTTP_PROXY: squidproxy:8282

20/04/2016 3:58:57.410 PM AutoPkgr[65326]: [DEBUG] Using HTTPS_PROXY: squidproxy:8282

20/04/2016 3:58:57.593 PM AutoPkgr[65326]: Attempting git pull for /Users/useraccount/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes...

20/04/2016 3:58:59.012 PM AutoPkgr[65326]: [DEBUG] Using HTTP_PROXY: squidproxy:8282

20/04/2016 3:58:59.012 PM AutoPkgr[65326]: [DEBUG] Using HTTPS_PROXY: squidproxy:8282

20/04/2016 3:58:59.208 PM AutoPkgr[65326]: Processing com.github.autopkg.munki.FlashPlayerNoRepackage...

20/04/2016 3:58:59.395 PM AutoPkgr[65326]: [DEBUG] Completed AutoPkg Task:

  /usr/bin/python /usr/local/bin/autopkg repo-list

20/04/2016 4:00:15.394 PM AutoPkgr[65326]: [DEBUG] Found app and version: AdobeFlashPlayer:21.0.0.213

20/04/2016 4:00:16.589 PM AutoPkgr[65326]: Processing MakeCatalogs.munki...

20/04/2016 4:00:16.609 PM AutoPkgr[65326]: Error [1] Error running recipes

 /Users/useraccount/Library/AutoPkg/Cache/com.github.autopkg.munki.FlashPlayerNoRepackage/downloads/AdobeFlashPlayer.dmg is not mounted

20/04/2016 4:00:16.610 PM AutoPkgr[65326]: [DEBUG] Completed AutoPkg Task:

  /usr/bin/python /usr/local/bin/autopkg run --recipe-list /Users/useraccount/Library/Application Support/AutoPkgr/Flash and Munki Import Only.txt --report-plist /var/folders/1j/kvh1jgv15gdfs24_0d5qvw0w0000gn/T/com.lindegroup.AutoPkgr/20160420155856 -v

2) Are you using the Use proxy settings in System Preferences or manually setting them?

System proxy settings are set to Auto Detect Proxy settings, so it looks for the following file http://wpad/wpad.dat as per the standard for WPAD
Autopkgr has the proxies set within the app.

3) When you export the proxy values on the CLI, are HTTPS_PROXY and the ilk all caps, half caps, or it doesn't matter? (AutoPkgr uses all caps, and but devel we found the specs where vague as to whether this matters).

I just ran the commands manually then as below for autopkg and it downloaded flash correctly.
export http_proxy=squidproxy:8282
export https_proxy=squidproxy:8282

4) Try doing a defaults read ~/Library/Preferences/com.lindegroup.AutoPkgr.plist HTTP_PROXY (and HTTPS_PROXY) see if those look correct.

both return the correct proxyname:port - i.e.    squidproxy:8282

Thanks


On 13 Apr 2016, at 10:39 PM, Eldon Ahrold <notifications@github.com<mailto:notifications@github.com>> wrote:


@lcompston<https://github.com/lcompston>,
Thanks for the report. I've got a couple of questions though.
1) With "Verbose Logs" turned on in AutoPkgr do you should see some log messages like below, do you?

2016-04-13 07:31:32.459 AutoPkgr[2040:66232] [DEBUG] Using HTTP_PROXY: http://myproxy.org:8080
2016-04-13 07:31:32.459 AutoPkgr[2040:66232] [DEBUG] Using HTTPS_PROXY: http://myproxy.org:8080


2) Are you using the Use proxy settings in System Preferences or manually setting them?

3) When you export the proxy values on the CLI, are HTTPS_PROXY and the ilk all caps, half caps, or it doesn't matter? (AutoPkgr uses all caps, and but devel we found the specs where vague as to whether this matters).

4) Try doing a defaults read ~/Library/Preferences/com.lindegroup.AutoPkgr.plist HTTP_PROXY (and HTTPS_PROXY) see if those look correct.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub<https://github.com/lindegroup/autopkgr/issues/519#issuecomment-209409873>


Important - This email and any attachments may be confidential. If received in error, please contact us and delete all copies. Before opening or using attachments check them for viruses and defects. Regardless of any loss, damage or consequence, whether caused by the negligence of the sender or not, resulting directly or indirectly from the use of any attached files our liability is limited to resupplying any affected attachments. Any representations or opinions expressed are those of the individual sender, and not necessarily those of the Department of Education and Training.

**Comment by eahrold** [comment]
Have you tried setting autopkgr to "use system settings" I wonder if that would work any better.

**Comment by lcompston** [comment]
System Preferences:  Automatically Detect - via a complex WPAD file - Works
System Preferences:  Hard coded HTTP and HTTPS - squidproxy:8282

In both instances, Autopkgr was set to use System Settings

However, with the System Settings set to Automatically Detect, and the Custom Proxy Settings set to squidproxy:8282 for both HTTP and HTTPS it accesses github via the proxy to update the repo, but fails to download items in the recipes.

So I can get it working, but I usually hard code applications like this specifically as most third party applications seem to have issues with complex WPAD files (or don't support them at all) so I have to say I am happy to see that Autopkgr does work with auto detect :)

**Comment by bradtchapman** [comment]
I'm having this issue as well.  Setting the proxies manually in AutoPkgr 1.5 has no effect.  Only works when doing it manually on the command line.

`myMacMini:AutoPkg miniadmin$ export http_proxy=proxy.acme.com:80
myMacMini:AutoPkg miniadmin$ export https_proxy=proxy.acme.com:80
myMacMini:AutoPkg miniadmin$ ./autopkg repo-update /Users/miniadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes
Attempting git pull for /Users/miniadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes...
Updating fe737e7..8df3673
Fast-forward
 AdobeDNGConverter/AdobeDNGConverter.munki.recipe   | 108 +++++++++++++++++++++
 .../AutodeskFusion360.download.recipe              |  53 ++++++++++
 AutodeskFusion360/AutodeskFusion360.munki.recipe   |  61 ++++++++++++
 BetterTouchTool/BetterTouchTool.download.recipe    |  28 +++---
 .../NetNewsWire.download.recipe                    |  12 +--
 .../NetNewsWire.install.recipe                     |   6 +-
 .../NetNewsWire.munki.recipe                       |  10 +-
 .../NetNewsWire.pkg.recipe                         |  34 ++-----
 ComicLife/ComicLife.download.recipe                |  29 ++++++
 ComicLife/ComicLife.munki.recipe                   |  52 ++++++++++
 ICanAnimate2/ICanAnimate2.download.recipe          |  37 +++++++
 ICanAnimate2/ICanAnimate2.munki.recipe             |  76 +++++++++++++++
 InstallPKG/InstallPKG.download.recipe              |  35 +++++++
 InstallPKG/InstallPKG.munki.recipe                 |  74 ++++++++++++++
 Koingo/AirRadar.download.recipe                    |   9 ++
 Koingo/AlarmClockPro.download.recipe               |   9 ++
 Koingo/AppBolish.download.recipe                   |  11 ++-
 Koingo/DataGuardian.download.recipe                |   9 ++
 Koingo/DigitalSentry.download.recipe               |  11 ++-
 Koingo/DisplayMaestro.download.recipe              |   9 ++
 Koingo/LibrarianPro.download.recipe                |   9 ++
 Koingo/MacPilot.download.recipe                    |   9 ++
 Koingo/ProjectCanvas.download.recipe               |  11 ++-
 Koingo/RoboPostman.download.recipe                 |  11 ++-
 Malwarebytes/Malwarebytes.munki.recipe             |  15 +++
 Malwarebytes/Malwarebytes.pkg.recipe               |  22 ++---
 ManyTricks/Keymou.pkg.recipe                       |   2 +-
 MirrorDisplays/MirrorDisplays.download.recipe      |  46 +++++++++
 MirrorDisplays/MirrorDisplays.munki.recipe         |  76 +++++++++++++++
 RingCentral/RingCentralMeetings.munki.recipe       |  18 +++-
 RingCentral/RingCentralMeetings.pkg.recipe         |   1 -
 SugarSync/SugarSync.download.recipe                |  42 ++++++--
 SugarSync/SugarSync.install.recipe                 |  17 +---
 SugarSync/SugarSync.munki.recipe                   |  29 +++++-
 SugarSync/SugarSync.pkg.recipe                     |  11 ++-
 Tor/TorBrowserBundle.download.recipe               |  25 +++--
 Tor/TorBrowserBundle.install.recipe                |  21 ++--
 Tor/TorBrowserBundle.munki.recipe                  |  10 +-
 Tor/TorBrowserBundle.pkg.recipe                    |  58 +----------
 Tor/TorBrowserBundleScripts/postinstall            |  17 ----
 Tunabelly/DiskDiet.download.recipe                 |  44 +--------
 Tunabelly/DiskDiet.install.recipe                  |  17 +---
 Tunabelly/DiskDiet.munki.recipe                    |  21 +---
 Tunabelly/DiskDiet.pkg.recipe                      |  33 +------
 greenfoot/greenfoot.munki.recipe                   |  63 ++++++++++++
 .../terminal-notifier.download.recipe              |  46 +++++++++
 terminal-notifier/terminal-notifier.munki.recipe   |  78 +++++++++++++++
 47 files changed, 1135 insertions(+), 290 deletions(-)
 create mode 100644 AdobeDNGConverter/AdobeDNGConverter.munki.recipe
 create mode 100644 AutodeskFusion360/AutodeskFusion360.download.recipe
 create mode 100644 AutodeskFusion360/AutodeskFusion360.munki.recipe
 rename {BlackPixel => Brent Simmons}/NetNewsWire.download.recipe (71%)
 rename {BlackPixel => Brent Simmons}/NetNewsWire.install.recipe (89%)
 rename {BlackPixel => Brent Simmons}/NetNewsWire.munki.recipe (87%)
 rename {BlackPixel => Brent Simmons}/NetNewsWire.pkg.recipe (50%)
 create mode 100644 ComicLife/ComicLife.download.recipe
 create mode 100644 ComicLife/ComicLife.munki.recipe
 create mode 100644 ICanAnimate2/ICanAnimate2.download.recipe
 create mode 100644 ICanAnimate2/ICanAnimate2.munki.recipe
 create mode 100644 InstallPKG/InstallPKG.download.recipe
 create mode 100644 InstallPKG/InstallPKG.munki.recipe
 create mode 100644 MirrorDisplays/MirrorDisplays.download.recipe
 create mode 100644 MirrorDisplays/MirrorDisplays.munki.recipe
 delete mode 100755 Tor/TorBrowserBundleScripts/postinstall
 create mode 100644 greenfoot/greenfoot.munki.recipe
 create mode 100644 terminal-notifier/terminal-notifier.download.recipe
 create mode 100644 terminal-notifier/terminal-notifier.munki.recipe

myMacMini:AutoPkg miniadmin$ ./autopkg repo-update /Users/miniadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes
`

Through the GUI, however, I get this:

`ERROR: fatal: unable to access 'https://github.com/autopkg/homebysix-recipes.git/': Could not resolve host: github.com
ERROR: fatal: unable to access 'https://github.com/autopkg/cgerke-recipes.git/': Could not resolve host: github.com
ERROR: fatal: unable to access 'https://github.com/autopkg/keeleysam-recipes.git/': Could not resolve host: github.com
ERROR: fatal: unable to access 'https://github.com/autopkg/rtrouton-recipes.git/': Could not resolve host: github.com
ERROR: fatal: unable to access 'https://github.com/autopkg/gregneagle-recipes.git/': Could not resolve host: github.com
ERROR: fatal: unable to access 'https://github.com/autopkg/jleggat-recipes.git/': Could not resolve host: github.com
ERROR: fatal: unable to access 'https://github.com/autopkg/hjuutilainen-recipes.git/': Could not resolve host: github.com
ERROR: fatal: unable to access 'https://github.com/autopkg/killahquam-recipes.git/': Could not resolve host: github.com
ERROR: fatal: unable to access 'https://github.com/autopkg/novaksam-recipes.git/': Could not resolve host: github.com
More details have been logged to the system.log`

**Comment by shawnhonsberger** [comment]
If you configure your proxies in `~/.gitconfig`, then it should clear up AutoPkg issues with the proxy, e.g adding:
```
https.proxy=proxy.example.com:8080
http.proxy=proxy.example.com:8080
```
If you still have trouble, try removing the following from `com.lindegroup.AutoPkgr.plist`:
```
HTTPS_PROXY
HTTP_PROXY
```
Closing this issue. Please feel free to re-open if it does not resolve.
