### ISSUE TITLE
Error running recipes should include which recipe failed

### ISSUE THREAD

**Issue by ftiff** [lindegroup/autopkgr#522]
When my recipes fails, I simply get the output of ProcessorError. 
Would it be possible to add which recipe failed? Is it linked to Autopkgr or autopkg?

![screen shot 2016-04-19 at 07 53 38](https://cloud.githubusercontent.com/assets/1491562/14629070/db7f4b90-0603-11e6-877d-2bd8c0a7a5a1.png)

**Comment by homebysix** [comment]
Hi @ftiff,

We recommend running this command in the Troubleshooting section of the readme. It will almost certainly give you more information about the error than we can fit in the dialog box:

```
/usr/bin/python /usr/local/bin/autopkg run --recipe-list ~/Library/Application\ Support/AutoPkgr/recipe_list.txt --report-plist /tmp/autopkg-output.xml
```

But you're right, it would be useful to have the recipe identifier above errors that correspond with that recipe.

**Comment by homebysix** [comment]
Next time you get an error like this, can you send us the latest report_plist? I'd like to see what errors/failures are recorded by the AutoPkg run.

```
open "$TMPDIR/com.lindegroup.AutoPkgr"
```
