### ISSUE TITLE
Add 'Open In Browser' to recipe popup menu

### ISSUE THREAD

**Issue by macmule** [lindegroup/autopkgr#525]
Hey folks,

It would be great if the popup menu had a option to open the recipe in a browser.

![screenshot 2016-05-06 09 24 12](https://cloud.githubusercontent.com/assets/2464974/15068045/82307a84-136c-11e6-8572-e33282dc5395.png)

Above is a screenshot of where I am thinking.

It would help in deciding if the recipe meets your preferred requirements.

**Comment by homebysix** [comment]
@macmule — That would be a cool feature! Although I'm not sure how AutoPkgr would determine the web URL of the recipe with 100% reliability.

Yes, it can determine the web URL of repositories. Yes, it knows which recipes are in which repositories. Yes, you can use `autopkg search` to determine the path of a recipe on GitHub relative to its repo. But linking those three things together neatly might be complex.

**Comment by macmule** [comment]
@homebysix is it possible to pull the recipes latest commit url?

**Comment by homebysix** [comment]
@macmule Sure is, with this monster shell one-liner:
```
cd ~/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/; echo "$(git remote -v | awk '/origin/{print $2}' | head -1 | sed 's/\.git$/\/commit/g')/$(git log -1 | awk '/commit /{print $2}')"
```

The problem for me is translating that into Obj-C and repeating it for every recipe in the list without greatly affecting performance or reliability.
