### ISSUE TITLE
Tooltip/PopOver for status warnings in recipe list

### ISSUE THREAD

**Issue by erikberglund** [lindegroup/autopkgr#526]
If a recipe in the recipe list for example is missing a dependecy a warning triangle is shown.

To find out what that means, you have to right click and show info, and understand that it's the red text that's the warning.

A small tooltip view or popover whenever you hover over a warning sign could show the error directly without having to open up the info.

This is what I instinctively did but it didn't work, therefor I'm adding this feature request.

Also, you can't right click the actual warning sign, you have to right click in another column, which also is unintuitive (for me).

**Comment by homebysix** [comment]
All good points. Thank you!
