### ISSUE TITLE
Icon for Slack chat is damaged

### ISSUE THREAD

**Issue by peshay** [lindegroup/autopkgr#527]
I connected AutoPkgr to Slack, but the bot want to have this Icon:
[https://raw.githubusercontent.com/lindegroup/autopkgr/master/AutoPkgr/Images.xcassets/AppIcon.appiconset/icon_32x32%402x.png](url)
But it downloads me a 9Byte png which does not work.

**Comment by homebysix** [comment]
Yay, a bug I can actually fix myself. ;-)

Queued up for 1.4.2, whenever that may be.
