### ISSUE TITLE
Error running recipes

### ISSUE THREAD

**Issue by betty02** [lindegroup/autopkgr#529]
Hi Chaps,

Never had much luck with AutoPkgr in the past so I got rid, now after a few months I feel it can make my life/job/world a little easier again!

So downloaded and installed, installed the JSSImporter, added my Casper URL and my logic details, then the admin password etc, went to test with ADPassMon, select the package and then pressed Run...I then get this error...

> Error running recipes

>A Python exception occurred during the execution of autopkg, see the system log for more details.

>[ERROR] : EOF when reading a line

My status icons are also all warning signs? Any ideas guys! Be great to get this working!

<img width="769" alt="screen shot 2016-05-17 at 14 02 51" src="https://cloud.githubusercontent.com/assets/19409181/15323100/313cf042-1c38-11e6-9a31-fdaf59dd078a.png">

Thanks,
Simon

**Comment by eahrold** [comment]
You probably just need to add the parent repo.

**Comment by betty02** [comment]
Ok - No idea how or what it is lol!

I just thought it picked it up from -

https://github.com/autopkg/jss-recipes.git

Guess I shall do some more reading and not get too keen to play!

**Comment by homebysix** [comment]
@betty02 Check out the [Troubleshooting](https://github.com/lindegroup/autopkgr#troubleshooting) section of the read me. It mentions parent recipes.
