### ISSUE TITLE
Error running recipes - ("bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)",)

### ISSUE THREAD

**Issue by betty02** [lindegroup/autopkgr#530]
Hi Chaps,

Had a scan of the troubleshooting guide but couldn't find anything SSL related? Error attached below!

Any ideas...
<img width="769" alt="screen shot 2016-05-18 at 11 36 16" src="https://cloud.githubusercontent.com/assets/19409181/15355810/f2fde81c-1cec-11e6-87d4-3aca2b57cc83.png">

**Comment by betty02** [comment]
Confused you all now haven't I lol :P Sorry!

**Comment by homebysix** [comment]
Hi @betty02. Based on the error and the recipe you have selected in your recipe list, I would say that you're having a JSS-related issue. I would start by investigating the `JSS_VERIFY_SSL` setting, which is accessible from the "Configure JSSImporter" options:

![configure JSSImporter](https://github.com/lindegroup/autopkgr/raw/master/doc-images/integration_casper.png)

If your JSS is not using an SSL certificate, or if it's using a self-signed SSL certificate, uncheck the Verify SSL box. (But more importantly, invest in and install an actual SSL certificate on your JSS.)

If the JSS is using a real SSL certificate and you still encounter this error, run `autopkg run -v Firefox.jss` (or any other JSS recipe) and see what specific errors you get.

**Comment by homebysix** [comment]
@betty02 Does that answer your question?

**Comment by T3chGuy77** [comment]
I am also getting the error message on the latest version of JSS and AutoPkg. We have an actual SSL certificate and running from terminal gives me the same error. How do I fix this issue?

**Comment by homebysix** [comment]
Hi @T3chGuy77 — if the issue is happening in Terminal, then it's not related to AutoPkgr. I'd recommend opening an issue with [JSSImporter](https://github.com/sheagcraig/JSSImporter/issues) with some verbose output (`autopkg run -v Foo.jss.recipe`).

**Comment by T3chGuy77** [comment]
I also see the error in the application. I'll submit an issue with JSSImporter to see if its an issue with them or where the issue is at.
