### ISSUE TITLE
FileWaveImporter installed when I updated Munkitools?

### ISSUE THREAD

**Issue by sheagcraig** [lindegroup/autopkgr#544]
I sat down on my Mac mini this morning to kick the tires on the AutoPkgr. I hit the install button for the Munkitools update in the install Tab. It downloaded, I authed, and then the Munkitools yellow dot and label disappeared for a couple of seconds. Then a green dot appeared and the label read "Filewave Importer".

I looked on the Folders & Integration pane and it also shows FileWaveImporter as installed (and it shows the munkitools as being current).

**Comment by homebysix** [comment]
FileWaveImporter is less of an "install" and more of a shared processor. If you've added the [autopkg/filewave](https://github.com/autopkg/filewave) repo at any point in the past, it may trigger that indicator to turn green.

Uninstalling is simply a matter of removing the repo (or clicking the Uninstall button in the configuration options, which does the same thing).

**Comment by sheagcraig** [comment]
I had never added it in the past-that's why I was surprised that it showed up on the first pane. I thought it should only be there if you added it with the integrations pane.

This obviously isn't that big of a deal to deal with. If you're not concerned, go ahead and close it.

**Comment by homebysix** [comment]
Interesting... Let me keep this open long enough to test on a fresh AutoPkgr VM.

**Comment by homebysix** [comment]
I was never able to reproduce this.
