### ISSUE TITLE
No Notifications in Message Center

### ISSUE THREAD

**Issue by workflowsguy** [lindegroup/autopkgr#545]
I have AutoPkgr configured to send notifications to "Report all items" to the message center. Only today I became aware that this feature no longer works. The last entry from Autopkgr is 50 days ago.

I changed notifications to "Report some items" with "New software is downloaded", "New software is imported", "Errors" and "Failures" and reran AutoPkgr. With those settings, however, only an error was logged, but not the downloaded and imported items.

Version 1.4.1 (1308) on 10.9.5

Thanks!

**Comment by leoos** [comment]
I thought my Autopkgr was having a similar issue as I wasn’t getting any emails.
Test emails sent fine.
However it seems like the scheduled runs (every 24 hours) are not happening in my case.
Also version 1.4.1 running on 10.9.5

Looking back through my console logs I noticed this in there

30/06/2016 05:10:00.122 AutoPkgr[371]: [DEBUG] Sending quit signal to helper tool…

I don’t think I did this myself


On 6 Jul 2016, at 11:47, workflowsguy <notifications@github.com<mailto:notifications@github.com>> wrote:


I have AutoPkgr configured to send notifications to "Report all items" to the message center. Only today I became aware that this feature no longer works. The last entry from Autopkgr is 50 days ago.

I changed notifications to "Report some items" with "New software is downloaded", "New software is imported", "Errors" and "Failures" and reran AutoPkgr. With those settings, however, only an error was logged, but not the downloaded and imported items.

Version 1.4.1 (1308) on 10.9.5

Thanks!

**Comment by homebysix** [comment]
@workflowsguy - Would you mind seeing whether the just-released version 1.4.2 fixes this issue for you?

**Comment by lkraft** [comment]
i'm using 1.4.2, and no longer getting any kind of notifications.  are there any updates to this?

**Comment by homebysix** [comment]
Hi @lkraft! I'd recommend switching up your notification trigger settings, even if only temporarily. A previous version of AutoPkgr had a [bug](https://github.com/lindegroup/autopkgr/issues/533) that would prevent notifications from being sent unless those options were toggled at least once. That should be fixed in 1.4.2 but it's worth testing to be sure.

Here are the options I use most often:
![screen shot 2016-12-01 at 9 11 42 am](https://cloud.githubusercontent.com/assets/7801391/20804094/6c6589c2-b7a6-11e6-9be3-3804e51a08f1.png)
 
Still waiting for @workflowsguy to confirm whether 1.4.2 fixed his issue. Ping!

**Comment by lkraft** [comment]
done, will keep you posted.  thank you!!!!

lisa

**Comment by lkraft** [comment]
![screen shot 2016-12-01 at 09 35 33](https://cloud.githubusercontent.com/assets/16673224/20804932/b010b11c-b7a9-11e6-9550-c0c2572d0217.png)

got this when trying to send a test email.

**Comment by homebysix** [comment]
@lkraft, have those email credentials worked in the past? Try re-typing the password just to make sure it's correct. (And if you're using G Suite with two-factor, you'll need to use an app-specific password.)

Failing that, you can nuke the ~/Library/Keychains/AutoPkgr.keychain and AutoPkgr.keychain-db files, then relaunch, re-enter credentials, and try the test email again.

**Comment by lkraft** [comment]
yes, those credentials have worked up until about two months ago.  will try an app specific.... and nuking the keychain.

**Comment by lkraft** [comment]
fixed.  you're a star!  thank you!!
