### ISSUE TITLE
Feature Request: Reset Recipe Repo

### ISSUE THREAD

**Issue by klou** [lindegroup/autopkgr#549]
I've had to run some scripts on the entire home directory, doing a blanket clean of some permissions.  I think that it affected the perms on my recipe repos, such that updates and pulls were no longer possible as the system thought I had made changes to just about every recipe.

It'd be nice to have a "Reset Recipe Repo(s)" that would essentially call "git checkout ." to clear this up.

The cause of my issue might've been something else, but it'd still be nice.

**Comment by homebysix** [comment]
Hi @klou — I agree, that sounds like a nice-to-have.

Be aware that you can often accomplish much the same effect by simply unchecking (removing) and rechecking (adding) the repo. Doing so will not affect your recipe list, so the same recipes will remain active before and after.

I'll leave this request open for future consideration.

**Comment by klou** [comment]
Didn't know!  Thanks for the tip -- I was thinking about how to resolve the errors that might arise from git commands, but within AutoPkgr.
