### ISSUE TITLE
Recipe error message so long that the "OK" button is off-screen

### ISSUE THREAD

**Issue by nathanperkins** [lindegroup/autopkgr#550]
Hello,

I can't close this error message because it is so long that the confirm button is off-screen.

Best,
Nathan

![screen shot 2016-08-03 at 11 38 55 am](https://cloud.githubusercontent.com/assets/10337495/17377549/0e6ee6f0-596f-11e6-9714-847d439b83c5.png)

**Comment by eahrold** [comment]
@nathanperkins, we haven't seen this for a while, I thought that bug was quashed. Anyway for now simply pressing enter should trigger the "OK" button on the alert panel.

**Comment by homebysix** [comment]
@eahrold I think this is due to the recent change from `urllib2` to `curl` in many processors. Network access errors are now quite a bit more verbose.
