### ISSUE TITLE
"Search for a recipe on GitHub" doesn't search by name

### ISSUE THREAD

**Issue by SmithersJr** [lindegroup/autopkgr#552]
Entering "Recipe Robot" provides no results, even thought there are recipes with "Recipe Robot" in their name.

**Comment by homebysix** [comment]
Hi @SmithersJr,

I noticed this recently as well while searching for other things with spaces in their name.

I'm not sure whether this is a recent change to the GitHub API or something we simply failed to detect until now, but I've [opened an issue](https://github.com/autopkg/autopkg/issues/305) for it to be addressed by AutoPkg. I'll keep this one open until that one is resolved.

**Comment by homebysix** [comment]
Resolved by https://github.com/autopkg/autopkg/commit/bd73659e59f8565849664fa62fd1f91927cef1d8. Thanks!
