### ISSUE TITLE
Feature Request: Support for multiple (mail) notifications

### ISSUE THREAD

**Issue by mihelm** [lindegroup/autopkgr#553]
Hi

I don't know how many people would find this useful, but I'll just throw the idea out there:

In our case, the people who need to know that new software is available are not necessarily the same people who need to know when some sort of failure occurs during a run. (Say, due to a developer not updating a certificate, which might occur on every run for several weeks.) So, if multiple notifications could be configured, I could tailor the notifications to the needs of the recipient.

Cheers, michael.

**Comment by aschwanb** [comment]
Hi michael

I think this feature would go against the unix philosophy: [Do one thing and do it well](https://en.wikipedia.org/wiki/Unix_philosophy#Do_One_Thing_and_Do_It_Well)

For me, AutoPkgr is a tool to download and package apps and import them into your deployment solution. It should notify you about these steps.

If you need a tool to tell people what's available in your deployment solution, you should use another tool.

But that's just my point of view.
