### ISSUE TITLE
Feature Request: Boxcar notification integration

### ISSUE THREAD

**Issue by WardsParadox** [lindegroup/autopkgr#559]
## Detailed Description

I have recently started using Boxcar for iOS to get notifications for many things in my move away from emails: scripts running periodically, munkireport-php backup notifications, etc. If autopkgr supported multiple boxcar notifications (ie: One type for success, warnings, and errors) that would be great. Boxcar is a notification API for iOS that allows you to send notifications to users using a token or a forwarding email. Being able to notify multiple people would also be beneficial.

I can see this helping others who may not have a slack instance they can integrate with.

**Comment by homebysix** [comment]
Hi @WardsParadox,

Sounds like a good idea. I used to use Boxcar a few years ago, but haven't touched it for a while. If there's still a [forwarding email for push notifications](http://help.boxcar.io/support/solutions/articles/6000015729-how-to-receive-push-notifications-for-emails-), you may be able to make use of that immediately with AutoPkgr.

**Comment by WardsParadox** [comment]
Yup have that working for now, albeit a bit slow. It's nice but I think the accessibility of having multiple tokens and a possibility of multiple alerts based on finish status might be nice. Either way, autopkgr works well enough either way.

**Comment by shawnhonsberger** [comment]
Closing, as Boxcar is discontinued: https://boxcar.io/client.
