### ISSUE TITLE
python ssl module error

### ISSUE THREAD

**Issue by everetteallen** [lindegroup/autopkgr#560]
Seeing this when running a recipe:
A Python exception occurred during the execution of autopkg, see the system log for more details.

[ERROR] No module named cryptography.hazmat.bindings.openssl.binding

After update to macOS 10.12.  Also seeing yellow dot by autopkg install see screen shot.
This is after asking AutoPkgr to do updates and adding autopkg by hand as well.

![screen shot 2016-10-10 at 4 46 08 pm](https://cloud.githubusercontent.com/assets/5263924/19250587/1873671e-8f09-11e6-97c8-a9665a0d08d1.png)

**Comment by everetteallen** [comment]
Also system.log shows:
====
Oct 10 13:29:27 itdhcp10136 AutoPkgr[66613]: Sparkle: ===== AutoPkgr =====
Oct 10 13:29:27 itdhcp10136 AutoPkgr[66613]: Sparkle: Extracting /Users/oitadmin/Library/Caches/com.lindegroup.AutoPkgr/Sparkle/AutoPkgr 1375/AutoPkgr-1.4.2.dmg as a DMG
Oct 10 13:29:31 itdhcp10136 AutoPkgr[66613]: Sparkle: copyItemAtPath:/Volumes/97EBA7DC-1957-4236-8CE6-119D570E4DDA/.background toPath:/Users/oitadmin/Library/Caches/com.lindegroup.AutoPkgr/Sparkle/AutoPkgr 1375/.background
Oct 10 13:29:31 itdhcp10136 AutoPkgr[66613]: Sparkle: copyItemAtPath:/Volumes/97EBA7DC-1957-4236-8CE6-119D570E4DDA/.DS_Store toPath:/Users/oitadmin/Library/Caches/com.lindegroup.AutoPkgr/Sparkle/AutoPkgr 1375/.DS_Store
Oct 10 13:29:31 itdhcp10136 AutoPkgr[66613]: Sparkle: copyItemAtPath:/Volumes/97EBA7DC-1957-4236-8CE6-119D570E4DDA/.VolumeIcon.icns toPath:/Users/oitadmin/Library/Caches/com.lindegroup.AutoPkgr/Sparkle/AutoPkgr 1375/.VolumeIcon.icns
Oct 10 13:29:31 itdhcp10136 AutoPkgr[66613]: Sparkle: copyItemAtPath:/Volumes/97EBA7DC-1957-4236-8CE6-119D570E4DDA/Applications toPath:/Users/oitadmin/Library/Caches/com.lindegroup.AutoPkgr/Sparkle/AutoPkgr 1375/Applications
Oct 10 13:29:31 itdhcp10136 AutoPkgr[66613]: Sparkle: copyItemAtPath:/Volumes/97EBA7DC-1957-4236-8CE6-119D570E4DDA/AutoPkgr.app toPath:/Users/oitadmin/Library/Caches/com.lindegroup.AutoPkgr/Sparkle/AutoPkgr 1375/AutoPkgr.app
Oct 10 13:29:37 itdhcp10136 AutoPkgr[66613]: [DEBUG] Sending quit signal to helper tool...
Oct 10 13:29:37 itdhcp10136 AutoPkgr[66613]: [DEBUG] No longer monitoring scheduled AutoPkg runs.
Oct 10 13:46:38 itdhcp10136 AutoPkgr[676]: BUG in libdispatch client: kevent[EVFILT_MACHPORT] monitored resource vanished before the source cancel handler was invoked
Oct 10 14:12:57 itdhcp10136 AutoPkgr[1006]: BUG in libdispatch client: kevent[EVFILT_MACHPORT] monitored resource vanished before the source cancel handler was invoked.
====

**Comment by homebysix** [comment]
@everetteallen: Does the same error appear if you run your recipe list using AutoPkg at the Terminal?

```
/usr/bin/python /usr/local/bin/autopkg run --verbose --recipe-list ~/Library/Application\ Support/AutoPkgr/recipe_list.txt
```

**Comment by jfuchtm** [comment]
Getting somewhat of the same error, A Python exception occurred during the execution of autopkg, see the system log for more details. [ERROR] : 'ascii' codec can't encode character u'\u2019' in position 201: ordinal not in range(128)
Runs fine via CLI.

**Comment by homebysix** [comment]
@jfuchtm: That's probably unrelated to the issue @everetteallen is reporting. As discussed [here](https://github.com/lindegroup/autopkgr/issues/360#issuecomment-244068121), it's very likely that there's a curly quote in an error message that AutoPkgr is trying to display.

**Comment by everetteallen** [comment]
Yes:
=========
itdhcp10136:~ oitadmin$ /usr/bin/python /usr/local/bin/autopkg run --verbose --recipe-list ~/Library/Application\ Support/AutoPkgr/recipe_list.txt
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 44, in <module>
    import autopkglib.github
  File "/Library/AutoPkg/autopkglib/__init__.py", line 622, in <module>
    import_processors()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 530, in import_processors
    mydirname + '.' + name, fromlist=[name]), name)
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 28, in <module>
    import jss
  File "/Library/Python/2.7/site-packages/python_jss-1.4.0-py2.7.egg/jss/__init__.py", line 60, in <module>
    from .jamf_software_server import JSS
  File "/Library/Python/2.7/site-packages/python_jss-1.4.0-py2.7.egg/jss/jamf_software_server.py", line 34, in <module>
    from .tlsadapter import TLSAdapter
  File "/Library/Python/2.7/site-packages/python_jss-1.4.0-py2.7.egg/jss/tlsadapter.py", line 26, in <module>
    from requests.packages.urllib3.contrib import pyopenssl
  File "/Library/Python/2.7/site-packages/requests-2.7.0-py2.7.egg/requests/packages/urllib3/contrib/pyopenssl.py", line 53, in <module>
    import OpenSSL.SSL
  File "/Library/Python/2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/Library/Python/2.7/site-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/Library/Python/2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
ImportError: No module named cryptography.hazmat.bindings.openssl.binding
==========

**Comment by homebysix** [comment]
@everetteallen: In that case, I'm afraid AutoPkgr has nothing to do with it. You might want to test upstream. Make sure your versions of AutoPkg, JSSImporter, and Python-JSS are all up to date, and test your recipe_list one recipe at a time if needed.

**Comment by nimoyjohnson** [comment]
Has anyone found a fix for this? Running 10.11 with latest AutoPKG, JSSImporter, Python-JSS, Git and AutoPkgr. This is occurring without having recipes or repo's defined. Mainly because you you cannot due to this error. 

![screen shot 2017-04-11 at 11 49 34 am](https://cloud.githubusercontent.com/assets/1630895/24918041/f0eeed42-1eac-11e7-8720-e67df17525f0.png)
.

**Comment by homebysix** [comment]
@nimoyjohnson The fix for this was added to the JSSImporter read me a while back. You can see the necessary `pip` command in the "Installation" section of [this page](https://github.com/sheagcraig/JSSImporter/#installation).

**Comment by nimoyjohnson** [comment]
yeah, still no dice. I've been able to verify this on 10.12 and 10.11.

**Comment by homebysix** [comment]
@nimoyjohnson Does the issue happen when you run JSS recipes in the Terminal? e.g. `autopkg run -v Firefox.jss`

If so, it's not AutoPkgr related. You may want to chime in on [this issue](https://github.com/sheagcraig/JSSImporter/issues/96), since your issue seems similar.
