### ISSUE TITLE
Error running recipes

### ISSUE THREAD

**Issue by jfuchtm** [lindegroup/autopkgr#561]
Getting a Python exception during the execution of autopkg:
[ERROR] : 'ascii' codec can't encode character u'\u2019' in position 201: ordinal not in range(128)

**Comment by homebysix** [comment]
Check out these related issues:
https://github.com/lindegroup/autopkgr/issues?utf8=%E2%9C%93&q=is%3Aissue%20%22codec%20can%27t%20encode%20character%22

TL:DR — You may have a syntax error in a recipe, or you may be seeing a "meta-error" where an AutoPkg error can't be parsed and results in a different error.
