### ISSUE TITLE
[Enhancement] Don't sent empty notifications

### ISSUE THREAD

**Issue by rrenstrom** [lindegroup/autopkgr#562]
I've the Slack notification template so it only sends a list of items imported into Munki. The modified template doesn't send errors or anything else (which are often superfluous and don't need to go to Slack), so it ends up sending an empty notification when there are just errors or other items that aren't included in my modified template.   A simple solution would be to check the notification text and don't send a notification if blank.

**Comment by homebysix** [comment]
Hi @rrenstrom,

Next time you get a blank notification, can you run this Terminal command:
```
open ${TMPDIR}com.lindegroup.AutoPkgr
```
And then post the contents of the most recently-modified file? I'm wondering whether the presence of a `virus_total_analyzer_summary_result` key (or another key) might be triggering notifications, but not included in the Slack notification template.

Thanks!

**Comment by rrenstrom** [comment]
Hi Elliot,

yes, there's a failures key, but it shouldn't use this as the final basis for sending the notification since in my slack notification template I've removed the failures section because I only want to be notified via slack when something is actually imported into munki (my slack template only has the munki_importer section), so in this case the notification text is blank.  

A potential fix in the code would be to check notification text before sending and don't send if it's null.
