### ISSUE TITLE
JSS importer not connecting

### ISSUE THREAD

**Issue by mgrevtech** [lindegroup/autopkgr#567]
![image](https://cloud.githubusercontent.com/assets/10722833/19528594/4f025bcc-9635-11e6-8652-c6b03a5a7d1e.png)

Why am I suddenly getting this error on JSS importer? It was working fine until a few days back. And there hasnt been any changes on my jss server or anywhere else for that matter.

If I use https for the JSS URL, it gives me the above error message. And if I use only http, it does not seem like its connecting to any casper share but shows a green signal anyway but however none of the packages are getting pushed onto my jss server.

![image](https://cloud.githubusercontent.com/assets/10722833/19528749/e90ccfa4-9635-11e6-822e-fd888f6baac9.png)

Any ideas please?

**Comment by homebysix** [comment]
Hi @mgrevtech,

The most common issue we've seen when people have trouble connecting to their JSS via JSSImporter is that there's a special character or symbol in their password that isn't escaped properly.

To detect this issue, open up Terminal and run this command:

```
defaults read com.github.autopkg API_PASSWORD
```

Compare the output with your actual JSS API password, and make sure it's correct.

If you're using port 8443, it's almost certain that you should be using https and not http. The green indicator simply tries to indicate whether it gets a response from the server, and doesn't necessarily guarantee that the port and protocol are the correct ones.

**Comment by mgrevtech** [comment]
Hi @homebysix 

Ran the command, looks like it is taking the right password, even though there is a special character in it. But still wont connect.

**Comment by homebysix** [comment]
Can you log into the JSS web interface from the AutoPkgr Mac, using the `casperadmin` username and password?

Also, know that clicking "Connect" isn't necessary unless you want to be re-prompted for distribution point passwords. Just make sure the URL, username, password, and distribution points are set up correctly, then click __Save and Close__. Then try to run a jss recipe.

**Comment by mgrevtech** [comment]
I was actually trying out the jss web interface right before you replied. Looks like I was trying with an old password while re-entering, sorry about that!

But it is strange though that the autopkgr suddenly stopped working and wasn't pushing any new packages into jss since Oct 14. I am pretty sure I haven't messed around with the jss importer settings or any other settings on autopkgr. The only reason I was re-entering the password (with the wrong one earlier) was because it wasn't working in the first place. So whatever was in there must have been the right password. So not sure whats going on.

You are right about clicking Connect (with the right password). It is only making the autopkgr crash/quit and not mounting the share. And I have to re-open the app.

**Comment by mgrevtech** [comment]
@homebysix Autopkgr ran without any errors but still none of the new packages are pushing through into jss.

> New software was downloaded:
> 
> NAME	VERSION
> VLC	2.2.4
> The following new items were downloaded:
> 
> /Users/administrator/Library/AutoPkg/Cache/local.jss.VLC/downloads/VLC.dmg
> /Users/administrator/Library/AutoPkg/Cache/com.github.autopkg.jss.VLC-SelfService/downloads/VLC.dmg
> The following packages were copied:
> 
> /Users/administrator/Library/AutoPkg/Cache/com.github.autopkg.pkg.FlashPlayerExtractPackage/AdobeFlashPlayer-23.0.0.185.pkg
> /Users/administrator/Library/AutoPkg/Cache/com.github.autopkg.pkg.OracleJava8/OracleJava8-1.8.111.14.pkg
> /Users/administrator/Library/AutoPkg/Cache/local.jss.AdobeFlashPlayer/AdobeFlashPlayer-23.0.0.185.pkg
> /Users/administrator/Library/AutoPkg/Cache/local.jss.MSOffice2011Updates/Office 2011 14.6.9 Update.pkg
> /Users/administrator/Library/AutoPkg/Cache/com.github.sheagcraig.jss.Office2011Updates-SelfService/Office 2011 14.6.9 Update.pkg
> /Users/administrator/Library/AutoPkg/Cache/local.jss.OracleJava8/OracleJava8-1.8.101.13.pkg
> /Users/administrator/Library/AutoPkg/Cache/com.github.sheagcraig.jss.OracleJava8-SelfService/OracleJava8-1.8.101.13.pkg
> /Users/administrator/Library/AutoPkg/Cache/com.github.autopkg.jss.FlashPlayerExtractPackage-SelfService/AdobeFlashPlayer-23.0.0.185.pkg
> The following changes were made to the JSS:
> 
> CATEGORIES	GROUPS	ICON	PACKAGE	POLICY	SCRIPTS
> Google Drive-update-smart			Google Drive	
> Skype-update-smart			Skype	
> GoogleChrome	
> GoogleChrome-Autoupdate-Smart			Auto Update GoogleChrome 54.0.2840.59	
> AdobeFlashPlayer-Autoupdate-Smart			Auto Update AdobeFlashPlayer 23.0.0.185	
> Firefox-Autoupdate-Smart			Auto Update Firefox 49.0.1	
> Firefox	
> Office2011Update-Autoupdate-Smart			Auto Update Office2011Update 14.6.9	
> Office2011Update	
> OracleJava8-Autoupdate-Smart			Auto Update OracleJava8 1.8.101.13	
> OracleJava8	
> VLC-Autoupdate-Smart			Auto Update VLC 2.2.4	
> AdobeFlashPlayer	
> VLC	
> This report was generated by AutoPkgr

**Comment by homebysix** [comment]
If the recipes are running with no errors, but the packages still aren't showing up on the JSS, you probably need to adjust your distribution point settings. What DP serves as your master?

Running this in Terminal might give you additional detail, especially in the JSSImporter processor output:

```
autopkg run -v local.jss.VLC
```

**Comment by mgrevtech** [comment]
DP is a separate jss server running on windows.

Running command: autopkg run -v local.jss.VLC

Processing local.jss.VLC...
SparkleUpdateInfoProvider
SparkleUpdateInfoProvider: Version retrieved from appcast: 2.2.4
SparkleUpdateInfoProvider: Found URL http://get.videolan.org/vlc/2.2.4/macosx/vlc-2.2.4.dmg
URLDownloader
URLDownloader: Storing new Last-Modified header: Thu, 02 Jun 2016 15:23:51 GMT
URLDownloader: Storing new ETag header: "239e6b3-5344d317dafc0"
URLDownloader: Downloaded /Users/administrator/Library/AutoPkg/Cache/local.jss.VLC/downloads/VLC.dmg
EndOfCheckPhase
CodeSignatureVerifier
CodeSignatureVerifier: Mounted disk image /Users/administrator/Library/AutoPkg/Cache/local.jss.VLC/downloads/VLC.dmg
CodeSignatureVerifier: Verifying application bundle signature...
CodeSignatureVerifier: /private/tmp/dmg.l2EHXJ/VLC.app: valid on disk
CodeSignatureVerifier: /private/tmp/dmg.l2EHXJ/VLC.app: satisfies its Designated Requirement
CodeSignatureVerifier: /private/tmp/dmg.l2EHXJ/VLC.app: explicit requirement satisfied
CodeSignatureVerifier: Signature is valid
AppDmgVersioner
AppDmgVersioner: Mounted disk image /Users/administrator/Library/AutoPkg/Cache/local.jss.VLC/downloads/VLC.dmg
AppDmgVersioner: BundleID: org.videolan.vlc
AppDmgVersioner: Version: 2.2.4
PkgRootCreator
PkgRootCreator: Created /Users/administrator/Library/AutoPkg/Cache/local.jss.VLC/VLC
PkgRootCreator: Created /Users/administrator/Library/AutoPkg/Cache/local.jss.VLC/VLC/Applications
Copier
Copier: Mounted disk image /Users/administrator/Library/AutoPkg/Cache/local.jss.VLC/downloads/VLC.dmg
Copier: Copied /private/tmp/dmg.VqPltJ/VLC.app to /Users/administrator/Library/AutoPkg/Cache/local.jss.VLC/VLC/Applications/VLC.app
PkgInfoCreator
PkgCreator
PkgCreator: Package already exists at path /Users/administrator/Library/AutoPkg/Cache/local.jss.VLC/VLC-2.2.4.pkg.
PkgCreator: Existing package matches version and identifier, not building.
JSSImporter
[Errno bad handshake] [('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')]
Failed.
Receipt written to /Users/administrator/Library/AutoPkg/Cache/local.jss.VLC/receipts/local.jss-receipt-20161019-214317.plist

The following recipes failed:
    local.jss.VLC
        Error in local.jss.VLC: Processor: JSSImporter: Error: [Errno bad handshake] [('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')]

The following new items were downloaded:
    Download Path                                                               
    -------------                                                               
    /Users/administrator/Library/AutoPkg/Cache/local.jss.VLC/downloads/VLC.dmg

**Comment by homebysix** [comment]
That seems to indicate an SSL error when talking to your JSS. Do you have the latest version of JSSImporter and python-jss? (AutoPkgr will indicate a green light in the Install tab if you're up to date.)

**Comment by mgrevtech** [comment]
Yep all up to date with green light. I had even tried re-installing JSSImporter. Do I need to add a Distribution Point separately as well (besides putting in the JSS URL, username, password) ? Because it wont let me add me a new DP. When I try to add a new DP, all it lets me do is choose which type of DP from the drop-down list. No other options available on this pop-up window, just blank.

**Comment by homebysix** [comment]
If you choose Local, AFP, or SMB, you'll see various other options appear. Make sure your Distribution Points table accurately reflects the DPs you want to upload new packages to.

**Comment by homebysix** [comment]
And just to confirm: Your URL still starts with https:// and ends with :8443, right? And you checked the "Verify SSL" box too?

**Comment by mgrevtech** [comment]
Hey @homebysix This is what I was talking about earlier about the DP adding window on autopkgr. No options to add, just blank.

![image](https://cloud.githubusercontent.com/assets/10722833/19555020/c1a49652-96c3-11e6-8ff8-51e7941cbfa0.png)

Yes URL starts with https and ends with 8443.

When I enable the Verify SSL option, this is what I get:

![image](https://cloud.githubusercontent.com/assets/10722833/19555147/44e7451e-96c4-11e6-9394-99495645b043.png)

Is there any way I can do a clean re-install of autopkgr? As I had mentioned before, I have not made any changes to the autopkgr mac machine or on JSS. It was working fine until last week. Could you help me fix this please? Thanks.

**Comment by homebysix** [comment]
@mgrevtech: There's probably no reason to do a clean reinstall of AutoPkgr. As you previously demonstrated by running `autopkg run -v local.jss.VLC`, the error persists even when AutoPkgr isn't involved. Even so, I'm happy to help you continue troubleshooting here.

I think you're seeing two issues:

- SSL error when JSSImporter connects to your JSS
- Distribution point configuration issues

Let's put the second issue aside for the moment. I suspect it'll be easier to troubleshoot after we fix the first issue.

To try to isolate the first issue, I have a few questions:

- Is your JSS certificate self signed, or is it a "real" cert?
- When you use `curl` to connect to your JSS API (script below), do you get a list of policies?

    ```
    #!/bin/bash
    USERNAME="casperadmin"
    PASSWORD='your_password'
    JSS="jss.example.com"
    PORT="8443"
    curl -k -u ${USERNAME}:${PASSWORD} https://${JSS}:${PORT}/JSSResource/policies | xmllint --pretty 1 -
    ```

- If it was working fine last week, something must have changed. Are you sure that the box your JSS is hosted on hasn't been modified? If you have an InfoSec team, maybe they removed some old ciphers from Tomcat's config file? That happened to me once.

- If you set up a fresh VM or test Mac with AutoPkgr and JSSImporter, is that Mac able to run JSS recipes successfully, or does it get the same error?

**Comment by mgrevtech** [comment]
Thanks @homebysix for continuing to help me with this!

- JSS certificate is self signed
- Yes I am getting a whole list of policies when I ran the curl script
- I am usually the only one who manages the jss server, its not likely that someone has modified anything on it. I am wondering, would a java update make any changes to the tomcat's config file? FYI, all other processes related to jss works fine such as connecting via casper admin, clients, ongoing policies, etc.
- The thought did cross my mind, setting up a new autopkgr mac. I do not have access to a spare mac at the moment but I will give it a try later on.

Meanwhile I was going through the jamf forums, there was a thread related to an issue on jss where if we enable an option called 'Enable SSL certificate verification' causes issues for clients to connect to jss. But this was disabled anyway. I tried enabling the option and running autopkgr, still no luck.

Other steps I have tried so far - rebooted jss server & autopkgr mac ; regenerated the jss self-signed certificate, restarted tomcat service.

**Comment by homebysix** [comment]
OK — If your JSS certificate is self-signed, you'll need to _uncheck_ the __Verify SSL__ checkbox. But leave the https: protocol and port 8443 as is (just like the URL you use to access the JSS web admin).

To verify that the checkbox setting "took," try this command in Terminal:

```
defaults read com.github.autopkg JSS_VERIFY_SSL
```

A result of `0` is what you're looking for.

Then try running AutoPkg again to see whether the same SSL error persists:

```
autopkg run -v local.jss.VLC
```

If that still doesn't work, then I'll have to refer you to the issues page of [JSSImporter](https://github.com/sheagcraig/JSSImporter/issues) or [python-jss](https://github.com/sheagcraig/python-jss/issues). Some deeper Python level SSL testing might be in order.

**Comment by mgrevtech** [comment]
Actually I have been testing alternatively with the SSL verify option both on and off. When its on, thats when I get the SSL error. When its off, the recipe runs fine without erros and it does create the specific policy with all the required settings on JSS (tested after deleting an existing policy) but just no actual package to install within that policy. Its only the package files that are not getting pushed into jss.

Yup getting the value 0 after running the defaults read command.

And here is the output of _autopkg run -v local.jss.VLC_ without SSL verify on. Again jss policy is created but no package still.

> Processing local.jss.VLC...
> SparkleUpdateInfoProvider
> SparkleUpdateInfoProvider: Version retrieved from appcast: 2.2.4
> SparkleUpdateInfoProvider: Found URL http://get.videolan.org/vlc/2.2.4/macosx/vlc-2.2.4.dmg
> URLDownloader
> URLDownloader: Item at URL is unchanged.
> URLDownloader: Using existing /Users/administrator/Library/AutoPkg/Cache/local.jss.VLC/downloads/VLC.dmg
> EndOfCheckPhase
> CodeSignatureVerifier
> CodeSignatureVerifier: Mounted disk image /Users/administrator/Library/AutoPkg/Cache/local.jss.VLC/downloads/VLC.dmg
> CodeSignatureVerifier: Verifying application bundle signature...
> CodeSignatureVerifier: /private/tmp/dmg.RdqjnO/VLC.app: valid on disk
> CodeSignatureVerifier: /private/tmp/dmg.RdqjnO/VLC.app: satisfies its Designated Requirement
> CodeSignatureVerifier: /private/tmp/dmg.RdqjnO/VLC.app: explicit requirement satisfied
> CodeSignatureVerifier: Signature is valid
> AppDmgVersioner
> AppDmgVersioner: Mounted disk image /Users/administrator/Library/AutoPkg/Cache/local.jss.VLC/downloads/VLC.dmg
> AppDmgVersioner: BundleID: org.videolan.vlc
> AppDmgVersioner: Version: 2.2.4
> PkgRootCreator
> PkgRootCreator: Created /Users/administrator/Library/AutoPkg/Cache/local.jss.VLC/VLC
> PkgRootCreator: Created /Users/administrator/Library/AutoPkg/Cache/local.jss.VLC/VLC/Applications
> Copier
> Copier: Mounted disk image /Users/administrator/Library/AutoPkg/Cache/local.jss.VLC/downloads/VLC.dmg
> Copier: Copied /private/tmp/dmg.vJbnWu/VLC.app to /Users/administrator/Library/AutoPkg/Cache/local.jss.VLC/VLC/Applications/VLC.app
> PkgInfoCreator
> PkgCreator
> PkgCreator: Package already exists at path /Users/administrator/Library/AutoPkg/Cache/local.jss.VLC/VLC-2.2.4.pkg.
> PkgCreator: Existing package matches version and identifier, not building.
> JSSImporter
> JSSImporter: Category type: category-'Digital Media' already exists according to JSS, moving on...
> JSSImporter: Category type: policy_category-'APPS Software Update' already exists according to JSS, moving on...
> JSSImporter: Package upload and object update skipped. If this is a mistake, ensure you have JSS_REPOS configured.
> JSSImporter: Found file: /Users/administrator/Library/AutoPkg/RecipeOverrides/SmartGroupTemplate.xml
> JSSImporter: ComputerGroup: VLC-Autoupdate-Smart updated.
> JSSImporter: Found file: /Users/administrator/Library/AutoPkg/RecipeOverrides/PolicyTemplate.xml
> JSSImporter: Policy: Auto Update VLC 2.2.4 created.
> JSSImporter: Found file: /Users/administrator/Library/AutoPkg/RecipeOverrides/VLC.png
> JSSImporter: Icon uploaded to JSS.
> Receipt written to /Users/administrator/Library/AutoPkg/Cache/local.jss.VLC/receipts/local.jss-receipt-20161020-204633.plist
> 
> The following changes were made to the JSS:
>     Package  Categories  Groups                Scripts  Extension Attributes  Policy                 Icon     
>     -------  ----------  ------                -------  --------------------  ------                 ----     
>                          VLC-Autoupdate-Smart                                 Auto Update VLC 2.2.4  VLC.png

**Comment by homebysix** [comment]
OK, that's progress. Leave the __Verify SSL__ checkbox unchecked, and now let's move on to the second issue: configuring your distribution points.

Quit AutoPkgr, then use TextWrangler or another text editor to dive into your ~/Library/Preferences/com.github.autopkg.plist file. Find the `JSS_REPOS` key (if there is one).

If you have a single SMB distribution point, your `JSS_REPOS` key will look like this:

```
    <key>JSS_REPOS</key>
    <array>
        <dict>
            <key>name</key>
            <string>DP_NAME</string>
            <key>password</key>
            <string>DP_PASSWORD</string>
        </dict>
    </array>
```

For `DP_NAME`, substitute the exact name of your distribution point as you see it on the JSS file share distribution point settings screen:

![screen shot 2016-10-20 at 10 59 51 am](https://cloud.githubusercontent.com/assets/7801391/19571839/7041ce56-96b4-11e6-88c2-e4a4a8d81bd8.png)

For `DP_PASSWORD`, substitute the read/write account password that has access to the SMB share. Again, this should match what's in your JSS settings:

![screen shot 2016-10-20 at 11 00 46 am](https://cloud.githubusercontent.com/assets/7801391/19571877/9a5a94d4-96b4-11e6-93ff-669fd0b59bbb.png)

Now try running `autopkg run -v local.jss.VLC` one more time, and see whether the package gets uploaded to your JSS. Success would be indicated by seeing this in the output:

```
The following changes were made to the JSS:
    Package 
    -------
    VLC-2.2.4.pkg
```

Or by seeing this, if the package already exists on your JSS:

```
JSSImporter: Package upload not needed.
```

But you should not see this:

```
JSSImporter: Package upload and object update skipped. If this is a mistake, ensure you have JSS_REPOS configured.
```

**Comment by mgrevtech** [comment]
@homebysix Does this look right? Am I doing something wrong. Doesnt look like its taking the DP settings. All values given are exactly as per in JSS.

![image](https://cloud.githubusercontent.com/assets/10722833/19580036/5e82bd42-972c-11e6-9042-1e161f6e5a2a.png)

Yea I am getting the "Package upload and object update skipped...." error on running autopkg. no packages uploaded.

**Comment by homebysix** [comment]
That configuration looks good to me, except for the fact that the TextWrangler window isn't saved. I'm assuming you saved the changes before you ran a JSS recipe.

There are other keys that can be specified for JSS_REPOS in addition to name and password, but I would think you'd get a different error if you were missing a required key.
