### ISSUE TITLE
AttributeError: '__NSCFString' object has no attribute 'get'

### ISSUE THREAD

**Issue by TheVakman** [lindegroup/autopkgr#570]
Hello, I just set this up but I am having an issue with any recipe that I try. Is there a particular version of Python that I should have installed?

According to Console/System Logs, this is the error:
```
(FULL AUTOPKG TRACEBACK) 
  File "/usr/local/bin/autopkg", line 2400, in <module>

    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 2394, in main

    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1854, in run_recipes

    recipe_paths.extend(recipe_list.get('recipes', []))
AttributeError: '__NSCFString' object has no attribute 'get'
```

This issue occurs on both Mac OS X 10.11 and macOS 10.12.
AutoPkg: 1.0.0
Git: 2.9.3 & 2.2.1

Thanks!

**Comment by homebysix** [comment]
Hi @TheVakman,

First, let's make sure this is an AutoPkgr error and not a recipe error. Try running this command in Terminal, and see what happens. If the error persists, it's not AutoPkgr.

```
/usr/bin/python /usr/local/bin/autopkg run --verbose --recipe-list ~/Library/Application\ Support/AutoPkgr/recipe_list.txt
```

For the `idna` error, you may want to chime in on this issue: https://github.com/sheagcraig/JSSImporter/issues/95

Thanks!

**Comment by TheVakman** [comment]
Hi @homebysix.

I did that as well already and the output looked very similar to the above error:
```
MACHINENAME:~ USERNAME$ /usr/bin/python /usr/local/bin/autopkg run --recipe-list ~/Library/Application\ Support/AutoPkgr/recipe_list.txt --report-plist /tmp/autopkg-report.xml
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 2400, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 2394, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1854, in run_recipes
    recipe_paths.extend(recipe_list.get('recipes', []))
AttributeError: '__NSCFString' object has no attribute 'get'
```

**Comment by homebysix** [comment]
OK, thanks! Let's continue the discussion here: https://github.com/autopkg/autopkg/issues/323

**Comment by homebysix** [comment]
In case anyone else stumbles upon this issue, the solution for now is to make sure you have more than one recipe "checked" in the AutoPkgr recipe list.

When AutoPkg 1.0.1 is released, it should resolve this issue permanently.
