### ISSUE TITLE
"Missing trust info" warnings on every run

### ISSUE THREAD

**Issue by homebysix** [lindegroup/autopkgr#571]
Public service announcement: If you are using AutoPkgr and have upgraded AutoPkg to version 1.0 or higher, you may be seeing warnings like this on every recipe run:

> WARNING: local.munki.AdobeReaderDC is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...

This is normal and expected behavior. [Please read about storing and verifying trust info in your recipes on the AutoPkg wiki](https://github.com/autopkg/autopkg/wiki/Autopkg-and-recipe-parent-trust-info).

AutoPkgr does not yet have a UI for updating or verifying recipe trust.

I will keep this issue open for a while, for visibility.

**Comment by brianwells** [comment]
I mostly solved this for myself by running the following command in Terminal:
```
A="$HOME/Library/Application Support/AutoPkgr"; for R in `cat "$A/recipe_list.txt"`; \
do if  [[ $R == local.* ]] ; then echo Skipping: $R; echo $R >> "$A/recipe_list.new"; \
else OV=`autopkg make-override $R | awk '{print substr($0,24)}'`; echo Created: $OV; \
/usr/libexec/PlistBuddy -c "print Identifier" "$OV" >> "$A/recipe_list.new"; fi; done; \
mv "$A/recipe_list.txt" "$A/recipe_list.bak"; mv "$A/recipe_list.new" "$A/recipe_list.txt"
```

What this does is ask `autopkg` to generate overrides for each recipe selected in AutoPkgr. It also adjusts the list of recipes selected in AutoPkgr to be the newly-created overrides. 

If you decide to try this, make sure to reopen the AutoPkgr app after running the command and have a good backup of your overrides and AutoPkgr recipe list.

**Comment by homebysix** [comment]
@brianwells I took your code and added some indentation to make it more readable, for the benefit of others:

```
#!/bin/bash
A="$HOME/Library/Application Support/AutoPkgr"
for R in $(cat "$A/recipe_list.txt"); do
    if  [[ $R == local.* ]] ; then
        echo Skipping: $R
        echo $R >> "$A/recipe_list.new"
    else
        OV=$(autopkg make-override $R | awk '{print substr($0,24)}')
        echo Created: $OV
        /usr/libexec/PlistBuddy -c "print Identifier" "$OV" >> "$A/recipe_list.new"
    fi
done
mv "$A/recipe_list.txt" "$A/recipe_list.bak"
mv "$A/recipe_list.new" "$A/recipe_list.txt"
```

And as discussed on Macadmins.org Slack, there's also the option of using [Easy Rider](https://github.com/sheagcraig/easy_rider) to create overrides in bulk.

**Comment by lkraft** [comment]
thanks elliot!!!!

**Comment by thomasm2film** [comment]
Hey. Also updated to 1.01 so obviously having the "issue".
When you write "AutoPkgr does not **yet** have a UI for updating or verifying recipe trust" - would that indicate that you might implement a handler for this? Thanks for all your work!

**Comment by homebysix** [comment]
@thomasm2film, An interface for the trust features would be great! Unfortunately we're short on development resources at the moment, so it's probably not going to be soon.

**Comment by lkraft** [comment]
hey elliot, is this error related to the above?  

Code signature verification failed. Note that all verification can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.

-lisa

**Comment by homebysix** [comment]
Hi @lkraft. No, that's an unrelated error. You may want to open an issue on the repository that the failing recipe belongs to.

**Comment by lkraft** [comment]
will do, thank you!
