### ISSUE TITLE
Use override of MakeCatalogs.munki instead of actual recipe

### ISSUE THREAD

**Issue by homebysix** [lindegroup/autopkgr#572]
Currently, if a Munki recipe is selected, AutoPkgr adds MakeCatalogs.munki to the end of the recipe list. However, with the introduction of the new [AutoPkg trust verbs](https://github.com/autopkg/autopkg/wiki/Autopkg-and-recipe-parent-trust-info), it may make more sense to use an override instead — especially because otherwise this error will occur on each AutoPkg run:

> WARNING: MakeCatalogs.munki is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...

Here's how AutoPkgr might work after implementing this feature request: When a Munki recipe is selected, AutoPkgr would run `autopkg make-override MakeCatalogs.munki` and then add `local.munki.MakeCatalogs` to the end of the recipe list.

**Comment by homebysix** [comment]
In the meantime, I have [added text](https://github.com/lindegroup/autopkgr/commit/f1a7fb19339592dc86d93592d05f5a5f66c26027#diff-04c6e90faac2675aa89e2176d2eec7d8R195) to the README.md on the latest branch to recommend creating an override for MakeCatalogs.munki. AutoPkgr/AutoPkg will use that override automatically, if present.

**Comment by klou** [comment]
+1, same solution.

**Comment by shawnhonsberger** [comment]
Proper workflow explained in the README.md. AutoPkgr users should manage overrides, including this one, rather than AutoPkgr itself.
