### ISSUE TITLE
getting error on repo that is not selected

### ISSUE THREAD

**Issue by lkraft** [lindegroup/autopkgr#577]
every time auotpkgr runs, i get this error (see screenshot) 
![screen shot 2016-12-14 at 06 39 38](https://cloud.githubusercontent.com/assets/16673224/21186395/5a1ca034-c1c9-11e6-8c3e-de328a31ae81.png)

for a repo that is not selected to run

![screen shot 2016-12-14 at 06 40 04](https://cloud.githubusercontent.com/assets/16673224/21186407/67193536-c1c9-11e6-9dc9-f81da79e7ac5.png)

**Comment by homebysix** [comment]
Hi Lisa! Take a look at your ~/Library/Application Support/AutoPkgr/recipe_list.txt file, and see if there's any Zoom recipe listed in there. If so, let me know what the identifier is, and I can tell you what's probably happening.

**Comment by lkraft** [comment]
File Doesn't Exist, Will Create: r com.github.hansen-m.download.zoom.
File Doesn't Exist, Will Create: r com.github.hansen-m.download.zoom.
local.pkg.ClamXav
local.pkg.TextWrangler
local.pkg.Skype
local.pkg.Silverlight
local.pkg.GoogleChrome
local.pkg.Firefox
local.pkg.Evernote
local.pkg.Dropbox
local.pkg.Cyberduck
local.pkg.BBEdit
local.pkg.AdobeReader
local.pkg.AdobeFlashPlayer


is it ok to just delete those first two lines?



	 	
lisa kraft
about.me/lbkraft <http://about.me/lbkraft>

**Comment by homebysix** [comment]
That's bizarre. I'm not sure how those two lines would have gotten in there.

Yes, it's OK to delete those first two lines, and then quit/relaunch AutoPkgr.

**Comment by lkraft** [comment]
rad, thank you!


	 	
lisa kraft
about.me/lbkraft <http://about.me/lbkraft>
