### ISSUE TITLE
JMAF Patch Reporting

### ISSUE THREAD

**Issue by bdelamarche** [lindegroup/autopkgr#580]
Hello everyone,

I write in this section may be in error so please excuse me.
Is it possible to create a grouptemplate.xml which acts on the jamf criterion patch reporting to create smart group based on this criteria ?

![adobe_acrobat_reader_dc-update-smart__](https://cloud.githubusercontent.com/assets/24192780/21390340/be77d784-c786-11e6-9908-b87d7edb2df7.jpg)

Many thanks in advance
Ben

**Comment by bdelamarche** [comment]
Hi all,

Thanks for your help.
I just success it with the API ;)

Please find the code below for Acrobat reader for example :

<computer_group> <name>%group_name%</name> <is_smart>true</is_smart> <criteria>
     <criterion>
       <name>Patch Reporting: Adobe Acrobat Reader DC</name>
       <priority>0</priority>
       <and_or>and</and_or>
       <search_type>less than</search_type>
       <value>15.020.20039</value>
    </criterion> <criterion> <name>Computer Group</name> <priority>1</priority> <and_or>and</and_or> <search_type>member of</search_type> <value>>/= 10.9</value> </criterion> </criteria>
</computer_group>

have a good day

**Comment by homebysix** [comment]
Hi @bdelamarche, thanks for posting your solution.

I don't recommend using Patch Reporting criteria to create groups that JSSImporter-created policies are scoped to. The reason for this is that the "latest" version according to Jamf might not match the "latest" version according to the AutoPkg recipe, and thus you might end up with a looping policy.
