### ISSUE TITLE
AutoPKGR contents differ from expected

### ISSUE THREAD

**Issue by DrChuTang** [lindegroup/autopkgr#581]
Running the latest version of AutoPKGr 1.4.2 and the latest version of AutoPkg 1.0.1 with Git 2.2.1.

Currently have a recipe to update Adobe Reader DC. When I run my overRide recipe I'm getting this error sent to my email:

Parent recipe com.github.jss-recipes.jss.AdobeReaderDC contents differ from expected. Path: /Users/myuser/Library/AutoPkg/RecipeRepos/com.github.autopkg.jss-recipes/Adobe Acrobat Reader DC/Adobe Acrobat Reader DC.jss.recipe

Any information would help since I don't understand what the problem is or what that error means?

**Comment by homebysix** [comment]
Hi @DrChuTang,

The issue you're encountering has the same solution as https://github.com/lindegroup/autopkgr/issues/571 — you'll need to add trust information to your overrides. [Please read up on storing and verifying trust info in your recipes on the AutoPkg wiki.](https://github.com/autopkg/autopkg/wiki/Autopkg-and-recipe-parent-trust-info). Thanks!
