### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 182: ordinal not in range(128)

### ISSUE THREAD

**Issue by macmule** [lindegroup/autopkgr#582]
Taken from: https://github.com/autopkg/autopkg/issues/111#issuecomment-272950580

Hi folks,

I think I have a reproducible method for this.

The below is a snippet from a recipe override that I did a copy/paste fail on:

```
		<key>MUNKI_REPO_SUBDIR</key>
		<string>%CATEGORY%/%DEVELOPER%/%NAME%</string>
		<string>%CATEGORY%/%DEVELOPER%/%NAME%</string>
```

Plutil picks this up: `Found non-key inside <dict> at line 11`

But AutoPKGr errors as per:
![screenshot 2017-01-16 11 36 50](https://cloud.githubusercontent.com/assets/2464974/21981682/7f63645a-dbe0-11e6-9037-0fb2cf3923af.png)

autopkg run -vvv on the recipe gives: 
```
autopkg run -vvv ~/Library/AutoPkg/RecipeOverrides/jHelper\ GUI-dataJAR.munki.recipe
WARNING: plist error for /Users/sadmin/Library/AutoPkg/RecipeOverrides/jHelper GUI-dataJAR.munki.recipe: Error Domain=NSCocoaErrorDomain Code=3840 "The data couldn’t be read because it isn’t in the correct format." (Found non-key inside <dict> at line 11) UserInfo=0x7ff218f8dbf0 {NSDebugDescription=Found non-key inside <dict> at line 11, kCFPropertyListOldStyleParsingError=The data couldn’t be read because it isn’t in the correct format.}
```

So.. I'd be looking to AutoPKGr's handling of the error

**Comment by Moisie2000** [comment]
Hello:

I'm getting this error now too. I've just updated to AutoPkg 1.0.1 and AutoPkgr 1.4.2 (under OS X 10.10.5), and am working through the new trust settings - but am getting this error too now.

In my case, I've just created a fresh override for Nick McSpadden's AppStoreApp Munki recipe; it runs without issue under autopkg on the command line, but fails with exactly the same error report as above when run from within AutoPkgr.

Here's the relevant excerpt from system.log:

```
Mar 13 12:55:01 macserver.abcdef.private AutoPkgr[99850]: (FULL AUTOPKG TRACEBACK) 
	  File "/usr/local/bin/autopkg", line 2407, in <module>
	
	    sys.exit(main(sys.argv))
	
	  File "/usr/local/bin/autopkg", line 2401, in main
	
	    
	exit(subcommands[verb]['function'](argv))
	  File "/usr/local/bin/autopkg", line 1939, in run_recipes
	
	    search_github=make_suggestions)
	
	  File "/usr/local/bin/autopkg", line 342, in load_recipe
	
	    search_github=search_github)
	
	  File "/usr/local/bin/autopkg", line 242, in locate_recipe
	
	    recipe_file = find_recipe(name, override_dirs + recipe_dirs)
	
	  File "/usr/local/bin/autopkg", line 197, in find_recipe
	
	    return (find_recipe_by_identifier(id_or_name, search_dirs) or
	
	  File "/Library/AutoPkg/autopkglib/__init__.py", line 141, in find_recipe_by_identifier
	
	if get_identifier_from_recipe_file(match) == identifier:
	  File "/Library/AutoPkg/autopkglib/__init__.py", line 124, in get_identifier_from_recipe_file
	
	"WARNING: plist error for %s: %s" % (filename, unicode(err)))
	
	UnicodeEncodeError
	: 
	'ascii' codec can't encode character u'\u2019' in position 169: ordinal not in range(128)
```

Sorry - I don't know about Python to start investigating myself! Hope this helps someone who does...

Thanks.

**Comment by Moisie2000** [comment]
Hello:

I'm just updated the thread on the AutoPkg page about this: https://github.com/autopkg/autopkg/issues/218

Whilst AutoPkgr should be able to gracefully handle non-ASCII return from AutoPkg, it looks like the underlying issue is actually on AutoPkg's side.

Hope that helps.

**Comment by homebysix** [comment]
This is correct:
>Whilst AutoPkgr should be able to gracefully handle non-ASCII return from AutoPkg, it looks like the underlying issue is actually on AutoPkg's side.

Thanks!
