### ISSUE TITLE
URLTextSearcher Processor not working with a proxy 

### ISSUE THREAD

**Issue by SashLi** [lindegroup/autopkgr#583]
Hi there,
first of all thank you for this nice piece of software.

I think I found a issue when there are receipts that are using the URLTextSearcher together with a proxy. I have the problem when I'm using the  OracleJava8.munki (from the autopkr receipt repo) with a proxy that I typed into AutoPkgr. The curl of the website in the URLTextSearcher fails when I only use the proxy settings field inside of AutoPkgr.

After a little bit of testing I found out that it is working directly with autopkg when I'm running the command directly from the command line with the proxy information:

`http_proxy=http://myproxyserver:8080 https_proxy=http://myproxyserver:8080 autopkg run  OracleJava8.munki`

I think that AutoPkgr is not giving the proxy informations correctly to the task of autokgr or not setting a correct proxy environment variabel

The Debug of AutoPkgr always show that a proxy is set when I run the "same" action from AutoPkgr

```
[DEBUG] Using HTTP_PROXY: http://myproxyserver:8080
[DEBUG] Using HTTPS_PROXY: http://myproxyserver:8080
```

Did anyone had the same issue before or a similar issue ?

**Comment by shawnhonsberger** [comment]
If you configure your proxies in `~/.gitconfig`, then it should clear up AutoPkg issues with the proxy, e.g adding.:
```https.proxy=proxy.example.com:8080
http.proxy=proxy.example.com:8080```
If you still have trouble, try removing the following from `com.lindegroup.AutoPkgr.plist`:
```HTTPS_PROXY
HTTP_PROXY```
Closing this issue. Please feel free to re-open if it does not resolve.
