### ISSUE TITLE
Error Running Recipes in AutoPkgr with Warnings

### ISSUE THREAD

**Issue by ado120** [lindegroup/autopkgr#585]
I am suddenly getting these errors when I am trying to run a recipe on anything, whether its getting Chrome.munki or munkitools2.munki

"WARNING: com.github.autopkg.munki.google-chrome is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...

WARNING: com.github.autopkg.munki.munkitools2 is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...

WARNING: com.github.homebysix.munki.CCleaner is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...

No valid recipe found for com.github.arubdesu.munki.HipChat"

Any ideas?

**Comment by homebysix** [comment]
Hi @ado120,

Check out https://github.com/lindegroup/autopkgr/issues/571, which has a link to the info you need on the AutoPkg wiki. Thanks!

Elliot
