### ISSUE TITLE
Flash Player.pkg issue

### ISSUE THREAD

**Issue by LehmanITR** [lindegroup/autopkgr#586]
Whenever I run AdobeFlashPlayer.pkg recipe I get this error:
"WARNING: com.github.autopkg.pkg.FlashPlayerExtractPackage is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...

Mismatch in authority names. Note that all verification can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value."

I had diabled certificates with:

defaults write com.github.autopkg JSS_SUPPRESS_WARNINGS -bool True

It downloads dmg but doesn't create pkg. Having no problems with other recipes.

**Comment by homebysix** [comment]
Hi @LehmanITR - This sounds like an issue with the underlying Flash recipe, and not with AutoPkgr itself. Try opening Terminal and running `autopkg run -v com.github.autopkg.pkg.FlashPlayerExtractPackage` to see whether the recipe fails outside of AutoPkgr.

**Comment by LehmanITR** [comment]
Thx

Mike Shur | Apple Systems Administrator
Lehman College, CUNY | Information Technology Division
718-960-8708 | http://www.lehman.edu

IT Staff will never ask for your password. Never provide your password to anyone by phone or by replying to/clicking on an email link.

On Mar 21, 2017, at 6:37 PM, Elliot Jordan <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @LehmanITR<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_LehmanITR&d=DwMFaQ&c=tzSjEhL4u5XIh9GXWARTsBI31pp--h2kWBIadC1LS_M&r=ikivzZ-w4bKVt6dt8ofDCXBWXRHDw1U5c5HiTef7gME&m=V6jz3Oquxko048uTuVfuLQkUSaSCDBaFtGpPQR59HqQ&s=PC_uDADShngiChMKCd7uFaWZpLagQ5Vmq83LqifoSg4&e=> - This sounds like an issue with the underlying Flash recipe, and not with AutoPkgr itself. Try opening Terminal and running autopkg run -v com.github.autopkg.pkg.FlashPlayerExtractPackage to see whether the recipe fails outside of AutoPkgr.
