### ISSUE TITLE
CodeSignatureVerifier flag visibility ?

### ISSUE THREAD

**Issue by mark-cohen** [lindegroup/autopkgr#587]
Adding visibility for the "CodeSignatureVerifier" flag in AutoPkgr would be helpful. Being able to see more info than the current modal dialogue box, akin to the autopkg CLI's output: "Code signature verification disabled for this recipe run." when a trust issue impedes a recipe run.

**Comment by homebysix** [comment]
@mark-cohen Are there situations in which you'd want to leave code signature verification disabled permanently? In those situations, I'd be inclined to set the `DISABLE_CODE_SIGNATURE_VERIFICATION` variable in specific recipe overrides, rather than globally.
