### ISSUE TITLE
curl failure

### ISSUE THREAD

**Issue by lkraft** [lindegroup/autopkgr#588]
while running this morning, got the following error:

Curl failure: Could not resolve host: dl.google.com (exit code 6)

Curl failure: Could not resolve host: download.mozilla.org (exit code 6)

Could not retrieve URL https://update.evernote.com/public/ENMacSMD/EvernoteMacUpdate.xml:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: update.evernote.com

Curl failure: Could not resolve host: www.dropbox.com (exit code 6)

Could not retrieve URL https://version.cyberduck.io/changelog.rss:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: version.cyberduck.io

Unexpected error retrieving product manifest: '<urlopen error [Errno 8] nodename nor servname provided, or not known>'

could this just be a network issue?  or did something else go horribly wrong?

**Comment by jsenick** [comment]
@lkraft Are you able to resolve hostnames in web browsers or using nslookup on the affected machine?

**Comment by homebysix** [comment]
Given that multiple domains failed, I would bet this was a one-off DNS or network outage. Closing, but @lkraft feel free to add more info if it's still happening.

**Comment by lkraft** [comment]
not still happening... thanks
