### ISSUE TITLE
Missing Parent Recipe Aborts Run

### ISSUE THREAD

**Issue by majorsl** [lindegroup/autopkgr#589]
Running the latest autopkgr. I added Platypus.munki and, despite the yellow exclamation mark, forgot to add the parent repo for the task.

This resulted in autopkgr aborting my entire run when it hit that recipe. In other words, it just quit at task 14 of 79, not collecting the following recipes.

It should probably just produce an error and carry on, perhaps?

**Comment by homebysix** [comment]
Hi @majorsl — do you mind trying this again with the latest build of AutoPkg (1.0.3 from master)?

I have a feeling it might be related to this:
https://github.com/autopkg/autopkg/issues/355

**Comment by shawnhonsberger** [comment]
All parent repos must be added.
