### ISSUE TITLE
failed local trust verification

### ISSUE THREAD

**Issue by jimmybaeyens** [lindegroup/autopkgr#591]
Hi Guys,

i keep receiving failed local trust verification... anyone knows how to tackle this?

thanks in advance,
Jimmy

**Comment by DrChuTang** [comment]
@jimmybaeyens are you using child recipes ? I had same issue and had to build trust with my child / parent.

**Comment by homebysix** [comment]
@jimmybaeyens Take a read through [this page](https://github.com/autopkg/autopkg/wiki/AutoPkg-and-recipe-parent-trust-info) and see if it's helpful.

**Comment by jimmybaeyens** [comment]
Thanks guys! will check now

**Comment by jimmybaeyens** [comment]
Hi Guys, still receive the same error although i've made overrides and updated trust info on all the recipes.. 
any advice on where i should look ? and thanks again.. kinda stuck here

**Comment by homebysix** [comment]
Hi @jimmybaeyens. Please make sure you have the actual overrides selected in AutoPkgr's recipe list, rather than the original recipes. Also try running your recipes in Terminal, and see what other details might be gained from the output there:
```
/usr/bin/python /usr/local/bin/autopkg run --verbose --recipe-list ~/Library/Application\ Support/AutoPkgr/recipe_list.txt
```

**Comment by jimmybaeyens** [comment]
autopkg run --verbose --recipe-list ~/Library/Application\ Support/Autopkgr/recipe_list.txt
Processing com.github.autopkg.munki.munkitools3...
Failed local trust verification.
Receipt written to /tmp/receipts/com.github.autopkg.munki-receipt-20170608-120813.plist
Processing com.github.autopkg.munki.MSWord2016...
Failed local trust verification.
Receipt written to /tmp/receipts/com.github.autopkg.munki-receipt-20170608-120813.plist
Processing com.github.autopkg.munki.MSPowerPoint2016...
Failed local trust verification.
Receipt written to /tmp/receipts/com.github.autopkg.munki-receipt-20170608-120813.plist
Processing com.github.autopkg.munki.MSOutlook2016...
Failed local trust verification.
Receipt written to /tmp/receipts/com.github.autopkg.munki-receipt-20170608-120813.plist
Processing com.github.autopkg.munki.MSOneNote2016...
Failed local trust verification.
Receipt written to /tmp/receipts/com.github.autopkg.munki-receipt-20170608-120813.plist
Processing com.github.autopkg.munki.MSExcel2016...
Failed local trust verification.
Receipt written to /tmp/receipts/com.github.autopkg.munki-receipt-20170608-120813.plist
Processing com.github.autopkg.munki.google-chrome...
Failed local trust verification.
Receipt written to /tmp/receipts/com.github.autopkg.munki-receipt-20170608-120813.plist
Processing com.github.autopkg.munki.FlashPlayerNoRepackage...
Failed local trust verification.
Receipt written to /tmp/receipts/com.github.autopkg.munki-receipt-20170608-120813.plist
Processing com.github.autopkg.munki.VLC...
Failed local trust verification.
Receipt written to /tmp/receipts/com.github.autopkg.munki-receipt-20170608-120813.plist
Processing com.github.autopkg.munki.Skype...
Failed local trust verification.
Receipt written to /tmp/receipts/com.github.autopkg.munki-receipt-20170608-120813.plist
Processing com.github.autopkg.pkg.AdobeReaderDC...
Failed local trust verification.
Receipt written to /tmp/receipts/com.github.autopkg.pkg-receipt-20170608-120813.plist
Processing com.github.autopkg.munki.OracleJava8...
Failed local trust verification.
Receipt written to /tmp/receipts/com.github.autopkg.munki-receipt-20170608-120813.plist
Processing MakeCatalogs.munki...
Failed local trust verification.
Receipt written to /tmp/receipts/MakeCatalogs-receipt-20170608-120814.plist

The following recipes failed:
    com.github.autopkg.munki.munkitools3
        No trust information present.
    com.github.autopkg.munki.MSWord2016
        No trust information present.
    com.github.autopkg.munki.MSPowerPoint2016
        No trust information present.
    com.github.autopkg.munki.MSOutlook2016
        No trust information present.
    com.github.autopkg.munki.MSOneNote2016
        No trust information present.
    com.github.autopkg.munki.MSExcel2016
        No trust information present.
    com.github.autopkg.munki.google-chrome
        No trust information present.
    com.github.autopkg.munki.FlashPlayerNoRepackage
        No trust information present.
    com.github.autopkg.munki.VLC
        No trust information present.
    com.github.autopkg.munki.Skype
        No trust information present.
    com.github.autopkg.pkg.AdobeReaderDC
        No trust information present.
    com.github.autopkg.munki.OracleJava8
        No trust information present.
    MakeCatalogs.munki
        No trust information present.

Nothing downloaded, packaged or imported.


if i look in the Autopkgr Folders & Integration my overrides are located in library/Autopkg/RecipeOverrides   al done yesterday...

**Comment by shawnhonsberger** [comment]
Do your overrides have unique identifiers in the code? It appears that the overrides do not have unique names. Autopkg may be actually running the parent recipe instead, in which it will find no trust information. If so, I would recommend a best practice to create a unique override name when you create the override to avoid this.

**Comment by jimmybaeyens** [comment]
thanks guys for the help again!!

**Comment by shawnhonsberger** [comment]
You're welcome!
