### ISSUE TITLE
A Python exception occurred during the execution of autopkg, see the system log for more details.  [ERROR] argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by biggievan** [lindegroup/autopkgr#592]
I am getting the following error message: "A Python exception occurred during the execution of autopkg, see the system log for more details.

[ERROR] argument of type 'NoneType' is not iterable"

I have had this issue before, but I can't remember the fix. It usually happens a day after I install Autopkgr for some reason.

**Comment by homebysix** [comment]
Have you confirmed whether this error occurs when you run your recipes in Terminal?

```
/usr/bin/python /usr/local/bin/autopkg run --verbose --recipe-list ~/Library/Application\ Support/AutoPkgr/recipe_list.txt
```

**Comment by v3rsusM0d3** [comment]
Hi guys

Same issue here. 

@homebysix, I can confirm this error occurs when I run the recipes in Terminal.

And I get several messages like the one below when I run recipes from the AutoPkgr GUI

_WARNING: com.github.valdore86.munki.KeePassX is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding..._

And then the below at the end of "Error running recipes window"

**_"A Python exception occurred during the execution of autopkg, see the system log for more details.
[ERROR] argument of type 'NoneType' is not iterable"_**




Ps: I have been a Mac sysadmin for only a few months and still learning all these stuff.

Any help appreciated.

Thanks

**Comment by homebysix** [comment]
The "NoneType" error is most likely [this one](https://github.com/autopkg/autopkg/issues/355), and will be fixed in the next release of AutoPkg.

The "missing trust info" error is unrelated. Read the TL;DR section at the top of [this page](https://github.com/autopkg/autopkg/wiki/AutoPkg-and-recipe-parent-trust-info).

@v3rsusM0d3 — Welcome to the MacAdmin world! Join us on Slack, if you haven't already: macadmins.org.

**Comment by biggievan** [comment]
Thanks Elliot!

On Wednesday, July 26, 2017, 8:33:55 AM PDT, Elliot Jordan <notifications@github.com> wrote:


The "NoneType" error is most likely this one, and will be fixed in the next release of AutoPkg.

The "missing trust info" error is unrelated. Read the TL;DR section at the top of this page.

@v3rsusM0d3 — Welcome to the MacAdmin world! Join us on Slack, if you haven't already: macadmins.org.
