### ISSUE TITLE
Consistent Error: unmounting ~/.../App.dmg failed: hdituil: couldn't unmount "disk$" - Resource busy

### ISSUE THREAD

**Issue by kwt5152** [lindegroup/autopkgr#593]
Hello,
I've been encountering this error message consistently. It doesn't appear to affect running recipes, but it does get quite annoying. The below error is the most recent one that has occurred. 

Error running recipes
unmounting /Users/$username/Library/AutoPkg/Cache/local.munki.Firefox/downloads/Firefox.dmg failed: hdiutil: couldn't unmount "disk8" - Resource busy

Is this a common problem? If so, is there a simple solution that I'm missing? Thanks!

**Comment by homebysix** [comment]
Hi @kwt5152 — Does this only happen when using AutoPkgr, or does the same error occur when you use AutoPkg to run the recipes in Terminal?

```
/usr/bin/python /usr/local/bin/autopkg run --verbose --recipe-list ~/Library/Application\ Support/AutoPkgr/recipe_list.txt
```
