### ISSUE TITLE
"Error mounting url" but it DOES mount (twice)

### ISSUE THREAD

**Issue by el2493** [lindegroup/autopkgr#594]
So I have AutoPkgr setup along with the JSS Importer.  I created a Recipe Override (for Silverlight) and chose to run only that recipe.  It seemed to cycle for a while, then gave a popup saying "Error running recipes: Error mounting URL"smb://[domain];[DP account name]:********@[IP address of Server, or server name of server/share name]: None"  However, a split second before or after getting that error message, the share mounted and I can see it in volumes.  

After looking at this for a while, I realized it actually looks like it's trying to mount the DP twice (so it mounts once successfully, then mounts a 2nd time with an _1 after the title and that's what's causing the error).  It seems like when it tries to mount for the 2nd time it breaks the rest of the process, so it doesn't complete even though the DP is mounted.  I checked and it only has 1 DP set up in JSS Importer (it did have 2, but I removed 1 of them).

I saw a few other issues that reported this or a similar error message.  One of them said it could have something to do with DeployStudio, which I did have installed on my computer though it wasn't running, so I uninstalled that and deleted entries from /Library/Application Support, /Library/Caches, and /Library/Preferences.  Also ran `sudo launchctl unload -F /Library/LaunchDaemons/com.deploystudio.server.plist` to ensure it wasn't running, then restarted computer.  Still got the same error message.

Anyone having this issue?  The computer I'm using is Sierra (10.12.3).  I've tried both having the JSS provide the DP and manually entering in the DP and it doesn't seem to make a difference.

**Comment by shawnhonsberger** [comment]
I would recommend running all macOS updates, and updating to the latest version of JSSImporter: https://github.com/jssimporter/JSSImporter/releases.
