### ISSUE TITLE
[Enhancement] Add button "check recipes sanity". (using plutil)

### ISSUE THREAD

**Issue by pexner** [lindegroup/autopkgr#598]
Could you add a button "check recipes sanity" next to the button "Run recipes now", which checks if the plists are OK?
Using
`find ~/Library/AutoPkg/ -name '*.recipe' -exec plutil -lint {} ';' | grep -v OK`
and report either "All OK" or malformed recipes.
This helps a lot in searching malformed recipes when getting an error:
```
A Python exception occurred during the execution of autopkg, see the system log for more details.

[ERROR] 'ascii' codec can't encode character u'\u2019' in position 197: ordinal not in range(128)
```
Thanks

**Comment by shawnhonsberger** [comment]
Recipe issues should be solved upstream of AutoPkgr.

**Comment by pexner** [comment]
I agree. But real world proves the contrary.
Please add this enhancement. It's not a big deal - but improves AutoPkgr a lot.

**Comment by homebysix** [comment]
I agree with @shawnhonsberger that recipe issues are firmly out of scope for AutoPkgr.

But if the enhancement you're requesting is not a big deal, perhaps a pull request that proves the concept would be welcomed.
