### ISSUE TITLE
Unable to connect to JSS server sslv3 alert handshake failure 

### ISSUE THREAD

**Issue by akhey** [lindegroup/autopkgr#601]
Hi guys,

Just installed AutoPkgr and JSSImporter on macOS Sierra and when running the recipe; i got the sslv3 error. I have looked at other threads that mentioned to change the ssl connection to tls1 but i couldnt find such file /Library/Python/2.7/site-packages/jss/contrib/requests/packages/urllib3/util/ssl_.py to modify it.

Please help.

AutoPkgr version 1.4.2
JSSImporter 0.5.1

Thanks

![image](https://user-images.githubusercontent.com/30459185/28607473-6b2a5c84-721f-11e7-8d04-e722c3be5969.png)

![image](https://user-images.githubusercontent.com/30459185/28607509-91d07d96-721f-11e7-9632-03941ac5a791.png)

**Comment by homebysix** [comment]
Hi @akhey,

If you're getting the error in Terminal, then AutoPkgr is not involved. You may want to get on macadmins.org Slack and join the #jamfnation room, or open an issue on the JSSImporter GitHub page.

Also make sure you have the required pyopenssl module installed, using the python command found on the [JSSImporter readme](https://github.com/sheagcraig/JSSImporter): `python -m ensurepip --user -U && pip install -I --user pyopenssl`

Thanks!
