### ISSUE TITLE
Multiple of the same apps from Autopkgr

### ISSUE THREAD

**Issue by simke414** [lindegroup/autopkgr#603]
Hi there,

I have a problem on my Munki Server. When the Autopkgr application search for updates, it downloads a few times the same application and i don't know why.
When i check on munki, we can see that many apps are duplicates but named differently, like "MSWord.dmg - MSWord_1.dmg ..." and i cannot find out how to just have it one and that's it.

I insert 2 screenshots below. Hopefully someone can help me out.

Thank you,
Kevin Simoes
![screen shot 2017-09-13 at 12 05 36](https://user-images.githubusercontent.com/31983155/30471826-6c94f91e-99fa-11e7-946c-d8931e743425.png)
![screen shot 2017-09-13 at 12 06 04](https://user-images.githubusercontent.com/31983155/30471827-6c953f6e-99fa-11e7-8121-36df267bd07d.png)

**Comment by simke414** [comment]
Nobody can help?

**Comment by homebysix** [comment]
Hi @simke414 — It seems like "MakeCatalogs.munki" did not run as part of your recipe list. Normally AutoPkgr adds this to the end of your recipe list automatically if you have any Munki recipes checked. Could you verify that's what happened? You can open ~/Library/Application Support/AutoPkgr/recipe_list.txt in a text editor to have a look.

**Comment by simke414** [comment]
@homebysix thank you for your reply.

That's what i got inside the txt file:

local.munki.OracleJava8
local.munki.VLC
local.munki.Silverlight
local.munki.MSWord2016
local.munki.MSPowerPoint2016
local.munki.MSOutlook2016
local.munki.MSExcel2016
local.munki.GoogleChrome
local.munki.FontAgent7
local.munki.Firefox
local.munki.FileZilla
local.munki.EasyFind
local.munki.Basecamp3
local.munki.AdobeShockwavePlayer
local.munki.AdobeFlashPlayer
local.munki.AdobeAir
local.munki.AdobeReaderDC
local.munki.VLC
local.munki.Silverlight
local.munki.OracleJava8
local.munki.MSOneDrive
local.munki.MSOutlook2016
local.munki.MSPowerPoint2016
local.munki.MSWord2016
local.munki.MSExcel2016
local.munki.FontAgent7
local.munki.FileZilla
local.munki.EasyFind
local.munki.AdobeShockwavePlayer
local.munki.AdobeFlashPlayer
local.munki.AdobeAir
local.munki.Firefox
local.munki.GoogleChrome
local.munki.FontAgent7
local.munki.MSOneDrive
local.munki.AdobeShockwavePlayer
local.munki.FileZilla
local.munki.VLC
local.munki.Silverlight
local.munki.GoogleChrome
local.munki.Firefox
local.munki.EasyFind
local.munki.MSOutlook2016
local.munki.MSPowerPoint2016
local.munki.MSWord2016
local.munki.MSExcel2016
local.munki.OracleJava8
local.munki.AdobeAir
local.munki.AdobeFlashPlayer
File Doesn't Exist, Will Create:

**Comment by homebysix** [comment]
Interesting. I think others have mentioned that too, rarely.

Remove the last line of that file, and replace it with `MakeCatalogs.munki`, then try again.

**Comment by homebysix** [comment]
@oleary-bruce If you run `autopkg verify-trust-info MakeCatalogs.munki` do you get "OK"?

And if you run your recipe list outside of AutoPkgr, do you get duplicate imports?
```
/usr/bin/python /usr/local/bin/autopkg run --verbose --recipe-list ~/Library/Application\ Support/AutoPkgr/recipe_list.txt
```

**Comment by oleary-bruce** [comment]
@homebysix No, I get FAILED. Hmmm...I don't recall doing anything out of the ordinary with my setup and recipes. In fact, less than normal, as I have been out on sick leave with vertigo for almost 7 weeks.

**Comment by homebysix** [comment]
If your MakeCatalogs recipe's trust info is out of date, that would explain why Munki recipes are resulting in multiple identical imports.

`autopkg update-trust-info MakeCatalogs.munki` should fix you up.

@simke414 Is the issue resolved for you now?

**Comment by oleary-bruce** [comment]
@homebysix Thanks, Elliot! That seems to have done the trick. Just to be OCD about it, I am going to test all my recipe overrides individually.
