### ISSUE TITLE
Casper JSS Recipes cannot find parent recipes

### ISSUE THREAD

**Issue by skinfor** [lindegroup/autopkgr#604]
So, hello everyone, I'm new to Autopkgr and I have it setup and it uses package recipes good but when I try and run the Casper JSS specific recipes they all seem to be missing the parent recipe.
Maybe I didn't set it up correctly?  I followed all the instructions that I could find and the other recipes seem to be working though.

Also, I am having an issue with Autopkgr actually moving the packages to the Casper share.  It will create categories and such, but not full policies and the packages needed in Casper.

Maybe these are combined issues, maybe not.  Thank you all in advance for any help that you can offer.  Have a very great day today!

**Comment by homebysix** [comment]
Hi @skinfor. I suspect this may not be AutoPkgr related, but related to the configuration of AutoPkg or JSSImporter. Can you follow steps 1 and 2 of the [troubleshooting section](https://github.com/lindegroup/autopkgr#troubleshooting) and report your results back?

**Comment by skinfor** [comment]
Will do, I’ll let you know what happens, thank you Elliot.

Stephen Kinford
PC Network Technician – ITS – Apple Support
Cuyahoga Community College – JSTC
216-987-4198 – Work
216-702-8384 – Cell
Stephen.kinford@tri-c.edu<mailto:Stephen.kinford@tri-c.edu>
2500 East 22nd St.
Cleveland, OH  44115

Tri-C® Where futures begin SM
www.tri-c.edu<http://www.tri-c.edu/>

**Comment by skinfor** [comment]
Thank you, Elliot, I was able to get the packaging side right with the correct recipes.  I’m still working on getting it to talk with Casper and the JSS recipes correctly but will work on that this week.  Appreciate the pointer where to look for a fix.

Stephen Kinford
PC Network Technician – ITS – Apple Support
Cuyahoga Community College – JSTC
216-987-4198 – Work
216-702-8384 – Cell
Stephen.kinford@tri-c.edu<mailto:Stephen.kinford@tri-c.edu>
2500 East 22nd St.
Cleveland, OH  44115

Tri-C® Where futures begin SM
www.tri-c.edu<http://www.tri-c.edu/>

**Comment by skinfor** [comment]
By the way watching your Macadmins of Recipe Robot from 2016.  I was there 2016 and this year but didn’t take your session and now wish I had. The video is helping with some other things.  Maybe I’ll see you in 2018.  Have a great evening!

Stephen Kinford
PC Network Technician – ITS – Apple Support
Cuyahoga Community College – JSTC
216-987-4198 – Work
216-702-8384 – Cell
Stephen.kinford@tri-c.edu<mailto:Stephen.kinford@tri-c.edu>
2500 East 22nd St.
Cleveland, OH  44115

Tri-C® Where futures begin SM
www.tri-c.edu<http://www.tri-c.edu/>

**Comment by homebysix** [comment]
Glad you enjoyed the session! :-)
