### ISSUE TITLE
[Enhancement] Teams notification via webhook

### ISSUE THREAD

**Issue by kdu2** [lindegroup/autopkgr#605]
Can Microsoft Teams be added as an option for a notification channel? Here is an example of using the webhook api to send a notification to a Teams channel for SCCM deployment status: http://www.scconfigmgr.com/2017/10/06/configmgr-osd-notification-service-teams/

it's essentially using powershell to send json data to a rest api. something with curl and json input would probably work?

**Comment by fridomac** [comment]
There is already a Post-Processor to post to Teams from AutoPkg, which I use currently (https://github.com/autopkg/sebtomasi-recipes/blob/master/PostProcessors/TeamsPoster.py).

But integration into AutoPkg would be nicer :-)

**Comment by Darkomen78** [comment]
> There is already a Post-Processor to post to Teams from AutoPkg, which I use currently (https://github.com/autopkg/sebtomasi-recipes/blob/master/PostProcessors/TeamsPoster.py).

How did you use that post-processor with a standard AutoPkgr-munki install ?

**Comment by fridomac** [comment]
You can add the Postprocessor in the AutoPkg setup, and you have to add the needed Variables into your Recipe.

**Comment by Darkomen78** [comment]
> You can add the Postprocessor in the AutoPkg setup, and you have to add the needed Variables into your Recipe.

Ho 😞 So you can't make a global summary like the Autopkgr Slack/email notifications.

**Comment by fridomac** [comment]
No, you get a separate Teams post for every recipe....

**Comment by shawnhonsberger** [comment]
Microsoft Teams is now available in AutoPkgr 1.5.4! Check it out here: https://github.com/lindegroup/autopkgr/releases/latest
