### ISSUE TITLE
VLC Email Notifications for VLC.dmg file Update

### ISSUE THREAD

**Issue by bditton** [lindegroup/autopkgr#609]
Hi

We are currently on VLC Version 2.2.8 and are consistently receiving email notifications every time a new VLC.dmg file has been downloaded can this be stopped as the VLC Version always stays the same as version 2.2.8.

**Comment by homebysix** [comment]
Hi @bditton - This is probably expected behavior, if you're using the default email notification settings. Check out the first question on this FAQ page: https://github.com/autopkg/autopkg/wiki/FAQ

AutoPkgr can be configured to email you only when items are imported, not simply downloaded. Go to the __Notifications__ tab, then customize the __Choose which actions trigger notification__ settings. For example, here's mine:

![screen shot 2018-01-18 at 4 57 00 pm](https://user-images.githubusercontent.com/7801391/35129519-dc794694-fc70-11e7-8bd8-b2d68dd69d85.png)

**Comment by bditton** [comment]
Hi that will help in the short term but it does not fix the issue at hand.

This is what the email looks like when receiving this VLC notification:

New software available for testing

AutoPkgr Notification


New software was downloaded:
NAME | VERSION
-- | --
VLC | 2.2.8

The following new items were downloaded:

/Users/administrator/Library/AutoPkg/Cache/com.github.autopkg.munki.VLC/downloads/VLC.dmg

NAME | RATIO (CLICK FOR DETAILS)
-- | --
VLC.dmg | 0/57

We are consistently recieving email from VLC confirming that new software has been downloaded. However the version that has been downloaded is the same version as before 2.2.8 and this doesn't change.
I am unsure as to why the version is not changing and why we are receiving emails for something that doesn't change. Any thoughts??

**Comment by homebysix** [comment]
The phenomenon you're experiencing is explained by the link I shared above. VLC is even used as the example. Here's the relevant section:

> AutoPkg's download processor makes use of a couple of standard HTTP headers ("last-modified" and "etag") to determine if the file has changed before requesting a download. If the vendor's web server does not send those headers, or the file is hosted on one of several replicas, AutoPkg cannot tell if the file on the server is different from the one it has.
>
> For example:
> VLC is hosted on multiple mirrors, and the different mirrors have different "last-modified" time stamps. If AutoPkg gets a mirror with a "last-modified" date that's different than what AutoPkg previously saw for VLC, AutoPkg will download the "newer" VLC. Of course, once it's downloaded, AutoPkg will discover it's a VLC version it already has.

**Comment by bditton** [comment]
Thank you for explaining. This is probably a silly question however i am new to autopkgr and munki. Is there a way to fix this or is what has been suggested by you the fix??

**Comment by homebysix** [comment]
@bditton - There's really nothing to "fix." It sounds like the notifications are working as expected, notifying you upon each new download. (Normally that would only be once per version, but with certain apps, including VLC, that could be on every AutoPkg run.)

If you adjust the notification settings in AutoPkgr to match the screenshot I posted above, the notifications will only notify you when a new version gets imported into Munki, which is probably more useful to you.

**Comment by bditton** [comment]
no worries thanks for your help i really appreciate it.
