### ISSUE TITLE
Acrobat Reader DC

### ISSUE THREAD

**Issue by ivyacres** [lindegroup/autopkgr#610]
How come Jamf is telling me the most current version of Adobe Acrobat Reader DC is 18.009.20050, but when I run Autopkgr the most current version it will download for me is 18.009.20044? Is this an Adobe issue, or a Jamf issue, or a recipe issue within autopkgr?

**Comment by ethanfann** [comment]
Greetings Ivyacres.

I believe that that would be a JAMF issue reporting a higher version than what is available. Heading on over to https://get.adobe.com/reader/otherversions/ and selecting Mac OS Intel 10.11-10.13 and English as the language reveals that the latest version they are offering is Reader DC 2018.009.20044.

<img width="1320" alt="screen shot 2018-02-06 at 6 09 49 pm" src="https://user-images.githubusercontent.com/6005240/35894778-50f73e7a-0b69-11e8-9f4a-dcb131114343.png">
