### ISSUE TITLE
Could not find parent recipe and No valid recipe found for all recipes ran

### ISSUE THREAD

**Issue by zachpw91** [lindegroup/autopkgr#613]
I recently set up AutoPkgr to test with JAMF integration. Repos and recipes seem to update, but when I try to run recipes, I receive the following:

*The following errors occurred:*
- Could not find parent recipe for com.github.jss-recipes.jss.Xcode
No valid recipe found for com.github.jss-recipes.jss.Xcode

Could not find parent recipe for com.github.jss-recipes.jss.TableauReader
No valid recipe found for com.github.jss-recipes.jss.TableauReader

Could not find parent recipe for com.github.jss-recipes.jss.SkypeForBusiness
No valid recipe found for com.github.jss-recipes.jss.SkypeForBusiness

Could not find parent recipe for com.github.jss-recipes.jss.MicrosoftWord
No valid recipe found for com.github.jss-recipes.jss.MicrosoftWord

Could not find parent recipe for com.github.jss-recipes.jss.MicrosoftPowerPoint
No valid recipe found for com.github.jss-recipes.jss.MicrosoftPowerPoint

Could not find parent recipe for com.github.jss-recipes.jss.MicrosoftOutlook
No valid recipe found for com.github.jss-recipes.jss.MicrosoftOutlook

Could not find parent recipe for com.github.jss-recipes.jss.MicrosoftOneNote
No valid recipe found for com.github.jss-recipes.jss.MicrosoftOneNote

Could not find parent recipe for com.github.jss-recipes.jss.MicrosoftLync
No valid recipe found for com.github.jss-recipes.jss.MicrosoftLync

Could not find parent recipe for com.github.jss-recipes.jss.MicrosoftExcel
No valid recipe found for com.github.jss-recipes.jss.MicrosoftExcel

Could not find parent recipe for com.github.jss-recipes.jss.GoogleChrome
No valid recipe found for com.github.jss-recipes.jss.GoogleChrome

Could not find parent recipe for com.github.jss-recipes.jss.Firefox_EN
No valid recipe found for com.github.jss-recipes.jss.Firefox_EN

Could not find parent recipe for com.github.jss-recipes.jss.FinalCutPro
No valid recipe found for com.github.jss-recipes.jss.FinalCutPro

Could not find parent recipe for com.github.jss-recipes.jss.BoxSync

No valid recipe found for com.github.jss-recipes.jss.BoxSync

Could not find parent recipe for com.github.jss-recipes.jss.AdobeFlashPlayer
No valid recipe found for com.github.jss-recipes.jss.AdobeFlashPlayer

Could not find parent recipe for com.github.jss-recipes.jss.AdobeAcrobatDC
No valid recipe found for com.github.jss-recipes.jss.AdobeAcrobatDC

Could not find parent recipe for com.github.jss-recipes.jss.AdobeAIR
No valid recipe found for com.github.jss-recipes.jss.AdobeAIR

No valid recipe found for com.github.autopkg.install.SkypeForBusiness

No valid recipe found for com.github.autopkg.install.Silverlight

No valid recipe found for com.github.autopkg.install.MSOneNote2016

No valid recipe found for com.github.autopkg.install.MSOutlook2016

No valid recipe found for com.github.autopkg.install.MSWord2016

No valid recipe found for com.github.autopkg.install.MSPowerPoint2016

No valid recipe found for com.github.autopkg.pkg.googlechrome

No valid recipe found for com.github.autopkg.download.firefox-rc-en_US

No valid recipe found for com.github.autopkg.pkg.FlashPlayerExtractPackage

No valid recipe found for com.github.autopkg.pkg.AdobeAIR

When trying to create overrides for these via the command line, the recipe's can't be found either:

autopkg make-override com.github.jss-recipes.jss
Didn't find a recipe for com.github.jss-recipes.jss.
No valid recipe found for com.github.jss-recipes.jss
Dir(s) searched:
.
~/Library/AutoPkg/Recipes
/Library/AutoPkg/Recipes
/Users/walts.9/Library/AutoPkg/RecipeRepos/com.github.autopkg.jss-recipe

Am I missing something?

**Comment by shawnhonsberger** [comment]
Please add the parent repo of the recipe override you are trying to use. This is illustrated in step 6 of the basic usage section of the README.md.

**Comment by hvaandres** [comment]
I updated mine and I still have the same issue
