### ISSUE TITLE
AutoPkgr fails to update its own munkitools

### ISSUE THREAD

**Issue by jelockwood** [lindegroup/autopkgr#614]
AutoPkgr requires three other components in order to function -

- AutoPkg
- Git
- MunkiTools

It lists the currently installed versions on the Install tab in the AutoPkgr GUI and if needed prompts to update these components. Currently it is listing an update for MunkiTools 3.2.1.3499 as being available. I have tried numerous times to install this update by clicking on the button and entering my admin password and it appears to go through the process but ends up back saying the same thing. I have also tried downloading and manually running the MunkiTools installer and this also made no difference. No error is displayed.

![autopkgr](https://user-images.githubusercontent.com/4300786/39567285-66823318-4eb6-11e8-901f-ac61f9f9e435.png)

I have seen this behaviour a few times before and sometimes subsequent updates to either AutoPkgr or MunkiTools has cleared the problem. Rebooting has not cleared this problem nor has an Apple OS update.

I am currently running AutoPkgr 1.4.2 under High Sierra 10.13.4 build 17E202. This is on a Mac mini (Late 2014).

Based on experience with GitHub and some recipes it maybe that the order of files being listed in GitHub under releases might be an issue, i.e. if the source files are listed before the compiled pkg this sometimes upsets some recipes. In this case looking at https://github.com/munki/munki/releases this would not seem likely.

**Comment by homebysix** [comment]
Yep, I renamed to focus on what the thread became about mostly. I'll close this one, but I don't expect a resolution on #493 anytime soon.
