### ISSUE TITLE
Curl/http errors

### ISSUE THREAD

**Issue by NoahDowdDraper** [lindegroup/autopkgr#615]
Suddenly AutoPkgr is reporting errors connecting to certain URLs in some recipes.
The server is behind a proxy, which is configured both in AutoPkgr and in /etc/bashrc.
These recipes DO work in AutoPkg from the command line.
Errors:

`Error in local.jss.AdobeFlashPlayer: Processor: AdobeFlashURLProvider: Error: Could not retrieve URL http://fpdownload2.macromedia.com/get/flashplayer/update/current/xml/version_en_mac_pl.xml`

`Error in local.jss.Oracle Java 8: Processor: URLTextSearcher: Error: Could not retrieve URL http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html`

`Error in local.jss.Adobe Acrobat Reader DC: Processor: URLDownloader: Error: Curl failure: Failed to connect to ardownload.adobe.com port 80: Operation timed out (exit code 7)`

`Error in local.jss.Sublime Text 3: Processor: URLDownloader: Error: Curl failure: Failed to connect to download.sublimetext.com port 80: Operation timed out (exit code 7)`

**Comment by homebysix** [comment]
Hi @NoahDowdDraper - Do you have any other bash or shell profiles in your path? Be sure to check the home folder of the user that AutoPkgr is configured to run as (e.g. ~/.bash_profile).

If you find a `http_proxy` or `https_proxy` environment variable in a profile, try removing those.

**Comment by NoahDowdDraper** [comment]
I'm just running it from an admin account to test. If I do an ``echo "$http_proxy"`` from the command line I get blank output. Like I said above I do have ALL_PROXY set but if I unset that other things that require curl or wget (including autopkg from the command line) will stop working.

**Comment by shawnhonsberger** [comment]
If you configure your proxies in `~/.gitconfig`, then it should clear up AutoPkg issues with the proxy, e.g adding.:
```https.proxy=proxy.example.com:8080
http.proxy=proxy.example.com:8080```
If you still have trouble, try removing the following from `com.lindegroup.AutoPkgr.plist`:
```HTTPS_PROXY
HTTP_PROXY```
Closing this issue. Please feel free to re-open if it does not resolve.
