### ISSUE TITLE
[Feature Request] Add code signing to Autopkgr

### ISSUE THREAD

**Issue by killahquam** [lindegroup/autopkgr#622]
Currently, the process of automating package signing is semi automatic and limited to Autopkg itself with a need to adjust the master recipe with PkgSigner, it would be great if we could integrate it into AutoPkgr where you could point it to your keychain for your cert access and have it sign the package.
The easiest I can think of which isn't really Autopkgr but Autopkg would be to create a flag which can be added to the override to handle the signing instead of having to make definition within the recipe master.

**Comment by homebysix** [comment]
@killahquam - If you're using Per Olofsson's PkgSigner processor, wouldn't you just need to put the  name of your certificate into the PkgSigner `signing_cert` input variable (see example [here](https://github.com/rtrouton/autopkg_recipes/blob/fd69f9b10108351a1aaf40590f2192e8a2debca1/Slack/Slack.pkg.recipe#L19-L20))? That would be done in your override, and AutoPkgr would respect the value you set. I don't see how a change to AutoPkgr would improve that process.

**Comment by killahquam** [comment]
@homebysix Unless I am unaware of something, you also need to define it in the main recipe right?
If you can do it all in the override then that would indeed be perfect.

**Comment by homebysix** [comment]
Yes - recipes that use PkgSigner would just need to expose the `signing_cert` processor argument as an input variable.
