### ISSUE TITLE
[Enhancement] Google Hangouts Chat Notification via webhook

### ISSUE THREAD

**Issue by moojomoore** [lindegroup/autopkgr#623]
Can google hangouts chat be added as a notification option?

Here is some information on that... [https://www.macblog.org/post/autopkg-hangouts-chat-notifications/](https://www.macblog.org/post/autopkg-hangouts-chat-notifications/)

**Comment by shawnhonsberger** [comment]
Google Hangouts (Chat) is now available in AutoPkgr 1.5.4! For Hangouts, copy the "AutoPkgr Slack Bot" Template into the "AutoPkgr Google Hangouts" Template and select Save. 

Check it out here: https://github.com/lindegroup/autopkgr/releases/latest

**Comment by Prodeguerriero** [comment]
@shawnhonsberger 
Would it be possible to add the bit about copying the Slack template to [this Wiki page?](https://github.com/lindegroup/autopkgr/wiki/Scheduling-and-Notifications)
