### ISSUE TITLE
Autopkgr 1.5 fails to update jss-importer 1.0.2

### ISSUE THREAD

**Issue by everetteallen** [lindegroup/autopkgr#626]
Autopkgr sees the new release of jss-importer 1.0.2 but pushing the update button ends in repo not found error. Is this known ?

**Comment by shawnhonsberger** [comment]
@ncsuega Yes this is a known issue. If you quit AutoPkgr, install 1.0.2 manually from the Github Release page, and re-launch, you should be able to use 1.0.2. Please note that the indicator light may remain yellow. A fix is on its way shortly - thanks for your patience.

**Comment by shawnhonsberger** [comment]
Hi @everetteallen, this new release should help, thanks! AutoPkgr 1.5.1: https://github.com/lindegroup/autopkgr/releases
