### ISSUE TITLE
AutoPkgr not running at scheduled times.

### ISSUE THREAD

**Issue by xconnor9** [lindegroup/autopkgr#630]
Hi there,

So for the past couple of months AutoPkgr would not run at the scheduled time, often fluctuating by a couple hours or so, but it was workable.
Suddenly it has stopped running automatically at all, I have checked the console when adjusting the schedule and it clearly states when the next run is scheduled, however it just never happens. 

I have tried using all three scheduling options to no success, restarted the machine, checked for conflicting applications etc. It's become a real pain and I'm not sure what the problem might be.

I managed to get it to run on schedule once when setting it to run every 1 hour, however it did not run again on the 2nd hour.

Console states:
"Next scheduled AutoPkg run will occur at 29/10/2019, 08:16" etc, however when the time comes, nothing happens, and nothing is caught in the console.

Any ideas? i'm not sure if this is an AutoPkgr issue, or an issue with my system.

Apologies if this is not the best place for this and thank you in advance.

**Comment by shawnhonsberger** [comment]
Hi, can you please share the following details: macOS version, AutoPkgr version, AutoPkg version, Munki or JSSImporter version, and how many accounts are on this macOS device?

**Comment by shawnhonsberger** [comment]
Thanks! A few more:

- Does this run logged in, or logged out? 
- What happens if you:

1. Disable the scheduled run.
2. Reinstall the helper tool by holding down the Option key while clicking the AutoPkgr icon in the menu bar, then choose Reinstall Helper Tool. 
3. Enable and schedule a new run.

**Comment by xconnor9** [comment]
@shawnhonsberger 
The machine is always logged into, however it seems as if autopkgr will not run at all until I connect to the machine and sign back in past the lock screen, which is strange.

I have reinstalled the helper tool (thanks, didn't know about that!)
After enabling a new schedule run, the console picked it up as normal:
"Registered StartCalendarInterval: com.lindegroup.AutoPkgr.schedule.268435477: Friday, November 1, 2019 at 10:00:00 AM Greenwich Mean Time"

Annndddd.... It appears to have run correctly!
I'll schedule in a daily run, and comment again on how it runs over the weekend to make sure its working correctly.

Hopefully it is, cheers for your help Shawn!

**Comment by shawnhonsberger** [comment]
Great news! Thanks, and good luck!

**Comment by xconnor9** [comment]
Hi @shawnhonsberger,

So over the weekend and monday, AutoPkgr ran, however, the runs slowly started to slip from the original scheduled time, and also took a horrendous amount of time to complete.

AutoPkgr was scheduled to run at 8am daily, and ran at the following times instead:
Saturday: 8:38am, finished at 6:43pm
Sunday: 8:50am, finished at 6:55pm
Monday: 9am, finished at 7pm!
Tuesday: 9:12am, finished at 9:53am (but only due to my connecting to the machine via remote desktop to check) This run failed anyways, so not much excitement there.

Looking through the console logs over the weekend, there are large multi hour gaps in between what appears to be the same process for Autopkgr. I imagine a scheduled autopkgr run should not take 10 hours? Any advice?

Cheers!

**Comment by xconnor9** [comment]
Screen sharing even, not remote desktop

**Comment by xconnor9** [comment]
By not allowing the mac server to enter sleep mode, AutoPkgr appears to have run at the correct time today, will monitor it over the next few days and report back.

**Comment by shawnhonsberger** [comment]
Great, thank you!

**Comment by xconnor9** [comment]
It appears that reinstalling the helper and disabling sleep mode has helped.
Thanks!
