### ISSUE TITLE
Cannot pickle Objective-C objects

### ISSUE THREAD

**Issue by vaarr80** [lindegroup/autopkgr#631]
Began receiving the following after updating to Autopkg 1.3 :

A Python exception occurred during the execution of autopkg, see the system log for more details.

[ERROR] TypeError: Cannot pickle Objective-C objects

I have confirmed that I get the same error when I run from Terminal.

**Comment by homebysix** [comment]
This is an upstream issue in AutoPkg 1.3 with JSSImporter installed. Follow this for details: https://github.com/autopkg/autopkg/issues/576
