### ISSUE TITLE
'Get Info' Description text is black w/ app in Dark Mode

### ISSUE THREAD

**Issue by apizz** [lindegroup/autopkgr#633]
When you get info on a recipe with AutoPkgr using dark mode theme, all text is white except for the description.

![Screen Shot 2019-11-08 at 11 13 30 AM](https://user-images.githubusercontent.com/11789931/68491460-e7398a80-0218-11ea-86db-bd3815cdaedf.png)

**Comment by apizz** [comment]
Any updates on this?  This is still an issue on the latest version of AutoPkgr

**Comment by shawnhonsberger** [comment]
Thanks for the report @apizz. This issue has been solved in the code and will be available in a forthcoming version of AutoPkgr. Thank you for your patience! :)

**Comment by apizz** [comment]
Great, thank you!

**Comment by shawnhonsberger** [comment]
Hi @apizz, this should be resolved now in AutoPkgr 1.5.3. Thanks!

AutoPkgr 1.5.3: Darkmode Duck! Check it out at: https://github.com/lindegroup/autopkgr/releases/latest
