### ISSUE TITLE
Error adding repro File "/usr/local/bin/autopkg, line 126

### ISSUE THREAD

**Issue by jacm82** [lindegroup/autopkgr#641]
Hello All, 

we update our computer to Catalina, since them we are having several issues to use Autopkgr. when trying to add repro we got the error showing on the attached image. 

please Helpp!!!!

![Screen Shot 2020-02-11 at 3 43 47 PM](https://user-images.githubusercontent.com/60940926/74268278-5c1fd300-4ce6-11ea-9b79-2ae213d3e6ac.png)

**Comment by homebysix** [comment]
Hi @jacm82 - What versions of AutoPkg and AutoPkgr are you running? Please update to the latest, if you aren't already.

**Comment by jacm82** [comment]
Helo @homebysix i was able to solve the issue by uninstalling [Autopkrg](https://github.com/lindegroup/autopkgr) and Autopkg,  update to the latest version,  and rebooting a couple of time. 

now i have the following issue:

![Screen Shot 2020-02-12 at 7 40 29 AM](https://user-images.githubusercontent.com/60940926/74327908-c595f500-4d6b-11ea-98d5-4c33988872e1.png)

the cache folder update very good, when don't make the transfer from the cache to the server. 

thanks in advance

**Comment by shawnhonsberger** [comment]
Are you trying to run recipes or recipe overrides?

**Comment by ftrojahn** [comment]
Same problem here:
```
Update to core components available:

    AutoPkg 2.0.2 update now available.

The following errors occurred:

    File "/usr/local/bin/autopkg", line 126 log_err(f"WARNING: plist error for {filename}: {err}") ^ SyntaxError: invalid syntax
```

If I run 'autopkg version' the reply is '2.0.2'. So, the "AutoPkg 2.0.2 update now available." might be wrong, too.

**Comment by homebysix** [comment]
@ftrojahn What version of AutoPkgr are you running? AutoPkgr 1.5.1 and earlier is not compatible with AutoPkg 2.

**Comment by shawnhonsberger** [comment]
@jacm82 make sure that you are using [overrides](https://github.com/lindegroup/autopkgr/wiki/Overrides-and-Trust-Info) of the recipes that you wish to use, and then only checking those overrides in your AutoPkgr recipe list. 

@ftrojahn go ahead and upgrade to AutoPkgr 1.5.2 and restart AutoPkgr. 

I'm closing this issue for now. Thank you.
