### ISSUE TITLE
Upgrading AutoPkgr to v1.5.3 broke Slack notifications; reverting does NOT restore functionality

### ISSUE THREAD

**Issue by fseesink** [lindegroup/autopkgr#646]
Subject line says it all.  Upgraded AutoPkgr from 1.5.2 to 1.5.3, and suddenly no longer get Slack notifications.  This appears similar to, though different from, #634 in that when I checked the Slack settings, the webhook was gone!

I thought, "Ok, fine.  The update hosed the URL."  I put it back, then clicked [Send Test], but all I got was
<img width="532" alt="Screen Shot 2020-05-14 at 4 18 36 PM" src="https://user-images.githubusercontent.com/48991/81981754-bdfe1a80-95fe-11ea-8dc3-8e0004087eb4.png">

Huh?  For a Slack webhook?!?  There IS no user name or passphrase!

And once you click [Save and Close], then go into the Slack configuration again, the webhook is gone once again!

So thought maybe it was a coincidence and maybe Slack had done something.  Logged in, dug around, found they now consider the webhook setup I was using as "legacy":

https://api.slack.com/legacy/custom-integrations#migrating_to_apps

So went about making an app to do the same.  Got the new webhook, tried using that in AutoPkgr 1.5.3, but no dice.  Same problem.  Same error dialog.

Then figured, "Screw this. Dark mode is nice, but if I have to choose between dark mode and no notifications vs. a functioning version, I'll just revert."  So I put AutoPkgr 1.5.2 back in place.

Only... nope.  That version is hosed as well.  Whatever this is, it's screwed up my config somehow.

Now I've tried deleting the files in `~/Library/Cache/com.lindegroup.AutoPkgr`, but no help.  There's the one file, `recipe_list.txt` in `~/Library/Application Support/AutoPkgr` but that doesn't look like it should be an issue.  The only file I haven't dared muck with is `~/Preferences/com.lindegroup.AutoPkgr.plist` as I don't want to lose my config.  I've had this setup running quite nicely for nearly a year now without issue.

But could really use some help in sorting this out.

**Comment by shawnhonsberger** [comment]
Hi @fseesink, thanks for the information. This is actually related to the AutoPkgr keychain item. Can you please follow the solution suggested in this closed issue and let me know how it goes? This should resolve it for you, thanks! https://github.com/lindegroup/autopkgr/issues/459

**Comment by fseesink** [comment]
Boo yah!  That worked!  Thanks so much!  Will have to try and remember that one.  Never had that happen before.
