### ISSUE TITLE
Slack notifications not working

### ISSUE THREAD

**Issue by mike6286** [lindegroup/autopkgr#648]
I have the trigger for notifications set to new software is downloaded but when I run a .download recipe it does not send a notification to slack. I am able to send a test notification to slack and test notification template to slack. I've tried multiple combinations including email notifications with slack notifications and every trigger combination. I have this issue on 1.5.1 and 1.5.2. Any help would be greatly appreciated.

**Comment by shawnhonsberger** [comment]
Hi @mike6286. I don't believe that notifications are sent for .download recipes.

**Comment by mike6286** [comment]
<img width="464" alt="Screen Shot 2020-07-28 at 1 58 23 PM" src="https://user-images.githubusercontent.com/54821649/88720864-68ec8380-d0da-11ea-8b26-77760009fa44.png">
Hi @shawnhonsberger , I may been wrong but I assumed since a new software download is a trigger, a notification would be sent for .download recipes.

**Comment by shawnhonsberger** [comment]
In one sense, that is correct. However, I am unsure if it works for .download recipes. Do you have the same issue with .pkg, .munki, or .jss recipes?

**Comment by mike6286** [comment]
Yes I am having the same issue with the .pkg recipe

**Comment by shawnhonsberger** [comment]
Thanks. What happens if you uncheck that, and instead select Any Action?

**Comment by phredman** [comment]
![image](https://user-images.githubusercontent.com/53264882/90177233-4021ea80-dd78-11ea-8dca-387a46f4969a.png)

I'm getting an "User name or passphrase you entered is not correct" issue when trying to drop my incoming webhook link and a botname. Unless I'm missing something - I shouldn't need a passphrase or username with this. right?

**Comment by shawnhonsberger** [comment]
@phredman you'll want to ensure that your Webhook url is correct. If it is correct, you may want to open Keychain Access and look for the AutoPkgr keychain. This is likely related to the AutoPkgr keychain item. Can you please follow the solution suggested in this [issue](https://github.com/lindegroup/autopkgr/issues/459). This should resolve it. If it doesn't, please feel free to open a new issue for this. :)

**Comment by shawnhonsberger** [comment]
@mike6286 What happens if you a) upgrade to AutoPkgr 1.5.4, uncheck **New software is downloaded**, and instead select **Any Action**?
