### ISSUE TITLE
Google Chat Notifications not working for Template Send Example...

### ISSUE THREAD

**Issue by everetteallen** [lindegroup/autopkgr#651]
In Customize Notification Templates on version 1.5.4 (1444) the Send Example does not send anything to Google Chat.  However the Send Test button under Send Notifications to Google Hangouts Channel does work as expected.  Not sure where to look in logs for this.

**Comment by shawnhonsberger** [comment]
Thanks @everetteallen. Is the case the same if you copy and paste the "AutoPkgr Slack Bot" template into the "AutoPkgr Google Hangouts" template and Save?

**Comment by everetteallen** [comment]
Missed that.  After copy/paste of the template works as expected.  Thanks

**Comment by shawnhonsberger** [comment]
Great to hear! Thanks for the update! I'll make sure to update that template in the next version.
