### ISSUE TITLE
UI issue in the Notifications pane

### ISSUE THREAD

**Issue by Prodeguerriero** [lindegroup/autopkgr#652]
Hello there,

Newbie here, getting to know the platform.

Today I managed to get the Google Chat webhook to work! I know, I know, not exactly rocket science. But there seems to be a small issue with the UI 😛 :

<img width="476" alt="Screenshot 2020-07-31 at 19 24 48" src="https://user-images.githubusercontent.com/15149858/89060710-c34c4500-d363-11ea-8e57-1c39b58d78a0.png">

Note that the screenshot is taken from a MacMini running 10.10, to which I connect using Screen Sharing.
My local installation of AutoPkgr doesn't seem to show the same symptom.

Also, I would suggest changing `Google Hangouts` with `Google Hangouts/Chat` as it works with Google Chat as well.

Thanks for the tool, it is really handy :)

**Comment by shawnhonsberger** [comment]
Hi @Prodeguerriero, thanks for the information and suggestion. For the best experience, I would recommend that you run AutoPkgr on macOS 10.13.6 or above. Thanks! :)
