### ISSUE TITLE
Run Recipes Now - Error

### ISSUE THREAD

**Issue by poohomar** [lindegroup/autopkgr#653]
Hello, 
I get the following error when I ran "Run Recipes Now", strange part is it still seemed to work?
In addition, I get this automated email output with tons of error information (see below).

Please advise.

Thank You,
Omar

WARNING: com.github.autopkg.pkg.Skype is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
WARNING: com.github.autopkg.pkg.Firefox_EN is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)>
Failed.

RECIPE | MESSAGE
-- | --
com.github.rtrouton.pkg.microsoftremotedesktop | Error in com.github.rtrouton.pkg.microsoftremotedesktop: Processor: URLDownloader: Error: Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://go.microsoft.com/fwlink/?linkid=868963', '--fail', '--output', '/Users/removed/Library/AutoPkg/Cache/com.github.rtrouton.pkg.microsoftremotedesktop/downloads/tmpndppxbhd', '--header', 'If-None-Match: "7fe2f7467543d61:0"', '--header', 'If-Modified-Since: Tue, 16 Jun 2020 00:30:03 GMT']' returned non-zero exit status 6.
com.github.autopkg.pkg.Thunderbird | Error in com.github.autopkg.pkg.Thunderbird: Processor: URLDownloader: Error: Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://download.mozilla.org/?product=thunderbird-latest&os=osx&lang=en-US', '--fail', '--output', '/Users/removed/Library/AutoPkg/Cache/com.github.autopkg.pkg.Thunderbird/downloads/tmpqtl7yg_2', '--header', 'If-None-Match: "13f20c19cfd6564d613698ede4693c61"', '--header', 'If-Modified-Since: Wed, 01 Jul 2020 03:03:00 GMT']' returned non-zero exit status 6.
com.github.autopkg.pkg.Firefox_EN | Error in com.github.autopkg.pkg.Firefox_EN: Processor: URLDownloader: Error: Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://download.mozilla.org/?product=firefox-latest&os=osx&lang=en-US', '--fail', '--output', '/Users/removed/Library/AutoPkg/Cache/com.github.autopkg.pkg.Firefox_EN/downloads/tmprrgmn3ig', '--header', 'If-None-Match: "05b7e61952885e11f5fb6392c01e851d"', '--header', 'If-Modified-Since: Wed, 03 Jun 2020 03:12:16 GMT']' returned non-zero exit status 6.
com.github.autopkg.pkg.AdobeReaderDC | Error in com.github.autopkg.pkg.AdobeReaderDC: Processor: AdobeReaderURLProvider: Error: Command '['/usr/bin/curl', '--compressed', '--location', '--header', 'x-requested-with: XMLHttpRequest', 'http://get.adobe.com/reader/webservices/json/standalone/?platform_type=Macintosh&platform_dist=OSX&platform_arch=x86-32&platform_misc=10.12.0&language=English&eventname=readerotherversions']' returned non-zero exit status 6.
com.github.autopkg.pkg.FlashPlayerExtractPackage | Error in com.github.autopkg.pkg.FlashPlayerExtractPackage: Processor: AdobeFlashURLProvider: Error: Command '['/usr/bin/curl', '--compressed', '--location', 'http://fpdownload2.macromedia.com/get/flashplayer/update/current/xml/version_en_mac_pl.xml']'returned non-zero exit status 6.
local.pkg.Cyberduck | Error in local.pkg.Cyberduck: Processor: SparkleUpdateInfoProvider: Error: Command '['/usr/bin/curl', '--compressed', '--location', 'https://version.cyberduck.io/changelog.rss']' returned non-zero exit status 6.
local.pkg.GoogleChrome | Error in local.pkg.GoogleChrome: Processor: URLDownloader: Error: Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg', '--fail', '--output', '/Users/removed/Library/AutoPkg/Cache/local.pkg.GoogleChrome/downloads/tmpt1ipy09f', '--header', 'If-None-Match: "638d83"', '--header', 'If-Modified-Since: Fri, 10 Jul 2020 23:47:05 GMT']' returned non-zero exit status 6.
local.pkg.Skype | Parent recipe com.github.autopkg.pkg.Skype contents differ from expected. Path: /Users/removed/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/Skype/Skype.pkg.recipe
local.pkg.MicrosoftSkypeForBusiness365 | Error in local.pkg.MicrosoftSkypeForBusiness365: Processor: URLDownloader: Error: Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://go.microsoft.com/fwlink/?linkid=832978', '--fail', '--output', '/Users/removed/Library/AutoPkg/Cache/local.pkg.MicrosoftSkypeForBusiness365/downloads/tmpy60qziou', '--header', 'If-None-Match: "5561d5b54835d61:0"', '--header', 'If-Modified-Since: Thu, 28 May 2020 23:35:45 GMT']' returned non-zero exit status 6.

**Comment by shawnhonsberger** [comment]
Hi @poohomar you'll want to update your trust info for the recipe overrides you're running. You can update the trust info for a recipe by right-clicking and selecting **Update Trust Info**. You can read about trust info here: https://github.com/lindegroup/autopkgr/wiki/Overrides-and-Trust-Info. Also, which version of AutoPkgr and macOS are you running? If you are using JSSImporter, please share that version as well.

**Comment by poohomar** [comment]
Hello Shawn,

I'm on version 2.1 with 10.15.6, and when I right click on any recipe the only options I'm presented are:
"Run This Recipe Only"
"Get Info"
"Parent Recipe..." (greyed out)
"Create Override".

When I run this command in terminal: "autopkg update-trust-info /Path Location
I get "Didn't find a recipe for /Path Location

Thanks,
poohomar

________________________________

**Comment by shawnhonsberger** [comment]
Hi @poohomar please make sure that you update to AutoPkgr 1.5.4. It appears you are on an out of date version. If you update to 1.5.4, you can update the trust info for a recipe by right-clicking and selecting **Update Trust Info**.
