### ISSUE TITLE
Latest autopkgr show blank screen with no option to configure 

### ISSUE THREAD

**Issue by sumank29** [lindegroup/autopkgr#654]
just installed the autopkrg on the latest mac os and don't see any option to configure further. thinking that it may require autopkg to be installed, hence installed the autopkg but no change. Below is the screensho

![image](https://user-images.githubusercontent.com/43595209/91588371-e6d7c080-e90c-11ea-8bff-6917f8b4233c.png)

**Comment by Prodeguerriero** [comment]
If with latest macOS you mean Catalina and not Big Sur, I can tell you I just went through the exact same process on both a MacBook Air (2015) and a Mac Mini (2012), and it works fine. Just FYI.

**Comment by sumank29** [comment]
> If with latest macOS you mean Catalina and not Big Sur, I can tell you I just went through the exact same process on both a MacBook Air (2015) and a Mac Mini (2012), and it works fine. Just FYI.

What is the exact process which you followed? I just installed the pkgr do we need to execute anything else

**Comment by sumank29** [comment]
i am really not sure and now getting fed up with autopkgr - did lot of searching but did find any help to fix this blank screen issue. I installed now git, autpkg  and jss importer manually tried to remove reinstall not luck, not idea were to search and what to do

**Comment by shawnhonsberger** [comment]
Thanks @sumank29. Try moving the ~/Library/Preferences/com.github.autopkg.plist temporarily to the Desktop, and then relaunch AutoPkgr.

**Comment by sumank29** [comment]
WOW is just worked fine and Thanks for making my day @shawnhonsberger  :) , just crusity how it just got fixed after moving file at desktop

**Comment by shawnhonsberger** [comment]
Great news @sumank29! You're welcome! At times, there are configurations of AutoPkg preferences that can tend to confuse AutoPkgr.

**Comment by M0hanRavichandran** [comment]
Hey @shawnhonsberger I have the same issue. I can able to install the app in my Macbook Pro and it works like a charm. Unfortunately, not in MacBook Air (2018) running on 10.15.6 like a fresh OS.

I couldn't able to find that .plist in the library folder. Any chance you can assist me in this ?
