### ISSUE TITLE
AutoPKGr Notification for errors occured String splitting

### ISSUE THREAD

**Issue by TK5-Tim** [lindegroup/autopkgr#658]
Independent from the way of notification (mail, Slack, etc.) the notification for "the following errors occurred" always appear as one String. If several Errors occur on the same AutoPKGr run the are all smashed together and not so easy to distinguish. 
It would be helpful if there would be a line break in for every error like it is for example for the Software downloaded. 
I tried to change the mail template to make it work but it seems like the variable for errors does not support splitting them in lines. 

As an example: 
How it currently looks:
```
Could not find parent recipe for ch.unibas.its.git.mcs.munki.CiscoWebexMeetings No valid recipe found for ch.unibas.its.git.mcs.munki.CiscoWebexMeetings WARNING: ch.unibas.its.git.mcs.munki.PasswordSafe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
```

How it would be helpful to look like: 
```
Could not find parent recipe for ch.unibas.its.git.mcs.munki.CiscoWebexMeetings
No valid recipe found for ch.unibas.its.git.mcs.munki.CiscoWebexMeetings 
WARNING: ch.unibas.its.git.mcs.munki.PasswordSafe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
```

**Comment by shawnhonsberger** [comment]
Thanks @TK5-Tim, I'll look into this.
