### ISSUE TITLE
Odd Download Recipe Error only occurs with new download - HPPrinterDrivers.munki

### ISSUE THREAD

**Issue by apizz** [lindegroup/autopkgr#661]
I recently filed this issue (https://github.com/autopkg/n8felton-recipes/issues/135) but am filing it here as well due to download behavior that appears to be an issue only with AutoPkgr.  Mac is running 10.15.7, autopkg 2.2, AutoPkgr is 1.5.5

We have AutoPkgr daily run through a recipe list.  Additionally, we have a separate mechanism which automatically removes any pkgs, dmgs, etc. that are older than 7 days from our autopkg cache to avoid the unnecessary accumulation of files that may include unique versions in the file name.

Recently, our auto removal mechanism deleted an old HP driver install pkg.  As a result, the downloads folder in our Cache directory for the recipe override was empty.  When the recipe runs as part of the scheduled run w/ AutoPkgr it fails.  Also fails on individually triggered runs via AutoPkgr, leaving a temporary file behind of what it had attempted to download.  

Interestingly, running the same recipe on the same autopkg box but solely with the `autopkg` binary and entirely separate from AutoPkgr _does not_ produce the same error.  Simply `curl`ing the collected URL from the recipe in a Terminal w/o any arguments except to output to a file completes just fine as well.

![Screen Shot 2021-02-13 at 6 25 57 PM](https://user-images.githubusercontent.com/11789931/107864712-ef757200-6e2c-11eb-8245-ec5d516cfe8d.png)

Once the recipe completes and the now cached PKG file is in the downloads folder, subsequent AutoPkgr-based runs of the same recipe do not produce any failures.  I'm not clear how the same recipe on the same box run within roughly the same time period would fail with AutoPkgr but not with `autopkg`.

Let me know if there is additional info that would be helpful to troubleshoot this.

**Comment by apizz** [comment]
To be clear, I've not run into this particular issue with other recipe overrides where the downloads folder in a recipe cache folder is empty.

**Comment by shawnhonsberger** [comment]
Thank you, @apizz. Do you have a proxy in place? Does this issue occur with AutoPkgr 1.5.4?

**Comment by apizz** [comment]
Testing now ...

**Comment by apizz** [comment]
Interesting, this does _not_ occur with 1.5.4.

**Comment by shawnhonsberger** [comment]
Thank you. Is this the only recipe where this occurs in 1.5.5?

**Comment by apizz** [comment]
Yes.  Per convo in https://github.com/autopkg/n8felton-recipes/issues/135, think this is in part due to fact that distribution is via `ftp://`

**Comment by shawnhonsberger** [comment]
Hmm.. So interesting. I think I understand the issue with the recipe, but I can't say I know why one would display, and not the other.

**Comment by apizz** [comment]
Not sure if you made any changes here, but after testing again several times with 1.5.6 I can no longer reproduce this issue with an existing or removed download.

**Comment by shawnhonsberger** [comment]
Great news, thanks @apizz!
