### ISSUE TITLE
AutoPkgr 1.5.6 - forgets that VirusTotalAnalyzer is installed

### ISSUE THREAD

**Issue by apizz** [lindegroup/autopkgr#665]
On previous versions, had installed the `VirusTotalAnalyzer` plugin.  Upon launch, indicated that it was not installed.  Clicking install caused it to be marked as installed.

Quitting & reopening and once again shows as uninstalled. Confirmed repo is present before & after quit and relaunch
![Screen Shot 2021-02-23 at 5 31 45 PM](https://user-images.githubusercontent.com/11789931/108917006-11c17980-75fd-11eb-883b-3a012c07b2e1.png)

![Screen Shot 2021-02-23 at 5 30 49 PM](https://user-images.githubusercontent.com/11789931/108916896-ec347000-75fc-11eb-81b8-ef460ba13e9b.png)

**Comment by ofirgalcon** [comment]
+1

**Comment by apizz** [comment]
After updating to autopkg 2.3 get the following error message which may shed additional light on the issue:

![Screen Shot 2021-03-01 at 10 31 07 PM](https://user-images.githubusercontent.com/11789931/109592887-0af3a480-7ade-11eb-9666-014af7c17019.png)

**Comment by dev-yeet** [comment]
getting the same error after updating to 2.3

**Comment by apizz** [comment]
This is still an issue with autopkg 2.3.1 & AutoPkgr 1.5.6

**Comment by shawnhonsberger** [comment]
Hi @apizz, @dev-yeet, and @ofirgalcon. This should be resolved in today's 1.5.7 release. Thanks for your help and patience! https://github.com/lindegroup/autopkgr/releases/latest

**Comment by apizz** [comment]
Confirmed resolved!  TY @shawnhonsberger !
