### ISSUE TITLE
Feature request: Add Make Override option for YAML-formatted recipe

### ISSUE THREAD

**Issue by apizz** [lindegroup/autopkgr#667]
Support for YAML recipes (`.recipe.yaml`) was added with autopkg 2.3.

**Comment by homebysix** [comment]
Some context: this would involve adding an optional `--format=yaml` argument to the [`make-override` call](https://github.com/lindegroup/autopkgr/blob/d6dfcdbe5cc5f9fc9f37798964984d3519866c7e/AutoPkgr/Models/AutoPkg%20Task/LGAutoPkgTask.m#L1004) somehow.

```
% autopkg make-override -h
Usage: autopkg make-override [options] [recipe]
Create a skeleton override file for a recipe. It will be stored in the first default override directory or that given by '--override-dir'

Options:
  -h, --help            show this help message and exit
  --prefs=FILE_PATH     
  -d DIRECTORY, --search-dir=DIRECTORY
                        Directory to search for recipes. Can be specified
                        multiple times.
  --override-dir=DIRECTORY
                        Directory to search for recipe overrides. Can be
                        specified multiple times.
  -n FILENAME, --name=FILENAME
                        Name for override file.
  -f, --force           Force overwrite an override file.
  -p, --pull            Pull the parent repos if they can't be found in the
                        search path. Implies agreement to search GitHub.
  --ignore-deprecation  Make an override even if the specified recipe or one
                        of its parents is deprecated.
  --format=FORMAT       The format of the recipe override to be created. Valid
                        options include: 'plist' (default) or 'yaml'
```

**Comment by apizz** [comment]
Yes, thank you for clarifying.  I've been bouncing around all day so was lazy on the details when I filed. Thanks for filing the gap @homebysix

**Comment by jazzace** [comment]
I'd go one step further. I think you need to let the user select what kind of override they want (plist or yaml). For example, I have decided that I am more comfortable with XML plists, so even if I override a YAML recipe, I want the override to be a plist. If you don't specify format, `make-override` will generate an XML plist. So I think AutoPkgr's Create Override option should either be two commands (Create Plist Override and Create YAML Override) or the dialog box that asks about giving the recipe a unique name should also allow the user to select plist or YAML and name the file accordingly (currently `.recipe.yaml` but that might change — see [autopkg/#767](https://github.com/autopkg/autopkg/issues/767)).

**Comment by shawnhonsberger** [comment]
Hi Everyone. Due to the fact that there is no native YAML library for macOS, AutoPkgr does not support `.yaml` recipes and they will not display in the recipe list. However, AutoPkgr will be able to run any recipe you like via your recipe list (even if those recipes are `.yaml` and are added to your recipe list manually, or have parent recipes that are `.yaml`). AutoPkgr's recipe list is stored at `~/Library/Application Support/AutoPkgr/recipe_list.txt` and can be edited with any text editor.
