### ISSUE TITLE
"AutoPkgr" needs to be updated warning macOS Monterey

### ISSUE THREAD

**Issue by lifeunexpected** [lindegroup/autopkgr#674]
Im getting this warning message when trying to open AutoPkgr on macOS Monterey for the first time and it then sends you too https://www.python.org/doc/sunset-python-2/.
So the python part of the code might need to be updated to python 3 or is it some left over python 2 code maybe?
I dont now i just wanted to open a issue ticket regarding it so maybe somebody with the correct skills could take a look.

<img width="251" alt="Screenshot 2021-11-02 at 22 42 51" src="https://user-images.githubusercontent.com/36742392/139956165-bc3b55e0-6211-47aa-968a-d5c50e68d78a.png">

**Comment by shawnhonsberger** [comment]
Thanks, @lifeunexpected. Which version of AutoPkg do you have installed? If you're using AutoPkg 2.0 and above, AutoPkg, and thus AutoPkgr should be using Python 3 that ships with AutoPkg.
