### ISSUE TITLE
Fresh install Monterey and Autopkgr2.3.1 not in applications

### ISSUE THREAD

**Issue by Lazzas** [lindegroup/autopkgr#676]
Hi have installed a fresh install Monterey and Autopkgr2.3.1 however the launcher is not in applications not in applications. Any ideas?

Thanks

Larry

**Comment by homebysix** [comment]
Hi @Lazzas - When you say "the launcher is not in applications," what specifically does that mean?

**Comment by Lazzas** [comment]
I can't configure it because the autopkgr is not in applications. I tried
it on my other computer running Bigsur and got the same result. If I
download a pre V2 version I can drag it into the applications folder then
upgrade it however it then has python script errors when loading a repo.

**Comment by homebysix** [comment]
Might you be confusing autopkg (command line tool, latest version 2.3.1) with AutoPkgr (Mac app, latest version 1.5.7)? The latter is installed into /Applications, the former is not.

**Comment by Lazzas** [comment]
I was yes.

**Comment by homebysix** [comment]
If you start with the Installation and Basic Usage steps in the [AutoPkgr read me](https://github.com/lindegroup/autopkgr#installation), you should be all set. Step 3 covers installation of autopkg via the AutoPkgr app.

**Comment by Lazzas** [comment]
Thanks.
