### ISSUE TITLE
Send notifications to Microsoft Teams channel broken

### ISSUE THREAD

**Issue by kfattic** [lindegroup/autopkgr#688]
When entering a Webhook URL for Microsoft Teams, an error message stating 'The user name or passphrase you entered is not correct' appears
![Screen Shot 2022-07-20 at 8 27 43 AM](https://user-images.githubusercontent.com/6775519/179994312-24ed3a4a-ec03-4c5b-8953-ee724f430c11.png)
.

**Comment by kfattic** [comment]
![Screen Shot 2022-07-20 at 1 55 34 PM](https://user-images.githubusercontent.com/6775519/180060851-a392c659-eda6-48b6-a448-9877ea7895e3.png)

**Comment by shawnhonsberger** [comment]
Hi @kfattic. If your Webhook url is correct, you may want to open Keychain Access and look for the AutoPkgr keychain. This is likely related to the AutoPkgr keychain item. Can you please follow the solution suggested in this [issue](https://github.com/lindegroup/autopkgr/issues/459)? This should resolve it. If it doesn't, please feel free to open a new issue for this. 🙂

1. Delete the AutoPkgr.keychain from Keychain access.
2. Quit Keychain access.
3. Reenter the Teams webhook and select Save & Close.
4. Go back into keychain access and see if the Keychain was successfully re-created and that there's an entry for AutoPkgr Teams Bot.

**Comment by kfattic** [comment]
There is!  Thank you much!  Issue resolved!
