### ISSUE TITLE
Connection to SIMPLEMDM REPO and Progress 

### ISSUE THREAD

**Issue by jalsaman** [lindegroup/autopkgr#690]
The SIMPLEMDM repo plugin is installed.
But when an override recipe is executed there is no progress bar or any log of what's happening in the background to trace what's happening and if it fails also there is no notification. 

The SIMPLEMDM integration should be more robust and should indicate a good log of what's happening.

**Comment by homebysix** [comment]
Hi @jalsaman. Have you already enabled [verbose logging](https://github.com/lindegroup/autopkgr/wiki/Troubleshooting#step-3-check-the-logs), and if so, what are you seeing there?

**Comment by jalsaman** [comment]
Hi Elliot,

I have enabled it now.

Where can I read the logs

[cid:DBB5286D-F5C3-4AC7-89A4-6E6E1CAE58F8]

On 20. Aug 2022, at 18:41, Elliot Jordan ***@***.******@***.***>> wrote:



Hi @jalsaman<https://github.com/jalsaman>. Have you already enabled verbose logging<https://github.com/lindegroup/autopkgr/wiki/Troubleshooting#step-3-check-the-logs>, and if so, what are you seeing there?

**Comment by homebysix** [comment]
Your question is answered on the same wiki page. Use the provided `log` command.

**Comment by shawnhonsberger** [comment]
Thanks @homebysix!
