### ISSUE TITLE
Always yellow indicator on Munki tools update

### ISSUE THREAD

**Issue by opus-nbo** [lindegroup/autopkgr#694]
The "Installation" Pane in AutoPkgr always displays a yellow indicator and a information about an update being available, even if the newest version of Munki tools was installed directly over AutoPkgr. A reboot of the machine does not change that.

Running AutoPkgr 1.6 on macOS 12.6

**Comment by rquigley-aus** [comment]
I can confirm I am having this issue in my environment as well.

Manually downloading and installing Munki Tools and quitting and reopening Autopkgr doesn't resolve the issue.

**Comment by homebysix** [comment]
This is a known issue when the version of `makecatalogs` installed is less than the Munki "metapackage" version. Current Munki versions are listed on the v6.0 release notes:

> **Package versioning**
> metapackage version: 6.0.0.4520
> munki core tools version: 6.0.0.4501
> LaunchAgents/LaunchDaemons version: 3.0.3265
> Apps package version: 6.0.0.4520
> Python package version: 3.9.13.4518

Best course of action is to ignore the yellow indicator for now.

See: https://github.com/lindegroup/autopkgr/issues/493, https://github.com/lindegroup/autopkgr/issues/595, https://github.com/munki/munki/issues/789

**Comment by jelockwood** [comment]
@homebysix 
Hi, yes I know this is a known issue as per your explanation in this issue. (And others.)

However this does regularly happen with AutoPkgr and Munki. Is there no way you can build in a more effective/different version check mechanism specifically for checking the Munki Tools? Perhaps by checking both the makecatalogs and metapackage versions separately even if your user interface does not display this. Or only checking the metapackage version and not the makecatalogs version.
