### ISSUE TITLE
Slack notifications not working

### ISSUE THREAD

**Issue by jaltonen** [lindegroup/autopkgr#695]
v1.6 on macos 12.6
the test notification works
the template notification works
no notifications on events
tried any action, tried checking the boxes individually.
nothing.

**Comment by shawnhonsberger** [comment]
Hi @jaltonen thanks. I'd recommend to start that you select "Any action" for notifications, then select your recipe overrides you plan to run in the Recipes tab, and select "Run Recipes." Do you still receive no notifications? What tool are you using AutoPkgr with e.g. JamfUploader, Munki, etc?

**Comment by jaltonen** [comment]
I have any action selected.

I select a recipe override and run only that recipe.

its a .munki recipe

I can see the pkg and the pkginfo show up in my repo as the run occurs.

I get an, error running recipes makecatalogs failed, dialog on the machine running autopkg because there are warnings about mismatched cases in some of the pkginfos in my munki repo.

 I get no slack notifications.

The software from the recipe is being added to the repo.

So I would think I would get a notification for the addition and the error/warning on the makecatalogs.

**Comment by jaltonen** [comment]
Ok.  I see now.
Running them from right click run only this recipe does not trigger the notification.
It works when I check the boxes and press the run recipes now button.

Thanks
