### ISSUE TITLE
AutoPkgr on macOS Ventura showing blank GUI

### ISSUE THREAD

**Issue by roratonet** [lindegroup/autopkgr#696]
On new AutoPkgr installation the GUI is not visible. The application starts and is showing up, but without any content.

Tested with
- macOS Ventura 13.0 Public Release and Mac Mini M1
- macOS Monterey 12.6 and MacBook Pro 2019 (Intel)

**Comment by roratonet** [comment]
https://github.com/lindegroup/autopkgr/issues/679

**Comment by rsaeks** [comment]
Ran into this issue today as well. Might be worthwhile to add into the Wiki page for installation to make sure Autopkg is installed prior:

https://github.com/lindegroup/autopkgr/wiki/Initial-Setup
