### ISSUE TITLE
Enhancement Request: Old content cleanup

### ISSUE THREAD

**Issue by rsaeks** [lindegroup/autopkgr#698]
It would be a nice enhancement to have an option to keep the previous X versions of an app to help cleanup content from previous runs automatically.

**Comment by shawnhonsberger** [comment]
Hi @rsaeks, thanks! This would actually need to be a part of the [AutoPkg](https://github.com/autopkg/autopkg) command line utility in order for AutoPkgr to perform it, as AutoPkgr is just a GUI wrapper for AutoPkg. Depending on your tool of choice e.g. Munki, Jamf, there are a few open source repo cleanup options out there. Have a great day, thanks!
