### ISSUE TITLE
"SyntaxWarning: "is not" with a literal." Errors when doing anything in AutoPkgr

### ISSUE THREAD

**Issue by jaleksiewicz** [lindegroup/autopkgr#700]
Hello I am receiving the following errors when trying to do anything within AutoPkgr. Examples include: adding a repo, refreshing repos, running recipes, etc. 

Please see the attached screenshot. I dont understand what this error means.

trying to add a repo I get: 

/Library/AutoPkg/JSSImporter/jss/auth.py:61: SyntaxWarning: "is not" with a literal. Did you mean "!="?
if r.status_code is not 401:

/Library/AutoPkg/JSSImporter/jss/jssobject.py:959: SyntaxWarning: "is not" with a literal. Did you mean "!="?
return len([device for device in self.findall(container_search) if

<img width="954" alt="2023-02-27_15-33-48" src="https://user-images.githubusercontent.com/115664820/221683114-d98eabec-6ca6-49f5-a4ca-868063399970.png">

**Comment by homebysix** [comment]
Looks like you're using JSSImporter, which is deprecated and no longer planning bug fixes. Please review the [JSSImporter wiki](https://github.com/jssimporter/JSSImporter/wiki) for alternatives.

**Comment by jaleksiewicz** [comment]
oh wow was that all it was? Now I feel really silly
