### ISSUE TITLE
Errors in Autopkg

### ISSUE THREAD

**Issue by lfo726** [lindegroup/autopkgr#702]
The following errors occurred:
- Could not find parent recipe for org.bitbucket.bonialgroup.autopkg_bonial.recipes.jamf.MicrosoftEdge_Bonial
No valid recipe found for org.bitbucket.bonialgroup.autopkg_bonial.recipes.jamf.MicrosoftEdge_Bonial
WARNING: org.bitbucket.bonialgroup.autopkg_bonial.recipes.jamf.GIMP_Bonial is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
curl: (35) error:06FFF089:digital envelope routines:CRYPTO_internal:bad key length
WARNING: org.bitbucket.bonialgroup.autopkg_bonial.recipes.jamf.Rectangle_Bonial is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
curl: (22) The requested URL returned error: 403
Failed.
WARNING: org.bitbucket.bonialgroup.autopkg_bonial.recipes.jamf.TeamViewer_Bonial is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
WARNING: org.bitbucket.bonialgroup.autopkg_bonial.recipes.jamf.PDFsam_Bonial is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
WARNING: org.bitbucket.bonialgroup.autopkg_bonial.recipes.jamf.Word_Bonial is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
WARNING: org.bitbucket.bonialgroup.autopkg_bonial.recipes.jamf.VisualStudioCode_Bonial is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
WARNING: org.bitbucket.bonialgroup.autopkg_bonial.recipes.jamf.Teams_Bonial is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
WARNING: org.bitbucket.bonialgroup.autopkg_bonial.recipes.jamf.TeamViewerQuickSupport_Bonial is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
WARNING: org.bitbucket.bonialgroup.autopkg_bonial.recipes.jamf.Spotify_Bonial is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
WARNING: org.bitbucket.bonialgroup.autopkg_bonial.recipes.jamf.Spectacle_Bonial is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
WARNING: org.bitbucket.bonialgroup.autopkg_bonial.recipes.jamf.Slack_Bonial is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
Failed local trust verification.
WARNING: org.bitbucket.bonialgroup.autopkg_bonial.recipes.jamf.Powerpoint_Bonial is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
WARNING: org.bitbucket.bonialgroup.autopkg_bonial.recipes.jamf.Outlook_Bonial is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
WARNING: org.bitbucket.bonialgroup.autopkg_bonial.recipes.jamf.OneNote_Bonial is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
WARNING: org.bitbucket.bonialgroup.autopkg_bonial.recipes.jamf.OneDrive_Bonial is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
WARNING: org.bitbucket.bonialgroup.autopkg_bonial.recipes.jamf.GoogleChrome_Bonial is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
WARNING: org.bitbucket.bonialgroup.autopkg_bonial.recipes.jamf.Firefox_Bonial is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
WARNING: org.bitbucket.bonialgroup.autopkg_bonial.recipes.jamf.Excel_Bonial is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
WARNING: org.bitbucket.bonialgroup.autopkg_bonial.recipes.jamf.Cyberduck_Bonial is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...

[11:08](https://bonial.slack.com/archives/D039GG7BSV7/p1693904926205169)
WARNING: org.bitbucket.bonialgroup.autopkg_bonial.recipes.jamf.CitrixWorkspace_Bonial is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
WARNING: org.bitbucket.bonialgroup.autopkg_bonial.recipes.jamf.AdobeCreativeCloud_Bonial is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
WARNING: org.bitbucket.bonialgroup.autopkg_bonial.recipes.jamf.AdobeAcrobatReader_Bonial is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
WARNING: org.bitbucket.bonialgroup.autopkg_bonial.recipes.jamf.BBEdit_Bonial is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...

**Comment by shawnhonsberger** [comment]
Thanks, @lfo726. Make sure to check out the AutoPkg Wiki regarding [trust info](https://github.com/autopkg/autopkg/wiki/AutoPkg-and-recipe-parent-trust-info). It is also recommended to create recipe overrides of the recipes you'd like to run - these will also contain trust info baked-in.
