### ISSUE TITLE
Specific version of application

### ISSUE THREAD

**Issue by poohomar** [lindegroup/autopkgr#703]
Hello,

If this has been asked, please forgive me.

Is there a way to download previous versions of an application, for example Google Chrome.

117.0.5938.9247 Lastest version
117.0.5938.88 - previous version, is there a way I can download this one instead.

Thanks for taking the time to look at this!

Omar

**Comment by shawnhonsberger** [comment]
Thanks @poohomar. This is not currently a feature of AutoPkg, which AutoPkgr relies on for most recipe functionality.
