### ISSUE TITLE
Github recipe search not working

### ISSUE THREAD

**Issue by opus-nbonenberger** [lindegroup/autopkgr#705]
When i search for a recipe in AutoPkgr in the Repos & Recipes Tab, there is an error displayed below the input field: 

> Error encountered searching for recipes

This does not work for quite a while. Is it just me or is it broken?

**Comment by homebysix** [comment]
This is an [upstream issue](https://github.com/autopkg/autopkg/issues/710) in AutoPkg. You will need to search for recipes on github.com for the time being. Stay tuned to the linked issue for developments.
