### ISSUE TITLE
Add option to change which user AutoPkgr runs as

### ISSUE THREAD

**Issue by diwanicki** [lindegroup/autopkgr#71]
Account which is used to configure in the GUI may not necessarily be the account in which the daemon should run...

**Comment by homebysix** [comment]
Now that 1.2 runs as a LaunchDaemon, is this still necessary @diwanicki ?

**Comment by homebysix** [comment]
Given that AutoPkg has always been designed to run as the currently logged in user, I think AutoPkgr should follow suit. I'm inclined not to pursue this farther.
