### ISSUE TITLE
Error kLGErrorKeychainAccessDescription - kLGErrorKeychainAccesssuggestion

### ISSUE THREAD

**Issue by Shaun-RDP** [lindegroup/autopkgr#714]
I am receiving the error message kLGErrorKeychainAccessDescription - kLGErrorKeychainAccesssuggestion after updating AutoPkgr this morning when it tries to send the notification to Teams.  I tried refreshing the Webhook URL but it gives the same error, it worked last night so I know it was a result of the update.

**Comment by shawnhonsberger** [comment]
Hi @Shaun-RDP. Thank you! I would try the following, as it is related to the AutoPkgr keychain item mentioned [here](https://github.com/lindegroup/autopkgr/issues/459), and let me know how it goes.

1. Delete the AutoPkgr.keychain from Keychain access.
2. Quit Keychain access.
3. Re-enter the Slack webhook and select Save & Close.
4. Go back into keychain access and see if the Keychain was successfully re-created and that there's an entry for AutoPkgr Slack Bot.

**Comment by Shaun-RDP** [comment]
I was able to delete the common AutoPkgr keychain but the AutoPkgr Microsoft Teams keychain asks for a Keychain password.  My Admin password is not accepted, and I have no idea what it would have created for the keychain password.  Removing the common keychain did not correct it.

![AutoPkgr](https://github.com/lindegroup/autopkgr/assets/143025700/a101d91c-1896-4672-8142-aeae29a61e4f)

**Comment by shawnhonsberger** [comment]
@Shaun-RDP after you deleted your AutoPkgr keychain, did you quit Keychain Access? That is just a standard Keychain Access prompt. You shouldn't need to interact with it. AutoPkgr is the owner of it.

**Comment by Shaun-RDP** [comment]
I closed Keychain Access, it still would not accept it.  I restarted the Mac and it still gives the same error.  I have even now reset default keychain and removed the AutoPkgr Teams keychain, restarted the Mac and still get the error.

**Comment by shawnhonsberger** [comment]
There is no need to reset the whole keychain. So when you are removing the AutoPkgr Keychain item, are you removing the AutoPkgr keychain, or the Teams bot keychain item? It should be the AutoPkgr keychain.

1. Delete the AutoPkgr.keychain from Keychain access.
2. Quit Keychain access.
3. Re-enter the Teams webhook and select Save & Close.
4. Go back into keychain access and see if the Keychain was successfully re-created and that there’s an entry for AutoPkgr Teams Bot.

I’ve just tested this and it works. If these steps do not work for you, hold the **Option** key and select **Reinstall Helper Tool** in the AutoPkgr item in the Menu bar, then repeat the steps.

**Comment by Shaun-RDP** [comment]
I got it working.  I had to goto `~/library/keychains` and manually remove the `AutoPakgr.keychain` and I deleted the `/var/db/.AutopkgrKeys` as it was not letting me remove it using Keychain Access.

**Comment by shawnhonsberger** [comment]
Ah, okay, thanks for the heads up! More importantly, I'm glad you got it working! Great news. 👍

**Comment by flammable** [comment]
Just commenting here that I encountered a similar issue - I had email notifications enabled in AutoPkgr 1.6, but received the same error message in 1.6.1 when I attempted to send a test email.

I was able to delete the AutoPkg keychain via Keychain Access, but in order to recreate it, Reinstall Helper Tool was the only thing that worked. I'm back up and running now. Thanks!

**Comment by inglenny** [comment]
I had the same issue as @flammable 

For everyone like me, who does not know how to use "Reinstall Helper Tool":

> You can reinstall Helper Tool by holding Option while clicking on the AutoPkgr icon in the menu bar, then clicking Reinstall Helper Tool. You will be prompted twice for your password.

I also had to remove the preferences file for autopkg to recreate the file: `~/Library/Preferences/com.lindegroup.AutoPkgr.plist`

Then after reentering the mail data in the fields recreated the Autopkgr keychain
