### ISSUE TITLE
Installation is not clean please help

### ISSUE THREAD

**Issue by ghost** [lindegroup/autopkgr#715]
Hello 
after installing AutoPkgr I only get this window.
I have the new operating system of MacOS
![Bildschirmfoto 2024-07-05 um 12 13 12](https://github.com/lindegroup/autopkgr/assets/174793295/e78ccbeb-06e1-4405-9fbc-033ac591c1eb)

**Comment by shawnhonsberger** [comment]
Hi @Tuga0muc please review the Wiki, or the [Releases](https://github.com/lindegroup/autopkgr/releases) page. You need to install AutoPkg first:

> - Due to the fact that macOS no longer ships with Python, you will now need to install [AutoPkg](https://github.com/autopkg/autopkg/releases) first on new Macs before installing AutoPkgr. This gives AutoPkgr the path to Python it needs to run smoothly. If you already have AutoPkg installed, you already have the built in Python that ships with AutoPkg and can just install AutoPkgr.
