### ISSUE TITLE
Teams Workflows - Webhooks are depreciated

### ISSUE THREAD

**Issue by Shaun-RDP** [lindegroup/autopkgr#716]
With Teams depreciating Webhooks, they have pushed everyone to use Workflows.  When I tried to create a workflow to connect the Webhook output to it fails.  After doing some research it appears that the incoming information is not compatible with the format that it is looking for.  Has anyone had success changing their Workflow to accommodate the Webhook data?

**Comment by kfattic** [comment]
I just had to update mine and I think they will start working again.  With that said, I get an error when trying to test in Autopkgr.

https://learn.microsoft.com/en-us/microsoftteams/m365-custom-connectors#update-connectors-url

![image](https://github.com/user-attachments/assets/f646e4a9-231f-4e55-9e93-68e867fda82a)

**Comment by shawnhonsberger** [comment]
Thank you @Shaun-RDP and @kfattic. @kfattic After you option-click the menu icon and reinstall the Helper Tool, do you still receive the error? That error is related to the helper tool's inability to access the Keychain. @Shaun-RDP does @kfattic's solution work for you?

**Comment by kfattic** [comment]
Reinstallation of the tool worked successfully for me.  Thanks!

**Comment by shawnhonsberger** [comment]
Great, thanks!
