### ISSUE TITLE
AutoPkgr no longer sending email notifications - keychain issue?

### ISSUE THREAD

**Issue by jelockwood** [lindegroup/autopkgr#717]
@homebysix 
We have previously setup (successfully) AutoPkgr to send email notifications via a Microsoft365 email account. This means we did sort out the per-app security to enable this. I am running AutoPkgr 1.6.1.

I have noticed that more recently it has stopped sending emails. Trying to use the test option in AutoPkgr results in the following error dialog.
![Screenshot 2024-07-19 at 09 55 45](https://github.com/user-attachments/assets/1ceb5e7b-9554-45b4-b8b1-7a12822a49fd)
The message seems to suggest a Keychain issue although historically I regard password, port connectivity or Microsoft365 security as more common causes.

I have run Console whilst repeating the Test option and here is an extract of the log with what I believe to be the relevant section of entries.

```
default	09:50:22.347645+0100	runningboardd	Calculated state for app<application.com.lindegroup.AutoPkgr.129714508.129714782(502)>: running-active (role: UserInteractiveFocal)
default	09:50:23.707528+0100	com.lindegroup.AutoPkgr.helper	[ERROR] The codesigning signature of one of the following items could not be verified. If either of the following messages displays NULL, please quit AutoPkgr, and manually remove the helper tool binary at /Library/PrivilegedHelperTools/com.lindegroup.AutoPkgr.helper.
default	09:50:23.708399+0100	com.lindegroup.AutoPkgr.helper	[ERROR] AutoPkgr codesign stats: In-memory binary, signed by The Linde Group Computer Support Inc, located at: /Applications/AutoPkgr.app
default	09:50:23.709089+0100	com.lindegroup.AutoPkgr.helper	[ERROR] Helper Tool codesign stats: In-memory binary, signed by The Linde Group Computer Support Inc, located at: /Library/PrivilegedHelperTools/com.lindegroup.AutoPkgr.helper
default	09:50:23.709538+0100	com.lindegroup.AutoPkgr.helper	Error creating xpc connection...
default	09:50:23.710206+0100	AutoPkgr	[DEBUG] Couldn’t communicate with a helper application.
default	09:50:23.734532+0100	com.lindegroup.AutoPkgr.helper	[ERROR] The codesigning signature of one of the following items could not be verified. If either of the following messages displays NULL, please quit AutoPkgr, and manually remove the helper tool binary at /Library/PrivilegedHelperTools/com.lindegroup.AutoPkgr.helper.
default	09:50:23.735071+0100	com.lindegroup.AutoPkgr.helper	[ERROR] AutoPkgr codesign stats: In-memory binary, signed by The Linde Group Computer Support Inc, located at: /Applications/AutoPkgr.app
default	09:50:23.735620+0100	com.lindegroup.AutoPkgr.helper	[ERROR] Helper Tool codesign stats: In-memory binary, signed by The Linde Group Computer Support Inc, located at: /Library/PrivilegedHelperTools/com.lindegroup.AutoPkgr.helper
default	09:50:23.735915+0100	com.lindegroup.AutoPkgr.helper	Error creating xpc connection...
default	09:50:23.736299+0100	AutoPkgr	[DEBUG] Couldn’t communicate with a helper application.
default	09:50:23.736478+0100	AutoPkgr	[DEBUG] Error [11]: kLGErrorKeychainAccessDescription 
 kLGErrorKeychainAccessSuggestion
default	09:50:23.736577+0100	AutoPkgr	[DEBUG] SMTP credentials retrieved.
default	09:50:23.736617+0100	AutoPkgr	There was a problem getting the SMTP credentials: Error Domain=AutoPkgr Code=11 "kLGErrorKeychainAccessDescription" UserInfo={NSLocalizedDescription=kLGErrorKeychainAccessDescription, NSLocalizedRecoverySuggestion=kLGErrorKeychainAccessSuggestion}
default	09:50:23.736682+0100	AutoPkgr	Error sending email: Error Domain=AutoPkgr Code=11 "kLGErrorKeychainAccessDescription" UserInfo={NSLocalizedDescription=kLGErrorKeychainAccessDescription, NSLocalizedRecoverySuggestion=kLGErrorKeychainAccessSuggestion}
default	09:50:27.052018+0100	runningboardd	Invalidating assertion 186-145-373192 (target:[app<application.com.lindegroup.AutoPkgr.129714508.129714782(502)>:20125]) from originator [daemon<com.apple.coreservices.launchservicesd>:145]
default	09:50:27.061225+0100	runningboardd	Invalidating assertion 186-178-373193 (target:[app<application.com.lindegroup.AutoPkgr.129714508.129714782(502)>:20125]) from originator [daemon<com.apple.WindowServer(88)>:178]
```
This also seems to suggest a Keychain issue since it refers to the problem being _getting_ the SMTP credentials not using or authenticating with them.

I can confirm that when I launch Keychain Access an AutoPkgr keychain is listed but as is normal, I as a user cannot access it. I can also confirm in that keychain two email account entries are listed including the current one. (We previously updated it when the email account changed.)
![Screenshot 2024-07-19 at 10 01 20](https://github.com/user-attachments/assets/e8e9f867-dc8c-4ff6-a1d8-dfee20ba1868)
I would based on the error message be suspecting that the keychain despite superficially looking ok may in fact be 'bad'. However before I try deleting it and re-launching AutoPkgr to try creating a new one, I am asking if you are able to confirm my feeling that it is the keychain at fault.

**Comment by shawnhonsberger** [comment]
Thanks @jelockwood. I would delete the AutoPkgr keychain, reinstall the AutoPkgr helper tool by holding Opt and selecting Reinstall Helper Tool. Then I would re-add the credentials and re-test. Thank you!

**Comment by jelockwood** [comment]
I followed your instructions and the email test now works so I would expect the normal notification to also work, thanks for your help.
