### ISSUE TITLE
Blank Settings window for AutoPkgr 1.6.1

### ISSUE THREAD

**Issue by rhype** [lindegroup/autopkgr#718]
I am running AutoPkgr 1.6.1 for the first time and it displays a blank settings window. Is there anything I can do to resolve this? See the attached screenshot.
<img width="725" alt="Screenshot 2024-08-02 at 4 20 47 PM" src="https://github.com/user-attachments/assets/42c09a72-1934-4ba9-8651-c9e6def6faf0">

**Comment by rhype** [comment]
<img width="396" alt="Screenshot 2024-08-02 at 4 28 54 PM" src="https://github.com/user-attachments/assets/a216ceed-b055-4316-b7d7-9e9cd3d7c97f">

**Comment by homebysix** [comment]
Did you already install `autopkg` itself? On macOS 12.3, that's required before installing AutoPkgr (see Initial Setup instructions AutoPkgr on macOS 12.3+ also requires AutoPkg to be installed first. You can get the latest AutoPkg release [here](https://github.com/autopkg/autopkg/releases/latest).).

**Comment by rhype** [comment]
Thanks that worked, that requirement is easy to miss. Thank you so much!
