### ISSUE TITLE
Can't update munkitools to 6.6.0

### ISSUE THREAD

**Issue by precursorca** [lindegroup/autopkgr#719]
When trying to update munkitools to 6.6.0 in Autopkgr 1.6.1 (on macOS 14.6.1) the munkitools pkg downloads but then a message appears "Can't communicate with a helper applications. Try your operation again. If that fails, quit and realunch the applications and try again."
![Can't communicate](https://github.com/user-attachments/assets/155cbd05-d67b-42b8-ace3-390e6ce4bcff)

**Comment by shawnhonsberger** [comment]
Thanks @precursorca! I would delete the AutoPkgr keychain, reinstall the AutoPkgr helper tool by holding Opt and selecting Reinstall Helper Tool. Then I would retry the installation. Thank you!

**Comment by precursorca** [comment]
I deleted the keychain but could not find Reinstall Helper tool when holding the Option button.

---
Alex Narvey
***@***.***

**Comment by precursorca** [comment]
I deleted the helper and reinstall AutoPkgr and it replaced the helper and then things seemed to work.
Although in this particular update the light stays orange. That sometimes happens with munki updates.

---
Alex Narvey
***@***.***

**Comment by shawnhonsberger** [comment]
Thanks @precursorca, good to hear. When you hold Option, Reinstall Helper Tool displays in the top Menu bar list.

**Comment by zkmedv** [comment]
> Thanks [@precursorca](https://github.com/precursorca), good to hear. When you hold Option, Reinstall Helper Tool displays in the top Menu bar list.

Thanks for the solution I searched quite for a while to resolve this issue!
