### ISSUE TITLE
List of "official" recipes

### ISSUE THREAD

**Issue by jpiel** [lindegroup/autopkgr#721]
I just realized that with a fresh install of autopkgr, my repo doesn't appear in the list of recipes by default.

Since my recipes depot is hosted by autopkg like others i was wondering why it doesn't appear.

That's not a big issue since i can add it manually (that should be how i did it years ago) but i was wondering if this was an expected behavior or not.

**Comment by shawnhonsberger** [comment]
Thanks, @jpiel Yes, it is expected behavior. Repos not in the default list have to be added manually. Thank you!

**Comment by jpiel** [comment]
Just for curiosity, how repos are added to the default list ?

**Comment by homebysix** [comment]
The "fallback repos" array is defined [here](https://github.com/lindegroup/autopkgr/blob/07dc66cbd771035a2e824f206ea0b2479ef591d6/AutoPkgr/Models/AutoPkg%20Task/LGAutoPkgRepo.m#L361).
